import { createHash, randomBytes } from "node:crypto";
import type { CompetencyAssessmentItemResult, Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { AuthorizationError, ResourceNotFoundError } from "@/domain/auth/errors";
import { requireOrganizationMembership, requirePermission } from "@/domain/permissions/authorization";

type ChecklistRule={id:string;required:boolean;criticalFailure:boolean};
export function determineCompetencyResult(rules:ChecklistRule[],results:Map<string,CompetencyAssessmentItemResult>){
  if(!rules.length)return "INCOMPLETE" as const;
  if(rules.some(r=>r.criticalFailure&&results.get(r.id)==="FAIL"))return "FAIL" as const;
  if(rules.some(r=>r.required&&!["PASS","NOT_APPLICABLE"].includes(results.get(r.id)??"NOT_OBSERVED")))return "REMEDIATION_REQUIRED" as const;
  return "PASS" as const;
}
async function authorized(userId:string,organizationId:string,permission:string){const m=await requireOrganizationMembership(userId,organizationId);await requirePermission(m.id,permission);return m;}
export async function createCompetencyAssessment(userId:string,organizationId:string,input:{employeeId:string;competencyDefinitionId:string;skillChecklistVersionId?:string;trainingAssignmentId?:string;complianceInstanceId?:string;notes?:string}){
  await authorized(userId,organizationId,"competency.assess");
  const [employee,definition,assessorEmployee,user]=await Promise.all([prisma.employee.findFirst({where:{id:input.employeeId,organizationId}}),prisma.competencyDefinition.findFirst({where:{id:input.competencyDefinitionId,OR:[{organizationId},{organizationId:null}]}}),prisma.employee.findFirst({where:{organizationId,userId}}),prisma.user.findUnique({where:{id:userId}})]);
  if(!employee||!definition||!user)throw new ResourceNotFoundError("Competency assessment resource not found");
  if(assessorEmployee?.id===employee.id)throw new AuthorizationError("Self-assessment is not permitted");
  if(input.skillChecklistVersionId&&!await prisma.skillChecklistVersion.findFirst({where:{id:input.skillChecklistVersionId,status:"ACTIVE",skillChecklist:{OR:[{organizationId},{organizationId:null}]}}}))throw new ResourceNotFoundError("Active checklist version not found");
  const credentials=await prisma.professionalCredential.findMany({where:{organizationId,OR:[{employeeId:assessorEmployee?.id},{userId}],status:"ACTIVE"},select:{credentialType:true,credentialName:true,jurisdiction:true,verificationStatus:true,expiresAt:true}});
  const name=assessorEmployee?[assessorEmployee.firstName,assessorEmployee.lastName].join(" "):(user.email??"Authorized assessor");
  return prisma.competencyAssessment.create({data:{organizationId,employeeId:employee.id,competencyDefinitionId:definition.id,skillChecklistVersionId:input.skillChecklistVersionId,trainingAssignmentId:input.trainingAssignmentId,complianceInstanceId:input.complianceInstanceId,assessorUserId:userId,assessorEmployeeId:assessorEmployee?.id,assessorNameSnapshot:name,assessorQualificationSnapshot:credentials as Prisma.InputJsonValue,status:"IN_PROGRESS",notes:input.notes}});
}
export async function finalizeCompetencyAssessment(userId:string,organizationId:string,id:string,input:{items:{skillChecklistItemId:string;result:CompetencyAssessmentItemResult;notes?:string}[];notes?:string}){
  await authorized(userId,organizationId,"competency.assess");
  return prisma.$transaction(async tx=>{const assessment=await tx.competencyAssessment.findFirst({where:{id,organizationId},include:{skillChecklistVersion:{include:{items:true}}}});if(!assessment)throw new ResourceNotFoundError("Assessment not found");if(["FINALIZED","VOIDED"].includes(assessment.status))throw new Error("Finalized competency evidence is immutable");
    const rules=assessment.skillChecklistVersion?.items??[];const supplied=new Map(input.items.map(x=>[x.skillChecklistItemId,x.result]));if(input.items.some(x=>!rules.some(r=>r.id===x.skillChecklistItemId)))throw new Error("Checklist item does not belong to assessment version");
    const result=determineCompetencyResult(rules,supplied);await tx.competencyAssessmentItem.createMany({data:input.items.map(x=>({competencyAssessmentId:id,skillChecklistItemId:x.skillChecklistItemId,result:x.result,notes:x.notes}))});const finalizedAt=new Date();const saved=await tx.competencyAssessment.update({where:{id},data:{status:"FINALIZED",result,completedAt:finalizedAt,finalizedAt,notes:input.notes??assessment.notes}});if(assessment.complianceInstanceId)await linkAndRecompute(tx,assessment.complianceInstanceId,"COMPETENCY_ASSESSMENT",saved.id);return saved;},{isolationLevel:"Serializable"});
}
export async function voidCompetencyAssessment(userId:string,organizationId:string,id:string,reason:string){await authorized(userId,organizationId,"competency.manage");const a=await prisma.competencyAssessment.findFirst({where:{id,organizationId}});if(!a)throw new ResourceNotFoundError("Assessment not found");if(a.status!=="FINALIZED")throw new Error("Only finalized evidence can be voided");const corrected=await prisma.$transaction(async tx=>{const c=await tx.evidenceCorrection.create({data:{organizationId,resourceType:"COMPETENCY_ASSESSMENT",resourceId:id,correctionType:"VOIDED",reason,correctedByUserId:userId}});await tx.competencyAssessment.update({where:{id},data:{status:"VOIDED"}});if(a.complianceInstanceId)await recomputeComplianceInstance(tx,a.complianceInstanceId);return c;});return corrected;}
export async function recomputeComplianceInstance(tx:Prisma.TransactionClient,instanceId:string){const i=await tx.complianceInstance.findUnique({where:{id:instanceId},include:{requirementVersion:{include:{competencyRequirements:true}},trainingAssignments:{include:{completion:true}},competencyAssessments:true}});if(!i)return null;const approved=await tx.requirementEquivalencyDecision.findFirst({where:{organizationId:i.organizationId,requirementVersionId:i.requirementVersionId,externalTrainingRecord:{employeeId:i.employeeId},decision:"APPROVED"}});const training=!!approved||i.trainingAssignments.some(a=>!!a.completion);const required=i.requirementVersion.competencyRequirements.filter(x=>x.required),legacy=(i.requirementVersion.competencyDefinition as {type?:string}|null)?.type==="REQUIRED",competencyRequired=legacy||required.length>0;const passed=(!competencyRequired||((required.length?required.every(r=>i.competencyAssessments.some(a=>a.competencyDefinitionId===r.competencyDefinitionId&&a.status==="FINALIZED"&&a.result==="PASS")):i.competencyAssessments.some(a=>a.status==="FINALIZED"&&a.result==="PASS"))))||(!!approved&&approved.competencyVerified);const failed=i.competencyAssessments.some(a=>a.status==="FINALIZED"&&["FAIL","REMEDIATION_REQUIRED"].includes(a.result??""));const satisfied=training&&passed&&!failed;await tx.complianceInstance.update({where:{id:i.id},data:{status:satisfied?(approved?"WAIVED_BY_EQUIVALENCY":"SATISFIED"):(i.status==="SATISFIED"||i.status==="WAIVED_BY_EQUIVALENCY"?"REQUIRED":i.status),satisfiedAt:satisfied?new Date():null}});await tx.trainingAssignment.updateMany({where:{complianceInstanceId:i.id,completion:{isNot:null}},data:{status:satisfied?"COMPLETED":competencyRequired?"TRAINING_COMPLETE_COMPETENCY_PENDING":"COMPLETED"}});return satisfied;}
async function linkAndRecompute(tx:Prisma.TransactionClient,instanceId:string,type:"COMPETENCY_ASSESSMENT"|"ATTESTATION"|"EQUIVALENCY_DECISION",referenceId:string){await tx.complianceInstanceEvidence.upsert({where:{complianceInstanceId_evidenceType_evidenceReferenceId:{complianceInstanceId:instanceId,evidenceType:type,evidenceReferenceId:referenceId}},create:{complianceInstanceId:instanceId,evidenceType:type,evidenceReferenceId:referenceId},update:{}});return recomputeComplianceInstance(tx,instanceId)}
export async function createAttestation(userId:string,organizationId:string,input:{attestationType:"POLICY_ACKNOWLEDGMENT"|"TRAINER_ATTESTATION"|"SUPERVISOR_COMPETENCY"|"EMPLOYEE_COMPLETION"|"DOCUMENT_REVIEW"|"OTHER";signerEmployeeId?:string;typedName:string;statementVersion:string;statementSnapshot:string;resourceType:string;resourceId:string;resourceVersionId?:string;ipAddress?:string;userAgent?:string;sessionReference?:string}){await requireOrganizationMembership(userId,organizationId);if(input.signerEmployeeId&&!await prisma.employee.findFirst({where:{id:input.signerEmployeeId,organizationId,userId}}))throw new AuthorizationError("Authenticated signer does not match represented employee");const signedAt=new Date();const canonical=JSON.stringify({organizationId,signerUserId:userId,resourceType:input.resourceType,resourceId:input.resourceId,resourceVersionId:input.resourceVersionId??null,statementVersion:input.statementVersion,statementSnapshot:input.statementSnapshot,signedAt:signedAt.toISOString()});return prisma.attestation.create({data:{...input,organizationId,signerUserId:userId,signedAt,signatureHash:createHash("sha256").update(canonical).digest("hex")}})}
export async function createEvidenceCorrection(userId:string,organizationId:string,input:{resourceType:string;resourceId:string;correctionType:"SUPERSEDED"|"VOIDED"|"CORRECTED_BY_REPLACEMENT"|"ADMINISTRATIVE_NOTE";reason:string;replacementResourceType?:string;replacementResourceId?:string}){await authorized(userId,organizationId,"competency.manage");return prisma.evidenceCorrection.create({data:{...input,organizationId,correctedByUserId:userId}})}
export async function createExternalTrainingRecord(userId:string,organizationId:string,input:{employeeId:string;providerName:string;trainingName:string;trainingDate:Date;trainingMinutes?:number;credentialNumber?:string;expiresAt?:Date;evidenceReference?:string;notes?:string}){await authorized(userId,organizationId,"training.manage");if(!await prisma.employee.findFirst({where:{id:input.employeeId,organizationId}}))throw new ResourceNotFoundError("Employee not found");return prisma.externalTrainingRecord.create({data:{...input,organizationId}})}
export async function createProfessionalCredential(userId:string,organizationId:string,input:{employeeId?:string;credentialType:"RN"|"CNS"|"CNP"|"PA"|"PHYSICIAN"|"CPR_INSTRUCTOR"|"FIRST_AID_INSTRUCTOR"|"OTHER";credentialName?:string;licenseNumber?:string;jurisdiction?:string;issuedAt?:Date;expiresAt?:Date;evidenceReference?:string}){await authorized(userId,organizationId,"competency.manage");if(input.employeeId&&!await prisma.employee.findFirst({where:{id:input.employeeId,organizationId}}))throw new ResourceNotFoundError("Employee not found");return prisma.professionalCredential.create({data:{...input,organizationId,verificationStatus:"UNVERIFIED"}})}
export async function decideEquivalency(userId:string,organizationId:string,input:{externalTrainingRecordId:string;requirementVersionId:string;decision:"APPROVED"|"DENIED"|"NEEDS_MORE_INFORMATION";competencyVerified:boolean;reason:string}){await authorized(userId,organizationId,"training.equivalency.review");const record=await prisma.externalTrainingRecord.findFirst({where:{id:input.externalTrainingRecordId,organizationId}});if(!record)throw new ResourceNotFoundError("External evidence not found");return prisma.$transaction(async tx=>{const decidedAt=new Date();const decision=await tx.requirementEquivalencyDecision.create({data:{...input,organizationId,reviewerUserId:userId,decidedAt}});await tx.externalTrainingRecord.update({where:{id:record.id},data:{reviewStatus:input.decision,reviewedByUserId:userId,reviewedAt:decidedAt}});const instances=await tx.complianceInstance.findMany({where:{organizationId,employeeId:record.employeeId,requirementVersionId:input.requirementVersionId},select:{id:true}});for(const instance of instances)await linkAndRecompute(tx,instance.id,"EQUIVALENCY_DECISION",decision.id);return decision;});}
export async function issueCertificate(userId:string|null,organizationId:string,employeeId:string,trainingCompletionId:string,type:"TRAINING"|"COMPETENCY"|"COMPLIANCE"="TRAINING",competencyAssessmentId?:string){if(userId)await authorized(userId,organizationId,"certificate.issue");const completion=await prisma.trainingCompletion.findFirst({where:{id:trainingCompletionId,organizationId,employeeId},include:{course:true,courseVersion:true,employee:true,organization:true,assignment:{include:{complianceInstance:{include:{requirementVersion:{include:{competencyRequirements:true}}}}}}}});if(!completion)throw new ResourceNotFoundError("Training evidence not found");if(type!=="TRAINING"&&completion.assignment.complianceInstance?.status!=="SATISFIED")throw new Error("Underlying evidence gates are not satisfied");if(competencyAssessmentId&&!await prisma.competencyAssessment.findFirst({where:{id:competencyAssessmentId,organizationId,employeeId,status:"FINALIZED",result:"PASS"}}))throw new Error("Passing competency evidence required");const existing=await prisma.certificate.findFirst({where:{trainingCompletionId,certificateType:type,status:"ACTIVE"}});if(existing)return existing;const opaque=randomBytes(8).toString("base64url").toUpperCase(),token=randomBytes(32).toString("base64url"),snapshot={employeeName:`${completion.employee.firstName} ${completion.employee.lastName}`,organizationName:completion.organization.displayName,trainingTitle:completion.course.title,courseVersion:completion.courseVersion.versionNumber,completedAt:completion.completedAt};return prisma.certificate.create({data:{organizationId,employeeId,certificateType:type,certificateNumber:`CP-${String(new Date().getUTCFullYear()).slice(-2)}-${opaque.slice(0,4)}-${opaque.slice(4,8)}`,courseVersionId:completion.courseVersionId,trainingCompletionId,competencyAssessmentId,verificationToken:token,certificateSnapshotJson:snapshot,issuedByUserId:userId}})}
export async function verifyCertificate(token:string){const c=await prisma.certificate.findUnique({where:{verificationToken:token},select:{certificateNumber:true,status:true,issuedAt:true,expiresAt:true,certificateSnapshotJson:true}});return c?{valid:true,...c}:null}
export async function revokeCertificate(userId:string,organizationId:string,id:string){await authorized(userId,organizationId,"certificate.revoke");const c=await prisma.certificate.findFirst({where:{id,organizationId}});if(!c)throw new ResourceNotFoundError("Certificate not found");return prisma.certificate.update({where:{id},data:{status:"REVOKED"}})}
