import { type AuditAccessCategory, Prisma, type User } from "@prisma/client";
import { z } from "zod";
import { AuthorizationError, ResourceNotFoundError } from "@/domain/auth/errors";
import { deriveOrganizationClientDocumentationReadiness } from "@/domain/clients/readiness";
import { requireOrganizationAccess, requireOrganizationMembership, requirePermission } from "@/domain/permissions/authorization";
import { prisma } from "@/lib/prisma";

export const auditAccessInput=z.object({name:z.string().trim().min(1).max(200),inspectorName:z.string().trim().max(200).optional(),inspectorEmail:z.string().trim().email(),startsAt:z.coerce.date(),expiresAt:z.coerce.date(),categories:z.array(z.enum(["CLIENTS","CLIENT_DOCUMENTS","STAFF","TRAINING_COMPLIANCE","CREDENTIALS_COMPETENCIES","POLICIES","EVIDENCE","AUDIT_PACKAGES"])).min(1),clientIds:z.array(z.string().cuid()).max(500).default([]),employeeIds:z.array(z.string().cuid()).max(1000).default([]),includeActiveStaff:z.boolean().default(false)}).strict();
type AuditAccessInput=z.input<typeof auditAccessInput>;

async function management(user:Pick<User,"id">,organizationId:string){const{membership}=await requireOrganizationAccess(user,organizationId);await requirePermission(membership.id,"audit.session.manage");return membership}
function validateWindow(startsAt:Date,expiresAt:Date){if(expiresAt<=startsAt)throw new AuthorizationError("Audit access expiration must be after its start");if(expiresAt.getTime()-startsAt.getTime()>31*86_400_000)throw new AuthorizationError("Audit access cannot exceed 31 days")}
async function validateScope(organizationId:string,input:{categories:AuditAccessCategory[];clientIds:string[];employeeIds:string[];includeActiveStaff:boolean}){const needsClients=input.categories.some(category=>["CLIENTS","CLIENT_DOCUMENTS"].includes(category)),needsStaff=input.categories.some(category=>["STAFF","TRAINING_COMPLIANCE","CREDENTIALS_COMPETENCIES","EVIDENCE"].includes(category));if(needsClients&&!input.clientIds.length)throw new AuthorizationError("Select at least one client for the requested client categories");if(needsStaff&&!input.includeActiveStaff&&!input.employeeIds.length)throw new AuthorizationError("Select employees or include active staff for the requested staff categories");const[clients,employees]=await Promise.all([prisma.client.count({where:{organizationId,id:{in:input.clientIds}}}),prisma.employee.count({where:{organizationId,id:{in:input.employeeIds}}})]);if(clients!==new Set(input.clientIds).size)throw new ResourceNotFoundError("One or more scoped clients were not found");if(employees!==new Set(input.employeeIds).size)throw new ResourceNotFoundError("One or more scoped employees were not found")}
async function inspector(organizationId:string,email:string){const user=await prisma.user.findFirst({where:{email:{equals:email,mode:"insensitive"},status:"ACTIVE"}});if(!user)throw new ResourceNotFoundError("An active linked inspector account was not found");const membership=await requireOrganizationMembership(user.id,organizationId);await requirePermission(membership.id,"audit.portal.read");return user}
async function event(organizationId:string,actorUserId:string,eventType:string,sessionId:string,metadataJson?:Prisma.InputJsonValue){await prisma.auditEvent.create({data:{organizationId,actorUserId,eventType,entityType:"AuditAccessSession",entityId:sessionId,metadataJson}})}

export async function createAuditAccessSession(user:Pick<User,"id">,organizationId:string,raw:AuditAccessInput){await management(user,organizationId);const input=auditAccessInput.parse(raw),categories=[...new Set(input.categories)];validateWindow(input.startsAt,input.expiresAt);await validateScope(organizationId,{...input,categories});const inspectorUser=await inspector(organizationId,input.inspectorEmail);const session=await prisma.$transaction(async tx=>tx.auditAccessSession.create({data:{organizationId,name:input.name,inspectorName:input.inspectorName,inspectorEmail:input.inspectorEmail.toLowerCase(),inspectorUserId:inspectorUser.id,startsAt:input.startsAt,expiresAt:input.expiresAt,categories,includeActiveStaff:input.includeActiveStaff,createdByUserId:user.id,clients:{create:[...new Set(input.clientIds)].map(clientId=>({clientId}))},employees:{create:[...new Set(input.employeeIds)].map(employeeId=>({employeeId}))}},include:{clients:true,employees:true}}));await event(organizationId,user.id,"audit.access_session_created",session.id,{categories,clientCount:session.clients.length,employeeCount:session.employees.length,includeActiveStaff:session.includeActiveStaff});if(session.startsAt<=new Date())await event(organizationId,user.id,"audit.access_session_activated",session.id);return session}

export async function listAuditAccessSessions(user:Pick<User,"id">,organizationId:string){await management(user,organizationId);const rows=await prisma.auditAccessSession.findMany({where:{organizationId},select:{id:true,name:true,inspectorName:true,inspectorEmail:true,startsAt:true,expiresAt:true,status:true,categories:true,includeActiveStaff:true,revokedAt:true,revocationReason:true,createdAt:true,_count:{select:{clients:true,employees:true}}},orderBy:[{createdAt:"desc"},{id:"desc"}],take:200});const now=new Date();return rows.map(row=>({...row,effectiveStatus:row.status==="REVOKED"?"REVOKED":row.startsAt>now?"SCHEDULED":row.expiresAt<=now?"EXPIRED":"ACTIVE"}))}
export async function getAuditAccessManagement(user:Pick<User,"id">,organizationId:string){const sessions=await listAuditAccessSessions(user,organizationId),[clients,employees]=await Promise.all([prisma.client.findMany({where:{organizationId,status:{not:"ARCHIVED"}},select:{id:true,legalFirstName:true,legalLastName:true,preferredName:true,status:true},orderBy:[{legalLastName:"asc"},{legalFirstName:"asc"}],take:1000}),prisma.employee.findMany({where:{organizationId,employmentStatus:{in:["PENDING","ACTIVE"]}},select:{id:true,firstName:true,lastName:true,preferredName:true,employmentStatus:true,jobTitle:true},orderBy:[{lastName:"asc"},{firstName:"asc"}],take:2000})]);return{sessions,options:{clients,employees}}}

export async function updateAuditAccessSession(user:Pick<User,"id">,organizationId:string,sessionId:string,raw:AuditAccessInput){await management(user,organizationId);const existing=await prisma.auditAccessSession.findFirst({where:{id:sessionId,organizationId}});if(!existing)throw new ResourceNotFoundError("Audit access session not found");if(existing.status==="REVOKED")throw new AuthorizationError("Revoked audit access cannot be changed");const input=auditAccessInput.parse(raw),categories=[...new Set(input.categories)];validateWindow(input.startsAt,input.expiresAt);await validateScope(organizationId,{...input,categories});const inspectorUser=await inspector(organizationId,input.inspectorEmail);const session=await prisma.$transaction(async tx=>{await tx.auditAccessClient.deleteMany({where:{sessionId}});await tx.auditAccessEmployee.deleteMany({where:{sessionId}});return tx.auditAccessSession.update({where:{id:sessionId},data:{name:input.name,inspectorName:input.inspectorName,inspectorEmail:input.inspectorEmail.toLowerCase(),inspectorUserId:inspectorUser.id,startsAt:input.startsAt,expiresAt:input.expiresAt,categories,includeActiveStaff:input.includeActiveStaff,clients:{create:[...new Set(input.clientIds)].map(clientId=>({clientId}))},employees:{create:[...new Set(input.employeeIds)].map(employeeId=>({employeeId}))}},include:{clients:true,employees:true}})});await event(organizationId,user.id,"audit.access_session_scope_updated",session.id,{categories,clientCount:session.clients.length,employeeCount:session.employees.length,includeActiveStaff:session.includeActiveStaff});return session}

export async function revokeAuditAccessSession(user:Pick<User,"id">,organizationId:string,sessionId:string,reason:string){await management(user,organizationId);const session=await prisma.auditAccessSession.findFirst({where:{id:sessionId,organizationId}});if(!session)throw new ResourceNotFoundError("Audit access session not found");if(session.status==="REVOKED")return session;const updated=await prisma.auditAccessSession.update({where:{id:session.id},data:{status:"REVOKED",revokedAt:new Date(),revokedByUserId:user.id,revocationReason:z.string().trim().min(1).max(1000).parse(reason)}});await event(organizationId,user.id,"audit.access_session_revoked",session.id);return updated}

async function activeSession(user:Pick<User,"id">,sessionId:string,category?:AuditAccessCategory,at=new Date()){const session=await prisma.auditAccessSession.findFirst({where:{id:sessionId,inspectorUserId:user.id},include:{clients:{select:{clientId:true}},employees:{select:{employeeId:true}},organization:{select:{id:true,displayName:true}}}});if(!session)throw new AuthorizationError("Audit access denied");const membership=await requireOrganizationMembership(user.id,session.organizationId);await requirePermission(membership.id,"audit.portal.read");if(session.status!=="ACTIVE"||session.startsAt>at||session.expiresAt<=at)throw new AuthorizationError("Audit access is inactive or expired");if(category&&!session.categories.includes(category))throw new AuthorizationError("Record category is outside this audit scope");return session}
async function scopedEmployeeIds(session:Awaited<ReturnType<typeof activeSession>>){const selected=session.employees.map(row=>row.employeeId);if(!session.includeActiveStaff)return selected;const active=await prisma.employee.findMany({where:{organizationId:session.organizationId,employmentStatus:"ACTIVE"},select:{id:true}});return [...new Set([...selected,...active.map(row=>row.id)])]}

export async function getAuditorPortal(user:Pick<User,"id">,sessionId:string,at=new Date()){const session=await activeSession(user,sessionId,undefined,at),categories=new Set(session.categories),clientIds=session.clients.map(row=>row.clientId),employeeIds=await scopedEmployeeIds(session);const[readiness,documents,staff,training,compliance,credentials,competencies,policies,packages]=await Promise.all([
  categories.has("CLIENTS")||categories.has("CLIENT_DOCUMENTS")?deriveOrganizationClientDocumentationReadiness(session.organizationId,{clientIds,at}):[],
  categories.has("CLIENT_DOCUMENTS")?prisma.clientDocument.findMany({where:{organizationId:session.organizationId,clientId:{in:clientIds},status:{not:"VOIDED"}},select:{id:true,documentType:true,status:true,generatedAt:true,authoritativeCompletedAt:true,template:{select:{name:true,versionNumber:true}}},orderBy:[{generatedAt:"desc"},{id:"desc"}],take:1000}):[],
  categories.has("STAFF")?prisma.employee.findMany({where:{organizationId:session.organizationId,id:{in:employeeIds}},select:{firstName:true,lastName:true,preferredName:true,jobTitle:true,employmentStatus:true,hireDate:true},orderBy:[{lastName:"asc"},{firstName:"asc"},{id:"asc"}]}):[],
  categories.has("TRAINING_COMPLIANCE")?prisma.trainingAssignment.groupBy({by:["status"],where:{organizationId:session.organizationId,employeeId:{in:employeeIds}},_count:true}):[],
  categories.has("TRAINING_COMPLIANCE")?prisma.complianceInstance.groupBy({by:["status"],where:{organizationId:session.organizationId,employeeId:{in:employeeIds}},_count:true}):[],
  categories.has("CREDENTIALS_COMPETENCIES")?prisma.professionalCredential.groupBy({by:["verificationStatus"],where:{organizationId:session.organizationId,employeeId:{in:employeeIds}},_count:true}):[],
  categories.has("CREDENTIALS_COMPETENCIES")?prisma.competencyAssessment.groupBy({by:["status","result"],where:{organizationId:session.organizationId,employeeId:{in:employeeIds}},_count:true}):[],
  categories.has("POLICIES")?prisma.policy.findMany({where:{organizationId:session.organizationId},select:{code:true,title:true,status:true,versions:{select:{versionNumber:true,status:true,effectiveFrom:true},orderBy:{versionNumber:"desc"},take:1}},orderBy:[{title:"asc"},{id:"asc"}]}):[],
  categories.has("AUDIT_PACKAGES")?prisma.auditPackage.findMany({where:{organizationId:session.organizationId,status:"GENERATED"},select:{id:true,scope:true,subjectType:true,generatedAt:true,recordCount:true,integrityDigest:true},orderBy:{generatedAt:"desc"},take:100}):[],
]);const evidence=categories.has("EVIDENCE")?{counts:{trainingCompletions:await prisma.trainingCompletion.count({where:{organizationId:session.organizationId,employeeId:{in:employeeIds}}}),certificates:await prisma.certificate.count({where:{organizationId:session.organizationId,employeeId:{in:employeeIds}}}),attestations:await prisma.attestation.count({where:{organizationId:session.organizationId,signerEmployeeId:{in:employeeIds}}}),externalTrainingRecords:await prisma.externalTrainingRecord.count({where:{organizationId:session.organizationId,employeeId:{in:employeeIds}}})},meaning:"Evidence totals include only records belonging to staff explicitly included in this audit scope."}:null;return{session:{id:session.id,name:session.name,organizationName:session.organization.displayName,inspectorName:session.inspectorName,startsAt:session.startsAt,expiresAt:session.expiresAt,status:"ACTIVE",categories:session.categories,readOnly:true},clients:readiness.map(row=>({client:{legalFirstName:row.client.legalFirstName,legalLastName:row.client.legalLastName,preferredName:row.client.preferredName,status:row.client.status},overallState:row.overallState,counts:row.counts,nearestActionableDeadline:row.nearestActionableDeadline,requirements:row.requirements.map(item=>({name:item.name,documentType:item.documentType,state:item.state,satisfied:item.satisfied,reason:item.reason,dueDate:item.dueDate,deadlinePhase:item.deadlinePhase,signatureStatus:item.signatureStatus}))})),documents,staff,trainingCompliance:{training,compliance},credentialsCompetencies:{credentials,competencies},policies,evidence,auditPackages:packages}}

export async function getAuditorDocumentPdf(user:Pick<User,"id">,sessionId:string,documentId:string){const session=await activeSession(user,sessionId,"CLIENT_DOCUMENTS"),clientIds=session.clients.map(row=>row.clientId),document=await prisma.clientDocument.findFirst({where:{id:documentId,organizationId:session.organizationId,clientId:{in:clientIds}},select:{id:true,clientId:true,documentType:true,finalPdf:true,renderedPdf:true}});if(!document)throw new ResourceNotFoundError("Document not found in audit scope");const bytes=document.finalPdf??document.renderedPdf;if(!bytes)throw new ResourceNotFoundError("Rendered document not found");await prisma.auditEvent.create({data:{organizationId:session.organizationId,actorUserId:user.id,eventType:"audit.scoped_document_downloaded",entityType:"ClientDocument",entityId:document.id,metadataJson:{sessionId:session.id,documentType:document.documentType}}});return Buffer.from(bytes)}

export async function getAuditorPackage(user:Pick<User,"id">,sessionId:string,packageId:string){const session=await activeSession(user,sessionId,"AUDIT_PACKAGES"),item=await prisma.auditPackage.findFirst({where:{id:packageId,organizationId:session.organizationId,status:"GENERATED"},select:{id:true,manifestJson:true,integrityDigest:true}});if(!item?.manifestJson)throw new ResourceNotFoundError("Audit package not found in audit scope");await prisma.auditEvent.create({data:{organizationId:session.organizationId,actorUserId:user.id,eventType:"audit.scoped_package_downloaded",entityType:"AuditPackage",entityId:item.id,metadataJson:{sessionId:session.id}}});return item}
