import type { BlockingScope, Prisma, WorkReadinessTrigger } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { ResourceNotFoundError } from "@/domain/auth/errors";

export const READINESS_ENGINE_VERSION="phase5-v1";
export const readinessScopes=["GENERAL_WORK","DIRECT_CONTACT","UNSUPERVISED_CONTACT","PERSON_SPECIFIC_TASK","MEDICATION_ADMINISTRATION"] as const;
export type ReadinessState="READY"|"BLOCKED"|"NOT_APPLICABLE"|"EVIDENCE_COMPLETE_AUTHORIZATION_NOT_IMPLEMENTED";
export type ReadinessReason={type:string;resourceType:string;resourceId:string;message:string;dueAt?:string|null};
export type ReadinessScopeResult={scope:BlockingScope;state:ReadinessState;reasons:ReadinessReason[]};

export function scopeAffected(blockingScope:BlockingScope,target:BlockingScope){if(blockingScope==="GENERAL_WORK")return target!=="MEDICATION_ADMINISTRATION";if(blockingScope==="DIRECT_CONTACT")return ["DIRECT_CONTACT","UNSUPERVISED_CONTACT","PERSON_SPECIFIC_TASK"].includes(target);if(blockingScope==="UNSUPERVISED_CONTACT")return target==="UNSUPERVISED_CONTACT";return blockingScope===target;}
export async function computeEmployeeWorkReadiness(organizationId:string,employeeId:string,evaluatedAt=new Date()){
 const employee=await prisma.employee.findFirst({where:{id:employeeId,organizationId},include:{complianceInstances:{where:{status:{notIn:["SATISFIED","WAIVED_BY_EQUIVALENCY","SUPERSEDED"]}},include:{requirementVersion:{include:{requirement:true}}}},policyAssignments:{where:{status:{in:["PENDING","OVERDUE"]}},include:{policyVersion:{include:{policy:true}}}},onboardings:{where:{status:{notIn:["COMPLETED","CANCELED"]}},include:{steps:{include:{stepDefinition:true}}}},duties:{where:{OR:[{effectiveUntil:null},{effectiveUntil:{gte:evaluatedAt}}]},include:{dutyDefinition:true}}}});if(!employee)throw new ResourceNotFoundError("Employee not found");
 const unresolved=employee.onboardings.flatMap(o=>o.steps).filter(s=>s.stepDefinition.required&&!["COMPLETED","NOT_APPLICABLE"].includes(s.status));
 const results:ReadinessScopeResult[]=readinessScopes.map(scope=>{const reasons:ReadinessReason[]=[];for(const i of employee.complianceInstances){const block=i.requirementVersion.blockingScope;if(block&&scopeAffected(block,scope)&&(i.status==="BLOCKED"||i.status==="PAST_DUE"||(i.hardBlockAt&&i.hardBlockAt<=evaluatedAt)))reasons.push({type:"COMPLIANCE",resourceType:"ComplianceInstance",resourceId:i.id,message:`${i.requirementVersion.requirement.code}: ${i.requirementVersion.requirement.name}`,dueAt:i.nominalDueAt?.toISOString()??null})}for(const a of employee.policyAssignments){const block=a.policyVersion.policy.blockingScope;if(block&&scopeAffected(block,scope)&&(a.dueAt===null||a.dueAt<=evaluatedAt))reasons.push({type:"POLICY",resourceType:"PolicyAssignment",resourceId:a.id,message:`Policy acknowledgment pending: ${a.policyVersion.policy.title}`,dueAt:a.dueAt?.toISOString()??null})}for(const s of unresolved){const block=s.stepDefinition.blockingScope??"GENERAL_WORK";if(scopeAffected(block,scope))reasons.push({type:"ONBOARDING_STEP",resourceType:"EmployeeOnboardingStep",resourceId:s.id,message:s.stepDefinition.name,dueAt:s.dueAt?.toISOString()??null})}let state:ReadinessState=reasons.length?"BLOCKED":"READY";if(scope==="MEDICATION_ADMINISTRATION")state=reasons.length?"BLOCKED":"EVIDENCE_COMPLETE_AUTHORIZATION_NOT_IMPLEMENTED";return{scope,state,reasons}});
 return{organizationId,employeeId,evaluatedAt:evaluatedAt.toISOString(),engineVersion:READINESS_ENGINE_VERSION,scopes:results};
}
export async function evaluateEmployeeWorkReadiness(organizationId:string,employeeId:string,trigger:WorkReadinessTrigger="MANUAL_REEVALUATION",evaluatedAt=new Date()){const result=await computeEmployeeWorkReadiness(organizationId,employeeId,evaluatedAt);const snapshot=await prisma.workReadinessEvaluation.create({data:{organizationId,employeeId,evaluatedAt,evaluationTrigger:trigger,resultJson:result as unknown as Prisma.InputJsonValue,engineVersion:READINESS_ENGINE_VERSION}});return{snapshot,result}}
