import type { BlockingScope, Prisma, WorkReadinessTrigger } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { ResourceNotFoundError } from "@/domain/auth/errors";

export const READINESS_ENGINE_VERSION="positive-evidence-v2";
export const readinessScopes=["GENERAL_WORK","DIRECT_CONTACT","UNSUPERVISED_CONTACT","PERSON_SPECIFIC_TASK","MEDICATION_ADMINISTRATION"] as const;
export type ReadinessState="READY"|"BLOCKED"|"REQUIREMENTS_PENDING"|"NOT_APPLICABLE"|"EVIDENCE_COMPLETE_AUTHORIZATION_NOT_IMPLEMENTED";
export type ReadinessReason={type:string;resourceType:string;resourceId:string;message:string;dueAt?:string|null};
export type ReadinessScopeResult={scope:BlockingScope;state:ReadinessState;reasons:ReadinessReason[]};

export function scopeAffected(blockingScope:BlockingScope,target:BlockingScope){if(blockingScope==="GENERAL_WORK")return target!=="MEDICATION_ADMINISTRATION";if(blockingScope==="DIRECT_CONTACT")return ["DIRECT_CONTACT","UNSUPERVISED_CONTACT","PERSON_SPECIFIC_TASK"].includes(target);if(blockingScope==="UNSUPERVISED_CONTACT")return target==="UNSUPERVISED_CONTACT";return blockingScope===target;}
export async function computeEmployeeWorkReadiness(organizationId:string,employeeId:string,evaluatedAt=new Date()){
 const [employee,completedEvaluation]=await Promise.all([prisma.employee.findFirst({where:{id:employeeId,organizationId},include:{complianceInstances:{where:{status:{not:"SUPERSEDED"}},include:{evidence:true,requirementVersion:{include:{requirement:true}}}},policyAssignments:{where:{status:{in:["PENDING","OVERDUE"]}},include:{policyVersion:{include:{policy:true}}}},onboardings:{where:{status:{notIn:["COMPLETED","CANCELED"]}},include:{steps:{include:{stepDefinition:true}}}},duties:{where:{OR:[{effectiveUntil:null},{effectiveUntil:{gte:evaluatedAt}}]},include:{dutyDefinition:true}},serviceEvents:true,serviceAssignments:{where:{status:{in:["PROPOSED","ACTIVE","BLOCKED"]},OR:[{endsAt:null},{endsAt:{gte:evaluatedAt}}]}}}}),prisma.complianceEvaluationRun.findFirst({where:{organizationId,scopeType:"EMPLOYEE",scopeReference:employeeId,status:"COMPLETED"},orderBy:{completedAt:"desc"},select:{id:true}})]);if(!employee)throw new ResourceNotFoundError("Employee not found");
 const unresolved=employee.onboardings.flatMap(o=>o.steps).filter(s=>s.stepDefinition.required&&!["COMPLETED","NOT_APPLICABLE"].includes(s.status));
 const results:ReadinessScopeResult[]=readinessScopes.map(scope=>{const reasons:ReadinessReason[]=[];const applicable=employee.complianceInstances.filter(i=>i.requirementVersion.blockingScope&&scopeAffected(i.requirementVersion.blockingScope,scope));for(const i of applicable){if(!["SATISFIED","WAIVED_BY_EQUIVALENCY"].includes(i.status))reasons.push({type:"COMPLIANCE",resourceType:"ComplianceInstance",resourceId:i.id,message:`${i.requirementVersion.requirement.code}: ${i.requirementVersion.requirement.name}`,dueAt:i.nominalDueAt?.toISOString()??null})}for(const a of employee.policyAssignments){const block=a.policyVersion.policy.blockingScope;if(block&&scopeAffected(block,scope))reasons.push({type:"POLICY",resourceType:"PolicyAssignment",resourceId:a.id,message:`Policy acknowledgment pending: ${a.policyVersion.policy.title}`,dueAt:a.dueAt?.toISOString()??null})}for(const s of unresolved){const block=s.stepDefinition.blockingScope??"GENERAL_WORK";if(scopeAffected(block,scope))reasons.push({type:"ONBOARDING_STEP",resourceType:"EmployeeOnboardingStep",resourceId:s.id,message:s.stepDefinition.name,dueAt:s.dueAt?.toISOString()??null})}
  const assignedScopes=new Set(employee.serviceAssignments.map(a=>a.blockingScope));
  const exactApplicability=applicable.some(i=>i.requirementVersion.blockingScope===scope),directContext=employee.serviceEvents.some(e=>["FIRST_DIRECT_CONTACT","FIRST_SUPERVISED_DIRECT_CONTACT","FIRST_UNSUPERVISED_DIRECT_CONTACT"].includes(e.eventType))||employee.serviceAssignments.some(a=>["DIRECT_CONTACT","UNSUPERVISED_CONTACT","PERSON_SPECIFIC_TASK","MEDICATION_ADMINISTRATION"].includes(a.blockingScope));
  const applicability=scope==="GENERAL_WORK"?true:scope==="DIRECT_CONTACT"?directContext||exactApplicability:scope==="UNSUPERVISED_CONTACT"?employee.serviceEvents.some(e=>e.eventType==="FIRST_UNSUPERVISED_DIRECT_CONTACT")||assignedScopes.has(scope)||exactApplicability:scope==="PERSON_SPECIFIC_TASK"?employee.serviceAssignments.some(a=>Boolean(a.serviceRecipientRef)&&["PERSON_SPECIFIC_TASK","MEDICATION_ADMINISTRATION"].includes(a.blockingScope)):employee.serviceAssignments.some(a=>a.blockingScope==="MEDICATION_ADMINISTRATION")||employee.serviceEvents.some(e=>e.eventType==="MEDICATION_DUTY_ASSIGNED")||exactApplicability;
  const blocking=reasons.some(r=>r.type!=="COMPLIANCE")||applicable.some(i=>i.status==="BLOCKED"||i.status==="PAST_DUE"||i.status==="EXPIRED"||Boolean(i.hardBlockAt&&i.hardBlockAt<=evaluatedAt));
  const scopeBasis=applicable.filter(i=>i.requirementVersion.blockingScope===scope);
  const positivelySatisfied=scopeBasis.length>0&&applicable.every(i=>["SATISFIED","WAIVED_BY_EQUIVALENCY"].includes(i.status)&&(i.evidence.length>0||i.status==="WAIVED_BY_EQUIVALENCY"));
  let state:ReadinessState=blocking?"BLOCKED":!applicability?(completedEvaluation||scope==="PERSON_SPECIFIC_TASK"||scope==="MEDICATION_ADMINISTRATION"?"NOT_APPLICABLE":"REQUIREMENTS_PENDING"):!completedEvaluation||!positivelySatisfied||reasons.length?"REQUIREMENTS_PENDING":"READY";
  if(scope==="MEDICATION_ADMINISTRATION"&&state==="READY")state="EVIDENCE_COMPLETE_AUTHORIZATION_NOT_IMPLEMENTED";
  return{scope,state,reasons}});
 return{organizationId,employeeId,evaluatedAt:evaluatedAt.toISOString(),engineVersion:READINESS_ENGINE_VERSION,scopes:results};
}
export async function evaluateEmployeeWorkReadiness(organizationId:string,employeeId:string,trigger:WorkReadinessTrigger="MANUAL_REEVALUATION",evaluatedAt=new Date()){const result=await computeEmployeeWorkReadiness(organizationId,employeeId,evaluatedAt);const snapshot=await prisma.workReadinessEvaluation.create({data:{organizationId,employeeId,evaluatedAt,evaluationTrigger:trigger,resultJson:result as unknown as Prisma.InputJsonValue,engineVersion:READINESS_ENGINE_VERSION}});return{snapshot,result}}
