import { createHash } from "node:crypto";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { Prisma, type ClientDocumentType, type User } from "@prisma/client";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { AuthorizationError, ResourceNotFoundError, ValidationError } from "@/domain/auth/errors";
import { requireOrganizationAccess, requirePermission } from "@/domain/permissions/authorization";
import { radiantCareTemplateAssets, renderRadiantCareTemplate } from "@/domain/clients/radiant-care-templates";

export const roiInput=z.object({direction:z.enum(["RELEASE_TO","RECEIVE_FROM","BOTH"]),recipientName:z.string().min(1).max(200),relationshipRole:z.string().max(150).optional(),address:z.string().max(500).optional(),phone:z.string().max(50).optional(),faxEmail:z.string().max(200).optional(),categories:z.array(z.enum(["FACE_SHEET_CONTACT","CSSP_ADDENDUM","ASSESSMENTS","PROGRESS_REPORTS","MEDICAL_HEALTH","MEDICATION","INCIDENT_REPORTS","BEHAVIOR_SUPPORT","SCHEDULES_ATTENDANCE","BILLING","OTHER"])).min(1),otherCategory:z.string().max(500).optional(),limitations:z.string().max(2000).optional(),purposes:z.array(z.enum(["SERVICE_COORDINATION","SERVICE_PLANNING_TEAM_MEETINGS","HEALTH_CARE","BILLING_FUNDING","PERSON_REPRESENTATIVE_REQUEST","OTHER"])).min(1),otherPurpose:z.string().max(500).optional(),effectiveDate:z.coerce.date(),expirationDate:z.coerce.date(),expirationEvent:z.string().max(500).optional(),clientPrintedName:z.string().max(200).optional(),clientDate:z.coerce.date().optional(),legalRepresentativePrintedName:z.string().max(200).optional(),legalRepresentativeDate:z.coerce.date().optional(),staffPrintedName:z.string().max(200).optional(),staffDate:z.coerce.date().optional()});
export const rightsInput=z.object({writtenCopyReceivedDate:z.coerce.date(),rightsExplainedDate:z.coerce.date(),explanationMethod:z.enum(["IN_PERSON","PHONE_VIDEO","INTERPRETER","EASY_READ_VISUAL","OTHER"]),explanationNotes:z.string().max(1000).optional(),annualReviewDate:z.coerce.date().optional(),grievanceContact:z.string().max(200).optional(),grievancePhoneEmail:z.string().max(300).optional(),clientPrintedName:z.string().max(200).optional(),clientDate:z.coerce.date().optional(),legalRepresentativePrintedName:z.string().max(200).optional(),legalRepresentativeDate:z.coerce.date().optional(),staffPrintedName:z.string().max(200).optional(),staffDate:z.coerce.date().optional()});
export const importedDocumentInput=z.object({documentType:z.enum(["INTAKE_CHECKLIST","FACE_SHEET","RIGHTS_ACKNOWLEDGMENT","ROI"]),fileName:z.string().trim().min(1).max(255).refine(value=>!/[\\/\0]/.test(value),"File name must not contain a path"),pdfBase64:z.string().min(1).max(14_000_000),disposition:z.enum(["HISTORICAL_COMPLETE","CURRENT_SIGNATURE_REQUIRED"]),completedAt:z.coerce.date().optional()}).superRefine((value,context)=>{if(value.disposition==="HISTORICAL_COMPLETE"&&!value.completedAt)context.addIssue({code:"custom",path:["completedAt"],message:"Completion date is required for a complete historical document"});if(value.completedAt&&value.completedAt>new Date())context.addIssue({code:"custom",path:["completedAt"],message:"Completion date cannot be in the future"})});
async function permission(user:Pick<User,"id">,organizationId:string,code:string){const{membership}=await requireOrganizationAccess(user,organizationId);await requirePermission(membership.id,code)}
async function template(organizationId:string,type:ClientDocumentType){const organizationTemplate=await prisma.clientDocumentTemplate.findFirst({where:{organizationId,documentType:type,status:"ACTIVE"},orderBy:{versionNumber:"desc"}});if(organizationTemplate)return organizationTemplate;const platformTemplate=await prisma.clientDocumentTemplate.findFirst({where:{organizationId:null,documentType:type,status:"ACTIVE"},orderBy:{versionNumber:"desc"}});if(!platformTemplate)throw new ResourceNotFoundError(`Active ${type} template not found`);return platformTemplate}
async function snapshot(organizationId:string,clientId:string){const client=await prisma.client.findFirst({where:{id:clientId,organizationId},include:{services:true,representatives:true,emergencyContacts:true,healthProfile:true,medications:true,contacts:{include:{professionalContact:true}},intakes:{include:{checklistItems:true},orderBy:{createdAt:"desc"},take:1}}});if(!client)throw new ResourceNotFoundError("Client not found");return JSON.parse(JSON.stringify(client)) as Prisma.InputJsonValue}
async function event(organizationId:string,userId:string,eventType:string,entityId:string,metadataJson?:Prisma.InputJsonValue){await prisma.auditEvent.create({data:{organizationId,actorUserId:userId,eventType,entityType:"ClientDocument",entityId,metadataJson}})}
async function withDraftLock<T>(organizationId:string,clientId:string,intakeId:string|undefined,type:ClientDocumentType,work:(tx:Prisma.TransactionClient)=>Promise<T>){return prisma.$transaction(async tx=>{const key=`client-document-draft:${organizationId}:${clientId}:${intakeId??"none"}:${type}`;await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${key}))`;return work(tx)})}

export async function generateClientDocument(user:Pick<User,"id">,organizationId:string,clientId:string,type:Exclude<ClientDocumentType,"ROI">,formData?:unknown){await permission(user,organizationId,"client.document.generate");const [definition,clientData]=await Promise.all([template(organizationId,type),snapshot(organizationId,clientId)]),structuredFormData=type==="RIGHTS_ACKNOWLEDGMENT"?rightsInput.optional().parse(formData)??null:formData??null,data={client:clientData,form:JSON.parse(JSON.stringify(structuredFormData))} as unknown as Prisma.InputJsonValue;const pdf=await renderDocument(definition,type,data,"DRAFT"),intake=await prisma.clientIntake.findFirst({where:{organizationId,clientId},orderBy:{createdAt:"desc"}});let regenerated=false;const document=await withDraftLock(organizationId,clientId,intake?.id,type,async tx=>{const existing=await tx.clientDocument.findFirst({where:{organizationId,clientId,intakeId:intake?.id,documentType:type,status:"DRAFT",source:"GENERATED",renewalOfDocumentId:null},orderBy:{generatedAt:"desc"}});regenerated=Boolean(existing);return existing?tx.clientDocument.update({where:{id:existing.id},data:{templateId:definition.id,snapshotJson:data,renderedPdf:Buffer.from(pdf),generatedByUserId:user.id,generatedAt:new Date()}}):tx.clientDocument.create({data:{organizationId,clientId,intakeId:intake?.id,templateId:definition.id,documentType:type,snapshotJson:data,renderedPdf:Buffer.from(pdf),generatedByUserId:user.id}})});await event(organizationId,user.id,regenerated?"client.document_draft_regenerated":"client.document_generated",document.id,{documentType:type,templateVersion:definition.versionNumber});return document}

export async function importClientDocument(user:Pick<User,"id">,organizationId:string,clientId:string,input:z.input<typeof importedDocumentInput>){await permission(user,organizationId,"client.document.generate");const data=importedDocumentInput.parse(input),client=await prisma.client.findFirst({where:{id:clientId,organizationId},select:{id:true}});if(!client)throw new ResourceNotFoundError("Client not found");let bytes:Buffer;try{bytes=Buffer.from(data.pdfBase64,"base64");if(!bytes.length||bytes.length>10_000_000||bytes.subarray(0,5).toString("ascii")!=="%PDF-")throw new Error();const parsed=await PDFDocument.load(bytes,{ignoreEncryption:false});if(!parsed.getPageCount())throw new Error()}catch{throw new ValidationError("Imported file must be a valid PDF no larger than 10 MB")}const definition=await template(organizationId,data.documentType),now=new Date(),complete=data.disposition==="HISTORICAL_COMPLETE",sourceDocumentHash=createHash("sha256").update(bytes).digest("hex"),storageBytes=new Uint8Array(bytes),document=await prisma.clientDocument.create({data:{organizationId,clientId,templateId:definition.id,documentType:data.documentType,status:complete?"COMPLETED":"READY_FOR_SIGNATURE",source:"IMPORTED",originalFileName:data.fileName,sourceDocumentHash,importedAt:now,finalizedAt:now,authoritativeCompletedAt:complete?data.completedAt:null,snapshotJson:{source:"IMPORTED",disposition:data.disposition} as Prisma.InputJsonValue,renderedPdf:storageBytes,finalPdf:complete?storageBytes:null,generatedByUserId:user.id},select:{id:true,documentType:true,status:true,source:true,originalFileName:true,sourceDocumentHash:true,importedAt:true,authoritativeCompletedAt:true}});await event(organizationId,user.id,complete?"client.document_historical_import_accepted":"client.document_import_ready_for_signature",document.id,{documentType:data.documentType,sourceDocumentHash});return document}

export async function createRoiAuthorization(user:Pick<User,"id">,organizationId:string,clientId:string,input:z.input<typeof roiInput>,renewalOfDocumentId?:string){await permission(user,organizationId,"client.document.generate");const data=roiInput.parse(input),max=new Date(data.effectiveDate);max.setFullYear(max.getFullYear()+1);if(data.expirationDate<=data.effectiveDate||data.expirationDate>max)throw new AuthorizationError("ROI expiration must be after the effective date and no more than one year later");if(renewalOfDocumentId)await renewalSource(organizationId,clientId,renewalOfDocumentId,"EXPIRATION_DATE_DRIVEN");const definition=await template(organizationId,"ROI"),clientSnapshot=await snapshot(organizationId,clientId),roiSnapshot=JSON.parse(JSON.stringify(data)) as Prisma.InputJsonValue,documentSnapshot={client:clientSnapshot,roi:roiSnapshot} as unknown as Prisma.InputJsonValue,pdf=await renderDocument(definition,"ROI",documentSnapshot,"DRAFT"),intake=await prisma.clientIntake.findFirst({where:{organizationId,clientId},orderBy:{createdAt:"desc"}});let regenerated=false;const result=await withDraftLock(organizationId,clientId,intake?.id,"ROI",async tx=>{const existing=!renewalOfDocumentId?await tx.clientDocument.findFirst({where:{organizationId,clientId,intakeId:intake?.id,documentType:"ROI",status:"DRAFT",source:"GENERATED",renewalOfDocumentId:null},include:{roiAuthorization:true},orderBy:{generatedAt:"desc"}}):null;regenerated=Boolean(existing);const document=existing?await tx.clientDocument.update({where:{id:existing.id},data:{templateId:definition.id,snapshotJson:documentSnapshot,renderedPdf:Buffer.from(pdf),generatedByUserId:user.id,generatedAt:new Date()}}):await tx.clientDocument.create({data:{organizationId,clientId,intakeId:intake?.id,templateId:definition.id,documentType:"ROI",snapshotJson:documentSnapshot,renderedPdf:Buffer.from(pdf),generatedByUserId:user.id,renewalOfDocumentId}});const roiValues={direction:data.direction,recipientName:data.recipientName,relationshipRole:data.relationshipRole,phone:data.phone,faxEmail:data.faxEmail,categories:data.categories,limitations:data.limitations,purposes:data.purposes,effectiveDate:data.effectiveDate,expirationDate:data.expirationDate,expirationEvent:data.expirationEvent,status:"ACTIVE" as const};const roi=existing?.roiAuthorization?await tx.roiAuthorization.update({where:{id:existing.roiAuthorization.id},data:roiValues}):await tx.roiAuthorization.create({data:{...roiValues,organizationId,clientId,documentId:document.id}});return{document,roi}});await event(organizationId,user.id,renewalOfDocumentId?"client.document_renewal_draft_created":regenerated?"client.document_draft_regenerated":"client.roi_created",result.document.id,{roiId:result.roi.id,expirationDate:data.expirationDate.toISOString(),renewalOfDocumentId});return result}

async function renewalSource(organizationId:string,clientId:string,documentId:string,policy:"ANNUAL"|"EXPIRATION_DATE_DRIVEN"){const source=await prisma.clientDocument.findFirst({where:{id:documentId,organizationId,clientId},include:{template:true,renewals:{select:{id:true}}}});if(!source)throw new ResourceNotFoundError("Renewal source document not found");if(source.status!=="COMPLETED"||!source.authoritativeCompletedAt)throw new AuthorizationError("Only an authoritatively completed document can be renewed");if(source.template.renewalPolicy!==policy)throw new AuthorizationError("Document renewal policy does not support this renewal");if(source.renewals.length)throw new AuthorizationError("A renewal cycle already exists for this document");return source}
export async function createRightsRenewal(user:Pick<User,"id">,organizationId:string,clientId:string,sourceDocumentId:string,formData?:unknown){await permission(user,organizationId,"client.document.generate");const source=await renewalSource(organizationId,clientId,sourceDocumentId,"ANNUAL"),definition=await template(organizationId,"RIGHTS_ACKNOWLEDGMENT"),clientData=await snapshot(organizationId,clientId),prior=(source.snapshotJson as {form?:unknown}).form,structuredFormData=rightsInput.parse(formData??prior),data={client:clientData,form:JSON.parse(JSON.stringify(structuredFormData))} as unknown as Prisma.InputJsonValue,pdf=await renderDocument(definition,"RIGHTS_ACKNOWLEDGMENT",data,"DRAFT"),intake=await prisma.clientIntake.findFirst({where:{organizationId,clientId},orderBy:{createdAt:"desc"}}),document=await prisma.clientDocument.create({data:{organizationId,clientId,intakeId:intake?.id,templateId:definition.id,documentType:"RIGHTS_ACKNOWLEDGMENT",snapshotJson:data,renderedPdf:Buffer.from(pdf),generatedByUserId:user.id,renewalOfDocumentId:source.id}});await event(organizationId,user.id,"client.document_renewal_draft_created",document.id,{renewalOfDocumentId:source.id,documentType:document.documentType,templateVersion:definition.versionNumber});return document}
export async function revokeRoi(user:Pick<User,"id">,organizationId:string,clientId:string,roiId:string,reason:string){await permission(user,organizationId,"client.update");const roi=await prisma.roiAuthorization.findFirst({where:{id:roiId,organizationId,clientId}});if(!roi)throw new ResourceNotFoundError("ROI not found");const updated=await prisma.roiAuthorization.update({where:{id:roi.id},data:{status:"REVOKED",revokedAt:new Date(),revocationReason:z.string().min(1).max(1000).parse(reason)}});await event(organizationId,user.id,"client.roi_revoked",roi.documentId??roi.id,{roiId});return updated}
export function roiExpirationState(roi:{status:string;expirationDate:Date},at=new Date()){if(roi.status==="REVOKED"||roi.status==="VOIDED")return roi.status;if(roi.expirationDate<at)return"EXPIRED";if(roi.expirationDate.getTime()-at.getTime()<=30*86400000)return"EXPIRING_SOON";return"ACTIVE"}

export async function finalizeClientDocument(user:Pick<User,"id">,organizationId:string,clientId:string,documentId:string){await permission(user,organizationId,"client.document.generate");const document=await prisma.clientDocument.findFirst({where:{id:documentId,organizationId,clientId},include:{template:true}});if(!document)throw new ResourceNotFoundError("Document not found");if(!document.renderedPdf)throw new AuthorizationError("Document has not been rendered");const renderedPdf=await renderDocument(document.template,document.documentType,document.snapshotJson as Prisma.InputJsonValue,"FINALIZED"),updated=await prisma.clientDocument.update({where:{id:document.id},data:{status:"READY_FOR_SIGNATURE",renderedPdf:Buffer.from(renderedPdf),finalizedAt:new Date()}});await event(organizationId,user.id,document.renewalOfDocumentId?"client.document_renewal_review_completed":"client.document_finalized",document.id,{documentType:document.documentType,renewalOfDocumentId:document.renewalOfDocumentId});return updated}
export async function getDocumentPdf(user:Pick<User,"id">,organizationId:string,clientId:string,documentId:string){await permission(user,organizationId,"client.document.read");const document=await prisma.clientDocument.findFirst({where:{id:documentId,organizationId,clientId}});if(!document)throw new ResourceNotFoundError("Document not found");const bytes=document.finalPdf??document.renderedPdf;if(!bytes)throw new ResourceNotFoundError("Rendered document not found");await event(organizationId,user.id,"client.document_downloaded",document.id,{finalized:Boolean(document.finalPdf)});return Buffer.from(bytes)}
export async function exportClientPacket(user:Pick<User,"id">,organizationId:string,clientId:string,documentIds:string[]){await permission(user,organizationId,"client.export");const documents=await prisma.clientDocument.findMany({where:{organizationId,clientId,id:{in:documentIds}}}),rank:Record<ClientDocumentType,number>={FACE_SHEET:0,RIGHTS_ACKNOWLEDGMENT:1,ROI:2,INTAKE_CHECKLIST:3};documents.sort((a,b)=>rank[a.documentType]-rank[b.documentType]||a.generatedAt.getTime()-b.generatedAt.getTime()||a.id.localeCompare(b.id));if(documents.length!==new Set(documentIds).size)throw new AuthorizationError("One or more documents are unavailable");const packet=await PDFDocument.create();for(const document of documents){const bytes=document.finalPdf??document.renderedPdf;if(!bytes)continue;const source=await PDFDocument.load(bytes),pages=await packet.copyPages(source,source.getPageIndices());pages.forEach(page=>packet.addPage(page))}const output=await packet.save();await prisma.auditEvent.create({data:{organizationId,actorUserId:user.id,eventType:"client.packet_exported",entityType:"Client",entityId:clientId,metadataJson:{documentIds:documents.map(row=>row.id),documentCount:documents.length,usedFinalizedBytes:documents.map(row=>Boolean(row.finalPdf))}}});return Buffer.from(output)}

async function renderDocument(definition:{name:string;versionNumber:number;contentJson:Prisma.JsonValue},type:ClientDocumentType,data:Prisma.InputJsonValue,status:"DRAFT"|"FINALIZED"){const content=definition.contentJson as Record<string,unknown>;if(content.renderer==="RADIANT_CARE_ACROFORM_V1"){if(content.asset!==radiantCareTemplateAssets[type])throw new AuthorizationError("Template asset does not match document type");return renderRadiantCareTemplate(type,data,status)}return createPdf(definition.name,data,{status,templateVersion:definition.versionNumber})}

async function createPdf(title:string,data:Prisma.InputJsonValue,meta:{status:string;templateVersion:number}){const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),newPage=()=>{const next=pdf.addPage([612,792]);next.drawRectangle({x:0,y:0,width:612,height:792,color:rgb(1,1,1)});return next};let page=newPage(),y=744;const line=(text:string,size=10,strong=false)=>{for(const part of wrap(text,92)){if(y<54){page=newPage();y=744}page.drawText(part,{x:54,y,size,font:strong?bold:font,color:rgb(0.08,0.12,0.18)});y-=size+5}};line(title,18,true);line(`Template version ${meta.templateVersion} | ${meta.status}`,9);line(`Generated ${new Date().toISOString()}`,9);y-=8;for(const [key,value] of flatten(data)){line(`${label(key)}: ${value}`,10)}for(const p of pdf.getPages()){p.drawText("Confidential client record",{x:54,y:28,size:8,font,color:rgb(.35,.35,.35)});if(meta.status==="DRAFT")p.drawText("DRAFT - NOT FINAL",{x:420,y:28,size:8,font:bold,color:rgb(.72,.12,.12)});p.drawText(`Page ${pdf.getPages().indexOf(p)+1} of ${pdf.getPageCount()}`,{x:500,y:28,size:8,font,color:rgb(.35,.35,.35)})}return pdf.save()}
const internalDocumentFields=new Set(["id","organizationId","clientId","intakeId","createdByUserId","completedByUserId","createdAt","updatedAt","lastSavedAt"]);
function flatten(value:unknown,prefix=""):Array<[string,string]>{if(value===null||value===undefined||value==="")return[];if(Array.isArray(value))return value.flatMap((item,index)=>flatten(item,`${prefix}[${index+1}]`));if(typeof value==="object")return Object.entries(value as Record<string,unknown>).filter(([key])=>!internalDocumentFields.has(key)&&!key.endsWith("Id")).flatMap(([key,item])=>flatten(item,prefix?`${prefix}.${key}`:key));return[[prefix,String(value)]]}
function label(value:string){return value.replaceAll("."," / ").replace(/([a-z])([A-Z])/g,"$1 $2").replaceAll("_"," ")}
function wrap(text:string,width:number){const words=text.replaceAll(/\s+/g," ").split(" "),lines:string[]=[];let current="";for(const word of words){if(`${current} ${word}`.trim().length>width){lines.push(current);current=word}else current=`${current} ${word}`.trim()}if(current)lines.push(current);return lines}
