import { createHash } from "node:crypto";
import { basename } from "node:path";
import {
  ClientImportClassification,
  ClientImportDocumentDisposition,
  ClientImportProposalState,
  ClientImportTarget,
  Prisma,
  type ClientDocumentType,
  type User,
} from "@prisma/client";
import { PDFDocument } from "pdf-lib";
import { getDocument } from "pdfjs-dist/legacy/build/pdf.mjs";
import { z } from "zod";
import { AuthorizationError, ResourceNotFoundError, ValidationError } from "@/domain/auth/errors";
import { requireOrganizationAccess, requirePermission } from "@/domain/permissions/authorization";
import { prisma } from "@/lib/prisma";
import { clientIntakeChecklistDefinitions, clientInput } from "./service";

export const CLIENT_IMPORT_MAX_FILES = 20;
export const CLIENT_IMPORT_MAX_FILE_BYTES = 10_000_000;
export const CLIENT_IMPORT_MAX_TOTAL_BYTES = 50_000_000;
const reviewedDate=z.preprocess(value=>typeof value==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(value)?`${value}T12:00:00Z`:value,z.coerce.date());
const fileInput = z.object({
  fileName: z.string().trim().min(1).max(255).refine(value => basename(value) === value && !/[\\/\0]/.test(value), "File name must not contain a path"),
  mimeType: z.literal("application/pdf"),
  pdfBase64: z.string().min(1).max(14_000_000),
});
export const createImportInput = z.object({
  requestId: z.string().uuid().optional(),
  target: z.nativeEnum(ClientImportTarget),
  existingClientId: z.string().cuid().optional(),
  files: z.array(fileInput).min(1).max(CLIENT_IMPORT_MAX_FILES),
}).superRefine((value, context) => {
  if (value.target === "UPDATE_EXISTING" && !value.existingClientId) context.addIssue({ code: "custom", path: ["existingClientId"], message: "An existing client is required" });
});
export const appendImportInput = z.object({
  sessionId: z.string().cuid(),
  files: z.array(fileInput).min(1).max(CLIENT_IMPORT_MAX_FILES),
});
export const reviewProposalInput = z.object({
  proposalId: z.string().cuid(),
  state: z.enum(["ACCEPTED", "CORRECTED", "REJECTED"]),
  correctedValue: z.union([z.string(), z.number(), z.boolean(), z.array(z.string())]).optional(),
}).superRefine((value, context) => {
  if (value.state === "CORRECTED" && value.correctedValue === undefined) context.addIssue({ code: "custom", path: ["correctedValue"], message: "A corrected value is required" });
});
const documentDecision = z.object({
  documentId: z.string().cuid(),
  disposition: z.nativeEnum(ClientImportDocumentDisposition),
  completedAt: reviewedDate.optional(),
}).superRefine((value, context) => {
  if (value.disposition === "HISTORICAL_COMPLETE" && !value.completedAt) context.addIssue({ code: "custom", path: ["completedAt"], message: "A confirmed completion date is required" });
  if (value.completedAt && value.completedAt > new Date()) context.addIssue({ code: "custom", path: ["completedAt"], message: "Completion date cannot be in the future" });
});
export const confirmImportInput = z.object({
  confirmed: z.literal(true),
  target: z.nativeEnum(ClientImportTarget),
  clientId: z.string().cuid().optional(),
  documents: z.array(documentDecision).max(CLIENT_IMPORT_MAX_FILES),
}).superRefine((value, context) => {
  if (value.target === "UPDATE_EXISTING" && !value.clientId) context.addIssue({ code: "custom", path: ["clientId"], message: "Select the existing client to update" });
});
export const importDocumentSettingsInput=z.object({documentId:z.string().cuid(),classification:z.nativeEnum(ClientImportClassification),disposition:z.nativeEnum(ClientImportDocumentDisposition),completedAt:reviewedDate.optional().nullable()}).superRefine((value,context)=>{
  if(value.completedAt&&value.completedAt>new Date())context.addIssue({code:"custom",path:["completedAt"],message:"Completion date cannot be in the future"});
});

export interface DocumentIntelligenceProvider {
  analyze(input: { bytes: Uint8Array; mimeType: "application/pdf" }): Promise<{ classification?: ClientImportClassification; fields: Array<{ fieldPath: string; value: unknown; sourceLocation?: string; confidence?: number }> }>;
}
export class UnconfiguredDocumentIntelligenceProvider implements DocumentIntelligenceProvider {
  async analyze(): Promise<never> { throw new AuthorizationError("OCR/document intelligence is not configured; preserve and review this document manually"); }
}

type Extracted = { fieldPath: string; value: Prisma.InputJsonValue; sourceLocation: string };
const fieldMap: Record<string, string> = {
  FACE_001_Legal_first_name:"client.legalFirstName",FACE_002_Last_name:"client.legalLastName",FACE_003_Preferred_name:"client.preferredName",FACE_004_Date_of_birth:"client.dateOfBirth",FACE_005_Gender:"client.gender",FACE_006_Phone:"client.phone",FACE_007_Email:"client.email",FACE_008_Street_address:"client.addressLine1",FACE_009_City:"client.city",FACE_010_State:"client.state",FACE_011_ZIP:"client.postalCode",FACE_012_MA_PMI_number:"client.maPmiNumber",FACE_013_Waiver_or_funding_program:"client.waiverProgram",FACE_014_County_tribe_of_financial_responsibility:"client.financialResponsibility",FACE_015_Primary_language:"client.primaryLanguage",FACE_016_Interpreter_needed_yes_no:"client.interpreterNeeded",FACE_017_Preferred_way_to_communicate:"client.preferredCommunication",FACE_025_Service_start_date:"services.0.startDate",FACE_034_Name:"representatives.0.name",FACE_035_Relationship:"representatives.0.relationship",FACE_036_Phone:"representatives.0.phone",FACE_038_Email:"representatives.0.email",FACE_039_Case_manager_name:"caseManager.name",FACE_040_Agency_county:"caseManager.agency",FACE_041_Phone:"caseManager.phone",FACE_042_Email:"caseManager.email",FACE_061_Primary_care_provider:"health.primaryCareProvider",FACE_062_Clinic:"health.clinic",FACE_063_Phone:"health.providerPhone",FACE_064_Dentist:"health.dentist",FACE_065_Pharmacy:"health.pharmacy",FACE_066_Pharmacy_phone:"health.pharmacyPhone",FACE_067_Health_insurance_health_plan:"health.healthInsurancePlan",FACE_068_Member_ID:"health.memberId",FACE_069_Diagnoses_health_conditions:"health.diagnoses",FACE_070_Allergies_medication_food_environmental_:"health.allergiesReactions",FACE_071_Special_diet_texture:"health.specialDietTexture",FACE_072_Choking_or_swallowing_risk_describe:"health.chokingSwallowingRisk",FACE_073_Seizures_type_protocol:"health.seizureProtocol",FACE_074_Mobility_adaptive_equipment:"health.mobilityEquipment",FACE_104_Other_health_needs_treatments_or_protoco:"health.otherHealthNeeds",FACE_107_Strengths_interests_and_what_is_importan:"client.strengthsInterests",FACE_108_Cultural_religious_or_personal_practices:"client.culturalPractices",FACE_109_Supports_needed_for_safety_communication:"client.supportNeeds",
  CHK_001_Person_served:"identity.fullName",CHK_002_Date_of_birth:"client.dateOfBirth",CHK_003_Service_start_date:"services.0.startDate",CHK_004_Service_s:"services.0.serviceType",
  RIGHTS_006_I_received_a_written_copy_of_these_right:"rights.writtenCopyReceivedDate",RIGHTS_008_These_rights_were_explained_to_me_in_a_w:"rights.rightsExplainedDate",RIGHTS_016_Annual_review_of_rights_use_for_yearly_r:"rights.annualReviewDate",RIGHTS_019_Date_Person_served:"rights.clientDate",RIGHTS_022_Date_Legal_representative_if_applicable:"rights.legalRepresentativeDate",RIGHTS_025_Date_Radiant_Care_staff:"rights.staffDate",
  ROI_001_Name:"identity.fullName",ROI_002_Date_of_birth:"client.dateOfBirth",ROI_003_MA_PMI_number:"client.maPmiNumber",ROI_007_Name_of_person_or_agency:"roi.recipientName",ROI_008_Relationship_role:"roi.relationshipRole",ROI_009_Address:"roi.address",ROI_010_Phone:"roi.phone",ROI_011_Fax_email:"roi.faxEmail",ROI_024_Limits_on_what_may_be_shared_if_any:"roi.limitations",ROI_032_This_authorization_expires_on_date_or_ev:"roi.expirationDate",ROI_033_Effective_date:"roi.effectiveDate",
};
const roiBooleanMap: Record<string, [string,string]> = {
  ROI_004_direction_Radiant_Care_may_RELEASE_infor:["roi.direction","RELEASE_TO"],ROI_005_direction_Radiant_Care_may_RECEIVE_infor:["roi.direction","RECEIVE_FROM"],ROI_006_direction_Both:["roi.direction","BOTH"],
  ROI_012_info_type_Face_sheet_contact_information:["roi.categories.FACE_SHEET_CONTACT","true"],ROI_013_info_type_CSSP_and_CSSP_addendum:["roi.categories.CSSP_ADDENDUM","true"],ROI_014_info_type_Assessments:["roi.categories.ASSESSMENTS","true"],ROI_015_info_type_Progress_reports:["roi.categories.PROGRESS_REPORTS","true"],ROI_016_info_type_Medical_health_information:["roi.categories.MEDICAL_HEALTH","true"],ROI_017_info_type_Medication_information:["roi.categories.MEDICATION","true"],ROI_025_purpose_Coordinate_services:["roi.purposes.SERVICE_COORDINATION","true"],ROI_026_purpose_Service_planning_team_meetings:["roi.purposes.SERVICE_PLANNING_TEAM_MEETINGS","true"],ROI_027_purpose_Health_care:["roi.purposes.HEALTH_CARE","true"],ROI_028_purpose_Billing_funding:["roi.purposes.BILLING_FUNDING","true"],ROI_029_purpose_Requested_by_person_legal_rep:["roi.purposes.PERSON_REPRESENTATIVE_REQUEST","true"],
};
const faceBooleanMap:Record<string,[string,Prisma.InputJsonValue]>={FACE_018_Living_situation_Own_home_apartment:["client.livingSituation","Own home or apartment"],FACE_019_Living_situation_Family_home:["client.livingSituation","Family home"],FACE_021_Service_s_to_be_provided_Individualized_:["services.types.IHS_WITHOUT_TRAINING",true],FACE_022_Service_s_to_be_provided_IHS_with_traini:["services.types.IHS_WITH_TRAINING",true],FACE_023_Service_s_to_be_provided_other:["services.types.OTHER",true],FACE_029_legal_rep_type_None_person_is_own_guardi:["representatives.none",true],FACE_030_legal_rep_type_Guardian:["representatives.0.representativeType","Guardian"],FACE_031_legal_rep_type_Conservator:["representatives.0.representativeType","Conservator"],FACE_032_legal_rep_type_Health_care_agent_POA:["representatives.0.representativeType","Health care agent / POA"],FACE_033_legal_rep_type_Parent_of_minor:["representatives.0.representativeType","Parent of minor"],FACE_100_Medication_responsibility_Person_manages:["health.medicationResponsibility","Person manages"],FACE_101_Medication_responsibility_Family_other_m:["health.medicationResponsibility","Family or other manages"],FACE_102_Medication_responsibility_Radiant_Care_a:["health.medicationResponsibility","Radiant Care assists"]};
function dynamicFacePath(name:string):string|null{const number=Number(name.match(/^FACE_(\d{3})_/)?.[1]);if(number>=46&&number<=60){const index=Math.floor((number-46)/5),field=["name","relationship","phone","alternatePhone","informationSharingAllowed"][(number-46)%5];return`emergencyContacts.${index}.${field}`}if(number>=75&&number<=99){const index=Math.floor((number-75)/5),field=["medication","dose","times","reason","prescriber"][(number-75)%5];return`medications.${index}.${field}`}return null}

async function authorize(user: Pick<User,"id">, organizationId: string, permission: string) { const { membership }=await requireOrganizationAccess(user,organizationId);await requirePermission(membership.id,permission); }
async function audit(organizationId:string,userId:string,eventType:string,entityId:string,metadataJson?:Prisma.InputJsonValue){await prisma.auditEvent.create({data:{organizationId,actorUserId:userId,eventType,entityType:"ClientImportSession",entityId,metadataJson}})}

function scalarFieldValue(field: unknown): string | boolean | null {
  const item=field as {getText?:()=>string|undefined;getSelected?:()=>string[];isChecked?:()=>boolean;getName:()=>string};
  if(item.getText){const value=item.getText()?.trim();return value||null}
  if(item.getSelected){const value=item.getSelected();return value.length?value.join(", "):null}
  if(item.isChecked)return item.isChecked();
  return null;
}
async function nativeText(bytes:Buffer){const task=getDocument({data:new Uint8Array(bytes),useSystemFonts:true});const pdf=await task.promise;const pages:string[]=[];for(let pageNumber=1;pageNumber<=pdf.numPages;pageNumber++){const page=await pdf.getPage(pageNumber),content=await page.getTextContent();pages.push(content.items.map(item=>("str" in item?item.str:"")).join(" "))}await task.destroy();return{pageCount:pdf.numPages,text:pages.join("\n")}}
function classify(fieldNames:string[],text:string):{classification:ClientImportClassification;signals:string[]}{const prefixes=new Set(fieldNames.map(name=>name.split("_")[0])),normalized=text.toLowerCase(),signals:string[]=[];let classification:ClientImportClassification="UNKNOWN";if(prefixes.has("FACE")||normalized.includes("client information / face sheet")&&normalized.includes("health information")){classification="FACE_SHEET";signals.push("face-sheet structure")}else if(prefixes.has("RIGHTS")||normalized.includes("service recipient rights")&&normalized.includes("protection-related rights")){classification="RIGHTS_ACKNOWLEDGMENT";signals.push("rights structure")}else if(prefixes.has("ROI")||normalized.includes("authorization to release information")&&normalized.includes("this authorization expires")){classification="ROI";signals.push("roi structure")}else if(prefixes.has("CHK")||normalized.includes("intake checklist")&&normalized.includes("first day of service")){classification="INTAKE_CHECKLIST";signals.push("checklist structure")}return{classification,signals}}
function normalize(value:Prisma.JsonValue){return JSON.stringify(value).trim().toLowerCase().replace(/\s+/g," ")}

async function analyzePdf(bytes:Buffer){
  let pdf:PDFDocument;try{pdf=await PDFDocument.load(bytes,{ignoreEncryption:false})}catch{throw new ValidationError("Imported file must be a valid, unencrypted PDF")}
  const fields=pdf.getForm().getFields(),fieldNames=fields.map(field=>field.getName()),extracted:Extracted[]=[];
  for(const field of fields){const name=field.getName(),value=scalarFieldValue(field);if(value===null||value===false||value==="")continue;const direct=fieldMap[name]??dynamicFacePath(name),booleanMapping=roiBooleanMap[name]??faceBooleanMap[name];if(direct)extracted.push({fieldPath:direct,value,sourceLocation:`PDF form field ${name}`});else if(booleanMapping&&value===true)extracted.push({fieldPath:booleanMapping[0],value:booleanMapping[1]==="true"?true:booleanMapping[1],sourceLocation:`PDF form field ${name}`})}
  let text="",pageCount=pdf.getPageCount();try{const result=await nativeText(bytes);text=result.text;pageCount=result.pageCount}catch{/* PDF remains reviewable when text extraction is unavailable. */}
  const result=classify(fieldNames,text),ocrRequired=fields.length===0&&text.replace(/\s+/g,"").length<40;
  return{...result,extracted,text:text.slice(0,200_000),pageCount,ocrRequired,method:fields.length?"PDF_FORM_FIELD" as const:text.trim()?"NATIVE_TEXT" as const:null};
}

async function analyzeFiles(files:z.output<typeof fileInput>[]){
  const analyzed=[] as Array<{fileName:string;mimeType:string;bytes:Buffer;sha256:string;result:Awaited<ReturnType<typeof analyzePdf>>}>;let totalBytes=0;
  for(const file of files){const bytes=Buffer.from(file.pdfBase64,"base64");totalBytes+=bytes.length;if(!bytes.length||bytes.length>CLIENT_IMPORT_MAX_FILE_BYTES||bytes.subarray(0,5).toString("ascii")!=="%PDF-")throw new ValidationError("Each upload must be a valid PDF no larger than 10 MB");if(totalBytes>CLIENT_IMPORT_MAX_TOTAL_BYTES)throw new ValidationError("Selected PDFs must total no more than 50 MB");analyzed.push({fileName:file.fileName,mimeType:file.mimeType,bytes,sha256:createHash("sha256").update(bytes).digest("hex"),result:await analyzePdf(bytes)})}
  if(new Set(analyzed.map(item=>item.sha256)).size!==analyzed.length)throw new ValidationError("The same document cannot be uploaded twice in one import");return analyzed;
}
async function persistAnalyzedDocuments(tx:Prisma.TransactionClient,organizationId:string,sessionId:string,analyzed:Awaited<ReturnType<typeof analyzeFiles>>){for(const item of analyzed){const document=await tx.clientImportDocument.create({data:{organizationId,sessionId,originalFileName:item.fileName,mimeType:item.mimeType,originalBytes:new Uint8Array(item.bytes),sha256:item.sha256,classification:item.result.classification,status:item.result.ocrRequired?"OCR_REQUIRED":item.result.extracted.length?"EXTRACTED":"REVIEW_REQUIRED",extractionMethod:item.result.method,pageCount:item.result.pageCount,ocrRequired:item.result.ocrRequired,extractedText:item.result.text||null,classificationSignals:item.result.signals}});if(item.result.extracted.length)await tx.clientImportProposal.createMany({data:item.result.extracted.map(field=>({organizationId,sessionId,documentId:document.id,fieldPath:field.fieldPath,proposedValue:field.value,sourceLocation:field.sourceLocation,extractionMethod:"PDF_FORM_FIELD",confidence:1}))})}}

export async function createClientImport(user:Pick<User,"id">,organizationId:string,input:z.input<typeof createImportInput>){
  await authorize(user,organizationId,"client.create");const data=createImportInput.parse(input);
  if(data.requestId){const prior=await prisma.clientImportSession.findFirst({where:{organizationId,creationRequestId:data.requestId,uploadedByUserId:user.id},select:{id:true}});if(prior)return getClientImport(user,organizationId,prior.id)}
  if(data.existingClientId&&!await prisma.client.findFirst({where:{id:data.existingClientId,organizationId},select:{id:true}}))throw new ResourceNotFoundError("Client not found");
  const analyzed=await analyzeFiles(data.files);
  const session=await prisma.$transaction(async tx=>{const created=await tx.clientImportSession.create({data:{organizationId,uploadedByUserId:user.id,creationRequestId:data.requestId,target:data.target,existingClientId:data.existingClientId}});await persistAnalyzedDocuments(tx,organizationId,created.id,analyzed);return created});
  await reconcileProposals(session.id);await audit(organizationId,user.id,"client.import_created",session.id,{documentCount:analyzed.length,classifications:analyzed.map(item=>item.result.classification),ocrRequired:analyzed.filter(item=>item.result.ocrRequired).length});const persisted=await prisma.clientImportDocument.findMany({where:{sessionId:session.id},select:{id:true,classification:true,status:true,ocrRequired:true}});for(const document of persisted)await audit(organizationId,user.id,"client.import_document_analyzed",session.id,{documentId:document.id,classification:document.classification,status:document.status,ocrRequired:document.ocrRequired});return getClientImport(user,organizationId,session.id);
}
export async function appendClientImportDocuments(user:Pick<User,"id">,organizationId:string,input:z.input<typeof appendImportInput>){await authorize(user,organizationId,"client.update");const data=appendImportInput.parse(input),session=await prisma.clientImportSession.findFirst({where:{id:data.sessionId,organizationId},include:{documents:{select:{sha256:true,originalBytes:true}}}});if(!session)throw new ResourceNotFoundError("Import session not found");if(session.status!=="REVIEW_REQUIRED")throw new AuthorizationError("Import review is closed");const analyzed=await analyzeFiles(data.files),existingBytes=session.documents.reduce((sum,item)=>sum+item.originalBytes.length,0);if(session.documents.length+analyzed.length>CLIENT_IMPORT_MAX_FILES)throw new ValidationError(`An import can contain no more than ${CLIENT_IMPORT_MAX_FILES} PDFs`);if(existingBytes+analyzed.reduce((sum,item)=>sum+item.bytes.length,0)>CLIENT_IMPORT_MAX_TOTAL_BYTES)throw new ValidationError("Import PDFs must total no more than 50 MB");const existing=new Set(session.documents.map(item=>item.sha256));if(analyzed.some(item=>existing.has(item.sha256)))throw new ValidationError("This document is already part of the import. It was not processed again.");await prisma.$transaction(tx=>persistAnalyzedDocuments(tx,organizationId,session.id,analyzed));await reconcileProposals(session.id);await audit(organizationId,user.id,"client.import_documents_added",session.id,{documentCount:analyzed.length,sha256:analyzed.map(item=>item.sha256)});return getClientImport(user,organizationId,session.id)}
async function reconcileProposals(sessionId:string){const proposals=await prisma.clientImportProposal.findMany({where:{sessionId}}),groups=new Map<string,typeof proposals>();for(const proposal of proposals)groups.set(proposal.fieldPath,[...(groups.get(proposal.fieldPath)??[]),proposal]);for(const group of groups.values()){if(group.length<2)continue;const values=new Set(group.map(item=>normalize(item.proposedValue)));await prisma.clientImportProposal.updateMany({where:{id:{in:group.map(item=>item.id)},state:"PROPOSED"},data:{state:values.size===1?"CORROBORATED":"CONFLICT"}})}}
function reviewedValue(proposal:{state:ClientImportProposalState;proposedValue:Prisma.JsonValue;correctedValue:Prisma.JsonValue|null}){return proposal.state==="CORRECTED"?proposal.correctedValue:proposal.proposedValue}
async function matches(organizationId:string,proposals:Array<{fieldPath:string;state:ClientImportProposalState;proposedValue:Prisma.JsonValue;correctedValue:Prisma.JsonValue|null}>){const values=new Map(proposals.filter(item=>item.state!=="REJECTED").map(item=>[item.fieldPath,reviewedValue(item)])),first=String(values.get("client.legalFirstName")??"").trim(),last=String(values.get("client.legalLastName")??"").trim(),dob=String(values.get("client.dateOfBirth")??"").trim(),pmi=String(values.get("client.maPmiNumber")??"").trim();if(!pmi&&!(first&&last&&dob))return[];return prisma.client.findMany({where:{organizationId,OR:[...(pmi?[{maPmiNumber:{equals:pmi,mode:"insensitive" as const}}]:[]),...(first&&last&&dob?[{legalFirstName:{equals:first,mode:"insensitive" as const},legalLastName:{equals:last,mode:"insensitive" as const},dateOfBirth:new Date(dob)}]:[])]},select:{id:true,legalFirstName:true,legalLastName:true,dateOfBirth:true,maPmiNumber:true},take:10})}
export async function getClientImport(user:Pick<User,"id">,organizationId:string,sessionId:string){await authorize(user,organizationId,"client.read");const session=await prisma.clientImportSession.findFirst({where:{id:sessionId,organizationId},include:{documents:{select:{id:true,originalFileName:true,mimeType:true,sha256:true,classification:true,status:true,extractionMethod:true,pageCount:true,ocrRequired:true,disposition:true,reviewedCompletedAt:true,confirmedDocumentId:true,createdAt:true}},proposals:{orderBy:[{fieldPath:"asc"},{createdAt:"asc"}]}}});if(!session)throw new ResourceNotFoundError("Import session not found");return{...session,possibleMatches:await matches(organizationId,session.proposals)}}
export async function getClientImportPdf(user:Pick<User,"id">,organizationId:string,sessionId:string,documentId:string){await authorize(user,organizationId,"client.read");const document=await prisma.clientImportDocument.findFirst({where:{id:documentId,sessionId,organizationId},select:{originalBytes:true,originalFileName:true}});if(!document)throw new ResourceNotFoundError("Import document not found");return document}
export async function listClientImports(user:Pick<User,"id">,organizationId:string,existingClientId?:string){await authorize(user,organizationId,"client.read");return prisma.clientImportSession.findMany({where:{organizationId,existingClientId},select:{id:true,status:true,target:true,existingClientId:true,createdAt:true,updatedAt:true,_count:{select:{documents:true,proposals:true}}},orderBy:{updatedAt:"desc"},take:20})}
export async function reviewClientImportProposal(user:Pick<User,"id">,organizationId:string,sessionId:string,input:z.input<typeof reviewProposalInput>){await authorize(user,organizationId,"client.update");const data=reviewProposalInput.parse(input),proposal=await prisma.clientImportProposal.findFirst({where:{id:data.proposalId,sessionId,organizationId},include:{session:true}});if(!proposal)throw new ResourceNotFoundError("Import proposal not found");if(proposal.session.status!=="REVIEW_REQUIRED")throw new AuthorizationError("Import review is closed");await prisma.clientImportProposal.update({where:{id:proposal.id},data:{state:data.state,correctedValue:data.state==="CORRECTED"?data.correctedValue as Prisma.InputJsonValue:Prisma.DbNull,reviewedByUserId:user.id,reviewedAt:new Date()}});await audit(organizationId,user.id,data.state==="REJECTED"?"client.import_proposal_rejected":"client.import_proposal_reviewed",sessionId,{proposalId:proposal.id,fieldPath:proposal.fieldPath,state:data.state});return getClientImport(user,organizationId,sessionId)}
export async function classifyClientImportDocument(user:Pick<User,"id">,organizationId:string,sessionId:string,documentId:string,classification:ClientImportClassification){await authorize(user,organizationId,"client.update");const document=await prisma.clientImportDocument.findFirst({where:{id:documentId,sessionId,organizationId},include:{session:true}});if(!document)throw new ResourceNotFoundError("Import document not found");if(document.session.status!=="REVIEW_REQUIRED")throw new AuthorizationError("Import review is closed");await prisma.clientImportDocument.update({where:{id:document.id},data:{classification,status:document.ocrRequired?"OCR_REQUIRED":"REVIEW_REQUIRED",classificationSignals:["authorized manual classification"]}});await audit(organizationId,user.id,"client.import_document_classified",sessionId,{documentId,classification,method:"MANUAL"});return getClientImport(user,organizationId,sessionId)}
export async function updateClientImportDocumentSettings(user:Pick<User,"id">,organizationId:string,sessionId:string,input:z.input<typeof importDocumentSettingsInput>){await authorize(user,organizationId,"client.update");const data=importDocumentSettingsInput.parse(input),document=await prisma.clientImportDocument.findFirst({where:{id:data.documentId,sessionId,organizationId},include:{session:true}});if(!document)throw new ResourceNotFoundError("Import document not found");if(document.session.status!=="REVIEW_REQUIRED")throw new AuthorizationError("Import review is closed");await prisma.clientImportDocument.update({where:{id:document.id},data:{classification:data.classification,disposition:data.disposition,reviewedCompletedAt:data.disposition==="HISTORICAL_COMPLETE"?data.completedAt:null,classificationSignals:document.classification===data.classification?undefined:["authorized manual classification"]}});await audit(organizationId,user.id,"client.import_document_settings_reviewed",sessionId,{documentId:document.id,classification:data.classification,disposition:data.disposition,completedAt:data.completedAt?.toISOString()??null});return getClientImport(user,organizationId,sessionId)}
export async function acceptRemainingClientImportProposals(user:Pick<User,"id">,organizationId:string,sessionId:string){await authorize(user,organizationId,"client.update");const session=await prisma.clientImportSession.findFirst({where:{id:sessionId,organizationId},select:{status:true}});if(!session)throw new ResourceNotFoundError("Import session not found");if(session.status!=="REVIEW_REQUIRED")throw new AuthorizationError("Import review is closed");const result=await prisma.clientImportProposal.updateMany({where:{sessionId,organizationId,state:{in:["PROPOSED","CORROBORATED"]}},data:{state:"ACCEPTED",reviewedByUserId:user.id,reviewedAt:new Date()}});await audit(organizationId,user.id,"client.import_proposals_bulk_accepted",sessionId,{count:result.count,conflictsExcluded:true});return getClientImport(user,organizationId,sessionId)}
export async function resolveClientImportConflict(user:Pick<User,"id">,organizationId:string,sessionId:string,proposalId:string,correctedValue?:unknown){await authorize(user,organizationId,"client.update");const chosen=await prisma.clientImportProposal.findFirst({where:{id:proposalId,sessionId,organizationId},include:{session:true}});if(!chosen)throw new ResourceNotFoundError("Import proposal not found");if(chosen.session.status!=="REVIEW_REQUIRED")throw new AuthorizationError("Import review is closed");const group=await prisma.clientImportProposal.findMany({where:{sessionId,organizationId,fieldPath:chosen.fieldPath}});if(!group.some(item=>item.state==="CONFLICT"))throw new ValidationError("This field no longer has an unresolved conflict");const now=new Date();await prisma.$transaction(async tx=>{await tx.clientImportProposal.updateMany({where:{id:{in:group.map(item=>item.id)}},data:{state:"REJECTED",correctedValue:Prisma.DbNull,reviewedByUserId:user.id,reviewedAt:now}});await tx.clientImportProposal.update({where:{id:chosen.id},data:{state:correctedValue===undefined?"ACCEPTED":"CORRECTED",correctedValue:correctedValue===undefined?Prisma.DbNull:correctedValue as Prisma.InputJsonValue,reviewedByUserId:user.id,reviewedAt:now}})});await audit(organizationId,user.id,"client.import_conflict_resolved",sessionId,{fieldPath:chosen.fieldPath,selectedProposalId:chosen.id,sourceDocumentId:chosen.documentId,corrected:correctedValue!==undefined});return getClientImport(user,organizationId,sessionId)}

function asDate(value:unknown){const date=new Date(String(value));if(Number.isNaN(date.getTime()))throw new ValidationError("A reviewed date is invalid");return date}
function objectValues(values:Map<string,Prisma.JsonValue>,prefix:string){const result:Record<string,Prisma.JsonValue>={};for(const[key,value]of values)if(key.startsWith(`${prefix}.`)&&!key.slice(prefix.length+1).includes("."))result[key.slice(prefix.length+1)]=value;return result}
function typeFor(classification:ClientImportClassification):ClientDocumentType|null{return classification==="UNKNOWN"?null:classification}
export async function confirmClientImport(user:Pick<User,"id">,organizationId:string,sessionId:string,input:z.input<typeof confirmImportInput>){
  await authorize(user,organizationId,"client.update");const data=confirmImportInput.parse(input),session=await prisma.clientImportSession.findFirst({where:{id:sessionId,organizationId},include:{documents:true,proposals:true}});if(!session)throw new ResourceNotFoundError("Import session not found");if(session.status==="CONFIRMED"&&session.existingClientId)return{clientId:session.existingClientId,createdDocuments:session.documents.flatMap(item=>item.confirmedDocumentId?[item.confirmedDocumentId]:[]),recovered:true};if(session.status!=="REVIEW_REQUIRED")throw new AuthorizationError("Import session is not open for confirmation");if(session.proposals.some(item=>["PROPOSED","CORROBORATED","CONFLICT"].includes(item.state)))throw new AuthorizationError("Every proposed value and conflict must be explicitly accepted, corrected, or rejected");
  const chosen=session.proposals.filter(item=>item.state==="ACCEPTED"||item.state==="CORRECTED"),values=new Map<string,Prisma.JsonValue>();for(const item of chosen){const value=reviewedValue(item);if(value===null)continue;const prior=values.get(item.fieldPath);if(prior!==undefined&&normalize(prior)!==normalize(value))throw new AuthorizationError(`Accepted values still conflict for ${item.fieldPath}`);values.set(item.fieldPath,value)}
  const scalarKeys=["legalFirstName","legalLastName","preferredName","gender","phone","email","addressLine1","city","state","postalCode","maPmiNumber","waiverProgram","financialResponsibility","primaryLanguage","preferredCommunication","strengthsInterests","culturalPractices","supportNeeds"] as const,clientData:Record<string,unknown>={};for(const key of scalarKeys){const value=values.get(`client.${key}`);if(value!==undefined)clientData[key]=String(value)}if(values.has("client.interpreterNeeded"))clientData.interpreterNeeded=String(values.get("client.interpreterNeeded")).toLowerCase().startsWith("y")||values.get("client.interpreterNeeded")===true;if(values.has("client.dateOfBirth"))clientData.dateOfBirth=asDate(values.get("client.dateOfBirth"));
  if(data.target==="CREATE_NEW")clientInput.parse(clientData);const targetId=data.target==="UPDATE_EXISTING"?data.clientId:undefined;if(targetId&&!await prisma.client.findFirst({where:{id:targetId,organizationId},select:{id:true}}))throw new ResourceNotFoundError("Client not found");
  const decisions=new Map(data.documents.map(item=>[item.documentId,item]));if(data.documents.some(item=>!session.documents.some(document=>document.id===item.documentId)))throw new ResourceNotFoundError("Import document not found");if(session.documents.some(document=>!decisions.has(document.id)))throw new ValidationError("Review the settings for every imported document before confirmation");
  const documentTypes=[...new Set(session.documents.map(document=>typeFor(document.classification)).filter((value):value is ClientDocumentType=>Boolean(value)))],templates=await prisma.clientDocumentTemplate.findMany({where:{documentType:{in:documentTypes},status:"ACTIVE",OR:[{organizationId},{organizationId:null}]},orderBy:[{organizationId:"desc"},{versionNumber:"desc"}]});
  const now=new Date(),result=await prisma.$transaction(async tx=>{
    let clientId=targetId;if(clientId)await tx.client.update({where:{id:clientId},data:clientData});else{const client=await tx.client.create({data:{...(clientData as z.output<typeof clientInput>),organizationId,createdByUserId:user.id,status:"INTAKE_IN_PROGRESS"}});clientId=client.id;await tx.clientIntake.create({data:{organizationId,clientId,status:"IN_PROGRESS",checklistItems:{create:clientIntakeChecklistDefinitions.map(([code,label],index)=>({code,label,sequence:index+1}))}}})}
    const service=objectValues(values,"services.0"),serviceTypes=[...values.keys()].filter(key=>key.startsWith("services.types.")).map(key=>key.split(".").at(-1)!);if(service.serviceType)serviceTypes.push(String(service.serviceType));for(const serviceType of new Set(serviceTypes)){const startDate=service.startDate?asDate(service.startDate):null;if(!await tx.clientService.findFirst({where:{organizationId,clientId,serviceType,startDate}}))await tx.clientService.create({data:{organizationId,clientId,serviceType,startDate,status:"PROPOSED"}})}
    const representative=objectValues(values,"representatives.0");if(representative.name&&!values.has("representatives.none")&&!await tx.clientRepresentative.findFirst({where:{organizationId,clientId,name:String(representative.name)}}))await tx.clientRepresentative.create({data:{organizationId,clientId,name:String(representative.name),representativeType:String(representative.representativeType??"OTHER"),relationship:representative.relationship?String(representative.relationship):null,email:representative.email?String(representative.email):null,phone:representative.phone?String(representative.phone):null}});
    const health=objectValues(values,"health");if(Object.keys(health).length)await tx.clientHealthProfile.upsert({where:{clientId},create:{organizationId,clientId,...Object.fromEntries(Object.entries(health).map(([key,value])=>[key,String(value)]))},update:Object.fromEntries(Object.entries(health).map(([key,value])=>[key,String(value)]))});
    for(let index=0;index<3;index++){const contact=objectValues(values,`emergencyContacts.${index}`);if(contact.name&&contact.relationship&&contact.phone&&!await tx.clientEmergencyContact.findFirst({where:{organizationId,clientId,name:String(contact.name),phone:String(contact.phone)}}))await tx.clientEmergencyContact.create({data:{organizationId,clientId,name:String(contact.name),relationship:String(contact.relationship),phone:String(contact.phone),alternatePhone:contact.alternatePhone?String(contact.alternatePhone):null,informationSharingAllowed:String(contact.informationSharingAllowed).toLowerCase().startsWith("y")||contact.informationSharingAllowed===true}})}
    for(let index=0;index<5;index++){const medication=objectValues(values,`medications.${index}`);if(medication.medication&&!await tx.clientMedication.findFirst({where:{organizationId,clientId,medication:String(medication.medication)}}))await tx.clientMedication.create({data:{organizationId,clientId,medication:String(medication.medication),dose:medication.dose?String(medication.dose):null,times:medication.times?String(medication.times):null,reason:medication.reason?String(medication.reason):null,prescriber:medication.prescriber?String(medication.prescriber):null}})}
    const caseManager=objectValues(values,"caseManager");if(caseManager.name){let contact=await tx.professionalContact.findFirst({where:{organizationId,name:String(caseManager.name),agency:caseManager.agency?String(caseManager.agency):null}});contact??=await tx.professionalContact.create({data:{organizationId,name:String(caseManager.name),agency:caseManager.agency?String(caseManager.agency):null,contactType:"CASE_MANAGER",email:caseManager.email?String(caseManager.email):null,phone:caseManager.phone?String(caseManager.phone):null}});await tx.clientProfessionalContact.upsert({where:{clientId_professionalContactId_role:{clientId,professionalContactId:contact.id,role:"CASE_MANAGER"}},create:{organizationId,clientId,professionalContactId:contact.id,role:"CASE_MANAGER",isPrimary:true},update:{isPrimary:true}})}
    const createdDocuments:string[]=[];for(const imported of session.documents){const decision=decisions.get(imported.id);if(!decision||decision.disposition==="PRESERVE_ONLY"||!typeFor(imported.classification))continue;const documentType=typeFor(imported.classification)!;const template=templates.find(item=>item.documentType===documentType&&item.organizationId===organizationId)??templates.find(item=>item.documentType===documentType&&item.organizationId===null);if(!template)throw new ResourceNotFoundError(`Active ${documentType} template not found`);const complete=decision.disposition==="HISTORICAL_COMPLETE",document=await tx.clientDocument.create({data:{organizationId,clientId,templateId:template.id,documentType,status:complete?"COMPLETED":"READY_FOR_SIGNATURE",source:"IMPORTED",originalFileName:imported.originalFileName,sourceDocumentHash:imported.sha256,importedAt:now,finalizedAt:now,authoritativeCompletedAt:complete?decision.completedAt:null,snapshotJson:{source:"IMPORTED",importSessionId:session.id,disposition:decision.disposition},renderedPdf:imported.originalBytes,finalPdf:complete?imported.originalBytes:null,generatedByUserId:user.id}});createdDocuments.push(document.id);await tx.clientImportDocument.update({where:{id:imported.id},data:{disposition:decision.disposition,status:"ACCEPTED",confirmedDocumentId:document.id}});if(documentType==="ROI"&&complete){const effective=values.get("roi.effectiveDate"),expiration=values.get("roi.expirationDate"),recipient=values.get("roi.recipientName"),direction=values.get("roi.direction"),categories=[...values.keys()].filter(key=>key.startsWith("roi.categories.")).map(key=>key.split(".").at(-1)!),purposes=[...values.keys()].filter(key=>key.startsWith("roi.purposes.")).map(key=>key.split(".").at(-1)!);if(effective&&expiration&&recipient&&direction&&categories.length&&purposes.length){const effectiveDate=asDate(effective),expirationDate=asDate(expiration),maximum=new Date(effectiveDate);maximum.setFullYear(maximum.getFullYear()+1);if(expirationDate<=effectiveDate||expirationDate>maximum)throw new AuthorizationError("Confirmed ROI expiration must be after the effective date and no more than one year later");await tx.roiAuthorization.create({data:{organizationId,clientId,documentId:document.id,direction:String(direction) as "RELEASE_TO"|"RECEIVE_FROM"|"BOTH",recipientName:String(recipient),relationshipRole:values.get("roi.relationshipRole")?String(values.get("roi.relationshipRole")):null,phone:values.get("roi.phone")?String(values.get("roi.phone")):null,faxEmail:values.get("roi.faxEmail")?String(values.get("roi.faxEmail")):null,categories,purposes,limitations:values.get("roi.limitations")?String(values.get("roi.limitations")):null,effectiveDate,expirationDate,status:"ACTIVE"}})}}}
    await tx.clientImportSession.update({where:{id:session.id},data:{status:"CONFIRMED",target:data.target,existingClientId:clientId,confirmedAt:now}});return{clientId,createdDocuments};
  });
  await audit(organizationId,user.id,"client.import_confirmed",session.id,{target:data.target,clientId:result.clientId,acceptedDocumentCount:result.createdDocuments.length});for(const documentId of result.createdDocuments)await audit(organizationId,user.id,"client.import_historical_document_accepted",session.id,{clientId:result.clientId,documentId});await audit(organizationId,user.id,"client.documentation_readiness_reconciled",session.id,{clientId:result.clientId});return result;
}
export async function cancelClientImport(user:Pick<User,"id">,organizationId:string,sessionId:string){await authorize(user,organizationId,"client.update");const result=await prisma.clientImportSession.updateMany({where:{id:sessionId,organizationId,status:"REVIEW_REQUIRED"},data:{status:"CANCELED",canceledAt:new Date()}});if(!result.count)throw new ResourceNotFoundError("Open import session not found");await audit(organizationId,user.id,"client.import_canceled",sessionId);return{sessionId,status:"CANCELED" as const}}
