import type { ClientDocumentRenewalPolicy, Prisma, User } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { requireOrganizationAccess, requirePermission } from "@/domain/permissions/authorization";

export type ClientRenewalStatus = "CURRENT" | "DUE_SOON" | "OVERDUE";
export const renewalDocumentSelect={id:true,clientId:true,templateId:true,documentType:true,status:true,authoritativeCompletedAt:true,renewalOfDocumentId:true,template:{select:{id:true,name:true,renewalPolicy:true,renewalWarningDays:true}},roiAuthorization:{select:{status:true,expirationDate:true}},envelope:{select:{status:true,completedAt:true}}} as const;
export type RenewalDocument = Prisma.ClientDocumentGetPayload<{select:typeof renewalDocumentSelect}>;

function calendarParts(value:Date,timeZone:string){const parts=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(value);const get=(type:string)=>Number(parts.find(part=>part.type===type)?.value);return{year:get("year"),month:get("month"),day:get("day")}}
function dateKey(parts:{year:number;month:number;day:number}){return`${parts.year.toString().padStart(4,"0")}-${parts.month.toString().padStart(2,"0")}-${parts.day.toString().padStart(2,"0")}`}
function utcDate(parts:{year:number;month:number;day:number}){return new Date(Date.UTC(parts.year,parts.month-1,parts.day))}
function daysInMonth(year:number,month:number){return new Date(Date.UTC(year,month,0)).getUTCDate()}
export function annualRenewalDueDate(completedAt:Date,timeZone:string){const source=calendarParts(completedAt,timeZone),year=source.year+1;return utcDate({year,month:source.month,day:Math.min(source.day,daysInMonth(year,source.month))})}
export function renewalState(dueDate:Date,warningDays:number,at:Date,timeZone:string):{status:ClientRenewalStatus;days:number}{const due=utcDate(calendarParts(dueDate,"UTC")),today=utcDate(calendarParts(at,timeZone)),days=Math.round((due.getTime()-today.getTime())/86_400_000);return{status:days<0?"OVERDUE":days<=warningDays?"DUE_SOON":"CURRENT",days}}

function completedAt(document:RenewalDocument){if(document.status!=="COMPLETED")return null;return document.authoritativeCompletedAt??document.envelope?.completedAt??null}
function latestCompletedInChain(root:RenewalDocument,byParent:Map<string,RenewalDocument>){let current=root,pending:RenewalDocument|null=null;for(;;){const next=byParent.get(current.id);if(!next)break;if(completedAt(next)){current=next;continue}if(next.status!=="VOIDED")pending=next;break}return{current,pending}}
function workflow(document:RenewalDocument|null){return document?{documentId:document.id,status:document.status,envelopeStatus:document.envelope?.status??null}:null}

export function deriveClientRenewalSummary(documents:RenewalDocument[],timeZone:string,at=new Date()){
  const relevant=documents.filter(document=>document.template.renewalPolicy!=="NONE"&&document.status!=="VOIDED");
  const byParent=new Map(relevant.filter(document=>document.renewalOfDocumentId).map(document=>[document.renewalOfDocumentId!,document]));
  const cycles:{documentId:string;templateId:string;templateName:string;documentType:string;policy:ClientDocumentRenewalPolicy;completedAt:string;dueDate:string;status:ClientRenewalStatus;daysUntilDue:number;workflow:ReturnType<typeof workflow>}[]=[];
  const annual=new Map<string,{current:RenewalDocument;pending:RenewalDocument|null}>();
  for(const root of relevant.filter(document=>!document.renewalOfDocumentId&&document.template.renewalPolicy==="ANNUAL")){const chain=latestCompletedInChain(root,byParent),anchor=completedAt(chain.current);if(!anchor)continue;const prior=annual.get(root.templateId),priorAt=prior&&completedAt(prior.current);if(!priorAt||anchor>priorAt)annual.set(root.templateId,chain)}
  const candidates=[...annual.values(),...relevant.filter(document=>!document.renewalOfDocumentId&&document.template.renewalPolicy==="EXPIRATION_DATE_DRIVEN").map(root=>latestCompletedInChain(root,byParent))];
  for(const candidate of candidates){const document=candidate.current,anchor=completedAt(document);if(!anchor)continue;if(document.template.renewalPolicy==="EXPIRATION_DATE_DRIVEN"&&["REVOKED","VOIDED"].includes(document.roiAuthorization?.status??""))continue;const due=document.template.renewalPolicy==="ANNUAL"?annualRenewalDueDate(anchor,timeZone):document.roiAuthorization?.expirationDate;if(!due)continue;const state=renewalState(due,document.template.renewalWarningDays,at,timeZone);cycles.push({documentId:document.id,templateId:document.templateId,templateName:document.template.name,documentType:document.documentType,policy:document.template.renewalPolicy,completedAt:anchor.toISOString(),dueDate:dateKey(calendarParts(due,"UTC")),status:state.status,daysUntilDue:state.days,workflow:workflow(candidate.pending)});}
  cycles.sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.documentId.localeCompare(b.documentId));
  const overdueCount=cycles.filter(row=>row.status==="OVERDUE").length,dueSoonCount=cycles.filter(row=>row.status==="DUE_SOON").length;
  return{status:overdueCount?"OVERDUE" as const:dueSoonCount?"DUE_SOON" as const:"CURRENT" as const,overdueCount,dueSoonCount,nearestDeadline:cycles[0]?.dueDate??null,affectedTemplates:cycles.filter(row=>row.status!=="CURRENT").map(row=>row.templateName),cycles};
}

async function authorize(user:Pick<User,"id">,organizationId:string){const{membership}=await requireOrganizationAccess(user,organizationId);await requirePermission(membership.id,"client.read")}
export async function getClientRenewalSummary(user:Pick<User,"id">,organizationId:string,clientId:string,at=new Date()){await authorize(user,organizationId);const organization=await prisma.organization.findUnique({where:{id:organizationId},select:{timezone:true}}),documents=await prisma.clientDocument.findMany({where:{organizationId,clientId},select:renewalDocumentSelect});return deriveClientRenewalSummary(documents,organization?.timezone??"UTC",at)}
export async function getOrganizationRenewalSummaries(user:Pick<User,"id">,organizationId:string,clientIds:string[],at=new Date()){await authorize(user,organizationId);const[organization,documents]=await Promise.all([prisma.organization.findUnique({where:{id:organizationId},select:{timezone:true}}),prisma.clientDocument.findMany({where:{organizationId,clientId:{in:clientIds}},select:renewalDocumentSelect})]),grouped=new Map<string,RenewalDocument[]>();for(const document of documents)grouped.set(document.clientId,[...(grouped.get(document.clientId)??[]),document]);return new Map(clientIds.map(id=>[id,deriveClientRenewalSummary(grouped.get(id)??[],organization?.timezone??"UTC",at)]))}
async function organizationRenewalActions(organizationId:string,at:Date){const clients=await prisma.client.findMany({where:{organizationId,status:{not:"ARCHIVED"}},select:{id:true,legalFirstName:true,legalLastName:true},orderBy:[{legalLastName:"asc"},{legalFirstName:"asc"},{id:"asc"}],take:1000}),organization=await prisma.organization.findUnique({where:{id:organizationId},select:{timezone:true}}),documents=await prisma.clientDocument.findMany({where:{organizationId,clientId:{in:clients.map(client=>client.id)}},select:renewalDocumentSelect}),grouped=new Map<string,RenewalDocument[]>();for(const document of documents)grouped.set(document.clientId,[...(grouped.get(document.clientId)??[]),document]);return clients.flatMap(client=>deriveClientRenewalSummary(grouped.get(client.id)??[],organization?.timezone??"UTC",at).cycles.filter(cycle=>cycle.status!=="CURRENT").map(cycle=>({id:`client-document-renewal:${cycle.documentId}`,client,documentId:cycle.documentId,templateName:cycle.templateName,documentType:cycle.documentType,status:cycle.status,dueDate:cycle.dueDate,daysUntilDue:cycle.daysUntilDue,workflow:cycle.workflow,actionHref:`/admin/clients?organizationId=${encodeURIComponent(organizationId)}&clientId=${encodeURIComponent(client.id)}&documentId=${encodeURIComponent(cycle.documentId)}`}))).sort((a,b)=>(a.status==="OVERDUE"?0:1)-(b.status==="OVERDUE"?0:1)||a.dueDate.localeCompare(b.dueDate)||a.id.localeCompare(b.id))}
export async function getOrganizationRenewalActions(user:Pick<User,"id">,organizationId:string,at=new Date()){await authorize(user,organizationId);return organizationRenewalActions(organizationId,at)}
/** Internal reconciliation projection. Callers must enforce tenant-scoped operational authorization. */
export async function getOrganizationRenewalActionsForNotificationReconciliation(organizationId:string,at=new Date()){return organizationRenewalActions(organizationId,at)}
export async function reconcileClientDocumentRenewals(user:Pick<User,"id">,organizationId:string,at=new Date()){await authorize(user,organizationId);const clients=await prisma.client.findMany({where:{organizationId,status:{not:"ARCHIVED"}},select:{id:true}}),summaries=await getOrganizationRenewalSummaries(user,organizationId,clients.map(row=>row.id),at);return{organizationId,evaluatedAt:at.toISOString(),clientsScanned:clients.length,overdue:[...summaries.values()].reduce((sum,row)=>sum+row.overdueCount,0),dueSoon:[...summaries.values()].reduce((sum,row)=>sum+row.dueSoonCount,0)}}
