import { Prisma, type User } from "@prisma/client";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { AuthorizationError, ResourceNotFoundError } from "@/domain/auth/errors";
import { requireOrganizationAccess, requirePermission } from "@/domain/permissions/authorization";
import type { ClientRenewalStatus } from "@/domain/clients/renewals";
import { getClientDocumentationReadiness, getOrganizationClientDocumentationReadiness, type DocumentationReadinessFilter } from "@/domain/clients/readiness";

export const clientInput = z.object({
  legalFirstName: z.string().trim().min(1).max(100), legalLastName: z.string().trim().min(1).max(100),
  preferredName: z.string().trim().max(100).optional().nullable(), dateOfBirth: z.coerce.date(), gender: z.string().max(100).optional().nullable(),
  phone: z.string().max(50).optional().nullable(), email: z.string().email().optional().nullable(), addressLine1: z.string().max(200).optional().nullable(),
  addressLine2: z.string().max(200).optional().nullable(), city: z.string().max(100).optional().nullable(), state: z.string().max(50).optional().nullable(),
  postalCode: z.string().max(20).optional().nullable(), maPmiNumber: z.string().max(100).optional().nullable(), waiverProgram: z.string().max(150).optional().nullable(),
  financialResponsibility: z.string().max(200).optional().nullable(), primaryLanguage: z.string().max(100).optional().nullable(), interpreterNeeded: z.boolean().optional(),
  preferredCommunication: z.string().max(100).optional().nullable(), livingSituation: z.string().max(500).optional().nullable(), strengthsInterests: z.string().max(5000).optional().nullable(),
  culturalPractices: z.string().max(5000).optional().nullable(), supportNeeds: z.string().max(5000).optional().nullable(),
});
export const intakeInput = z.object({
  currentStep: z.enum(["CLIENT","SERVICES","REPRESENTATIVE","CASE_MANAGER","EMERGENCY_CONTACTS","HEALTH_MEDICATION","ABOUT_PERSON","DOCUMENTS","SIGNATURES","REVIEW_COMPLETE"]),
  client: clientInput.partial().optional(),
  services: z.array(z.object({ serviceType:z.string().min(1).max(150), startDate:z.coerce.date().optional().nullable(), authorizedUnits:z.number().nonnegative().optional().nullable(), authorizedHours:z.number().nonnegative().optional().nullable(), authorizationStart:z.coerce.date().optional().nullable(), authorizationEnd:z.coerce.date().optional().nullable(), scheduleJson:z.record(z.string(),z.unknown()).optional().nullable(), status:z.enum(["PROPOSED","ACTIVE","PAUSED","ENDED","CANCELLED"]).optional() })).max(50).optional(),
  representatives: z.array(z.object({ representativeType:z.string().min(1).max(100), name:z.string().min(1).max(200), relationship:z.string().max(100).optional().nullable(), email:z.string().email().optional().nullable(), phone:z.string().max(50).optional().nullable(), isPrimary:z.boolean().optional() })).max(20).optional(),
  emergencyContacts: z.array(z.object({ name:z.string().min(1).max(200), relationship:z.string().min(1).max(100), phone:z.string().min(1).max(50), alternatePhone:z.string().max(50).optional().nullable(), informationSharingAllowed:z.boolean().optional() })).max(20).optional(),
  health: z.object({ primaryCareProvider:z.string().max(200).optional().nullable(), clinic:z.string().max(200).optional().nullable(), providerPhone:z.string().max(50).optional().nullable(), dentist:z.string().max(200).optional().nullable(), pharmacy:z.string().max(200).optional().nullable(), pharmacyPhone:z.string().max(50).optional().nullable(), healthInsurancePlan:z.string().max(200).optional().nullable(), memberId:z.string().max(100).optional().nullable(), diagnoses:z.string().max(5000).optional().nullable(), allergiesReactions:z.string().max(5000).optional().nullable(), specialDietTexture:z.string().max(5000).optional().nullable(), chokingSwallowingRisk:z.string().max(5000).optional().nullable(), seizureProtocol:z.string().max(5000).optional().nullable(), mobilityEquipment:z.string().max(5000).optional().nullable(), medicationResponsibility:z.string().max(1000).optional().nullable(), otherHealthNeeds:z.string().max(5000).optional().nullable() }).optional(),
  medications: z.array(z.object({ medication:z.string().min(1).max(200), dose:z.string().max(100).optional().nullable(), times:z.string().max(500).optional().nullable(), reason:z.string().max(500).optional().nullable(), prescriber:z.string().max(200).optional().nullable() })).max(100).optional(),
  checklist: z.array(z.object({ code:z.string().min(1).max(100), label:z.string().min(1).max(300), status:z.enum(["PENDING","COMPLETE","NOT_APPLICABLE"]), completedAt:z.coerce.date().optional().nullable(), notes:z.string().max(2000).optional().nullable(), sequence:z.number().int().positive() })).max(50).optional(),
});

async function authorize(user:Pick<User,"id">, organizationId:string, permission:string){const{membership}=await requireOrganizationAccess(user,organizationId);await requirePermission(membership.id,permission);}
async function clientOrThrow(organizationId:string,id:string){const client=await prisma.client.findFirst({where:{id,organizationId}});if(!client)throw new ResourceNotFoundError("Client not found");return client;}
async function audit(organizationId:string,actorUserId:string,eventType:string,entityType:string,entityId:string,metadataJson?:Prisma.InputJsonValue){await prisma.auditEvent.create({data:{organizationId,actorUserId,eventType,entityType,entityId,metadataJson}})}
const intakeChecklist=[
  ["REFERRAL_CASE_MANAGER_RECEIVED","Referral and case manager contact information received"],
  ["CSSP_ASSESSMENTS_RECEIVED","Coordinated Service and Support Plan (CSSP) and any assessments received from case manager"],
  ["FUNDING_CONFIRMED","Service authorization / funding confirmed"],
  ["FACE_SHEET_COMPLETED","Form 01 - Client Information / Face Sheet completed"],
  ["RIGHTS_NOTICE","Form 02 - Rights Notice given and signed (rights explained within 5 working days of service start)"],
  ["POLICY_ACKNOWLEDGMENT","Form 03 - Policy Acknowledgment: all policies given and signed"],
  ["ROI_STATUS","Form 04 - Release(s) of Information signed for each party who needs information"],
  ["MEDICATION_AUTHORIZATION_IF_APPLICABLE","Form 05 - Medication Authorization signed (only if Radiant Care assists with or administers medication)"],
  ["FUNDS_PROPERTY_AUTHORIZATION_IF_APPLICABLE","Form 06 - Funds and Property Authorization signed (only if Radiant Care assists with money or property)"],
  ["PERSON_SPECIFIC_ORIENTATION","Person-specific orientation completed by every staff member before working with the person"],
  ["PRELIMINARY_SUPPORT_PLAN","Form 07 - Preliminary Support Plan / Self-Management Assessment completed (within 15 calendar days of service start)"],
  ["SUPPORT_TEAM_MEETING","Support team meeting held (within 45 calendar days of service start) - Form 08"],
  ["CSSP_ADDENDUM","CSSP Addendum written and signed - Form 08"],
  ["PROGRESS_REVIEW_SCHEDULE","Progress review schedule set per the person's request - Form 08"],
  ["MAR_STARTED_IF_APPLICABLE","Medication Administration Record (MAR) started, if medication is administered"],
  ["SIGNED_DOCUMENT_RECORD","All signed forms uploaded to the person's SharePoint record"],
  ["STAFF_COMPLETING_INTAKE","Staff completing intake review"],
  ["MANAGER_REVIEW","Designated coordinator / manager review"],
] as const;

export async function createClient(user:Pick<User,"id">,organizationId:string,input:z.input<typeof clientInput>){await authorize(user,organizationId,"client.create");const data=clientInput.parse(input);const client=await prisma.client.create({data:{...data,organizationId,createdByUserId:user.id,status:"INTAKE_IN_PROGRESS"}});const intake=await prisma.clientIntake.create({data:{organizationId,clientId:client.id,status:"IN_PROGRESS",checklistItems:{create:intakeChecklist.map(([code,label],index)=>({code,label,sequence:index+1}))}}});await audit(organizationId,user.id,"client.created","Client",client.id,{intakeId:intake.id});return{client,intake};}
export async function listClients(user:Pick<User,"id">,organizationId:string,filters:{search?:string;status?:string;renewalStatus?:ClientRenewalStatus;readiness?:DocumentationReadinessFilter}={}){
  await authorize(user,organizationId,"client.read");
  const search=filters.search?.trim();
  const clients=await prisma.client.findMany({
    where:{organizationId,status:filters.status as never,OR:search?[{legalFirstName:{contains:search,mode:"insensitive"}},{legalLastName:{contains:search,mode:"insensitive"}},{preferredName:{contains:search,mode:"insensitive"}}]:undefined},
    select:{id:true,status:true,legalFirstName:true,legalLastName:true,preferredName:true,updatedAt:true,intakes:{select:{status:true,currentStep:true},orderBy:{createdAt:"desc"},take:1},_count:{select:{services:{where:{status:"ACTIVE"}},documents:{where:{status:{in:["READY_FOR_SIGNATURE","PARTIALLY_SIGNED"]}}}}}},
    orderBy:[{legalLastName:"asc"},{legalFirstName:"asc"}],take:100,
  });
  const readiness=await getOrganizationClientDocumentationReadiness(user,organizationId,{clientIds:clients.map(client=>client.id),filter:filters.readiness}),byClient=new Map(readiness.map(row=>[row.client.id,row])),priorityByClient=new Map(readiness.map((row,index)=>[row.client.id,index]));
  const rows=clients.map(client=>{const documentationReadiness=byClient.get(client.id);return documentationReadiness?{...client,renewalSummary:documentationReadiness.renewalSummary,documentationReadiness}:null}).filter((client):client is NonNullable<typeof client>=>client!==null);
  return rows.filter(client=>!filters.renewalStatus||client.renewalSummary.status===filters.renewalStatus).sort((a,b)=>priorityByClient.get(a.id)!-priorityByClient.get(b.id)!);
}
export async function getClient(user:Pick<User,"id">,organizationId:string,id:string){await authorize(user,organizationId,"client.read");await clientOrThrow(organizationId,id);const[client,documentationReadiness]=await Promise.all([prisma.client.findUniqueOrThrow({where:{id},include:{services:true,representatives:true,emergencyContacts:true,healthProfile:true,medications:true,contacts:{include:{professionalContact:true}},intakes:{include:{checklistItems:{orderBy:{sequence:"asc"}}},orderBy:{createdAt:"desc"}},documents:{include:{template:true,envelope:{include:{signers:true}}},orderBy:{generatedAt:"desc"}},documentRequests:{include:{representative:{select:{id:true,representativeType:true,relationship:true}},obligationDocument:{select:{id:true,documentType:true}},fulfilledDocument:{select:{id:true,documentType:true,status:true}}},orderBy:{createdAt:"desc"}},roiAuthorizations:true}}),getClientDocumentationReadiness(user,organizationId,id)]);return{...client,renewalSummary:documentationReadiness.renewalSummary,documentationReadiness};}
export async function saveIntake(user:Pick<User,"id">,organizationId:string,clientId:string,input:z.input<typeof intakeInput>){await authorize(user,organizationId,"client.intake.manage");await clientOrThrow(organizationId,clientId);const data=intakeInput.parse(input),intake=await prisma.clientIntake.findFirstOrThrow({where:{organizationId,clientId,status:{in:["DRAFT","IN_PROGRESS","REOPENED"]}},orderBy:{createdAt:"desc"}});await prisma.$transaction(async tx=>{if(data.client)await tx.client.update({where:{id:clientId},data:data.client});if(data.services){await tx.clientService.deleteMany({where:{clientId,status:"PROPOSED"}});await tx.clientService.createMany({data:data.services.map(row=>({...row,organizationId,clientId,scheduleJson:row.scheduleJson as Prisma.InputJsonValue|undefined}))})}if(data.representatives){await tx.clientRepresentative.deleteMany({where:{clientId}});await tx.clientRepresentative.createMany({data:data.representatives.map(row=>({...row,organizationId,clientId}))})}if(data.emergencyContacts){await tx.clientEmergencyContact.deleteMany({where:{clientId}});await tx.clientEmergencyContact.createMany({data:data.emergencyContacts.map(row=>({...row,organizationId,clientId}))})}if(data.health)await tx.clientHealthProfile.upsert({where:{clientId},create:{...data.health,organizationId,clientId},update:data.health});if(data.medications){await tx.clientMedication.deleteMany({where:{clientId}});await tx.clientMedication.createMany({data:data.medications.map(row=>({...row,organizationId,clientId}))})}if(data.checklist)for(const item of data.checklist)await tx.clientIntakeChecklistItem.upsert({where:{intakeId_code:{intakeId:intake.id,code:item.code}},create:{...item,intakeId:intake.id},update:item});await tx.clientIntake.update({where:{id:intake.id},data:{currentStep:data.currentStep,lastSavedAt:new Date(),progressJson:{lastCompletedStep:data.currentStep}}});});await audit(organizationId,user.id,"client.intake_saved","ClientIntake",intake.id,{step:data.currentStep});return getClient(user,organizationId,clientId);}
export async function completeIntake(user:Pick<User,"id">,organizationId:string,clientId:string){await authorize(user,organizationId,"client.intake.manage");const client=await getClient(user,organizationId,clientId),intake=client.intakes.find(row=>["DRAFT","IN_PROGRESS","REOPENED"].includes(row.status));if(!intake)throw new ResourceNotFoundError("Open intake not found");if(!client.legalFirstName||!client.legalLastName||!client.dateOfBirth)throw new AuthorizationError("Required client identity fields are incomplete");const completedAt=new Date();await prisma.$transaction([prisma.clientIntake.update({where:{id:intake.id},data:{status:"COMPLETED",currentStep:"REVIEW_COMPLETE",completedAt,completedByUserId:user.id,lastSavedAt:completedAt}}),prisma.client.update({where:{id:clientId},data:{status:"ACTIVE"}})]);await audit(organizationId,user.id,"client.intake_completed","ClientIntake",intake.id);return{intakeId:intake.id,completedAt};}

export async function createProfessionalContact(user:Pick<User,"id">,organizationId:string,input:{name:string;agency?:string;contactType:string;email?:string;phone?:string;supervisorName?:string;supervisorPhone?:string}){await authorize(user,organizationId,"client.intake.manage");const parsed=z.object({name:z.string().min(1).max(200),agency:z.string().max(200).optional(),contactType:z.string().min(1).max(100),email:z.string().email().optional(),phone:z.string().max(50).optional(),supervisorName:z.string().max(200).optional(),supervisorPhone:z.string().max(50).optional()}).parse(input);return prisma.professionalContact.create({data:{...parsed,organizationId}})}
export async function assignProfessionalContact(user:Pick<User,"id">,organizationId:string,clientId:string,professionalContactId:string,role="CASE_MANAGER"){await authorize(user,organizationId,"client.intake.manage");await clientOrThrow(organizationId,clientId);const contact=await prisma.professionalContact.findFirst({where:{id:professionalContactId,organizationId}});if(!contact)throw new ResourceNotFoundError("Professional contact not found");const link=await prisma.clientProfessionalContact.upsert({where:{clientId_professionalContactId_role:{clientId,professionalContactId,role}},create:{organizationId,clientId,professionalContactId,role,isPrimary:role==="CASE_MANAGER"},update:{isPrimary:role==="CASE_MANAGER"}});await audit(organizationId,user.id,"client.contact_assigned","Client",clientId,{professionalContactId,role});return link;}
