import type { ComplianceEmail } from "@/domain/notifications/email";

function escapeHtml(value:string){return value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;")}
function displayDate(value:Date){return new Intl.DateTimeFormat("en-US",{dateStyle:"long",timeStyle:"short",timeZone:"UTC"}).format(value)+" UTC"}
export function renderSignatureInvitationEmail(input:{organizationName:string;signerName:string;documentDescription:string;signingUrl:string;expiresAt:Date}):ComplianceEmail{
  const organization=input.organizationName.trim(),signer=input.signerName.trim(),document=input.documentDescription.trim(),expires=displayDate(input.expiresAt),url=new URL(input.signingUrl);
  if(url.protocol!=="https:"&&process.env.NODE_ENV==="production")throw new Error("Production signing links must use HTTPS");
  const subject=`${organization}: document signature requested`,text=[`Hello ${signer},`,"",`${organization} has asked you to review and sign a document in Compliance Platform.`,`Document: ${document}`,`This secure invitation expires ${expires}.`,"",`Review and sign securely: ${url.toString()}`,"","Do not forward this link. The platform will verify the invitation before displaying the document.","Email acceptance does not mean the document has been reviewed or signed."].join("\n");
  const html=`<!doctype html><html><body style="margin:0;background:#f4f6f8;color:#172033;font-family:Arial,sans-serif"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:24px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:auto;background:#ffffff;border:1px solid #d8dee8;border-radius:8px"><tr><td style="padding:32px"><p style="margin:0 0 16px">Hello ${escapeHtml(signer)},</p><h1 style="font-size:22px;line-height:1.3;margin:0 0 16px">A document needs your signature</h1><p style="line-height:1.6">${escapeHtml(organization)} has asked you to review and sign a document in Compliance Platform.</p><p style="line-height:1.6"><strong>Document:</strong> ${escapeHtml(document)}<br><strong>Invitation expires:</strong> ${escapeHtml(expires)}</p><p style="margin:28px 0"><a href="${escapeHtml(url.toString())}" style="background:#174ea6;color:#ffffff;text-decoration:none;padding:12px 18px;border-radius:5px;display:inline-block">Review and sign securely</a></p><p style="font-size:14px;line-height:1.6;color:#4f5b6d">Do not forward this link. The platform verifies the invitation before displaying the document. Email acceptance does not mean the document has been reviewed or signed.</p><p style="font-size:12px;line-height:1.5;color:#667085;word-break:break-all">If the button does not work, open: ${escapeHtml(url.toString())}</p></td></tr></table></td></tr></table></body></html>`;
  return{to:"",subject,text,html};
}
