import type { ComplianceEmail } from "@/domain/notifications/email";

function escapeHtml(value:string){return value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;")}
export function renderSignatureInvitationEmail(input:{organizationName:string;signerName:string;documentDescription:string;signingUrl:string;expiresAt:Date;expirationHours?:number}):ComplianceEmail{
  const organization=input.organizationName.trim(),url=new URL(input.signingUrl),expirationHours=input.expirationHours??72;
  if(url.protocol!=="https:"&&process.env.NODE_ENV==="production")throw new Error("Production signing links must use HTTPS");
  const subject="Document ready for your review and signature",text=[organization,"","You have received a document requiring your review and electronic signature.","",`Review and Sign Document: ${url.toString()}`,"",`This secure invitation expires in ${expirationHours} hours.`,"","If you were not expecting this request, contact the organization that sent it.","Do not forward this secure invitation."].join("\n");
  const html=`<!doctype html><html><body style="margin:0;background:#f5f4ef;color:#183127;font-family:Arial,sans-serif"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:24px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:560px;margin:auto;background:#ffffff;border:1px solid #deddd6;border-radius:10px"><tr><td style="padding:32px"><p style="margin:0 0 22px;font-size:18px;font-weight:700">${escapeHtml(organization)}</p><p style="font-size:16px;line-height:1.6;margin:0 0 24px">You have received a document requiring your review and electronic signature.</p><p style="margin:0 0 26px"><a href="${escapeHtml(url.toString())}" style="background:#1f4636;color:#ffffff;text-decoration:none;padding:12px 18px;border-radius:6px;display:inline-block;font-weight:700">Review and Sign Document</a></p><p style="font-size:14px;line-height:1.6;color:#59645f;margin:0 0 14px">This secure invitation expires in ${expirationHours} hours.</p><p style="font-size:14px;line-height:1.6;color:#59645f;margin:0">If you were not expecting this request, contact the organization that sent it. Do not forward this secure invitation.</p></td></tr></table></td></tr></table></body></html>`;
  return{to:"",fromName:organization,subject,text,html};
}
