import { beforeAll, describe, expect, it } from "vitest";
import { PrismaClient } from "@prisma/client";
import { deadlineState, getActionCenter, refreshActionCenter } from "@/domain/action-center/service";
import { startIssueRemediation } from "@/domain/compliance-issues/service";

const db = new PrismaClient();
describe.sequential("Phase 17 compliance Action Center", () => {
  const at = new Date("2026-09-18T12:00:00.000Z");
  let organizationId: string, otherOrganizationId: string, ownerId: string, viewerId: string, employeeUserId: string, employeeId: string, issueId: string;
  beforeAll(async () => {
    const tag = `phase17-${Date.now()}`;
    const [owner, ownerRole, operationsPermission] = await Promise.all([db.user.findUniqueOrThrow({ where: { email: "alex.owner@example.test" } }), db.roleDefinition.findFirstOrThrow({ where: { organizationId: null, code: "ORGANIZATION_OWNER" } }), db.permission.findUniqueOrThrow({ where: { code: "compliance.operations.read" } })]);
    ownerId = owner.id;
    const organization = await db.organization.create({ data: { legalName: tag, displayName: tag, slug: tag } }); organizationId = organization.id;
    const other = await db.organization.create({ data: { legalName: `${tag}-other`, displayName: `${tag}-other`, slug: `${tag}-other` } }); otherOrganizationId = other.id;
    const membership = await db.organizationMembership.create({ data: { organizationId, userId: ownerId, status: "ACTIVE" } }); await db.membershipRole.create({ data: { membershipId: membership.id, roleDefinitionId: ownerRole.id } });
    const viewer = await db.user.create({ data: { email: `${tag}-viewer@example.test`, status: "ACTIVE" } }); viewerId = viewer.id;
    const viewerRole = await db.roleDefinition.create({ data: { organizationId, code: `${tag}-OPS`, name: "Operations reader", scope: "ORGANIZATION", permissions: { create: { permissionId: operationsPermission.id } } } });
    const viewerMembership = await db.organizationMembership.create({ data: { organizationId, userId: viewer.id, status: "ACTIVE" } }); await db.membershipRole.create({ data: { membershipId: viewerMembership.id, roleDefinitionId: viewerRole.id } });
    const employeeUser = await db.user.create({ data: { email: `${tag}-employee@example.test`, status: "ACTIVE" } }); employeeUserId = employeeUser.id;
    await db.organizationMembership.create({ data: { organizationId, userId: employeeUser.id, status: "ACTIVE" } });
    const employee = await db.employee.create({ data: { organizationId, userId: employeeUser.id, employeeNumber: "P17-001", firstName: "Action", lastName: "Worker", employmentStatus: "ACTIVE" } }); employeeId = employee.id;
    await db.employee.create({ data: { organizationId: otherOrganizationId, firstName: "Foreign", lastName: "Worker", employmentStatus: "ACTIVE" } });
    const policy = await db.policy.create({ data: { organizationId, code: `${tag}-POL`, title: "Safety acknowledgment", requiresAcknowledgment: true } });
    const policyVersion = await db.policyVersion.create({ data: { policyId: policy.id, versionNumber: 1, status: "PUBLISHED", effectiveFrom: at, publishedAt: at, body: "Safety", contentHash: tag, createdByUserId: ownerId } });
    await db.policyAssignment.createMany({ data: [
      { fingerprint: `${tag}:policy-overdue`, organizationId, employeeId, policyVersionId: policyVersion.id, sourceType: "MANUAL", status: "OVERDUE", dueAt: new Date("2026-09-17T12:00:00Z") },
      { fingerprint: `${tag}:policy-none`, organizationId, employeeId, policyVersionId: policyVersion.id, sourceType: "MANUAL", status: "PENDING" },
    ] });
    const course = await db.trainingCourse.create({ data: { organizationId, catalogKey: `${tag}:course`, code: `${tag}-COURSE`, title: "Required training", category: "SAFETY", ownershipType: "ORGANIZATION" } });
    const version = await db.trainingCourseVersion.create({ data: { courseId: course.id, versionNumber: 1, status: "PUBLISHED", effectiveFrom: at, publishedAt: at, contentHash: `${tag}-course` } });
    await db.trainingAssignment.createMany({ data: [
      { fingerprint: `${tag}:training-soon`, organizationId, employeeId, courseVersionId: version.id, sourceType: "MANUAL", status: "NOT_STARTED", dueAt: new Date("2026-09-25T12:00:00Z") },
      { fingerprint: `${tag}:training-future`, organizationId, employeeId, courseVersionId: version.id, sourceType: "MANUAL", status: "IN_PROGRESS", dueAt: new Date("2026-12-01T12:00:00Z") },
    ] });
    const competency = await db.competencyDefinition.create({ data: { organizationId, code: `${tag}-COMP`, name: "Observed safe practice", method: "OBSERVED_SKILL", ownerType: "ORGANIZATION" } });
    await db.competencyAssessment.create({ data: { organizationId, employeeId, competencyDefinitionId: competency.id, assessorUserId: ownerId, assessorNameSnapshot: "Owner", status: "FINALIZED", result: "REMEDIATION_REQUIRED", finalizedAt: at } });
    await db.externalTrainingRecord.create({ data: { organizationId, employeeId, providerName: "Outside Provider", trainingName: "Prior safety course", trainingDate: new Date("2026-08-01"), reviewStatus: "PENDING", evidenceReference: "s3://evidence/reference" } });
    const issue = await db.complianceIssue.create({ data: { fingerprint: `${tag}:clinical`, activeKey: `${tag}:clinical`, organizationId, employeeId, issueType: "CLINICAL_SIGNOFF_REQUIRED", priority: "HIGH", status: "OPEN", sourceType: "MedicationQualificationPathway", sourceId: `${tag}-pathway`, contextJson: {}, reasonCodesJson: ["CLINICAL_SIGNOFF_REQUIRED"], remediationActionsJson: [], evidenceReferencesJson: [], firstDetectedAt: at, latestDetectedAt: at } }); issueId = issue.id;
    await db.complianceIssue.create({ data: { fingerprint: `${tag}:service`, activeKey: `${tag}:service`, organizationId, employeeId, issueType: "ASSIGNMENT_BLOCKED", priority: "HIGH", status: "OPEN", sourceType: "ServiceAssignment", sourceId: `${tag}-assignment`, contextJson: {}, reasonCodesJson: ["TRAINING_REQUIRED"], remediationActionsJson: [], evidenceReferencesJson: [], firstDetectedAt: at, latestDetectedAt: at } });
    await db.auditEvent.create({ data: { organizationId, actorUserId: ownerId, employeeId, eventType: "employee.policy_acknowledged", entityType: "PolicyAssignment", entityId: `${tag}-audit`, occurredAt: at } });
  });
  const owner = () => ({ id: ownerId });

  it("classifies only legitimate deadlines with the centralized 30-day display window", () => { expect(deadlineState(new Date("2026-09-17"), at)).toBe("OVERDUE"); expect(deadlineState(new Date("2026-09-25"), at)).toBe("DUE_SOON"); expect(deadlineState(new Date("2026-12-01"), at)).toBe("FUTURE"); expect(deadlineState(null, at)).toBe("NO_DEADLINE"); expect(deadlineState(null, at, true)).toBe("REQUIRES_REVIEW"); });
  it("aggregates factual summaries and all supported operation categories", async () => { const result = await getActionCenter(owner(), organizationId, {}, at); expect(result.summary.employeesRequiringAttention).toBe(1); expect(result.summary.overdue).toBeGreaterThan(0); expect(result.summary.dueSoon).toBeGreaterThan(0); expect(result.actions.map(x => x.category)).toEqual(expect.arrayContaining(["TRAINING", "POLICY", "COMPETENCY", "EVIDENCE", "MEDICATION_CLINICAL", "SERVICE_ASSIGNMENT"])); });
  it("keeps clinical actions privileged and service blockers non-overridable", async () => { const result = await getActionCenter(owner(), organizationId, {}, at), clinical = result.actions.find(x => x.category === "MEDICATION_CLINICAL")!, blocker = result.actions.find(x => x.category === "SERVICE_ASSIGNMENT")!; expect(clinical.clinicallyPrivileged).toBe(true); expect(clinical.nextAction).toMatch(/clinical professional/); expect(blocker.serviceOverrideAllowed).toBe(false); });
  it("provides an evidence queue without granting review permission to a read-only operator", async () => { const ownerResult = await getActionCenter(owner(), organizationId, {}, at), viewerResult = await getActionCenter({ id: viewerId }, organizationId, {}, at); expect(ownerResult.evidenceReview[0].reviewerActionAvailable).toBe(true); expect(viewerResult.evidenceReview[0].reviewerActionAvailable).toBe(false); expect(ownerResult.evidenceReview[0].source).toBe("Outside Provider"); });
  it("filters, searches, sorts deterministically, and bounds pagination", async () => { const overdue = await getActionCenter(owner(), organizationId, { deadlineState: "OVERDUE" }, at); expect(overdue.actions.every(x => x.deadlineState === "OVERDUE")).toBe(true); const searched = await getActionCenter(owner(), organizationId, { search: "P17-001", pageSize: 500 }, at); expect(searched.actions.length).toBeGreaterThan(0); expect(searched.filters.pageSize).toBe(100); const all = await getActionCenter(owner(), organizationId, {}, at); expect(all.actions[0].deadlineState).toBe("OVERDUE"); expect((await getActionCenter(owner(), organizationId, {}, at)).actions.map(x => x.id)).toEqual(all.actions.map(x => x.id)); });
  it("integrates remediation without falsely resolving the underlying issue", async () => { await startIssueRemediation(owner(), organizationId, issueId); const result = await getActionCenter(owner(), organizationId, {}, at), action = result.actions.find(x => x.sourceId === issueId)!; expect(action.status).toBe("IN_PROGRESS"); expect(action.remediationState).toBe("IN_PROGRESS"); expect((await db.complianceIssue.findUniqueOrThrow({ where: { id: issueId } })).resolvedAt).toBeNull(); });
  it("returns recent tenant-scoped audit activity", async () => { const result = await getActionCenter(owner(), organizationId, {}, at); expect(result.recentActivity.map(x => x.eventType)).toContain("employee.policy_acknowledged"); expect(result.recentActivity.every(x => !x.entityId.includes("foreign"))).toBe(true); });
  it("denies ordinary employees and cross-tenant operators at the server boundary", async () => { await expect(getActionCenter({ id: employeeUserId }, organizationId)).rejects.toThrow(/compliance.operations.read/); await expect(getActionCenter(owner(), otherOrganizationId)).rejects.toThrow(); await expect(refreshActionCenter(owner(), otherOrganizationId, at)).rejects.toThrow(); await expect(startIssueRemediation(owner(), otherOrganizationId, issueId)).rejects.toThrow(); });
  it("reuses idempotent reconciliation without duplicating active issues", async () => { await refreshActionCenter(owner(), organizationId, at); const before = await db.complianceIssue.count({ where: { organizationId, status: { in: ["OPEN", "IN_PROGRESS"] } } }); await refreshActionCenter(owner(), organizationId, at); expect(await db.complianceIssue.count({ where: { organizationId, status: { in: ["OPEN", "IN_PROGRESS"] } } })).toBe(before); });
  it("uses careful empty-state language and never certifies legal compliance", async () => { const tag = `phase17-empty-${Date.now()}`, org = await db.organization.create({ data: { legalName: tag, displayName: tag, slug: tag } }), ownerRole = await db.roleDefinition.findFirstOrThrow({ where: { organizationId: null, code: "ORGANIZATION_OWNER" } }), membership = await db.organizationMembership.create({ data: { organizationId: org.id, userId: ownerId, status: "ACTIVE" } }); await db.membershipRole.create({ data: { membershipId: membership.id, roleDefinitionId: ownerRole.id } }); const result = await getActionCenter(owner(), org.id, {}, at); expect(result.summary.openActions).toBe(0); expect(result.emptyState).toMatch(/currently available platform data/); expect(result.emptyState).toMatch(/not a legal certification/i); });
});
