import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { evaluateIntake, livingSituationOptions, serviceTypeOptions } from "@/domain/clients/intake-state";

function completeSource(){return{legalFirstName:"TEST CLIENT",legalLastName:"ALPHA",dateOfBirth:"1991-02-03",livingSituation:"OWN_HOME_APARTMENT",services:[{serviceType:"RESPITE",startDate:"2026-02-01",authorizedHours:5,authorizationStart:"2026-02-01",authorizationEnd:"2026-12-31",scheduleJson:{authorizationPeriod:"daily"}}],representatives:[],contacts:[{role:"CASE_MANAGER"}],emergencyContacts:[{name:"SYNTHETIC CONTACT",relationship:"Synthetic relationship",phone:"555-0100"}],healthProfile:{medicationResponsibility:"PERSON_MANAGES"},medications:[],progressJson:{visitedSections:["CLIENT","SERVICES","REPRESENTATIVE","CASE_MANAGER","EMERGENCY_CONTACTS","HEALTH","MEDICATIONS","RIGHTS","ROI"],documentAnswers:{rights:{writtenCopyReceivedDate:"2026-02-01",rightsExplainedDate:"2026-02-01",explanationMethod:"IN_PERSON"},roi:{recipientName:"SYNTHETIC RECIPIENT",categories:["FACE_SHEET_CONTACT"],purposes:["SERVICE_COORDINATION"],effectiveDate:"2026-02-01",expirationDate:"2026-12-31"}}},intakeStatus:"IN_PROGRESS"}}

describe("guided intake state",()=>{
  it("uses the approved finite living and service choices",()=>{expect(livingSituationOptions.map(item=>item.label)).toEqual(["Own home/apartment","Family home","Other"]);expect(serviceTypeOptions.map(item=>item.label)).toEqual(["IHS with training","IHS without training","IHS with family training","Respite","Homemaking","Overnight sleep","Overnight awake"])});
  it("distinguishes unvisited, saved-complete, and saved-incomplete and recomputes after edits",()=>{const complete=evaluateIntake(completeSource());expect(complete.sectionStates.CLIENT).toBe("COMPLETE");expect(complete.sectionStates.SERVICES).toBe("COMPLETE");expect(complete.sectionStates.ABOUT_PERSON).toBe("UNVISITED");const edited=evaluateIntake({...completeSource(),services:[]});expect(edited.sectionStates.SERVICES).toBe("INCOMPLETE");expect(edited.blockers).toEqual(expect.arrayContaining([expect.objectContaining({step:"SERVICES"})]))});
  it("keeps terminal navigation actionable and exposes explicit accessible status text",()=>{const source=readFileSync(join(process.cwd(),"src/app/admin/clients/guided-intake.tsx"),"utf8");expect(source).toContain("Complete and open Documents");expect(source).toContain("aria-label={`${item.label}: ${statusText(status)}`}");expect(source).toContain("Saved - needs attention");expect(source).not.toContain("disabled={index===intakeSteps.length-1}")});
});
