import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { PDFDocument } from "pdf-lib";
import { getDocument } from "pdfjs-dist/legacy/build/pdf.mjs";
import { renderRadiantCareTemplate, radiantCareTemplateAssets } from "@/domain/clients/radiant-care-templates";

async function text(bytes:Uint8Array){const task=getDocument({data:bytes,useSystemFonts:true}),pdf=await task.promise,pages:string[]=[];for(let number=1;number<=pdf.numPages;number++){const content=await(await pdf.getPage(number)).getTextContent();pages.push(content.items.map(item=>"str" in item?item.str:"").join(" "))}await task.destroy();return pages.join(" ")}
async function sourceValues(){const root=join(process.cwd(),"reference","intake-forms"),values=new Set<string>();for(const file of Object.values(radiantCareTemplateAssets)){const pdf=await PDFDocument.load(readFileSync(join(root,file)));for(const field of pdf.getForm().getFields()){const item=field as unknown as{getText?:()=>string|undefined;getSelected?:()=>string[]};const candidates=item.getText?[item.getText()??""]:item.getSelected?item.getSelected():[];for(const value of candidates){const normalized=value.trim();if(normalized.length>=8&&!/^(not applicable|unknown|none)$/i.test(normalized))values.add(normalized)}}}return[...values]}
function snapshot(name:"ALPHA"|"BETA"){return{client:{legalFirstName:"TEST CLIENT",legalLastName:name,dateOfBirth:name==="ALPHA"?"1990-04-03":"1992-06-05",maPmiNumber:`SYNTHETIC-${name}`,services:[],representatives:[],emergencyContacts:[],medications:[],contacts:[],intakes:[{checklistItems:[]}]},form:{writtenCopyReceivedDate:"2026-09-01",rightsExplainedDate:"2026-09-01",staffPrintedName:"SYNTHETIC STAFF"},roi:{direction:"BOTH",recipientName:"SYNTHETIC COUNTY",categories:["FACE_SHEET_CONTACT"],purposes:["SERVICE_COORDINATION"],effectiveDate:"2026-09-01",expirationDate:"2027-08-31"}}}
describe("source-client and cross-client template isolation",()=>{
  it("derives populated source values programmatically and finds none in sanitized production masters",async()=>{const values=await sourceValues();expect(values.length).toBeGreaterThan(0);const root=join(process.cwd(),"reference","intake-forms","templates");for(const file of Object.values(radiantCareTemplateAssets)){const sanitized=await text(new Uint8Array(readFileSync(join(root,file))));for(const value of values)expect(sanitized).not.toContain(value)}});
  it("generates all authoritative documents from only the selected synthetic client",async()=>{const source=await sourceValues();for(const type of Object.keys(radiantCareTemplateAssets) as Array<keyof typeof radiantCareTemplateAssets>){const alpha=await text(await renderRadiantCareTemplate(type,snapshot("ALPHA"),"FINALIZED")),beta=await text(await renderRadiantCareTemplate(type,snapshot("BETA"),"FINALIZED"));expect(alpha).toContain("TEST CLIENT ALPHA");expect(beta).toContain("TEST CLIENT BETA");expect(alpha).not.toContain("TEST CLIENT BETA");expect(beta).not.toContain("TEST CLIENT ALPHA");for(const value of source){expect(alpha).not.toContain(value);expect(beta).not.toContain(value)}}});
  it("keeps populated references out of production defaults and container inputs",async()=>{const values=await sourceValues(),productionText=[readFileSync(join(process.cwd(),"prisma","seed.ts"),"utf8"),readFileSync(join(process.cwd(),"Dockerfile"),"utf8"),readFileSync(join(process.cwd(),"src","domain","clients","radiant-care-templates.ts"),"utf8")].join("\n");expect(productionText).toContain("reference/intake-forms/templates");expect(productionText).not.toContain("COPY reference/intake-forms /app/reference/intake-forms");for(const value of values)expect(productionText).not.toContain(value)});
});
