import { PrismaClient } from "@prisma/client";
import { beforeAll, describe, expect, it, vi } from "vitest";
import { getClientImport, listClientImports } from "@/domain/clients/imports";
import { getClient, listClients, updateClientLifecycle } from "@/domain/clients/service";
import { getOrganizationDocumentRequestActions } from "@/domain/clients/document-requests";
import { getOrganizationRenewalActions } from "@/domain/clients/renewals";

const db=new PrismaClient();

describe.sequential("client operations workspace",()=>{
  let organizationId:string,otherOrganizationId:string,adminId:string,caregiverId:string,auditorId:string,onboardingId:string,activeId:string,closedId:string,documentId:string,requestId:string,importId:string;
  const admin=()=>({id:adminId});
  beforeAll(async()=>{
    const tag=`client-ops-${Date.now()}`,[organization,other,adminUser,caregiver,auditor]=await Promise.all([
      db.organization.create({data:{legalName:"Synthetic Client Operations",displayName:"Synthetic Client Operations",slug:tag}}),
      db.organization.create({data:{legalName:"Synthetic Other Tenant",displayName:"Synthetic Other Tenant",slug:`${tag}-other`}}),
      db.user.create({data:{email:`${tag}-manager@example.test`,status:"ACTIVE"}}),
      db.user.create({data:{email:`${tag}-caregiver@example.test`,status:"ACTIVE"}}),
      db.user.create({data:{email:`${tag}-auditor@example.test`,status:"ACTIVE"}}),
    ]);organizationId=organization.id;otherOrganizationId=other.id;adminId=adminUser.id;caregiverId=caregiver.id;auditorId=auditor.id;
    const permissions=await db.permission.findMany({where:{code:{startsWith:"client."}}}),read=permissions.find(row=>row.code==="client.read")!,managerRole=await db.roleDefinition.create({data:{organizationId,code:"CLIENT_OPS_MANAGER",name:"Client operations manager",scope:"ORGANIZATION",permissions:{create:permissions.map(permission=>({permissionId:permission.id}))}}}),auditorRole=await db.roleDefinition.create({data:{organizationId,code:"SCOPED_READ_ONLY",name:"Scoped read only",scope:"ORGANIZATION",permissions:{create:{permissionId:read.id}}}});
    await db.organizationMembership.create({data:{organizationId,userId:adminId,status:"ACTIVE",roles:{create:{roleDefinitionId:managerRole.id}}}});await db.organizationMembership.create({data:{organizationId,userId:caregiverId,status:"ACTIVE"}});await db.organizationMembership.create({data:{organizationId,userId:auditorId,status:"ACTIVE",roles:{create:{roleDefinitionId:auditorRole.id}}}});await db.organizationMembership.create({data:{organizationId:otherOrganizationId,userId:adminId,status:"ACTIVE"}});
    const templates=await Promise.all(["INTAKE_CHECKLIST","FACE_SHEET","RIGHTS_ACKNOWLEDGMENT","ROI"].map((documentType,index)=>db.clientDocumentTemplate.create({data:{organizationId,code:`OPS-${index}`,name:`Synthetic ${documentType}`,documentType:documentType as "INTAKE_CHECKLIST"|"FACE_SHEET"|"RIGHTS_ACKNOWLEDGMENT"|"ROI",versionNumber:1,renewalPolicy:documentType==="RIGHTS_ACKNOWLEDGMENT"?"ANNUAL":documentType==="ROI"?"EXPIRATION_DATE_DRIVEN":"NONE",contentJson:{signerRoles:["CLIENT"]}}})));
    const [onboarding,active,closed]=await Promise.all([
      db.client.create({data:{organizationId,createdByUserId:adminId,status:"INTAKE_IN_PROGRESS",legalFirstName:"Avery",legalLastName:"Onboarding",dateOfBirth:new Date("1990-01-01")}}),
      db.client.create({data:{organizationId,createdByUserId:adminId,status:"ACTIVE",legalFirstName:"Bailey",legalLastName:"Current",dateOfBirth:new Date("1991-01-01")}}),
      db.client.create({data:{organizationId,createdByUserId:adminId,status:"DISCHARGED",dischargedAt:new Date(),legalFirstName:"Casey",legalLastName:"Closed",dateOfBirth:new Date("1992-01-01")}}),
    ]);onboardingId=onboarding.id;activeId=active.id;closedId=closed.id;
    await db.clientIntake.create({data:{organizationId,clientId:onboardingId,status:"IN_PROGRESS",currentStep:"SERVICES"}});await db.clientIntake.create({data:{organizationId,clientId:activeId,status:"COMPLETED",currentStep:"REVIEW_COMPLETE",completedAt:new Date(),completedByUserId:adminId}});await db.clientService.create({data:{organizationId,clientId:activeId,serviceType:"IN_HOME_SUPPORT",status:"ACTIVE",startDate:new Date("2026-01-15")}});const contact=await db.professionalContact.create({data:{organizationId,name:"Synthetic Case Manager",agency:"Synthetic County",contactType:"CASE_MANAGER"}});await db.clientProfessionalContact.create({data:{organizationId,clientId:activeId,professionalContactId:contact.id,role:"CASE_MANAGER",isPrimary:true}});await db.clientRepresentative.create({data:{organizationId,clientId:activeId,representativeType:"LEGAL_REPRESENTATIVE",name:"Synthetic Representative",isPrimary:true}});
    const face=await db.clientDocument.create({data:{organizationId,clientId:activeId,templateId:templates[1].id,documentType:"FACE_SHEET",status:"COMPLETED",source:"GENERATED",snapshotJson:{synthetic:true},authoritativeCompletedAt:new Date("2026-09-01"),generatedByUserId:adminId}}),rights=await db.clientDocument.create({data:{organizationId,clientId:activeId,templateId:templates[2].id,documentType:"RIGHTS_ACKNOWLEDGMENT",status:"COMPLETED",source:"IMPORTED",originalFileName:"synthetic-history.pdf",sourceDocumentHash:"a".repeat(64),importedAt:new Date(),snapshotJson:{synthetic:true},authoritativeCompletedAt:new Date("2025-01-01"),generatedByUserId:adminId}}),signatureDocument=await db.clientDocument.create({data:{organizationId,clientId:activeId,templateId:templates[3].id,documentType:"ROI",status:"PARTIALLY_SIGNED",source:"GENERATED",snapshotJson:{synthetic:true},generatedByUserId:adminId}});documentId=rights.id;
    const envelope=await db.signatureEnvelope.create({data:{organizationId,clientId:activeId,documentId:signatureDocument.id,mode:"SEND_FOR_SIGNATURE",provider:"synthetic",status:"PARTIALLY_SIGNED",signers:{create:[{role:"CLIENT",name:"Synthetic Client",email:"client@example.test",status:"SIGNED",signedAt:new Date()},{role:"LEGAL_REPRESENTATIVE",name:"Synthetic Representative",email:"representative@example.test",status:"SENT",sentAt:new Date()}]}}});void envelope;
    const request=await db.clientDocumentRequest.create({data:{organizationId,clientId:activeId,documentType:"INTAKE_CHECKLIST",recipientType:"CLIENT",recipientName:"Synthetic Client",deliveryChannel:"MANUAL",status:"OUTSTANDING",requestedAt:new Date(),dueAt:new Date("2026-10-15"),createdByUserId:adminId,activeKey:`${activeId}:INTAKE`}});requestId=request.id;
    const imported=await db.clientImportSession.create({data:{organizationId,uploadedByUserId:adminId,existingClientId:activeId,target:"UPDATE_EXISTING",status:"CONFIRMED",confirmedAt:new Date(),documents:{create:{organizationId,originalFileName:"synthetic-history.pdf",mimeType:"application/pdf",originalBytes:Buffer.from("%PDF-synthetic"),sha256:"b".repeat(64),classification:"FACE_SHEET",status:"ACCEPTED",pageCount:1,disposition:"HISTORICAL_COMPLETE",confirmedDocumentId:face.id}}}});importId=imported.id;
    await db.auditEvent.create({data:{organizationId,actorUserId:adminId,eventType:"client.document_historical_import_accepted",entityType:"ClientDocument",entityId:rights.id,metadataJson:{clientId:activeId}}});
  });

  it("provides a tenant-isolated searchable directory with lifecycle and intake summaries",async()=>{const rows=await listClients(admin(),organizationId,{search:"Avery",status:"INTAKE_IN_PROGRESS"});expect(rows.map(row=>row.id)).toEqual([onboardingId]);expect(rows[0].intakes[0]).toMatchObject({status:"IN_PROGRESS",currentStep:"SERVICES"});expect((await listClients(admin(),organizationId)).some(row=>row.id===closedId)).toBe(true);await expect(listClients(admin(),otherOrganizationId)).rejects.toThrow(/client.read|denied/i)});
  it("filters authoritative signature, request, import, readiness, and renewal projections",async()=>{expect((await listClients(admin(),organizationId,{operational:"OUTSTANDING_SIGNATURE"})).map(row=>row.id)).toContain(activeId);expect((await listClients(admin(),organizationId,{operational:"OUTSTANDING_REQUEST"})).map(row=>row.id)).toContain(activeId);expect((await listClients(admin(),organizationId,{operational:"IMPORTED_HISTORY"})).map(row=>row.id)).toContain(activeId);const rows=await listClients(admin(),organizationId,{readiness:"OVERDUE"});expect(rows.map(row=>row.id)).toContain(activeId);expect(rows.find(row=>row.id===activeId)?.renewalSummary.overdueCount).toBeGreaterThan(0)});
  it("keeps directory query volume constant as clients are added",async()=>{const clientQueries=vi.spyOn(db.client,"findMany"),templateQueries=vi.spyOn(db.clientDocumentTemplate,"findMany"),documentQueries=vi.spyOn(db.clientDocument,"findMany"),requestQueries=vi.spyOn(db.clientDocumentRequest,"findMany");await listClients(admin(),organizationId);const counts=[clientQueries.mock.calls.length,templateQueries.mock.calls.length,documentQueries.mock.calls.length,requestQueries.mock.calls.length];await db.client.create({data:{organizationId,createdByUserId:adminId,status:"INTAKE_IN_PROGRESS",legalFirstName:"Delta",legalLastName:"Synthetic",dateOfBirth:new Date("1993-01-01")}});await listClients(admin(),organizationId);expect([clientQueries.mock.calls.length-counts[0],templateQueries.mock.calls.length-counts[1],documentQueries.mock.calls.length-counts[2],requestQueries.mock.calls.length-counts[3]]).toEqual(counts);vi.restoreAllMocks()});
  it("aggregates overview, services, contacts, provenance, requests, signing progress, deadlines, and meaningful history",async()=>{const client=await getClient(admin(),organizationId,activeId);expect(client.services[0]).toMatchObject({serviceType:"IN_HOME_SUPPORT",status:"ACTIVE"});expect(client.contacts[0].professionalContact.name).toBe("Synthetic Case Manager");expect(client.representatives[0].name).toBe("Synthetic Representative");expect(client.documents.find(row=>row.id===documentId)).toMatchObject({source:"IMPORTED",status:"COMPLETED"});expect(client.documents.find(row=>row.envelope)?.envelope?.status).toBe("PARTIALLY_SIGNED");expect(client.documentRequests.find(row=>row.id===requestId)?.status).toBe("OUTSTANDING");expect(client.documentationReadiness.counts.overdue).toBeGreaterThan(0);expect(client.importSessions.map(row=>row.id)).toContain(importId);expect(client.history.map(row=>row.eventType)).toContain("client.document_historical_import_accepted")});
  it("resumes only same-tenant import sessions without changing canonical data",async()=>{expect((await listClientImports(admin(),organizationId,activeId)).map(row=>row.id)).toContain(importId);const session=await getClientImport(admin(),organizationId,importId);expect(session.status).toBe("CONFIRMED");await expect(getClientImport(admin(),otherOrganizationId,importId)).rejects.toThrow(/not found|client.read|denied/i);expect((await db.client.findUniqueOrThrow({where:{id:activeId}})).legalFirstName).toBe("Bailey")});
  it("keeps client workspace attention links consistent with authoritative Action Center sources",async()=>{const [renewals,requests]=await Promise.all([getOrganizationRenewalActions(admin(),organizationId,new Date("2026-10-01T12:00:00Z")),getOrganizationDocumentRequestActions(organizationId,new Date("2026-10-01T12:00:00Z"))]);expect(renewals.find(item=>item.client.id===activeId)?.actionHref).toContain(`clientId=${activeId}`);expect(requests.find(item=>item.id.includes(requestId))?.actionHref).toContain(`clientId=${activeId}`)});
  it("requires completed intake before activation and records authorized lifecycle changes without deleting history",async()=>{await expect(updateClientLifecycle(admin(),organizationId,onboardingId,{status:"ACTIVE",reason:"Synthetic activation attempt"})).rejects.toThrow(/intake/);const documentCount=await db.clientDocument.count({where:{clientId:activeId}}),historyCount=await db.auditEvent.count({where:{organizationId}});await updateClientLifecycle(admin(),organizationId,activeId,{status:"DISCHARGED",reason:"Synthetic service closure"});expect((await db.client.findUniqueOrThrow({where:{id:activeId}})).dischargedAt).toBeInstanceOf(Date);expect(await db.clientDocument.count({where:{clientId:activeId}})).toBe(documentCount);expect(await db.auditEvent.count({where:{organizationId}})).toBeGreaterThan(historyCount);await updateClientLifecycle(admin(),organizationId,activeId,{status:"ACTIVE",reason:"Synthetic authorized reactivation"});expect((await db.client.findUniqueOrThrow({where:{id:activeId}})).status).toBe("ACTIVE");await updateClientLifecycle(admin(),organizationId,closedId,{status:"ARCHIVED",reason:"Synthetic records closure"});expect((await db.client.findUniqueOrThrow({where:{id:closedId}})).archivedAt).toBeInstanceOf(Date)});
  it("denies caregiver, read-only auditor mutation, and cross-tenant IDOR access",async()=>{await expect(listClients({id:caregiverId},organizationId)).rejects.toThrow(/client.read/);await expect(updateClientLifecycle({id:auditorId},organizationId,activeId,{status:"DISCHARGED",reason:"Unauthorized"})).rejects.toThrow(/client.update/);await expect(getClient(admin(),otherOrganizationId,activeId)).rejects.toThrow(/not found|client.read|denied/i)});
});
