import { PDFDocument } from "pdf-lib";
import { PrismaClient } from "@prisma/client";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { beforeAll, describe, expect, it, vi } from "vitest";
import { assignProfessionalContact, completeIntake, createClient, createProfessionalContact, getClient, saveIntake } from "@/domain/clients/service";
import { createRoiAuthorization, exportClientPacket, finalizeClientDocument, generateClientDocument, roiExpirationState } from "@/domain/clients/documents";
import { createSignatureEnvelope, createSignNowSession, LocalTestSignatureProvider, recordLocalTestSignature, type ESignatureProvider } from "@/domain/clients/signatures";

const db=new PrismaClient();
describe.sequential("client management, intake, documents, and signatures",()=>{
  let organizationId:string,otherOrganizationId:string,adminId:string,employeeId:string,clientId:string,secondClientId:string,faceDocumentId:string,rightsDocumentId:string,roiDocumentId:string;
  const admin=()=>({id:adminId});
  beforeAll(async()=>{const tag=`clients-${Date.now()}`,[organization,other,adminUser,employee]=await Promise.all([db.organization.create({data:{legalName:"Radiant Care LLC",displayName:"Radiant Care",slug:tag}}),db.organization.create({data:{legalName:`${tag}-other`,displayName:`${tag}-other`,slug:`${tag}-other`}}),db.user.create({data:{email:`${tag}-admin@example.test`,status:"ACTIVE"}}),db.user.create({data:{email:`${tag}-employee@example.test`,status:"ACTIVE"}})]);organizationId=organization.id;otherOrganizationId=other.id;adminId=adminUser.id;employeeId=employee.id;await db.clientDocumentTemplate.createMany({data:templateDefinitions.map(row=>({...row,organizationId}))});const permissions=await db.permission.findMany({where:{code:{startsWith:"client."}}}),role=await db.roleDefinition.create({data:{organizationId,code:"CLIENT_MANAGER",name:"Client manager",scope:"ORGANIZATION",permissions:{create:permissions.map(permission=>({permissionId:permission.id}))}}});await db.organizationMembership.create({data:{organizationId,userId:adminId,status:"ACTIVE",roles:{create:{roleDefinitionId:role.id}}}});await db.organizationMembership.create({data:{organizationId,userId:employeeId,status:"ACTIVE"}});await db.employee.create({data:{organizationId,userId:employeeId,firstName:"Ordinary",lastName:"Employee",employmentStatus:"ACTIVE"}});});
  it("retains four sanitized authoritative template assets, reviewed source text, and source layouts",async()=>{const root=join(process.cwd(),"reference/intake-forms/templates"),manifest=JSON.parse(readFileSync(join(root,"manifest.json"),"utf8")) as {templates:{file:string;pages:number;sha256:string;requiredText:string[]}[]};expect(manifest.templates).toHaveLength(4);for(const item of manifest.templates){const bytes=readFileSync(join(root,item.file)),pdf=await PDFDocument.load(bytes);expect(pdf.getPageCount()).toBe(item.pages);expect(pdf.getForm().getFields()).toHaveLength(0);expect(createHash("sha256").update(bytes).digest("hex")).toBe(item.sha256);expect(item.requiredText.length).toBeGreaterThanOrEqual(5)}expect(manifest.templates.find(row=>row.file.startsWith("02_"))?.requiredText).toContain("These rights were explained to me in a way I understand (within 5 working days of service start).");expect(manifest.templates.find(row=>row.file.startsWith("04_"))?.requiredText).toContain("You may cancel this authorization at any time by telling Radiant Care in writing.");const layout=JSON.parse(readFileSync(join(root,"field-layout.json"),"utf8"));expect(layout["02_Service_Recipient_Rights_Acknowledgment.pdf"]).toHaveProperty("RIGHTS_005_I_received_a_written_copy_of_these_right");expect(layout["04_Authorization_to_Release_Information.pdf"]).toHaveProperty("ROI_032_This_authorization_expires_on_date_or_ev")});
  it("selects organization-scoped authoritative version 2 templates with actual signature roles",async()=>{const templates=await db.clientDocumentTemplate.findMany({where:{organizationId},orderBy:{code:"asc"}});expect(templates).toHaveLength(4);expect(templates.every(row=>row.versionNumber===2)).toBe(true);expect(templates.map(row=>(row.contentJson as {asset:string}).asset)).toEqual(["00_Intake_Checklist_Staff_Use.pdf","01_Client_Information_Face_Sheet.pdf","02_Service_Recipient_Rights_Acknowledgment.pdf","04_Authorization_to_Release_Information.pdf"]);expect((templates.find(row=>row.documentType==="RIGHTS_ACKNOWLEDGMENT")?.contentJson as {signerRoles:string[]}).signerRoles).toEqual(["CLIENT","LEGAL_REPRESENTATIVE_IF_APPLICABLE","RADIANT_CARE_STAFF"])});
  it("creates a tenant-scoped client and the exact operational checklist",async()=>{const result=await createClient(admin(),organizationId,{legalFirstName:"Jamie",legalLastName:"River",preferredName:"Jay",dateOfBirth:"1990-04-03",maPmiNumber:"PMI-100"});clientId=result.client.id;expect(result.intake.status).toBe("IN_PROGRESS");const items=await db.clientIntakeChecklistItem.findMany({where:{intakeId:result.intake.id},orderBy:{sequence:"asc"}});expect(items).toHaveLength(18);expect(items.map(row=>row.label)).toContain("Form 07 - Preliminary Support Plan / Self-Management Assessment completed (within 15 calendar days of service start)");expect(items.map(row=>row.label)).toContain("Support team meeting held (within 45 calendar days of service start) - Form 08");expect(await db.auditEvent.count({where:{organizationId,eventType:"client.created",entityId:clientId}})).toBe(1)});
  it("preserves guided progress, canonical records, conditional sections, and document-specific answers across backward edits",async()=>{let saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"SERVICES",services:[{serviceType:"IN_HOME_SUPPORT",authorizedHours:20,status:"ACTIVE",scheduleJson:{days:["MON","WED"]}}]});const serviceId=saved.services[0].id;saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"REPRESENTATIVE",representatives:[]});saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"EMERGENCY_CONTACTS",emergencyContacts:[{name:"Morgan River",relationship:"Sibling",phone:"555-0100",informationSharingAllowed:true}]});const emergencyId=saved.emergencyContacts[0].id;saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"HEALTH",health:{allergiesReactions:"Penicillin - rash",medicationResponsibility:"Organization assists under the care plan"}});saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"MEDICATIONS",medications:[]});saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"RIGHTS",rights:{writtenCopyReceivedDate:"2026-01-02",rightsExplainedDate:"2026-01-02",explanationMethod:"IN_PERSON"}});saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"ROI",roi:{direction:"BOTH",recipientName:"County",categories:["FACE_SHEET_CONTACT"],purposes:["SERVICE_COORDINATION"],effectiveDate:"2026-01-01",expirationDate:"2026-12-31"}});saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"CLIENT",client:{strengthsInterests:"Music and community",supportNeeds:"Plain-language communication"},services:[{id:serviceId,serviceType:"IN_HOME_SUPPORT",authorizedHours:24,status:"ACTIVE"}],emergencyContacts:[{id:emergencyId,name:"Morgan River",relationship:"Sibling",phone:"555-0100",informationSharingAllowed:true}]});const progress=saved.intakes[0].progressJson as {completedSections:string[];documentAnswers:{rights:{explanationMethod:string};roi:{recipientName:string}}};expect(progress.completedSections).toEqual(expect.arrayContaining(["SERVICES","REPRESENTATIVE","EMERGENCY_CONTACTS","HEALTH","MEDICATIONS","RIGHTS","ROI","CLIENT"]));expect(progress.documentAnswers.rights.explanationMethod).toBe("IN_PERSON");expect(progress.documentAnswers.roi.recipientName).toBe("County");expect(saved.services).toHaveLength(1);expect(saved.services[0].id).toBe(serviceId);expect(Number(saved.services[0].authorizedHours)).toBe(24);expect(saved.emergencyContacts[0].id).toBe(emergencyId);expect(saved.representatives).toHaveLength(0);expect(saved.medications).toHaveLength(0);expect(saved.healthProfile?.allergiesReactions).toContain("Penicillin")});
  it("reuses one professional case manager across clients",async()=>{const contact=await createProfessionalContact(admin(),organizationId,{name:"Case Manager One",agency:"County",contactType:"CASE_MANAGER",email:"case@example.test"});const second=await createClient(admin(),organizationId,{legalFirstName:"Second",legalLastName:"Client",dateOfBirth:"2000-01-01"});secondClientId=second.client.id;await assignProfessionalContact(admin(),organizationId,clientId,contact.id);await assignProfessionalContact(admin(),organizationId,secondClientId,contact.id);expect(await db.clientProfessionalContact.count({where:{professionalContactId:contact.id}})).toBe(2);expect(await db.professionalContact.count({where:{id:contact.id}})).toBe(1)});
  it("completes intake with actor attribution",async()=>{const result=await completeIntake(admin(),organizationId,clientId);expect(result.completedAt).toBeInstanceOf(Date);expect((await db.client.findUniqueOrThrow({where:{id:clientId}})).status).toBe("ACTIVE");expect((await db.clientIntake.findUniqueOrThrow({where:{id:result.intakeId}})).completedByUserId).toBe(adminId)});
  it("generates and freezes the authoritative three-page Face Sheet",async()=>{const face=await generateClientDocument(admin(),organizationId,clientId,"FACE_SHEET",{staffPrintedName:"Fictitious Staff"});faceDocumentId=face.id;expect((await PDFDocument.load(Buffer.from(face.renderedPdf!))).getPageCount()).toBe(3);await finalizeClientDocument(admin(),organizationId,clientId,face.id);await db.client.update({where:{id:clientId},data:{preferredName:"Changed Later"}});const stored=await db.clientDocument.findUniqueOrThrow({where:{id:face.id}}),snapshot=stored.snapshotJson as{client:{preferredName?:string}};expect(snapshot.client.preferredName).toBe("Jay");expect(stored.renderedPdf&&Buffer.from(stored.renderedPdf).subarray(0,4).toString()).toBe("%PDF")});
  it("supports source-mapped repeatable Rights and ROI while enforcing the one-year maximum",async()=>{const rights={writtenCopyReceivedDate:"2026-01-02",rightsExplainedDate:"2026-01-02",explanationMethod:"IN_PERSON" as const,annualReviewDate:"2027-01-02",grievanceContact:"Fictitious Coordinator",grievancePhoneEmail:"555-0100"},first=await generateClientDocument(admin(),organizationId,clientId,"RIGHTS_ACKNOWLEDGMENT",rights),second=await generateClientDocument(admin(),organizationId,clientId,"RIGHTS_ACKNOWLEDGMENT",{...rights,rightsExplainedDate:"2026-06-01"});rightsDocumentId=first.id;expect(first.id).not.toBe(second.id);expect((await PDFDocument.load(Buffer.from(first.renderedPdf!))).getPageCount()).toBe(2);expect((first.snapshotJson as {form:{explanationMethod:string}}).form.explanationMethod).toBe("IN_PERSON");await expect(createRoiAuthorization(admin(),organizationId,clientId,{direction:"BOTH",recipientName:"County",categories:["FACE_SHEET_CONTACT"],purposes:["SERVICE_COORDINATION"],effectiveDate:"2026-01-01",expirationDate:"2027-01-02"})).rejects.toThrow(/one year/);const roi=await createRoiAuthorization(admin(),organizationId,clientId,{direction:"BOTH",recipientName:"Fictitious County",relationshipRole:"Case manager",address:"100 Test Ave",categories:["FACE_SHEET_CONTACT","MEDICAL_HEALTH"],purposes:["SERVICE_COORDINATION"],effectiveDate:"2026-01-01",expirationDate:"2026-12-31"});roiDocumentId=roi.document.id;expect((await PDFDocument.load(Buffer.from(roi.document.renderedPdf!))).getPageCount()).toBe(2);expect(roiExpirationState(roi.roi,new Date("2026-12-15"))).toBe("EXPIRING_SOON");expect(roiExpirationState(roi.roi,new Date("2027-01-02"))).toBe("EXPIRED")});
  it("collects required signatures in arbitrary order into one envelope and one final document",async()=>{const envelope=await createSignatureEnvelope(admin(),organizationId,clientId,faceDocumentId,"SIGN_NOW",[{role:"CLIENT",name:"Jamie River"},{role:"ORGANIZATION_STAFF",name:"Staff One"}]);const afterStaff=await recordLocalTestSignature(admin(),organizationId,clientId,envelope.id,envelope.signers[1].id);expect(afterStaff.status).toBe("PARTIALLY_SIGNED");expect(afterStaff.document.status).toBe("PARTIALLY_SIGNED");const complete=await recordLocalTestSignature(admin(),organizationId,clientId,envelope.id,envelope.signers[0].id);expect(complete.status).toBe("COMPLETED");expect(complete.document.finalPdf).not.toBeNull();expect(await db.clientDocument.count({where:{id:faceDocumentId}})).toBe(1);expect(await db.signatureEnvelope.count({where:{documentId:faceDocumentId}})).toBe(1)});
  it("exercises Sign Now and Send for Signature provider boundaries",async()=>{const doc=await generateClientDocument(admin(),organizationId,secondClientId,"FACE_SHEET");await finalizeClientDocument(admin(),organizationId,secondClientId,doc.id);const local=new LocalTestSignatureProvider(),signNow=await createSignatureEnvelope(admin(),organizationId,secondClientId,doc.id,"SIGN_NOW",[{role:"CLIENT",name:"Second Client"}],local);expect((await createSignNowSession(admin(),organizationId,secondClientId,signNow.id,signNow.signers[0].id,local)).url).toMatch(/^local-signing:/);const rights=await generateClientDocument(admin(),organizationId,secondClientId,"RIGHTS_ACKNOWLEDGMENT",{writtenCopyReceivedDate:"2026-01-02",rightsExplainedDate:"2026-01-02",explanationMethod:"IN_PERSON"});await finalizeClientDocument(admin(),organizationId,secondClientId,rights.id);const send=vi.fn(async()=>{}),provider:ESignatureProvider={name:"test-remote",createEnvelope:async()=>({providerEnvelopeId:"remote-1"}),createSigningSession:async()=>({url:"https://sign.example.test"}),send,retrieveCompletedDocument:async()=>null,void:async()=>{}};const remote=await createSignatureEnvelope(admin(),organizationId,secondClientId,rights.id,"SEND_FOR_SIGNATURE",[{role:"CLIENT",name:"Second Client",email:"second@example.test"}],provider);expect(remote.status).toBe("SENT");expect(send).toHaveBeenCalledOnce()});
  it("prevents the local mock provider from masquerading as production execution",async()=>{vi.stubEnv("NODE_ENV","production");await expect(new LocalTestSignatureProvider().createEnvelope({documentId:"x"})).rejects.toThrow(/disabled in production/);vi.unstubAllEnvs()});
  it("exports the authoritative packet in Face, Rights, ROI, Checklist order using finalized bytes",async()=>{await finalizeClientDocument(admin(),organizationId,clientId,rightsDocumentId);await finalizeClientDocument(admin(),organizationId,clientId,roiDocumentId);const checklist=await generateClientDocument(admin(),organizationId,clientId,"INTAKE_CHECKLIST",{intakeCompletedBy:"Fictitious Staff"});await finalizeClientDocument(admin(),organizationId,clientId,checklist.id);const packet=await exportClientPacket(admin(),organizationId,clientId,[checklist.id,roiDocumentId,rightsDocumentId,faceDocumentId]);expect(packet.subarray(0,4).toString()).toBe("%PDF");expect((await PDFDocument.load(packet)).getPageCount()).toBe(10);const audit=await db.auditEvent.findFirstOrThrow({where:{organizationId,eventType:"client.packet_exported",entityId:clientId},orderBy:{occurredAt:"desc"}});expect((audit.metadataJson as {documentIds:string[]}).documentIds).toEqual([faceDocumentId,rightsDocumentId,roiDocumentId,checklist.id]);expect((audit.metadataJson as {usedFinalizedBytes:boolean[]}).usedFinalizedBytes).toEqual([true,false,false,false])});
  it("enforces RBAC, employee isolation, and cross-tenant IDOR protection",async()=>{await expect(getClient({id:employeeId},organizationId,clientId)).rejects.toThrow(/client.read/);await expect(getClient(admin(),otherOrganizationId,clientId)).rejects.toThrow(/denied/);await db.organizationMembership.create({data:{organizationId:otherOrganizationId,userId:adminId,status:"ACTIVE"}});await expect(getClient(admin(),otherOrganizationId,clientId)).rejects.toThrow(/client.read/)});
});

const templateDefinitions=[
  {code:"00-INTAKE-CHECKLIST",name:"Radiant Care LLC - Intake Checklist",documentType:"INTAKE_CHECKLIST" as const,versionNumber:2,contentJson:{renderer:"RADIANT_CARE_ACROFORM_V1",asset:"00_Intake_Checklist_Staff_Use.pdf",signerRoles:["ORGANIZATION_STAFF","DESIGNATED_COORDINATOR_OR_MANAGER"]}},
  {code:"01-FACE-SHEET",name:"Radiant Care LLC - Client Information / Face Sheet",documentType:"FACE_SHEET" as const,versionNumber:2,contentJson:{renderer:"RADIANT_CARE_ACROFORM_V1",asset:"01_Client_Information_Face_Sheet.pdf",signerRoles:["CLIENT_OR_LEGAL_REPRESENTATIVE","RADIANT_CARE_STAFF"]}},
  {code:"02-RIGHTS",name:"Radiant Care LLC - Service Recipient Rights",documentType:"RIGHTS_ACKNOWLEDGMENT" as const,versionNumber:2,contentJson:{renderer:"RADIANT_CARE_ACROFORM_V1",asset:"02_Service_Recipient_Rights_Acknowledgment.pdf",signerRoles:["CLIENT","LEGAL_REPRESENTATIVE_IF_APPLICABLE","RADIANT_CARE_STAFF"]}},
  {code:"04-ROI",name:"Radiant Care LLC - Authorization to Release Information",documentType:"ROI" as const,versionNumber:2,contentJson:{renderer:"RADIANT_CARE_ACROFORM_V1",asset:"04_Authorization_to_Release_Information.pdf",signerRoles:["CLIENT","LEGAL_REPRESENTATIVE_IF_APPLICABLE","RADIANT_CARE_STAFF"]}},
];
