import { PDFDocument } from "pdf-lib";
import { PrismaClient } from "@prisma/client";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { beforeAll, describe, expect, it, vi } from "vitest";
import { assignProfessionalContact, completeIntake, createClient, createProfessionalContact, getClient, saveIntake } from "@/domain/clients/service";
import { createRoiAuthorization, deleteClientDocumentDraft, exportClientPacket, finalizeClientDocument, generateClientDocument, importClientDocument, reviseClientDocumentDraft, roiExpirationState } from "@/domain/clients/documents";
import { createSignatureEnvelope, createSignNowSession, LocalTestSignatureProvider, recordLocalTestSignature, type ESignatureProvider } from "@/domain/clients/signatures";
import { mapRadiantCareTemplateFields } from "@/domain/clients/radiant-care-templates";

const db=new PrismaClient();
describe.sequential("client management, intake, documents, and signatures",()=>{
  let organizationId:string,otherOrganizationId:string,adminId:string,employeeId:string,clientId:string,secondClientId:string,faceDocumentId:string,rightsDocumentId:string,roiDocumentId:string;
  const admin=()=>({id:adminId});
  beforeAll(async()=>{const tag=`clients-${Date.now()}`,[organization,other,adminUser,employee]=await Promise.all([db.organization.create({data:{legalName:"Radiant Care LLC",displayName:"Radiant Care",slug:tag}}),db.organization.create({data:{legalName:`${tag}-other`,displayName:`${tag}-other`,slug:`${tag}-other`}}),db.user.create({data:{email:`${tag}-admin@example.test`,status:"ACTIVE"}}),db.user.create({data:{email:`${tag}-employee@example.test`,status:"ACTIVE"}})]);organizationId=organization.id;otherOrganizationId=other.id;adminId=adminUser.id;employeeId=employee.id;await db.clientDocumentTemplate.createMany({data:templateDefinitions.map(row=>({...row,organizationId}))});const permissions=await db.permission.findMany({where:{code:{startsWith:"client."}}}),role=await db.roleDefinition.create({data:{organizationId,code:"CLIENT_MANAGER",name:"Client manager",scope:"ORGANIZATION",permissions:{create:permissions.map(permission=>({permissionId:permission.id}))}}});await db.organizationMembership.create({data:{organizationId,userId:adminId,status:"ACTIVE",roles:{create:{roleDefinitionId:role.id}}}});await db.organizationMembership.create({data:{organizationId,userId:employeeId,status:"ACTIVE"}});await db.employee.create({data:{organizationId,userId:employeeId,firstName:"Ordinary",lastName:"Employee",employmentStatus:"ACTIVE"}});});
  it("retains four sanitized authoritative template assets, reviewed source text, and source layouts",async()=>{const root=join(process.cwd(),"reference/intake-forms/templates"),manifest=JSON.parse(readFileSync(join(root,"manifest.json"),"utf8")) as {templates:{file:string;pages:number;sha256:string;requiredText:string[]}[]};expect(manifest.templates).toHaveLength(4);for(const item of manifest.templates){const bytes=readFileSync(join(root,item.file)),pdf=await PDFDocument.load(bytes);expect(pdf.getPageCount()).toBe(item.pages);expect(pdf.getForm().getFields()).toHaveLength(0);expect(createHash("sha256").update(bytes).digest("hex")).toBe(item.sha256);expect(item.requiredText.length).toBeGreaterThanOrEqual(5)}expect(manifest.templates.find(row=>row.file.startsWith("02_"))?.requiredText).toContain("These rights were explained to me in a way I understand (within 5 working days of service start).");expect(manifest.templates.find(row=>row.file.startsWith("04_"))?.requiredText).toContain("You may cancel this authorization at any time by telling Radiant Care in writing.");const layout=JSON.parse(readFileSync(join(root,"field-layout.json"),"utf8"));expect(layout["02_Service_Recipient_Rights_Acknowledgment.pdf"]).toHaveProperty("RIGHTS_005_I_received_a_written_copy_of_these_right");expect(layout["04_Authorization_to_Release_Information.pdf"]).toHaveProperty("ROI_032_This_authorization_expires_on_date_or_ev")});
  it("selects organization-scoped authoritative version 2 templates with actual signature roles",async()=>{const templates=await db.clientDocumentTemplate.findMany({where:{organizationId},orderBy:{code:"asc"}});expect(templates).toHaveLength(4);expect(templates.every(row=>row.versionNumber===2)).toBe(true);expect(templates.map(row=>(row.contentJson as {asset:string}).asset)).toEqual(["00_Intake_Checklist_Staff_Use.pdf","01_Client_Information_Face_Sheet.pdf","02_Service_Recipient_Rights_Acknowledgment.pdf","04_Authorization_to_Release_Information.pdf"]);expect((templates.find(row=>row.documentType==="RIGHTS_ACKNOWLEDGMENT")?.contentJson as {signerRoles:string[]}).signerRoles).toEqual(["CLIENT","LEGAL_REPRESENTATIVE_IF_APPLICABLE","RADIANT_CARE_STAFF"])});
  it("creates a tenant-scoped client and the exact operational checklist",async()=>{const result=await createClient(admin(),organizationId,{legalFirstName:"Jamie",legalLastName:"River",preferredName:"Jay",dateOfBirth:"1990-04-03",maPmiNumber:"PMI-100"});clientId=result.client.id;expect(result.intake.status).toBe("IN_PROGRESS");const items=await db.clientIntakeChecklistItem.findMany({where:{intakeId:result.intake.id},orderBy:{sequence:"asc"}});expect(items).toHaveLength(18);expect(items.map(row=>row.label)).toContain("Form 07 - Preliminary Support Plan / Self-Management Assessment completed (within 15 calendar days of service start)");expect(items.map(row=>row.label)).toContain("Support team meeting held (within 45 calendar days of service start) - Form 08");expect(await db.auditEvent.count({where:{organizationId,eventType:"client.created",entityId:clientId}})).toBe(1)});
  it("creates without a DOB and recovers the same client after an ambiguous response",async()=>{const requestId=crypto.randomUUID(),input={legalFirstName:"Optional",legalLastName:`DOB-${Date.now()}`,requestId},first=await createClient(admin(),organizationId,input),retry=await createClient(admin(),organizationId,input);expect(first.client.dateOfBirth).toBeNull();expect(retry.client.id).toBe(first.client.id);expect(await db.client.count({where:{organizationId,creationRequestId:requestId}})).toBe(1);expect(await db.clientIntake.count({where:{clientId:first.client.id}})).toBe(1)});
  it("preserves guided progress, canonical records, conditional sections, and document-specific answers across backward edits",async()=>{
    let saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"SERVICES",services:[{serviceType:"IHS_WITH_TRAINING",startDate:"2026-01-15",authorizedHours:20,authorizationStart:"2026-01-01",authorizationEnd:"2026-12-31",status:"ACTIVE",scheduleJson:{authorizationPeriod:"weekly",serviceSchedule:"Monday and Wednesday at home"}}]});
    const serviceId=saved.services[0].id;
    saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"REPRESENTATIVE",representatives:[]});
    saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"EMERGENCY_CONTACTS",emergencyContacts:[{name:"Morgan River",relationship:"Sibling",phone:"555-0100",informationSharingAllowed:true}]});
    const emergencyId=saved.emergencyContacts[0].id;
    saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"HEALTH",health:{allergiesReactions:"Penicillin - rash",medicationResponsibility:"RADIANT_CARE_ASSISTS"}});
    saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"MEDICATIONS",medications:[]});
    saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"RIGHTS",rights:{writtenCopyReceivedDate:"2026-01-02",rightsExplainedDate:"2026-01-02",explanationMethod:"IN_PERSON"}});
    saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"ROI",roi:{direction:"BOTH",recipientName:"County",categories:["FACE_SHEET_CONTACT"],purposes:["SERVICE_COORDINATION"],effectiveDate:"2026-01-01",expirationDate:"2026-12-31"}});
    saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"CLIENT",client:{livingSituation:"OWN_HOME_APARTMENT",strengthsInterests:"Music and community",supportNeeds:"Plain-language communication"},services:[{id:serviceId,serviceType:"IHS_WITH_TRAINING",startDate:"2026-01-15",authorizedHours:24,authorizationStart:"2026-01-01",authorizationEnd:"2026-12-31",status:"ACTIVE",scheduleJson:{authorizationPeriod:"weekly",serviceSchedule:"Monday and Wednesday at home"}}],emergencyContacts:[{id:emergencyId,name:"Morgan River",relationship:"Sibling",phone:"555-0100",informationSharingAllowed:true}]});
    const intakeProgress=saved.intakes[0].progressJson as {completedSections:string[];visitedSections:string[];sectionStates:Record<string,string>;documentAnswers:{rights:{explanationMethod:string};roi:{recipientName:string}}};
    expect(intakeProgress.completedSections).toEqual(expect.arrayContaining(["SERVICES","REPRESENTATIVE","EMERGENCY_CONTACTS","HEALTH","MEDICATIONS","RIGHTS","ROI","CLIENT"]));
    expect(intakeProgress.sectionStates.CLIENT).toBe("COMPLETE");expect(intakeProgress.sectionStates.ABOUT_PERSON).toBe("UNVISITED");
    expect(intakeProgress.documentAnswers.rights.explanationMethod).toBe("IN_PERSON");expect(intakeProgress.documentAnswers.roi.recipientName).toBe("County");
    expect(saved.services[0].id).toBe(serviceId);expect(Number(saved.services[0].authorizedHours)).toBe(24);expect((saved.services[0].scheduleJson as {authorizationPeriod:string}).authorizationPeriod).toBe("weekly");expect(saved.emergencyContacts[0].id).toBe(emergencyId);expect(saved.representatives).toHaveLength(0);expect(saved.medications).toHaveLength(0);expect(saved.healthProfile?.allergiesReactions).toContain("Penicillin");
  });
  it("reuses one professional case manager across clients",async()=>{const contact=await createProfessionalContact(admin(),organizationId,{name:"Case Manager One",agency:"County",contactType:"CASE_MANAGER",email:"case@example.test"});const second=await createClient(admin(),organizationId,{legalFirstName:"Second",legalLastName:"Client",dateOfBirth:"2000-01-01"});secondClientId=second.client.id;await assignProfessionalContact(admin(),organizationId,clientId,contact.id);await assignProfessionalContact(admin(),organizationId,secondClientId,contact.id);await saveIntake(admin(),organizationId,clientId,{currentStep:"CASE_MANAGER"});expect(await db.clientProfessionalContact.count({where:{professionalContactId:contact.id}})).toBe(2);expect(await db.professionalContact.count({where:{id:contact.id}})).toBe(1)});
  it("returns actionable blockers, records deferred recommendations, and prepares the classified import idempotently",async()=>{await saveIntake(admin(),organizationId,clientId,{currentStep:"CLIENT",client:{livingSituation:null}});await expect(completeIntake(admin(),organizationId,clientId)).rejects.toMatchObject({message:expect.stringContaining("listed sections"),details:{sections:expect.arrayContaining([expect.objectContaining({step:"CLIENT"})])}});await saveIntake(admin(),organizationId,clientId,{currentStep:"CLIENT",client:{legalFirstName:"Jamie",legalLastName:"River",dateOfBirth:"1990-04-03",livingSituation:"OWN_HOME_APARTMENT"}});await saveIntake(admin(),organizationId,clientId,{currentStep:"EMERGENCY_CONTACTS",emergencyContacts:[]});const imported=await PDFDocument.create(),bytes=Buffer.from(await imported.save()),hash=createHash("sha256").update(bytes).digest("hex"),session=await db.clientImportSession.create({data:{organizationId,uploadedByUserId:adminId,existingClientId:clientId,target:"UPDATE_EXISTING",status:"CONFIRMED",confirmedAt:new Date()}});await db.clientImportDocument.create({data:{organizationId,sessionId:session.id,originalFileName:"synthetic-face.pdf",mimeType:"application/pdf",originalBytes:bytes,sha256:hash,classification:"FACE_SHEET",status:"ACCEPTED",pageCount:1}});await expect(completeIntake(admin(),organizationId,clientId)).rejects.toMatchObject({details:{acknowledgmentRequired:true,recommendations:[expect.objectContaining({step:"EMERGENCY_CONTACTS"})]}});const result=await completeIntake(admin(),organizationId,clientId,{acknowledgeRecommendations:true}),preparation="documentPreparation" in result?result.documentPreparation:undefined;expect(result.completedAt).toBeInstanceOf(Date);expect(result.deferredRecommendations).toEqual([expect.objectContaining({step:"EMERGENCY_CONTACTS"})]);expect(preparation).toMatchObject({prepared:["Face Sheet"],notPrepared:[]});expect(await db.clientDocument.count({where:{clientId,status:"DRAFT",source:"GENERATED",documentType:"FACE_SHEET"}})).toBe(1);expect((await db.client.findUniqueOrThrow({where:{id:clientId}})).status).toBe("ACTIVE");const completed=await db.clientIntake.findUniqueOrThrow({where:{id:result.intakeId}});expect(completed.completedByUserId).toBe(adminId);expect(completed.progressJson).toMatchObject({deferredRecommendations:[expect.objectContaining({step:"EMERGENCY_CONTACTS"})],recommendationsAcknowledgedAt:expect.any(String)});expect(await db.auditEvent.count({where:{organizationId,eventType:"client.intake_recommendations_deferred",entityId:result.intakeId}})).toBe(1);const repeat=await completeIntake(admin(),organizationId,clientId);expect(repeat).toMatchObject({intakeId:result.intakeId,alreadyCompleted:true});expect(await db.clientDocument.count({where:{clientId,status:"DRAFT",source:"GENERATED",documentType:"FACE_SHEET"}})).toBe(1)});
  it("updates canonical information after intake while preserving completion evidence and retiring stale drafts",async()=>{const intakeBefore=await db.clientIntake.findFirstOrThrow({where:{clientId,status:"COMPLETED"}}),service=await db.clientService.findFirstOrThrow({where:{clientId}}),stale=await generateClientDocument(admin(),organizationId,clientId,"INTAKE_CHECKLIST"),updated=await saveIntake(admin(),organizationId,clientId,{postCompletionUpdate:true,currentStep:"SERVICES",client:{phone:"555-0198"},services:[{id:service.id,serviceType:service.serviceType,startDate:service.startDate,authorizedHours:30,authorizationStart:service.authorizationStart,authorizationEnd:service.authorizationEnd,status:service.status,scheduleJson:service.scheduleJson as Record<string,unknown>}]});const intakeAfter=await db.clientIntake.findUniqueOrThrow({where:{id:intakeBefore.id}}),audit=await db.auditEvent.findFirstOrThrow({where:{organizationId,eventType:"client.post_intake_updated",entityId:clientId},orderBy:{occurredAt:"desc"}});expect(updated.phone).toBe("555-0198");expect(Number(updated.services[0].authorizedHours)).toBe(30);expect(intakeAfter).toMatchObject({status:"COMPLETED",completedAt:intakeBefore.completedAt,completedByUserId:intakeBefore.completedByUserId,progressJson:intakeBefore.progressJson});expect((await db.clientDocument.findUniqueOrThrow({where:{id:stale.id}})).status).toBe("VOIDED");expect(audit.metadataJson).toMatchObject({completedIntakeId:intakeBefore.id,step:"SERVICES",changedSections:["client","services"],staleDraftIds:expect.arrayContaining([stale.id])});await expect(saveIntake(admin(),organizationId,clientId,{postCompletionUpdate:true,currentStep:"RIGHTS",rights:{writtenCopyReceivedDate:"2026-01-01"}})).rejects.toThrow(/cannot be edited/)});
  it("maps post-intake structured service updates into the next authoritative draft",async()=>{const face=await generateClientDocument(admin(),organizationId,clientId,"FACE_SHEET"),fields=mapRadiantCareTemplateFields("FACE_SHEET",face.snapshotJson as Record<string,unknown>);expect(fields).toMatchObject({FACE_022_Service_s_to_be_provided_IHS_with_traini:true,FACE_025_Service_start_date:"01/15/2026",FACE_026_Authorized_units_hours:"30 hours weekly",FACE_027_Authorization_dates:"01/01/2026 - 12/31/2026"})});
  it("presents only the newest equivalent draft as actionable while preserving historical duplicates",async()=>{const template=await db.clientDocumentTemplate.findFirstOrThrow({where:{organizationId,documentType:"INTAKE_CHECKLIST"}}),intake=await db.clientIntake.findFirstOrThrow({where:{clientId,status:"COMPLETED"}}),older=await db.clientDocument.create({data:{organizationId,clientId,intakeId:intake.id,templateId:template.id,documentType:"INTAKE_CHECKLIST",snapshotJson:{legacy:"older"},generatedByUserId:adminId,generatedAt:new Date("2026-01-01")}}),newer=await db.clientDocument.create({data:{organizationId,clientId,intakeId:intake.id,templateId:template.id,documentType:"INTAKE_CHECKLIST",snapshotJson:{legacy:"newer"},generatedByUserId:adminId,generatedAt:new Date("2026-02-01")}}),view=await getClient(admin(),organizationId,clientId);expect(view.documents.find(row=>row.id===older.id)).toMatchObject({isCurrentActionable:false,isHistoricalDuplicate:true});expect(view.documents.find(row=>row.id===newer.id)).toMatchObject({isCurrentActionable:true,isHistoricalDuplicate:false});await db.clientDocument.updateMany({where:{id:{in:[older.id,newer.id]}},data:{status:"VOIDED",voidedAt:new Date()}})});
  it("generates and freezes the authoritative three-page Face Sheet",async()=>{const face=await generateClientDocument(admin(),organizationId,clientId,"FACE_SHEET",{staffPrintedName:"Fictitious Staff"});faceDocumentId=face.id;expect((await PDFDocument.load(Buffer.from(face.renderedPdf!))).getPageCount()).toBe(3);await finalizeClientDocument(admin(),organizationId,clientId,face.id);await db.client.update({where:{id:clientId},data:{preferredName:"Changed Later"}});const stored=await db.clientDocument.findUniqueOrThrow({where:{id:face.id}}),snapshot=stored.snapshotJson as{client:{preferredName?:string}};expect(snapshot.client.preferredName).toBe("Jay");expect(stored.renderedPdf&&Buffer.from(stored.renderedPdf).subarray(0,4).toString()).toBe("%PDF")});
  it("regenerates active drafts idempotently while preserving finalized records",async()=>{const rights={writtenCopyReceivedDate:"2026-01-02",rightsExplainedDate:"2026-01-02",explanationMethod:"IN_PERSON" as const,annualReviewDate:"2027-01-02",grievanceContact:"Fictitious Coordinator",grievancePhoneEmail:"555-0100"},first=await generateClientDocument(admin(),organizationId,clientId,"RIGHTS_ACKNOWLEDGMENT",rights),second=await generateClientDocument(admin(),organizationId,clientId,"RIGHTS_ACKNOWLEDGMENT",{...rights,rightsExplainedDate:"2026-06-01"});rightsDocumentId=first.id;expect(second.id).toBe(first.id);expect((second.snapshotJson as {form:{rightsExplainedDate:string}}).form.rightsExplainedDate).toContain("2026-06-01");expect(await db.clientDocument.count({where:{clientId,documentType:"RIGHTS_ACKNOWLEDGMENT",status:"DRAFT"}})).toBe(1);expect((await PDFDocument.load(Buffer.from(second.renderedPdf!))).getPageCount()).toBe(2);const concurrent=await Promise.all([generateClientDocument(admin(),organizationId,clientId,"INTAKE_CHECKLIST"),generateClientDocument(admin(),organizationId,clientId,"INTAKE_CHECKLIST")]);expect(concurrent[0].id).toBe(concurrent[1].id);expect(await db.clientDocument.count({where:{clientId,documentType:"INTAKE_CHECKLIST",status:"DRAFT"}})).toBe(1);await expect(createRoiAuthorization(admin(),organizationId,clientId,{direction:"BOTH",recipientName:"County",categories:["FACE_SHEET_CONTACT"],purposes:["SERVICE_COORDINATION"],effectiveDate:"2026-01-01",expirationDate:"2027-01-02"})).rejects.toThrow(/one year/);const roi=await createRoiAuthorization(admin(),organizationId,clientId,{direction:"BOTH",recipientName:"Fictitious County",relationshipRole:"Case manager",address:"100 Test Ave",categories:["FACE_SHEET_CONTACT","MEDICAL_HEALTH"],purposes:["SERVICE_COORDINATION"],effectiveDate:"2026-01-01",expirationDate:"2026-12-31"}),regenerated=await createRoiAuthorization(admin(),organizationId,clientId,{direction:"BOTH",recipientName:"Updated Synthetic County",categories:["FACE_SHEET_CONTACT"],purposes:["SERVICE_COORDINATION"],effectiveDate:"2026-01-01",expirationDate:"2026-12-31"});roiDocumentId=roi.document.id;expect(regenerated.document.id).toBe(roi.document.id);expect(regenerated.roi.recipientName).toBe("Updated Synthetic County");expect((await PDFDocument.load(Buffer.from(regenerated.document.renderedPdf!))).getPageCount()).toBe(2);expect(roiExpirationState(regenerated.roi,new Date("2026-12-15"))).toBe("EXPIRING_SOON")});
  it("versions and soft-deletes only eligible unsigned generated drafts",async()=>{const draft=await generateClientDocument(admin(),organizationId,secondClientId,"RIGHTS_ACKNOWLEDGMENT",{writtenCopyReceivedDate:"2026-03-01",rightsExplainedDate:"2026-03-01",explanationMethod:"IN_PERSON"}),revision=await reviseClientDocumentDraft(admin(),organizationId,secondClientId,draft.id,{formData:{writtenCopyReceivedDate:"2026-03-01",rightsExplainedDate:"2026-03-02",explanationMethod:"PHONE_VIDEO"}});expect(revision.id).not.toBe(draft.id);expect((await db.clientDocument.findUniqueOrThrow({where:{id:draft.id}}))).toMatchObject({status:"VOIDED",voidedAt:expect.any(Date)});expect(revision.status).toBe("DRAFT");expect((revision.snapshotJson as {form:{explanationMethod:string}}).form.explanationMethod).toBe("PHONE_VIDEO");expect(await db.auditEvent.count({where:{organizationId,eventType:"client.document_draft_revised",entityId:revision.id}})).toBe(1);await expect(reviseClientDocumentDraft(admin(),otherOrganizationId,secondClientId,revision.id,{})).rejects.toThrow();const deleted=await deleteClientDocumentDraft(admin(),organizationId,secondClientId,revision.id);expect(deleted).toMatchObject({status:"VOIDED",voidedAt:expect.any(Date)});expect(await db.auditEvent.count({where:{organizationId,eventType:"client.document_draft_deleted",entityId:revision.id}})).toBe(1);const imported=await importClientDocument(admin(),organizationId,secondClientId,{documentType:"FACE_SHEET",fileName:"preserved.pdf",pdfBase64:Buffer.from(revision.renderedPdf!).toString("base64"),disposition:"CURRENT_SIGNATURE_REQUIRED"});await expect(reviseClientDocumentDraft(admin(),organizationId,secondClientId,imported.id,{})).rejects.toThrow(/unsigned platform draft/);await expect(deleteClientDocumentDraft(admin(),organizationId,secondClientId,imported.id)).rejects.toThrow(/unsigned, unfinalized platform draft/);await expect(deleteClientDocumentDraft(admin(),organizationId,clientId,faceDocumentId)).rejects.toThrow(/unsigned, unfinalized platform draft/)});
  it("collects required signatures in arbitrary order into one envelope and one final document",async()=>{const envelope=await createSignatureEnvelope(admin(),organizationId,clientId,faceDocumentId,"SIGN_NOW",[{role:"CLIENT",name:"Jamie River"},{role:"ORGANIZATION_STAFF",name:"Staff One"}]);const afterStaff=await recordLocalTestSignature(admin(),organizationId,clientId,envelope.id,envelope.signers[1].id);expect(afterStaff.status).toBe("PARTIALLY_SIGNED");expect(afterStaff.document.status).toBe("PARTIALLY_SIGNED");const complete=await recordLocalTestSignature(admin(),organizationId,clientId,envelope.id,envelope.signers[0].id);expect(complete.status).toBe("COMPLETED");expect(complete.document.finalPdf).not.toBeNull();expect(await db.clientDocument.count({where:{id:faceDocumentId}})).toBe(1);expect(await db.signatureEnvelope.count({where:{documentId:faceDocumentId}})).toBe(1)});
  it("exercises Sign Now and Send for Signature provider boundaries",async()=>{const doc=await generateClientDocument(admin(),organizationId,secondClientId,"FACE_SHEET");await finalizeClientDocument(admin(),organizationId,secondClientId,doc.id);const local=new LocalTestSignatureProvider(),signNow=await createSignatureEnvelope(admin(),organizationId,secondClientId,doc.id,"SIGN_NOW",[{role:"CLIENT",name:"Second Client"}],local);expect((await createSignNowSession(admin(),organizationId,secondClientId,signNow.id,signNow.signers[0].id,local)).url).toMatch(/^local-signing:/);const rights=await generateClientDocument(admin(),organizationId,secondClientId,"RIGHTS_ACKNOWLEDGMENT",{writtenCopyReceivedDate:"2026-01-02",rightsExplainedDate:"2026-01-02",explanationMethod:"IN_PERSON"});await finalizeClientDocument(admin(),organizationId,secondClientId,rights.id);const send=vi.fn(async()=>{}),provider:ESignatureProvider={name:"test-remote",createEnvelope:async()=>({providerEnvelopeId:"remote-1"}),createSigningSession:async()=>({url:"https://sign.example.test"}),send,retrieveCompletedDocument:async()=>null,void:async()=>{}};const remote=await createSignatureEnvelope(admin(),organizationId,secondClientId,rights.id,"SEND_FOR_SIGNATURE",[{role:"CLIENT",name:"Second Client",email:"second@example.test"}],provider);expect(remote.status).toBe("SENT");expect(send).toHaveBeenCalledOnce()});
  it("prevents the local mock provider from masquerading as production execution",async()=>{vi.stubEnv("NODE_ENV","production");await expect(new LocalTestSignatureProvider().createEnvelope({documentId:"x"})).rejects.toThrow(/disabled in production/);vi.unstubAllEnvs()});
  it("carries TEST CLIENT ALPHA guided values through persistence, snapshots, and authoritative field mapping",async()=>{
    const created=await createClient(admin(),organizationId,{legalFirstName:"TEST CLIENT",legalLastName:"ALPHA",dateOfBirth:"1991-02-03"}),id=created.client.id,caseManager=await createProfessionalContact(admin(),organizationId,{name:"SYNTHETIC CASE MANAGER",agency:"SYNTHETIC COUNTY",contactType:"CASE_MANAGER",email:"synthetic-case@example.test"});
    await saveIntake(admin(),organizationId,id,{currentStep:"CLIENT",client:{livingSituation:"FAMILY_HOME",maPmiNumber:"SYNTHETIC-ALPHA"}});
    await saveIntake(admin(),organizationId,id,{currentStep:"SERVICES",services:[{serviceType:"IHS_WITH_FAMILY_TRAINING",startDate:"2026-02-01",authorizedHours:45,authorizationStart:"2026-02-01",authorizationEnd:"2027-01-31",scheduleJson:{authorizationPeriod:"weekly",serviceSchedule:"Weekdays at synthetic residence"}}]});
    await saveIntake(admin(),organizationId,id,{currentStep:"REPRESENTATIVE",representatives:[{representativeType:"GUARDIAN",name:"SYNTHETIC GUARDIAN",relationship:"Synthetic relationship",email:"guardian@example.test"}]});
    await assignProfessionalContact(admin(),organizationId,id,caseManager.id);await saveIntake(admin(),organizationId,id,{currentStep:"CASE_MANAGER"});
    await saveIntake(admin(),organizationId,id,{currentStep:"EMERGENCY_CONTACTS",emergencyContacts:[{name:"SYNTHETIC EMERGENCY CONTACT",relationship:"Synthetic relationship",phone:"555-0199",informationSharingAllowed:true}]});
    await saveIntake(admin(),organizationId,id,{currentStep:"HEALTH",health:{primaryCareProvider:"SYNTHETIC CLINICIAN",allergiesReactions:"SYNTHETIC ALLERGY",medicationResponsibility:"FAMILY_OTHER_MANAGES"}});
    await saveIntake(admin(),organizationId,id,{currentStep:"MEDICATIONS",medications:[]});
    await saveIntake(admin(),organizationId,id,{currentStep:"RIGHTS",rights:{writtenCopyReceivedDate:"2026-02-01",rightsExplainedDate:"2026-02-02",explanationMethod:"INTERPRETER",grievanceContact:"SYNTHETIC GRIEVANCE CONTACT"}});
    await saveIntake(admin(),organizationId,id,{currentStep:"ROI",roi:{direction:"BOTH",recipientName:"SYNTHETIC ROI RECIPIENT",categories:["FACE_SHEET_CONTACT","MEDICAL_HEALTH"],purposes:["SERVICE_COORDINATION"],effectiveDate:"2026-02-01",expirationDate:"2027-01-31"}});
    const face=await generateClientDocument(admin(),organizationId,id,"FACE_SHEET"),rights=await generateClientDocument(admin(),organizationId,id,"RIGHTS_ACKNOWLEDGMENT",{writtenCopyReceivedDate:"2026-02-01",rightsExplainedDate:"2026-02-02",explanationMethod:"INTERPRETER",grievanceContact:"SYNTHETIC GRIEVANCE CONTACT"}),roi=await createRoiAuthorization(admin(),organizationId,id,{direction:"BOTH",recipientName:"SYNTHETIC ROI RECIPIENT",categories:["FACE_SHEET_CONTACT","MEDICAL_HEALTH"],purposes:["SERVICE_COORDINATION"],effectiveDate:"2026-02-01",expirationDate:"2027-01-31"});
    const faceFields=mapRadiantCareTemplateFields("FACE_SHEET",face.snapshotJson as Record<string,unknown>),rightsFields=mapRadiantCareTemplateFields("RIGHTS_ACKNOWLEDGMENT",rights.snapshotJson as Record<string,unknown>),roiFields=mapRadiantCareTemplateFields("ROI",roi.document.snapshotJson as Record<string,unknown>);
    expect(faceFields).toMatchObject({FACE_001_Legal_first_name:"TEST CLIENT",FACE_002_Last_name:"ALPHA",FACE_019_Living_situation_Family_home:true,FACE_022_Service_s_to_be_provided_IHS_with_traini:true,FACE_026_Authorized_units_hours:"45 hours weekly",FACE_025_Service_start_date:"02/01/2026",FACE_027_Authorization_dates:"02/01/2026 - 01/31/2027",FACE_030_legal_rep_type_Guardian:true,FACE_034_Name:"SYNTHETIC GUARDIAN",FACE_039_Case_manager_name:"SYNTHETIC CASE MANAGER",FACE_061_Primary_care_provider:"SYNTHETIC CLINICIAN",FACE_101_Medication_responsibility_Family_other_m:true});
    expect(rightsFields).toMatchObject({RIGHTS_005_I_received_a_written_copy_of_these_right:true,RIGHTS_010_How_rights_were_explained_Phone_video:false,RIGHTS_011_How_rights_were_explained_Interpreter_us:true,RIGHTS_003_Radiant_Care_contact_for_problems_or_gri:"SYNTHETIC GRIEVANCE CONTACT"});
    expect(roiFields).toMatchObject({ROI_006_direction_Both:true,ROI_007_Name_of_person_or_agency:"SYNTHETIC ROI RECIPIENT",ROI_012_info_type_Face_sheet_contact_information:true,ROI_016_info_type_Medical_health_information:true,ROI_025_purpose_Coordinate_services:true,ROI_033_Effective_date:"02/01/2026"});
    expect(Buffer.from(face.renderedPdf!).subarray(0,4).toString()).toBe("%PDF");expect(Buffer.from(rights.renderedPdf!).subarray(0,4).toString()).toBe("%PDF");expect(Buffer.from(roi.document.renderedPdf!).subarray(0,4).toString()).toBe("%PDF");
  });
  it("exports the authoritative packet in Face, Rights, ROI, Checklist order using finalized bytes",async()=>{await finalizeClientDocument(admin(),organizationId,clientId,rightsDocumentId);await finalizeClientDocument(admin(),organizationId,clientId,roiDocumentId);const checklist=await generateClientDocument(admin(),organizationId,clientId,"INTAKE_CHECKLIST",{intakeCompletedBy:"Fictitious Staff"});await finalizeClientDocument(admin(),organizationId,clientId,checklist.id);const packet=await exportClientPacket(admin(),organizationId,clientId,[checklist.id,roiDocumentId,rightsDocumentId,faceDocumentId]);expect(packet.subarray(0,4).toString()).toBe("%PDF");expect((await PDFDocument.load(packet)).getPageCount()).toBe(10);const audit=await db.auditEvent.findFirstOrThrow({where:{organizationId,eventType:"client.packet_exported",entityId:clientId},orderBy:{occurredAt:"desc"}});expect((audit.metadataJson as {documentIds:string[]}).documentIds).toEqual([faceDocumentId,rightsDocumentId,roiDocumentId,checklist.id]);expect((audit.metadataJson as {usedFinalizedBytes:boolean[]}).usedFinalizedBytes).toEqual([true,false,false,false])});
  it("enforces RBAC, employee isolation, and cross-tenant IDOR protection",async()=>{await expect(getClient({id:employeeId},organizationId,clientId)).rejects.toThrow(/client.read/);await expect(getClient(admin(),otherOrganizationId,clientId)).rejects.toThrow(/denied/);await db.organizationMembership.create({data:{organizationId:otherOrganizationId,userId:adminId,status:"ACTIVE"}});await expect(getClient(admin(),otherOrganizationId,clientId)).rejects.toThrow(/client.read/)});
});

const templateDefinitions=[
  {code:"00-INTAKE-CHECKLIST",name:"Radiant Care LLC - Intake Checklist",documentType:"INTAKE_CHECKLIST" as const,versionNumber:2,contentJson:{renderer:"RADIANT_CARE_ACROFORM_V1",asset:"00_Intake_Checklist_Staff_Use.pdf",signerRoles:["ORGANIZATION_STAFF","DESIGNATED_COORDINATOR_OR_MANAGER"]}},
  {code:"01-FACE-SHEET",name:"Radiant Care LLC - Client Information / Face Sheet",documentType:"FACE_SHEET" as const,versionNumber:2,contentJson:{renderer:"RADIANT_CARE_ACROFORM_V1",asset:"01_Client_Information_Face_Sheet.pdf",signerRoles:["CLIENT_OR_LEGAL_REPRESENTATIVE","RADIANT_CARE_STAFF"]}},
  {code:"02-RIGHTS",name:"Radiant Care LLC - Service Recipient Rights",documentType:"RIGHTS_ACKNOWLEDGMENT" as const,versionNumber:2,contentJson:{renderer:"RADIANT_CARE_ACROFORM_V1",asset:"02_Service_Recipient_Rights_Acknowledgment.pdf",signerRoles:["CLIENT","LEGAL_REPRESENTATIVE_IF_APPLICABLE","RADIANT_CARE_STAFF"]}},
  {code:"04-ROI",name:"Radiant Care LLC - Authorization to Release Information",documentType:"ROI" as const,versionNumber:2,contentJson:{renderer:"RADIANT_CARE_ACROFORM_V1",asset:"04_Authorization_to_Release_Information.pdf",signerRoles:["CLIENT","LEGAL_REPRESENTATIVE_IF_APPLICABLE","RADIANT_CARE_STAFF"]}},
];
