import { PDFDocument } from "pdf-lib";
import { PrismaClient } from "@prisma/client";
import { beforeAll, describe, expect, it, vi } from "vitest";
import { assignProfessionalContact, completeIntake, createClient, createProfessionalContact, getClient, saveIntake } from "@/domain/clients/service";
import { createRoiAuthorization, exportClientPacket, finalizeClientDocument, generateClientDocument, roiExpirationState } from "@/domain/clients/documents";
import { createSignatureEnvelope, createSignNowSession, LocalTestSignatureProvider, recordLocalTestSignature, type ESignatureProvider } from "@/domain/clients/signatures";

const db=new PrismaClient();
describe.sequential("client management, intake, documents, and signatures",()=>{
  let organizationId:string,otherOrganizationId:string,adminId:string,employeeId:string,clientId:string,secondClientId:string,faceDocumentId:string;
  const admin=()=>({id:adminId});
  beforeAll(async()=>{const tag=`clients-${Date.now()}`,[organization,other,adminUser,employee]=await Promise.all([db.organization.create({data:{legalName:tag,displayName:tag,slug:tag}}),db.organization.create({data:{legalName:`${tag}-other`,displayName:`${tag}-other`,slug:`${tag}-other`}}),db.user.create({data:{email:`${tag}-admin@example.test`,status:"ACTIVE"}}),db.user.create({data:{email:`${tag}-employee@example.test`,status:"ACTIVE"}})]);organizationId=organization.id;otherOrganizationId=other.id;adminId=adminUser.id;employeeId=employee.id;const permissions=await db.permission.findMany({where:{code:{startsWith:"client."}}}),role=await db.roleDefinition.create({data:{organizationId,code:"CLIENT_MANAGER",name:"Client manager",scope:"ORGANIZATION",permissions:{create:permissions.map(permission=>({permissionId:permission.id}))}}});await db.organizationMembership.create({data:{organizationId,userId:adminId,status:"ACTIVE",roles:{create:{roleDefinitionId:role.id}}}});await db.organizationMembership.create({data:{organizationId,userId:employeeId,status:"ACTIVE"}});await db.employee.create({data:{organizationId,userId:employeeId,firstName:"Ordinary",lastName:"Employee",employmentStatus:"ACTIVE"}});});
  it("creates a tenant-scoped client and resumable draft intake",async()=>{const result=await createClient(admin(),organizationId,{legalFirstName:"Jamie",legalLastName:"River",preferredName:"Jay",dateOfBirth:"1990-04-03",maPmiNumber:"PMI-100"});clientId=result.client.id;expect(result.intake.status).toBe("IN_PROGRESS");expect(await db.clientIntakeChecklistItem.count({where:{intakeId:result.intake.id}})).toBe(18);expect(await db.auditEvent.count({where:{organizationId,eventType:"client.created",entityId:clientId}})).toBe(1)});
  it("saves structured services, emergency contacts, health, medications, and person-centered data",async()=>{const saved=await saveIntake(admin(),organizationId,clientId,{currentStep:"HEALTH_MEDICATION",client:{strengthsInterests:"Music and community",supportNeeds:"Plain-language communication"},services:[{serviceType:"IN_HOME_SUPPORT",authorizedHours:20,status:"ACTIVE",scheduleJson:{days:["MON","WED"]}}],emergencyContacts:[{name:"Morgan River",relationship:"Sibling",phone:"555-0100",informationSharingAllowed:true}],health:{allergiesReactions:"Penicillin - rash",medicationResponsibility:"Organization assists under the care plan"},medications:[{medication:"Example medication",dose:"10 mg",times:"Morning",reason:"Intake context",prescriber:"Dr Example"}]});expect(saved.services).toHaveLength(1);expect(saved.emergencyContacts).toHaveLength(1);expect(saved.medications).toHaveLength(1);expect(saved.healthProfile?.allergiesReactions).toContain("Penicillin")});
  it("reuses one professional case manager across clients",async()=>{const contact=await createProfessionalContact(admin(),organizationId,{name:"Case Manager One",agency:"County",contactType:"CASE_MANAGER",email:"case@example.test"});const second=await createClient(admin(),organizationId,{legalFirstName:"Second",legalLastName:"Client",dateOfBirth:"2000-01-01"});secondClientId=second.client.id;await assignProfessionalContact(admin(),organizationId,clientId,contact.id);await assignProfessionalContact(admin(),organizationId,secondClientId,contact.id);expect(await db.clientProfessionalContact.count({where:{professionalContactId:contact.id}})).toBe(2);expect(await db.professionalContact.count({where:{id:contact.id}})).toBe(1)});
  it("completes intake with actor attribution",async()=>{const result=await completeIntake(admin(),organizationId,clientId);expect(result.completedAt).toBeInstanceOf(Date);expect((await db.client.findUniqueOrThrow({where:{id:clientId}})).status).toBe("ACTIVE");expect((await db.clientIntake.findUniqueOrThrow({where:{id:result.intakeId}})).completedByUserId).toBe(adminId)});
  it("generates Face Sheet data once and freezes the finalized snapshot",async()=>{const face=await generateClientDocument(admin(),organizationId,clientId,"FACE_SHEET");faceDocumentId=face.id;await finalizeClientDocument(admin(),organizationId,clientId,face.id);await db.client.update({where:{id:clientId},data:{preferredName:"Changed Later"}});const stored=await db.clientDocument.findUniqueOrThrow({where:{id:face.id}}),snapshot=stored.snapshotJson as{client:{preferredName?:string}};expect(snapshot.client.preferredName).toBe("Jay");expect(stored.renderedPdf&&Buffer.from(stored.renderedPdf).subarray(0,4).toString()).toBe("%PDF")});
  it("supports repeatable rights acknowledgments and ROI while enforcing the one-year maximum",async()=>{const rights={writtenCopyReceivedDate:"2026-01-02",rightsExplainedDate:"2026-01-02",explanationMethod:"IN_PERSON" as const,annualReviewDate:"2027-01-02"},first=await generateClientDocument(admin(),organizationId,clientId,"RIGHTS_ACKNOWLEDGMENT",rights),second=await generateClientDocument(admin(),organizationId,clientId,"RIGHTS_ACKNOWLEDGMENT",{...rights,rightsExplainedDate:"2026-06-01"});expect(first.id).not.toBe(second.id);expect((first.snapshotJson as {form:{explanationMethod:string}}).form.explanationMethod).toBe("IN_PERSON");await expect(createRoiAuthorization(admin(),organizationId,clientId,{direction:"BOTH",recipientName:"County",categories:["FACE_SHEET_CONTACT"],purposes:["SERVICE_COORDINATION"],effectiveDate:"2026-01-01",expirationDate:"2027-01-02"})).rejects.toThrow(/one year/);const roi=await createRoiAuthorization(admin(),organizationId,clientId,{direction:"BOTH",recipientName:"County",categories:["FACE_SHEET_CONTACT","MEDICAL_HEALTH"],purposes:["SERVICE_COORDINATION"],effectiveDate:"2026-01-01",expirationDate:"2026-12-31"});expect(roiExpirationState(roi.roi,new Date("2026-12-15"))).toBe("EXPIRING_SOON");expect(roiExpirationState(roi.roi,new Date("2027-01-02"))).toBe("EXPIRED")});
  it("collects required signatures in arbitrary order into one envelope and one final document",async()=>{const envelope=await createSignatureEnvelope(admin(),organizationId,clientId,faceDocumentId,"SIGN_NOW",[{role:"CLIENT",name:"Jamie River"},{role:"ORGANIZATION_STAFF",name:"Staff One"}]);const afterStaff=await recordLocalTestSignature(admin(),organizationId,clientId,envelope.id,envelope.signers[1].id);expect(afterStaff.status).toBe("PARTIALLY_SIGNED");expect(afterStaff.document.status).toBe("PARTIALLY_SIGNED");const complete=await recordLocalTestSignature(admin(),organizationId,clientId,envelope.id,envelope.signers[0].id);expect(complete.status).toBe("COMPLETED");expect(complete.document.finalPdf).not.toBeNull();expect(await db.clientDocument.count({where:{id:faceDocumentId}})).toBe(1);expect(await db.signatureEnvelope.count({where:{documentId:faceDocumentId}})).toBe(1)});
  it("exercises Sign Now and Send for Signature provider boundaries",async()=>{const doc=await generateClientDocument(admin(),organizationId,secondClientId,"FACE_SHEET");await finalizeClientDocument(admin(),organizationId,secondClientId,doc.id);const local=new LocalTestSignatureProvider(),signNow=await createSignatureEnvelope(admin(),organizationId,secondClientId,doc.id,"SIGN_NOW",[{role:"CLIENT",name:"Second Client"}],local);expect((await createSignNowSession(admin(),organizationId,secondClientId,signNow.id,signNow.signers[0].id,local)).url).toMatch(/^local-signing:/);const rights=await generateClientDocument(admin(),organizationId,secondClientId,"RIGHTS_ACKNOWLEDGMENT",{writtenCopyReceivedDate:"2026-01-02",rightsExplainedDate:"2026-01-02",explanationMethod:"IN_PERSON"});await finalizeClientDocument(admin(),organizationId,secondClientId,rights.id);const send=vi.fn(async()=>{}),provider:ESignatureProvider={name:"test-remote",createEnvelope:async()=>({providerEnvelopeId:"remote-1"}),createSigningSession:async()=>({url:"https://sign.example.test"}),send,retrieveCompletedDocument:async()=>null,void:async()=>{}};const remote=await createSignatureEnvelope(admin(),organizationId,secondClientId,rights.id,"SEND_FOR_SIGNATURE",[{role:"CLIENT",name:"Second Client",email:"second@example.test"}],provider);expect(remote.status).toBe("SENT");expect(send).toHaveBeenCalledOnce()});
  it("prevents the local mock provider from masquerading as production execution",async()=>{vi.stubEnv("NODE_ENV","production");await expect(new LocalTestSignatureProvider().createEnvelope({documentId:"x"})).rejects.toThrow(/disabled in production/);vi.unstubAllEnvs()});
  it("exports a combined PDF using finalized bytes when available",async()=>{const checklist=await generateClientDocument(admin(),organizationId,clientId,"INTAKE_CHECKLIST"),packet=await exportClientPacket(admin(),organizationId,clientId,[faceDocumentId,checklist.id]);expect(packet.subarray(0,4).toString()).toBe("%PDF");expect((await PDFDocument.load(packet)).getPageCount()).toBeGreaterThanOrEqual(3);expect(await db.auditEvent.count({where:{organizationId,eventType:"client.packet_exported",entityId:clientId}})).toBe(1)});
  it("enforces RBAC, employee isolation, and cross-tenant IDOR protection",async()=>{await expect(getClient({id:employeeId},organizationId,clientId)).rejects.toThrow(/client.read/);await expect(getClient(admin(),otherOrganizationId,clientId)).rejects.toThrow(/denied/);await db.organizationMembership.create({data:{organizationId:otherOrganizationId,userId:adminId,status:"ACTIVE"}});await expect(getClient(admin(),otherOrganizationId,clientId)).rejects.toThrow(/client.read/)});
});
