import { PrismaClient, type ClientDocumentType } from "@prisma/client";
import { beforeAll, describe, expect, it, vi } from "vitest";
import { getActionCenter } from "@/domain/action-center/service";
import { AuthorizationError, ResourceNotFoundError } from "@/domain/auth/errors";
import { getClientDocumentationReadiness, getOrganizationClientDocumentationReadiness } from "@/domain/clients/readiness";
import { prisma } from "@/lib/prisma";

const db=new PrismaClient();
describe.sequential("client documentation compliance readiness",()=>{
 const at=new Date("2026-10-01T12:00:00.000Z");
 let organizationId:string,otherOrganizationId:string,adminId:string,readerId:string,ordinaryId:string,readyId:string,missingId:string,outstandingId:string,approachingId:string,dueSoonId:string,dueTodayId:string,overdueId:string,renewedId:string,signatureId:string,signedId:string,fulfilledId:string;
 let templates:Record<ClientDocumentType,string>;
 const admin=()=>({id:adminId});
 async function client(label:string,organization=organizationId){return(await db.client.create({data:{organizationId:organization,legalFirstName:label,legalLastName:"Readiness",dateOfBirth:new Date("1990-01-01"),status:"ACTIVE",createdByUserId:adminId}})).id}
 async function document(clientId:string,type:ClientDocumentType,status:"COMPLETED"|"READY_FOR_SIGNATURE"="COMPLETED",completedAt=new Date("2026-01-01T12:00:00Z"),renewalOfDocumentId?:string){return db.clientDocument.create({data:{organizationId,clientId,templateId:templates[type],documentType:type,status,snapshotJson:{},generatedByUserId:adminId,authoritativeCompletedAt:status==="COMPLETED"?completedAt:null,renewalOfDocumentId}})}
 async function completeNonRights(clientId:string,face=true){await Promise.all([document(clientId,"INTAKE_CHECKLIST"),face?document(clientId,"FACE_SHEET"):Promise.resolve(null)]);const roi=await document(clientId,"ROI");await db.roiAuthorization.create({data:{organizationId,clientId,documentId:roi.id,direction:"BOTH",recipientName:"Authorized recipient",categories:[],purposes:[],effectiveDate:new Date("2026-01-01"),expirationDate:new Date("2027-01-01"),status:"ACTIVE"}})}
 async function readyClient(label:string,rightsCompletedAt:Date){const id=await client(label);await completeNonRights(id);await document(id,"RIGHTS_ACKNOWLEDGMENT","COMPLETED",rightsCompletedAt);return id}

 beforeAll(async()=>{const tag=`client-readiness-${Date.now()}`,[org,other,administrator,reader,ordinary]=await Promise.all([db.organization.create({data:{legalName:tag,displayName:tag,slug:tag,timezone:"UTC"}}),db.organization.create({data:{legalName:`${tag}-other`,displayName:`${tag}-other`,slug:`${tag}-other`,timezone:"UTC"}}),db.user.create({data:{email:`${tag}-admin@example.test`,status:"ACTIVE"}}),db.user.create({data:{email:`${tag}-reader@example.test`,status:"ACTIVE"}}),db.user.create({data:{email:`${tag}-ordinary@example.test`,status:"ACTIVE"}})]);organizationId=org.id;otherOrganizationId=other.id;adminId=administrator.id;readerId=reader.id;ordinaryId=ordinary.id;
  const permissions=await db.permission.findMany({where:{code:{in:["client.read","compliance.operations.read"]}}}),adminRole=await db.roleDefinition.create({data:{organizationId,code:`${tag}-ADMIN`,name:"Readiness administrator",scope:"ORGANIZATION",permissions:{create:permissions.map(row=>({permissionId:row.id}))}}}),readerRole=await db.roleDefinition.create({data:{organizationId,code:`${tag}-READER`,name:"Readiness reader",scope:"ORGANIZATION",permissions:{create:permissions.filter(row=>row.code==="client.read").map(row=>({permissionId:row.id}))}}}),[adminMembership,readerMembership]=await Promise.all([db.organizationMembership.create({data:{organizationId,userId:adminId,status:"ACTIVE"}}),db.organizationMembership.create({data:{organizationId,userId:readerId,status:"ACTIVE"}}),db.organizationMembership.create({data:{organizationId,userId:ordinaryId,status:"ACTIVE"}})]);await Promise.all([db.membershipRole.create({data:{membershipId:adminMembership.id,roleDefinitionId:adminRole.id}}),db.membershipRole.create({data:{membershipId:readerMembership.id,roleDefinitionId:readerRole.id}})]);
  const definitions=[{code:"00-CHECKLIST",name:"Intake checklist",documentType:"INTAKE_CHECKLIST" as const,renewalPolicy:"NONE" as const},{code:"01-FACE",name:"Face sheet",documentType:"FACE_SHEET" as const,renewalPolicy:"NONE" as const},{code:"02-RIGHTS",name:"Rights acknowledgment",documentType:"RIGHTS_ACKNOWLEDGMENT" as const,renewalPolicy:"ANNUAL" as const},{code:"04-ROI",name:"Release of information",documentType:"ROI" as const,renewalPolicy:"EXPIRATION_DATE_DRIVEN" as const}],created=await Promise.all(definitions.map(row=>db.clientDocumentTemplate.create({data:{organizationId,...row,versionNumber:1,renewalWarningDays:30,contentJson:{signerRoles:["CLIENT","ORGANIZATION_STAFF"]}}})));templates=Object.fromEntries(created.map(row=>[row.documentType,row.id])) as Record<ClientDocumentType,string>;
  readyId=await readyClient("Ready",new Date("2026-01-01"));missingId=await client("Missing");
  outstandingId=await client("Outstanding");await completeNonRights(outstandingId,false);await document(outstandingId,"RIGHTS_ACKNOWLEDGMENT");await db.clientDocumentRequest.create({data:{organizationId,clientId:outstandingId,templateId:templates.FACE_SHEET,documentType:"FACE_SHEET",recipientType:"CLIENT",recipientName:"Outstanding Readiness",deliveryChannel:"MANUAL",status:"OUTSTANDING",activeKey:`${tag}:outstanding`,requestedAt:at,sentAt:at,createdByUserId:adminId}});
  approachingId=await readyClient("Approaching",new Date("2025-10-21"));dueSoonId=await readyClient("DueSoon",new Date("2025-10-06"));dueTodayId=await readyClient("DueToday",new Date("2025-10-01"));overdueId=await readyClient("Overdue",new Date("2025-09-30"));
  renewedId=await client("Renewed");await completeNonRights(renewedId);const source=await document(renewedId,"RIGHTS_ACKNOWLEDGMENT","COMPLETED",new Date("2024-01-01"));await document(renewedId,"RIGHTS_ACKNOWLEDGMENT","COMPLETED",new Date("2026-09-15"),source.id);
  signatureId=await client("Signature");await completeNonRights(signatureId);const unsigned=await document(signatureId,"RIGHTS_ACKNOWLEDGMENT","READY_FOR_SIGNATURE");await db.signatureEnvelope.create({data:{organizationId,clientId:signatureId,documentId:unsigned.id,mode:"SIGN_NOW",provider:"local-test",status:"PARTIALLY_SIGNED"}});
  signedId=await client("Signed");await completeNonRights(signedId);const signed=await document(signedId,"RIGHTS_ACKNOWLEDGMENT");await db.signatureEnvelope.create({data:{organizationId,clientId:signedId,documentId:signed.id,mode:"SIGN_NOW",provider:"local-test",status:"COMPLETED",completedAt:new Date("2026-01-01T12:00:00Z")}});
  fulfilledId=await client("Fulfilled");await completeNonRights(fulfilledId,false);await document(fulfilledId,"RIGHTS_ACKNOWLEDGMENT");const fulfilledDocument=await document(fulfilledId,"FACE_SHEET"),fulfilledRequest=await db.clientDocumentRequest.create({data:{organizationId,clientId:fulfilledId,templateId:templates.FACE_SHEET,documentType:"FACE_SHEET",recipientType:"CLIENT",recipientName:"Fulfilled Readiness",deliveryChannel:"MANUAL",status:"FULFILLED",fulfilledDocumentId:fulfilledDocument.id,fulfilledAt:at,createdByUserId:adminId}});void fulfilledRequest;
 });

 it("derives complete/current, missing, outstanding collection, fulfilled collection, and aggregate counts",async()=>{const[ready,missing,outstanding,fulfilled]=await Promise.all([getClientDocumentationReadiness(admin(),organizationId,readyId,at),getClientDocumentationReadiness(admin(),organizationId,missingId,at),getClientDocumentationReadiness(admin(),organizationId,outstandingId,at),getClientDocumentationReadiness(admin(),organizationId,fulfilledId,at)]);expect(ready.overallState).toBe("CURRENT");expect(ready.counts).toMatchObject({applicable:4,satisfied:4,missing:0,overdue:0});expect(missing.overallState).toBe("MISSING");expect(missing.counts.missing).toBe(4);const requested=outstanding.requirements.find(row=>row.documentType==="FACE_SHEET")!;expect(requested).toMatchObject({state:"OUTSTANDING_COLLECTION",satisfied:false});expect(outstanding.counts).toMatchObject({missing:1,outstandingRequests:1});expect(fulfilled.requirements.find(row=>row.documentType==="FACE_SHEET")).toMatchObject({state:"CURRENT",satisfied:true,outstandingRequests:[]})});
 it("uses authoritative renewal results for approaching, due-soon, due-today, overdue, and completed renewal",async()=>{const rows=await getOrganizationClientDocumentationReadiness(admin(),organizationId,{clientIds:[approachingId,dueSoonId,dueTodayId,overdueId,renewedId],at}),byId=new Map(rows.map(row=>[row.client.id,row]));expect(byId.get(approachingId)?.requirements.find(row=>row.documentType==="RIGHTS_ACKNOWLEDGMENT")).toMatchObject({state:"DUE_SOON",deadlinePhase:"APPROACHING",daysUntilDue:20});expect(byId.get(dueSoonId)?.requirements.find(row=>row.documentType==="RIGHTS_ACKNOWLEDGMENT")).toMatchObject({state:"DUE_SOON",deadlinePhase:"DUE_SOON",daysUntilDue:5});expect(byId.get(dueTodayId)?.requirements.find(row=>row.documentType==="RIGHTS_ACKNOWLEDGMENT")).toMatchObject({state:"DUE_SOON",deadlinePhase:"DUE_TODAY",daysUntilDue:0});expect(byId.get(overdueId)?.requirements.find(row=>row.documentType==="RIGHTS_ACKNOWLEDGMENT")).toMatchObject({state:"OVERDUE",deadlinePhase:"OVERDUE",daysUntilDue:-1});expect(byId.get(renewedId)?.requirements.find(row=>row.documentType==="RIGHTS_ACKNOWLEDGMENT")).toMatchObject({state:"CURRENT"});expect(byId.get(dueTodayId)?.nearestActionableDeadline).toBe("2026-10-01")});
 it("does not let incomplete signatures, historical documents, or pending renewals falsely satisfy a requirement",async()=>{const[unsigned,signed]=await Promise.all([getClientDocumentationReadiness(admin(),organizationId,signatureId,at),getClientDocumentationReadiness(admin(),organizationId,signedId,at)]);expect(unsigned.requirements.find(row=>row.documentType==="RIGHTS_ACKNOWLEDGMENT")).toMatchObject({state:"ATTENTION_NEEDED",satisfied:false,signatureStatus:"PARTIALLY_SIGNED"});expect(signed.requirements.find(row=>row.documentType==="RIGHTS_ACKNOWLEDGMENT")).toMatchObject({state:"CURRENT",satisfied:true,signatureStatus:"COMPLETED"});const source=await db.clientDocument.findFirstOrThrow({where:{clientId:overdueId,documentType:"RIGHTS_ACKNOWLEDGMENT",status:"COMPLETED"}}),draft=await document(overdueId,"RIGHTS_ACKNOWLEDGMENT","READY_FOR_SIGNATURE",new Date(),source.id);const after=await getClientDocumentationReadiness(admin(),organizationId,overdueId,at);expect(after.requirements.find(row=>row.documentType==="RIGHTS_ACKNOWLEDGMENT")).toMatchObject({state:"OVERDUE",documentId:source.id});await db.clientDocument.update({where:{id:draft.id},data:{status:"VOIDED",voidedAt:at}})});
 it("filters and prioritizes deterministically without collapsing requirement identity",async()=>{const overdue=await getOrganizationClientDocumentationReadiness(admin(),organizationId,{filter:"OVERDUE",at}),missing=await getOrganizationClientDocumentationReadiness(admin(),organizationId,{filter:"MISSING",at}),requests=await getOrganizationClientDocumentationReadiness(admin(),organizationId,{filter:"OUTSTANDING_REQUESTS",at}),first=await getOrganizationClientDocumentationReadiness(admin(),organizationId,{at}),second=await getOrganizationClientDocumentationReadiness(admin(),organizationId,{at});expect(overdue.map(row=>row.client.id)).toContain(overdueId);expect(missing.map(row=>row.client.id)).toContain(missingId);expect(requests.map(row=>row.client.id)).toContain(outstandingId);expect(first[0].overallState).toBe("OVERDUE");expect(second.map(row=>[row.client.id,row.overallState,row.requirements.map(item=>item.id)])).toEqual(first.map(row=>[row.client.id,row.overallState,row.requirements.map(item=>item.id)]))});
 it("matches Action Center obligations and provides correct minimum-data deep links",async()=>{const readiness=await getClientDocumentationReadiness(admin(),organizationId,overdueId,at),requirement=readiness.requirements.find(row=>row.documentType==="RIGHTS_ACKNOWLEDGMENT")!,actionCenter=await getActionCenter(admin(),organizationId,{},at);expect(actionCenter.clientDocumentRenewals.map(row=>row.documentId)).toContain(requirement.documentId);expect(requirement.actionHref).toContain(`clientId=${overdueId}`);expect(requirement.actionHref).toContain(`documentId=${requirement.documentId}`);expect(requirement.actionHref).not.toContain("Readiness");expect(JSON.stringify(readiness)).not.toContain("snapshotJson");expect(JSON.stringify(readiness)).not.toContain("renderedPdf")});
 it("enforces authorization, tenant isolation, IDOR resistance, and creates no view audit noise",async()=>{const before=await db.auditEvent.count({where:{organizationId}});expect((await getClientDocumentationReadiness({id:readerId},organizationId,readyId,at)).overallState).toBe("CURRENT");await expect(getClientDocumentationReadiness({id:ordinaryId},organizationId,readyId,at)).rejects.toBeInstanceOf(AuthorizationError);const permission=await db.permission.findUniqueOrThrow({where:{code:"client.read"}}),otherRole=await db.roleDefinition.create({data:{organizationId:otherOrganizationId,code:`OTHER-READINESS-${Date.now()}`,name:"Other readiness reader",scope:"ORGANIZATION",permissions:{create:{permissionId:permission.id}}}}),otherMembership=await db.organizationMembership.create({data:{organizationId:otherOrganizationId,userId:adminId,status:"ACTIVE"}});await db.membershipRole.create({data:{membershipId:otherMembership.id,roleDefinitionId:otherRole.id}});await expect(getClientDocumentationReadiness(admin(),otherOrganizationId,readyId,at)).rejects.toBeInstanceOf(ResourceNotFoundError);await expect(getClientDocumentationReadiness(admin(),organizationId,await client("Foreign",otherOrganizationId),at)).rejects.toBeInstanceOf(ResourceNotFoundError);expect(await db.auditEvent.count({where:{organizationId}})).toBe(before)});
 it("uses fixed-count batched queries rather than per-client document/request queries",async()=>{const documentFindMany=prisma.clientDocument.findMany.bind(prisma.clientDocument),requestFindMany=prisma.clientDocumentRequest.findMany.bind(prisma.clientDocumentRequest),templateFindMany=prisma.clientDocumentTemplate.findMany.bind(prisma.clientDocumentTemplate),documentQuery=vi.spyOn(prisma.clientDocument,"findMany").mockImplementation(documentFindMany),requestQuery=vi.spyOn(prisma.clientDocumentRequest,"findMany").mockImplementation(requestFindMany),templateQuery=vi.spyOn(prisma.clientDocumentTemplate,"findMany").mockImplementation(templateFindMany);try{const rows=await getOrganizationClientDocumentationReadiness(admin(),organizationId,{clientIds:[readyId,missingId,outstandingId,overdueId],at});expect(rows).toHaveLength(4);expect(documentQuery).toHaveBeenCalledTimes(1);expect(requestQuery).toHaveBeenCalledTimes(1);expect(templateQuery).toHaveBeenCalledTimes(1)}finally{documentQuery.mockRestore();requestQuery.mockRestore();templateQuery.mockRestore()}});
});
