import { describe,expect,it } from "vitest";
import { applicabilitySchemaV1, deadlineSchemaV1, ruleDocumentSchemaV1, triggerSchemaV1 } from "@/domain/compliance/schemas/rules";
import { calculateDeadline, calculateLegalDelay, calculateStatus, nextAnnualDue } from "@/domain/compliance/deadlines/calculator";
import { evaluateApplicability, resolveTrigger, type WorkforceContext } from "@/domain/compliance/rules/interpreter";
const ctx:WorkforceContext={employmentStatus:"ACTIVE",employmentType:"VOLUNTEER",licenses:new Set(["MN_245D"]),duties:new Map([["DIRECT_SUPPORT",new Date("2026-09-01T00:00:00Z")]]),roles:new Map(),hireDate:new Date("2026-09-01T00:00:00Z"),events:new Map()};
describe("typed compliance rules",()=>{
  it("calculates 60 calendar days with local-date semantics",()=>expect(calculateDeadline(ctx.hireDate!,{schemaVersion:1,type:"WITHIN_CALENDAR_DAYS",days:60},"America/Chicago")?.toISOString()).toBe("2026-10-31T00:00:00.000Z"));
  it("preserves an exact 72-hour deadline",()=>expect(calculateDeadline(new Date("2026-09-05T15:30:00Z"),{schemaVersion:1,type:"WITHIN_HOURS",hours:72},"America/Chicago")?.toISOString()).toBe("2026-09-08T15:30:00.000Z"));
  it("reports a missing direct-contact trigger without inventing a date",()=>expect(resolveTrigger(triggerSchemaV1.parse({schemaVersion:1,type:"FIRST_DIRECT_CONTACT"}),ctx)).toEqual({resolved:false,reason:"FIRST_DIRECT_CONTACT event is missing"}));
  it("supports direct-support and volunteer applicability",()=>expect(evaluateApplicability({schemaVersion:1,all:[{type:"EMPLOYEE_DUTY",duty:"DIRECT_SUPPORT"},{type:"EMPLOYMENT_TYPE",employmentTypes:["VOLUNTEER"]}]},ctx)).toBe(true));
  it("does not apply duty conditions without the duty",()=>expect(evaluateApplicability({schemaVersion:1,all:[{type:"EMPLOYEE_DUTY",duty:"MEDICATION_ADMINISTRATION"}]},ctx)).toBe(false));
  it("applies the 2026 annual delay without changing nominal due",()=>{const nominal=new Date("2026-09-01T00:00:00Z"),delay=calculateLegalDelay(nominal,{schemaVersion:1,type:"CALENDAR_DAYS_AFTER_NOMINAL_DUE",days:90,effectiveFrom:"2026-08-01",appliesTo:"ANNUAL_ONLY"},new Date("2026-09-20T00:00:00Z"),"America/Chicago",true);expect(delay?.toISOString()).toBe("2026-11-30T00:00:00.000Z");expect(calculateStatus(new Date("2026-09-20T00:00:00Z"),nominal,delay,null)).toBe("WITHIN_LEGAL_DELAY");expect(calculateStatus(new Date("2026-12-01T00:00:00Z"),nominal,delay,null)).toBe("PAST_DUE")});
  it("does not apply the amendment before its effective date or to initial training",()=>{const grace={schemaVersion:1,type:"CALENDAR_DAYS_AFTER_NOMINAL_DUE",days:90,effectiveFrom:"2026-08-01",appliesTo:"ANNUAL_ONLY"};expect(calculateLegalDelay(new Date("2026-07-01T00:00:00Z"),grace,new Date(),"America/Chicago",true)).toBeNull();expect(calculateLegalDelay(new Date("2026-09-01T00:00:00Z"),grace,new Date(),"America/Chicago",false)).toBeNull()});
  it("keeps annual recurrence at one year",()=>expect(nextAnnualDue(new Date("2026-09-01T00:00:00Z"),{schemaVersion:1,type:"ANNUAL"})?.toISOString()).toBe("2027-09-01T00:00:00.000Z"));
  it("rejects malformed and arbitrary rule execution",()=>{expect(()=>applicabilitySchemaV1.parse({schemaVersion:1,all:[{type:"JAVASCRIPT",code:"process.exit()"}]})).toThrow();expect(()=>deadlineSchemaV1.parse({schemaVersion:1,type:"BUSINESS_DAYS",days:2})).toThrow();expect(()=>ruleDocumentSchemaV1.parse({})).toThrow()});
});
