import { beforeAll,describe,expect,it } from "vitest";
import { PrismaClient } from "@prisma/client";
import { evaluateEmployeeCompliance } from "@/domain/compliance/evaluation/service";
import { requireEmployeeAccess } from "@/domain/permissions/authorization";
import { ResourceNotFoundError } from "@/domain/auth/errors";
const db=new PrismaClient();let orgA:{id:string},orgB:{id:string},employee:{id:string},noDuty:{id:string},adminB:{id:string},ruleset:{id:string},hireReq:{id:string;requirementId:string},contactReq:{id:string},baseVersion:number;
beforeAll(async()=>{const tag=`compliance-${Date.now()}`;baseVersion=Math.floor(Date.now()/1000);orgA=await db.organization.create({data:{legalName:"Compliance A",displayName:"Compliance A",slug:`${tag}-a`,licenses:{create:{licenseType:"OTHER",licenseStatus:"ACTIVE",effectiveDate:new Date("2026-01-01")}}}});orgB=await db.organization.create({data:{legalName:"Compliance B",displayName:"Compliance B",slug:`${tag}-b`}});adminB=await db.user.create({data:{email:`${tag}@example.test`,status:"ACTIVE"}});const read=await db.permission.upsert({where:{code:"employee.read"},update:{},create:{code:"employee.read"}}),role=await db.roleDefinition.create({data:{code:`READ-${tag}`,name:"Reader",scope:"PLATFORM",isPlatformStandard:true,permissions:{create:{permissionId:read.id}}}});await db.organizationMembership.create({data:{organizationId:orgB.id,userId:adminB.id,status:"ACTIVE",roles:{create:{roleDefinitionId:role.id}}}});const duty=await db.dutyDefinition.upsert({where:{code:"DIRECT_SUPPORT"},update:{},create:{code:"DIRECT_SUPPORT",name:"Direct support"}});employee=await db.employee.create({data:{organizationId:orgA.id,firstName:"Engine",lastName:"Test",hireDate:new Date("2026-09-01"),employmentStatus:"ACTIVE",duties:{create:{dutyDefinitionId:duty.id,effectiveFrom:new Date("2026-09-01")}}}});noDuty=await db.employee.create({data:{organizationId:orgA.id,firstName:"No",lastName:"Duty",hireDate:new Date("2026-09-01"),employmentStatus:"ACTIVE"}});
  const make=async(code:string,name:string,trigger:object,deadline:object)=>{const r=await db.complianceRequirement.create({data:{code:`${tag}-${code}`,name,licenseType:"OTHER",requirementCategory:"WORKFORCE"}});return db.complianceRequirementVersion.create({data:{requirementId:r.id,versionNumber:1,effectiveFrom:new Date("2026-01-01"),verificationStatus:"PRIMARY_SOURCE_VERIFIED",status:"ACTIVE",applicabilityDefinition:{schemaVersion:1,all:[{type:"ORGANIZATION_LICENSE",licenseType:"OTHER"},{type:"EMPLOYEE_DUTY",duty:"DIRECT_SUPPORT"}]},triggerDefinition:trigger,deadlineDefinition:deadline,recurrenceDefinition:{schemaVersion:1,type:"NONE"}}})};hireReq=await make("HIRE","Hire",{schemaVersion:1,type:"EMPLOYEE_HIRED"},{schemaVersion:1,type:"WITHIN_CALENDAR_DAYS",days:60});contactReq=await make("CONTACT","Contact",{schemaVersion:1,type:"FIRST_DIRECT_CONTACT"},{schemaVersion:1,type:"WITHIN_HOURS",hours:72});ruleset=await db.complianceRuleset.create({data:{licenseType:"OTHER",version:baseVersion,effectiveFrom:new Date("2026-01-01"),status:"ACTIVE",requirements:{create:[{requirementVersionId:hireReq.id},{requirementVersionId:contactReq.id}]}}});});
describe("compliance evaluation engine",()=>{
  it("uses tenant workforce data, records ruleset version, and leaves missing triggers unresolved",async()=>{const result=await evaluateEmployeeCompliance(orgA.id,employee.id,"MANUAL",new Date("2026-09-20"));expect(result.run?.rulesetVersionSnapshot).toBe(baseVersion);expect(result.instances).toHaveLength(1);expect(result.instances[0].nominalDueAt?.toISOString()).toBe("2026-10-31T00:00:00.000Z");expect(result.unresolved).toHaveLength(1)});
  it("does not generate duty-scoped instances for employees without the duty",async()=>expect((await evaluateEmployeeCompliance(orgA.id,noDuty.id,"MANUAL",new Date("2026-09-20"))).instances).toHaveLength(0));
  it("is idempotent",async()=>{await evaluateEmployeeCompliance(orgA.id,employee.id,"MANUAL",new Date("2026-09-20"));await evaluateEmployeeCompliance(orgA.id,employee.id,"MANUAL",new Date("2026-09-20"));expect(await db.complianceInstance.count({where:{employeeId:employee.id,requirementVersionId:hireReq.id}})).toBe(1)});
  it("uses exact service-event timestamps",async()=>{await db.employeeServiceEvent.create({data:{organizationId:orgA.id,employeeId:employee.id,eventType:"FIRST_DIRECT_CONTACT",occurredAt:new Date("2026-09-05T15:30:00Z")}});const result=await evaluateEmployeeCompliance(orgA.id,employee.id,"SERVICE_EVENT_CREATED",new Date("2026-09-06"));expect(result.instances.find(i=>i.requirementVersionId===contactReq.id)?.nominalDueAt?.toISOString()).toBe("2026-09-08T15:30:00.000Z")});
  it("preserves and supersedes old instances after a rule version change",async()=>{await db.complianceRequirementVersion.update({where:{id:hireReq.id},data:{status:"SUPERSEDED",effectiveUntil:new Date("2026-09-30")}});const replacement=await db.complianceRequirementVersion.create({data:{requirementId:hireReq.requirementId,versionNumber:2,effectiveFrom:new Date("2026-10-01"),verificationStatus:"PRIMARY_SOURCE_VERIFIED",status:"ACTIVE",applicabilityDefinition:{schemaVersion:1,all:[{type:"ORGANIZATION_LICENSE",licenseType:"OTHER"},{type:"EMPLOYEE_DUTY",duty:"DIRECT_SUPPORT"}]},triggerDefinition:{schemaVersion:1,type:"EMPLOYEE_HIRED"},deadlineDefinition:{schemaVersion:1,type:"WITHIN_CALENDAR_DAYS",days:30}}});await db.complianceRuleset.update({where:{id:ruleset.id},data:{status:"SUPERSEDED",effectiveUntil:new Date("2026-09-30")}});await db.complianceRuleset.create({data:{licenseType:"OTHER",version:baseVersion+1,effectiveFrom:new Date("2026-10-01"),status:"ACTIVE",requirements:{create:{requirementVersionId:replacement.id}}}});await evaluateEmployeeCompliance(orgA.id,employee.id,"RULESET_CHANGED",new Date("2026-10-05"));expect((await db.complianceInstance.findFirstOrThrow({where:{employeeId:employee.id,requirementVersionId:hireReq.id}})).status).toBe("SUPERSEDED");expect(await db.complianceInstance.count({where:{employeeId:employee.id,requirementVersionId:replacement.id}})).toBe(1)});
  it("denies cross-tenant compliance resource access",async()=>await expect(requireEmployeeAccess(adminB,orgB.id,employee.id)).rejects.toBeInstanceOf(ResourceNotFoundError));
});
