import { describe, expect, it } from "vitest";
import { writeFile } from "node:fs/promises";
import { PDFDocument, PDFName, PDFString, StandardFonts } from "pdf-lib";
import { analyzeClientImportPdf } from "@/domain/clients/imports";

async function textPdf(pages:string[]){const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica);for(const text of pages){const page=pdf.addPage([612,792]);page.drawText(text,{x:42,y:720,size:14,font,maxWidth:530})}return Buffer.from(await pdf.save())}

describe("client import PDF extraction",()=>{
  it("extracts the required exact client values with page provenance from native text",async()=>{const result=await analyzeClientImportPdf(await textPdf(["Admission Form Legal first name: Jane Legal last name: Example Date of birth: 01/15/1990","Address: 123 Example Street Phone: 555-0100 Case manager: Alex Sample"])),values=new Map(result.extracted.map(item=>[item.fieldPath,item]));expect(result.pageCount).toBe(2);expect(values.get("client.legalFirstName")).toMatchObject({value:"Jane",sourceLocation:"Page 1 labeled text",method:"NATIVE_TEXT"});expect(values.get("client.legalLastName")?.value).toBe("Example");expect(values.get("client.dateOfBirth")?.value).toBe("01/15/1990");expect(values.get("client.addressLine1")).toMatchObject({value:"123 Example Street",sourceLocation:"Page 2 labeled text"});expect(values.get("client.phone")?.value).toBe("555-0100");expect(values.get("caseManager.name")?.value).toBe("Alex Sample");expect(result.classification).toBe("ADMISSION_FORM");expect(result.extractionStatus).toBe("TEXT_EXTRACTED");expect(result.diagnostics.version).toBe(3)});

  it("extracts the required exact client values from common AcroForm fields",async()=>{const pdf=await PDFDocument.create(),page=pdf.addPage([612,792]),form=pdf.getForm(),font=await pdf.embedFont(StandardFonts.Helvetica),fields={legal_first_name:"Jane",legal_last_name:"Example",date_of_birth:"01/15/1990",address:"123 Example Street",phone:"555-0100",case_manager_name:"Alex Sample",service_authorization_number:"AUTH-100"};let y=700;for(const[name,value]of Object.entries(fields)){const field=form.createTextField(name);field.setText(value);field.addToPage(page,{x:40,y,width:220,height:20});y-=35}form.updateFieldAppearances(font);const result=await analyzeClientImportPdf(Buffer.from(await pdf.save())),values=new Map(result.extracted.map(item=>[item.fieldPath,item]));expect(values.get("client.legalFirstName")).toMatchObject({value:"Jane",method:"PDF_FORM_FIELD",sourceLocation:"Page 1 · PDF form field legal_first_name"});expect(values.get("client.legalLastName")?.value).toBe("Example");expect(values.get("client.dateOfBirth")?.value).toBe("01/15/1990");expect(values.get("client.addressLine1")?.value).toBe("123 Example Street");expect(values.get("client.phone")?.value).toBe("555-0100");expect(values.get("caseManager.name")?.value).toBe("Alex Sample");expect(values.get("services.0.authorizationIdentifier")?.value).toBe("AUTH-100");expect(result.extractionStatus).toBe("FORM_FIELDS_EXTRACTED")});

  it("truthfully separates readable text with no mapped fields from OCR-required image content",async()=>{const readable=await analyzeClientImportPdf(await textPdf(["Synthetic correspondence without a supported client field label"]));expect(readable.extractionStatus).toBe("TEXT_EXTRACTED");expect(readable.extracted).toEqual([]);const mixed=await PDFDocument.create(),font=await mixed.embedFont(StandardFonts.Helvetica),page=mixed.addPage();page.drawText("Legal first name: Mixed Last name: Example",{x:40,y:700,font,size:14});const imagePage=mixed.addPage(),pixel=await mixed.embedPng(Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64"));imagePage.drawImage(pixel,{x:0,y:0,width:500,height:700});const analyzed=await analyzeClientImportPdf(Buffer.from(await mixed.save()));expect(analyzed.extracted).toContainEqual(expect.objectContaining({fieldPath:"client.legalFirstName",value:"Mixed",sourceLocation:"Page 1 labeled text"}));expect(["OCR_REQUIRED","OCR_COMPLETED"]).toContain(analyzed.extractionStatus);expect(analyzed.pagesRequiringOcr).toEqual([2])});

  it("records PHI-free partial OCR diagnostics without claiming completion",async()=>{const pdf=await PDFDocument.create(),page=pdf.addPage(),pixel=await pdf.embedPng(Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64"));page.drawImage(pixel,{x:0,y:0,width:500,height:700});const result=await analyzeClientImportPdf(Buffer.from(await pdf.save()),{ocrExecutor:async()=>({available:true,pages:new Map(),failed:[1],skipped:[],durationMs:123,engine:{ocr:"synthetic",renderer:"synthetic"},pageResults:[{pageNumber:1,status:"FAILED",stage:"RENDER",durationMs:123,failureCategory:"RENDER_TIMEOUT",retryEligible:true,renderDpi:120}],failureCategory:"RENDER_TIMEOUT",retryEligible:true})});expect(result.extractionStatus).toBe("OCR_REQUIRED");expect(result.diagnostics).toMatchObject({ocrAttempted:true,ocrCompleted:false,processedPageCount:0,failedPageCount:1,skippedPageCount:0,failureCategory:"RENDER_TIMEOUT",retryEligible:true,mappedProposalCount:0});expect(JSON.stringify(result.diagnostics)).not.toContain("Synthetic Person");expect(JSON.stringify(result.diagnostics)).not.toContain("01/02/1990")});

  it("preserves partial OCR text and page provenance when another page fails",async()=>{const pdf=await PDFDocument.create();pdf.addPage();pdf.addPage();const result=await analyzeClientImportPdf(Buffer.from(await pdf.save()),{ocrExecutor:async()=>({available:true,pages:new Map([[1,"Person served name: Synthetic Person DOB: 01/02/1990"]]),failed:[2],skipped:[],durationMs:321,engine:{ocr:"synthetic",renderer:"synthetic"},pageResults:[{pageNumber:1,status:"PROCESSED",stage:"COMPLETE",durationMs:100,retryEligible:false,renderDpi:180,textDetected:true},{pageNumber:2,status:"FAILED",stage:"OCR",durationMs:221,failureCategory:"OCR_TIMEOUT",retryEligible:true,renderDpi:180}],failureCategory:"OCR_TIMEOUT",retryEligible:true})});expect(result.extractionStatus).toBe("OCR_REQUIRED");expect(result.textPages[0]).toMatchObject({pageNumber:1,method:"LOCAL_OCR"});expect(result.extracted).toContainEqual(expect.objectContaining({fieldPath:"identity.fullName",value:"Synthetic Person",sourceLocation:"Page 1 OCR text"}));expect(result.diagnostics).toMatchObject({processedPageCount:1,failedPageCount:1,failureCategory:"OCR_TIMEOUT"})});

  it("retries a failed bounded render once at lower resolution",async()=>{const pdf=await PDFDocument.create();pdf.addPage();let renderCalls=0;const result=await analyzeClientImportPdf(Buffer.from(await pdf.save()),{ocrEngine:{available:true,ocr:"synthetic",renderer:"synthetic"},processRunner:async(command,args)=>{if(command==="pdftoppm"){renderCalls++;expect(args).toContain("-scale-to");if(renderCalls===1)throw new Error("synthetic render failure");await writeFile(`${args.at(-1)}.jpg`,Buffer.from("synthetic image"));return""}return"Legal first name: Retry Legal last name: Success"}});expect(renderCalls).toBe(2);expect(result.extractionStatus).toBe("OCR_COMPLETED");expect(result.diagnostics.pageResults).toEqual([expect.objectContaining({status:"PROCESSED",renderDpi:100})]);expect(result.extracted).toContainEqual(expect.objectContaining({fieldPath:"client.legalFirstName",value:"Retry",method:"LOCAL_OCR"}))});

  it("maps exact values from scanned OCR and mixed native/scanned pages",async()=>{const scan=await PDFDocument.create();scan.addPage();const scanned=await analyzeClientImportPdf(Buffer.from(await scan.save()),{ocrExecutor:async()=>({available:true,pages:new Map([[1,"Legal first name: Jane Legal last name: Example Date of birth: 01/15/1990 Address: 123 Example Street Phone: 555-0100 Case manager: Alex Sample"]]),failed:[],skipped:[],durationMs:10,engine:{ocr:"synthetic",renderer:"synthetic"},pageResults:[{pageNumber:1,status:"PROCESSED",stage:"COMPLETE",durationMs:10,retryEligible:false,renderDpi:140,textDetected:true}],failureCategory:null,retryEligible:false})});for(const[path,value]of [["client.legalFirstName","Jane"],["client.legalLastName","Example"],["client.addressLine1","123 Example Street"],["client.phone","555-0100"],["caseManager.name","Alex Sample"]])expect(scanned.extracted).toContainEqual(expect.objectContaining({fieldPath:path,value,method:"LOCAL_OCR"}));const mixed=await PDFDocument.create(),font=await mixed.embedFont(StandardFonts.Helvetica);mixed.addPage().drawText("Legal first name: Jane Legal last name: Example",{x:40,y:700,font,size:14});mixed.addPage();const analyzed=await analyzeClientImportPdf(Buffer.from(await mixed.save()),{ocrExecutor:async()=>({available:true,pages:new Map([[2,"Date of birth: 01/15/1990 Address: 123 Example Street Phone: 555-0100 Case manager: Alex Sample"]]),failed:[],skipped:[],durationMs:10,engine:{ocr:"synthetic",renderer:"synthetic"},pageResults:[{pageNumber:2,status:"PROCESSED",stage:"COMPLETE",durationMs:10,retryEligible:false,renderDpi:140,textDetected:true}],failureCategory:null,retryEligible:false})});expect(analyzed.extracted).toEqual(expect.arrayContaining([expect.objectContaining({fieldPath:"client.legalFirstName",value:"Jane",method:"NATIVE_TEXT"}),expect.objectContaining({fieldPath:"client.dateOfBirth",value:"01/15/1990",method:"LOCAL_OCR"})]))});

  it("distinguishes harmless text and supported forms from executable PDF structures",async()=>{const harmless=await textPdf(["A printed reference to /JavaScript and /EmbeddedFile is inert page text"]);await expect(analyzeClientImportPdf(harmless)).resolves.toMatchObject({extractionStatus:"TEXT_EXTRACTED"});const active=await PDFDocument.create();active.addPage();active.catalog.set(PDFName.of("OpenAction"),active.context.obj({S:PDFName.of("JavaScript"),JS:PDFString.of("app.alert('synthetic')")}));await expect(analyzeClientImportPdf(Buffer.from(await active.save()))).rejects.toThrow(/JavaScript|automatic open action/);const attached=await PDFDocument.create();attached.addPage();await attached.attach(Buffer.from("synthetic"),"synthetic.txt",{mimeType:"text/plain"});await expect(analyzeClientImportPdf(Buffer.from(await attached.save()))).rejects.toThrow(/embedded file attachments/)});

  it("recognizes common person-served and service-coordinator labels conservatively",async()=>{const result=await analyzeClientImportPdf(await textPdf(["Person served name: Synthetic Person DOB: 01/02/1990 Service coordinator: Casey Coordinator County: Synthetic County Phone: 555-0101"]));expect(result.extracted).toContainEqual(expect.objectContaining({fieldPath:"identity.fullName",value:"Synthetic Person",sourceLocation:"Page 1 labeled text"}));expect(result.extracted).toContainEqual(expect.objectContaining({fieldPath:"caseManager.name",value:"Casey Coordinator",sourceLocation:"Page 1 labeled text"}))});
});

describe("document classification by title", () => {
  it("prefers the document title over later mentions of other form names", async () => {
    const { classifyDocumentText } = await import("@/domain/clients/document-registry");
    expect(classifyDocumentText("Self-Management Assessment Name of person served: Jordan Example. See also the CSSP Addendum.").classification).toBe("SMA");
  });
});

describe("document classification tie-break", () => {
  it("prefers the longer alias when two start at the same place", async () => {
    const { classifyDocumentText } = await import("@/domain/clients/document-registry");
    expect(classifyDocumentText("CSSP Addendum for Basic Support Services Name of person served: Jordan Example").classification).toBe("CSSP_ADDENDUM");
  });
});
