import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const source=(path:string)=>readFileSync(join(process.cwd(),path),"utf8");
describe("client documents workspace",()=>{
  it("provides accessible in-place document selection and authoritative same-origin previews",()=>{const portal=source("src/app/admin/clients/clients-portal.tsx"),viewer=source("src/app/admin/clients/document-pdf-viewer.tsx"),route=source("src/app/api/organizations/[organizationId]/clients/[clientId]/documents/route.ts"),config=source("next.config.ts");expect(portal).toContain('className="documents-split"');expect(portal).toContain('role="listbox"');expect(portal).toContain('aria-selected={active}');expect(portal).toContain('setSelectedDocumentId(document.id)');expect(portal).toContain('DocumentPdfViewer');expect(viewer).toContain('className="authoritative-document-preview"');expect(viewer).toContain('PDF preview unavailable');expect(viewer).toContain('Retry');expect(portal).toContain('&disposition=inline');expect(route).toContain('z.enum(["inline","attachment"])');expect(config).toContain('/api/organizations/:organizationId/clients/:clientId/documents');expect(config).toContain('frame-ancestors \'self\'')});
  it("chooses final, progressive current, or source renditions without presenting an unsigned source as signed",()=>{const portal=source("src/app/admin/clients/clients-portal.tsx");expect(portal).toContain('selectedDocument.envelope.status==="COMPLETED"&&!selectedDocument.signatureIntegrityIssue?"final":"current"');expect(portal).toContain('selectedDocument.status==="COMPLETED"?"final":"source"');expect(portal).toContain("No accepted signature is hidden by an unsigned source preview.")});
  it("keeps requests, generation, persistent imports, renewals, and signing controls contextual",()=>{const portal=source("src/app/admin/clients/clients-portal.tsx");for(const text of ["Request document","Generate document","Import documents","outstanding document request(s)","Renewal details","Sign now","Send for signature","Reissue","Revoke","Download signature evidence"])expect(portal).toContain(text);expect(portal).toContain("if(result.id)setSelectedDocumentId(result.id)");expect(portal).toContain('className="persistent-client-import"')});
  it("keeps the header import persistent and removes redundant actions from the ordinary Documents toolbar",()=>{const portal=source("src/app/admin/clients/clients-portal.tsx"),header=portal.slice(portal.indexOf('className="record-actions"'),portal.indexOf('className="admin-nav record-tabs"')),documents=portal.slice(portal.indexOf('{tab === "Documents"'),portal.indexOf('className="documents-split"'));expect(header).toContain("Import documents");expect(header).toContain("setClientImportOpen");expect(header).not.toContain("Generate document");expect(documents).toContain("Generate document");expect(documents).toContain("Request document");expect(documents).not.toContain("Import PDF")});
  it("uses accessible dismissible popovers and protects the document lifecycle",()=>{const portal=source("src/app/admin/clients/clients-portal.tsx"),popover=source("src/app/admin/clients/action-popover.tsx");for(const text of ["Edit document","Delete draft","Ready for signature","Save as new draft version","DELETE_DRAFT","REVISE_DRAFT"])expect(portal).toContain(text);expect(popover).toContain('event.key==="Escape"');expect(popover).toContain('event.key!=="Tab"');expect(popover).toContain('document.addEventListener("pointerdown"');expect(popover).toContain('trigger.current?.focus()');expect(popover).toContain('role="dialog"')});
  it("matches the approved compact Generate and Request popover structures",()=>{const portal=source("src/app/admin/clients/clients-portal.tsx"),css=source("src/app/globals.css");for(const text of ["Choose a template","Generating creates a new draft. Earlier versions stay in History.","Request a document","Send a link so someone can complete or sign it.","Send to","Due date","request-menu-callout"])expect(portal).toContain(text);expect(css).toContain(".generation-menu{width:294px");expect(css).toContain(".request-menu{width:330px");expect(css).toContain("grid-template-columns:1.15fr 1fr");expect(css).toContain("border-radius:9px");expect(portal).not.toContain('value="SMS"')});
  it("adapts the 30/70 workspace for tablet and mobile",()=>{const css=source("src/app/globals.css");expect(css).toContain("grid-template-columns:minmax(260px,30%) minmax(0,70%)");expect(css).toContain(".documents-split{display:flex;flex-direction:column");expect(css).toContain(".document-select-card.selected")});
});
