import { describe, expect, it } from "vitest";
import { writeFile } from "node:fs/promises";
import { PDFDocument, PDFName, PDFString, StandardFonts } from "pdf-lib";
import { analyzeClientImportPdf } from "@/domain/clients/imports";

async function textPdf(pages:string[]){const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica);for(const text of pages){const page=pdf.addPage([612,792]);page.drawText(text,{x:42,y:720,size:14,font,maxWidth:530})}return Buffer.from(await pdf.save())}

describe("client import PDF extraction",()=>{
  it("extracts exact mapped values with page provenance across selectable-text pages",async()=>{const result=await analyzeClientImportPdf(await textPdf(["Admission Form Legal first name: Pageone Last name: Person Date of birth: 04/03/1990","Street address: 123 Test Avenue City: Saint Paul State: MN ZIP: 55101 Case manager: Casey Manager Agency: Synthetic County"])),values=new Map(result.extracted.map(item=>[item.fieldPath,item]));expect(result.pageCount).toBe(2);expect(values.get("client.legalFirstName")).toMatchObject({value:"Pageone",sourceLocation:"Page 1 labeled text",method:"NATIVE_TEXT"});expect(values.get("client.legalLastName")?.value).toBe("Person");expect(values.get("client.dateOfBirth")?.value).toBe("04/03/1990");expect(values.get("client.addressLine1")).toMatchObject({value:"123 Test Avenue",sourceLocation:"Page 2 labeled text"});expect(values.get("client.city")?.value).toBe("Saint Paul");expect(values.get("client.state")?.value).toBe("MN");expect(values.get("client.postalCode")?.value).toBe("55101");expect(values.get("caseManager.name")?.value).toBe("Casey Manager");expect(result.classification).toBe("ADMISSION_FORM");expect(result.extractionStatus).toBe("TEXT_EXTRACTED")});

  it("extracts populated text, checkbox, radio, and select AcroForm values without duplicate text proposals",async()=>{const pdf=await PDFDocument.create(),page=pdf.addPage([612,792]),form=pdf.getForm(),font=await pdf.embedFont(StandardFonts.Helvetica);const first=form.createTextField("first_name");first.setText("Interactive");first.addToPage(page,{x:40,y:700,width:180,height:20});const dob=form.createTextField("DOB");dob.setText("05/06/1991");dob.addToPage(page,{x:40,y:660,width:180,height:20});const checkbox=form.createCheckBox("ROI_012_info_type_Face_sheet_contact_information");checkbox.addToPage(page,{x:40,y:620,width:15,height:15});checkbox.check();const radio=form.createRadioGroup("contact_method");radio.addOptionToPage("Email",page,{x:40,y:580,width:15,height:15});radio.addOptionToPage("Phone",page,{x:80,y:580,width:15,height:15});radio.select("Email");const select=form.createDropdown("preferred_language");select.addOptions(["English","Somali"]);select.select("Somali");select.addToPage(page,{x:40,y:540,width:180,height:20});form.updateFieldAppearances(font);const result=await analyzeClientImportPdf(Buffer.from(await pdf.save())),values=result.extracted.filter(item=>item.fieldPath==="client.legalFirstName");expect(values).toHaveLength(1);expect(values[0]).toMatchObject({value:"Interactive",method:"PDF_FORM_FIELD",sourceLocation:"Page 1 · PDF form field first_name"});expect(result.extracted).toContainEqual(expect.objectContaining({fieldPath:"client.dateOfBirth",value:"05/06/1991",sourceLocation:"Page 1 · PDF form field DOB"}));expect(result.extracted).toContainEqual(expect.objectContaining({fieldPath:"roi.categories.FACE_SHEET_CONTACT",value:true,sourceLocation:"Page 1 · PDF form field ROI_012_info_type_Face_sheet_contact_information"}));expect(result.rawFields).toMatchObject({contact_method:"Email",preferred_language:"Somali"});expect(result.extractionStatus).toBe("FORM_FIELDS_EXTRACTED")});

  it("truthfully separates readable text with no mapped fields from OCR-required image content",async()=>{const readable=await analyzeClientImportPdf(await textPdf(["Synthetic correspondence without a supported client field label"]));expect(readable.extractionStatus).toBe("TEXT_EXTRACTED");expect(readable.extracted).toEqual([]);const mixed=await PDFDocument.create(),font=await mixed.embedFont(StandardFonts.Helvetica),page=mixed.addPage();page.drawText("Legal first name: Mixed Last name: Example",{x:40,y:700,font,size:14});const imagePage=mixed.addPage(),pixel=await mixed.embedPng(Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64"));imagePage.drawImage(pixel,{x:0,y:0,width:500,height:700});const analyzed=await analyzeClientImportPdf(Buffer.from(await mixed.save()));expect(analyzed.extracted).toContainEqual(expect.objectContaining({fieldPath:"client.legalFirstName",value:"Mixed",sourceLocation:"Page 1 labeled text"}));expect(["OCR_REQUIRED","OCR_COMPLETED"]).toContain(analyzed.extractionStatus);expect(analyzed.pagesRequiringOcr).toEqual([2])});

  it("records PHI-free partial OCR diagnostics without claiming completion",async()=>{const pdf=await PDFDocument.create(),page=pdf.addPage(),pixel=await pdf.embedPng(Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64"));page.drawImage(pixel,{x:0,y:0,width:500,height:700});const result=await analyzeClientImportPdf(Buffer.from(await pdf.save()),{ocrExecutor:async()=>({available:true,pages:new Map(),failed:[1],skipped:[],durationMs:123,engine:{ocr:"synthetic",renderer:"synthetic"},pageResults:[{pageNumber:1,status:"FAILED",stage:"RENDER",durationMs:123,failureCategory:"RENDER_TIMEOUT",retryEligible:true,renderDpi:120}],failureCategory:"RENDER_TIMEOUT",retryEligible:true})});expect(result.extractionStatus).toBe("OCR_REQUIRED");expect(result.diagnostics).toMatchObject({ocrAttempted:true,ocrCompleted:false,processedPageCount:0,failedPageCount:1,skippedPageCount:0,failureCategory:"RENDER_TIMEOUT",retryEligible:true,mappedProposalCount:0});expect(JSON.stringify(result.diagnostics)).not.toContain("Synthetic Person");expect(JSON.stringify(result.diagnostics)).not.toContain("01/02/1990")});

  it("preserves partial OCR text and page provenance when another page fails",async()=>{const pdf=await PDFDocument.create();pdf.addPage();pdf.addPage();const result=await analyzeClientImportPdf(Buffer.from(await pdf.save()),{ocrExecutor:async()=>({available:true,pages:new Map([[1,"Person served name: Synthetic Person DOB: 01/02/1990"]]),failed:[2],skipped:[],durationMs:321,engine:{ocr:"synthetic",renderer:"synthetic"},pageResults:[{pageNumber:1,status:"PROCESSED",stage:"COMPLETE",durationMs:100,retryEligible:false,renderDpi:180,textDetected:true},{pageNumber:2,status:"FAILED",stage:"OCR",durationMs:221,failureCategory:"OCR_TIMEOUT",retryEligible:true,renderDpi:180}],failureCategory:"OCR_TIMEOUT",retryEligible:true})});expect(result.extractionStatus).toBe("OCR_REQUIRED");expect(result.textPages[0]).toMatchObject({pageNumber:1,method:"LOCAL_OCR"});expect(result.extracted).toContainEqual(expect.objectContaining({fieldPath:"identity.fullName",value:"Synthetic Person",sourceLocation:"Page 1 OCR text"}));expect(result.diagnostics).toMatchObject({processedPageCount:1,failedPageCount:1,failureCategory:"OCR_TIMEOUT"})});

  it("retries a failed high-resolution render once at lower resolution",async()=>{const pdf=await PDFDocument.create();pdf.addPage();let renderCalls=0;const result=await analyzeClientImportPdf(Buffer.from(await pdf.save()),{ocrEngine:{available:true,ocr:"synthetic",renderer:"synthetic"},processRunner:async(command,args)=>{if(command==="pdftoppm"){renderCalls++;if(renderCalls===1)throw new Error("synthetic render failure");await writeFile(`${args.at(-1)}.jpg`,Buffer.from("synthetic image"));return""}return"Legal first name: Retry Last name: Success"}});expect(renderCalls).toBe(2);expect(result.extractionStatus).toBe("OCR_COMPLETED");expect(result.diagnostics.pageResults).toEqual([expect.objectContaining({status:"PROCESSED",renderDpi:110})]);expect(result.extracted).toContainEqual(expect.objectContaining({fieldPath:"client.legalFirstName",value:"Retry",method:"LOCAL_OCR"}))});

  it("distinguishes harmless text and supported forms from executable PDF structures",async()=>{const harmless=await textPdf(["A printed reference to /JavaScript and /EmbeddedFile is inert page text"]);await expect(analyzeClientImportPdf(harmless)).resolves.toMatchObject({extractionStatus:"TEXT_EXTRACTED"});const active=await PDFDocument.create();active.addPage();active.catalog.set(PDFName.of("OpenAction"),active.context.obj({S:PDFName.of("JavaScript"),JS:PDFString.of("app.alert('synthetic')")}));await expect(analyzeClientImportPdf(Buffer.from(await active.save()))).rejects.toThrow(/JavaScript|automatic open action/);const attached=await PDFDocument.create();attached.addPage();await attached.attach(Buffer.from("synthetic"),"synthetic.txt",{mimeType:"text/plain"});await expect(analyzeClientImportPdf(Buffer.from(await attached.save()))).rejects.toThrow(/embedded file attachments/)});

  it("recognizes common person-served and service-coordinator labels conservatively",async()=>{const result=await analyzeClientImportPdf(await textPdf(["Person served name: Synthetic Person DOB: 01/02/1990 Service coordinator: Casey Coordinator County: Synthetic County Phone: 555-0101"]));expect(result.extracted).toContainEqual(expect.objectContaining({fieldPath:"identity.fullName",value:"Synthetic Person",sourceLocation:"Page 1 labeled text"}));expect(result.extracted).toContainEqual(expect.objectContaining({fieldPath:"caseManager.name",value:"Casey Coordinator",sourceLocation:"Page 1 labeled text"}))});
});
