import { beforeAll, describe, expect, it } from "vitest";
import { PrismaClient } from "@prisma/client";
import { acknowledgePolicy } from "@/domain/policies/service";
import { claimEmployeePortalInvitation, getEmployeePortal, inviteEmployeeToPortal } from "@/domain/portal/service";
import { completeManualOnboardingStep } from "@/domain/onboarding/service";
import { requireEmployeeSelfAccess } from "@/domain/permissions/authorization";
import { startAttempt, submitAttempt } from "@/domain/training/assessments/service";
import { completeContent } from "@/domain/training/progress/service";
import { EmailDeliveryError, persistEmailAttempt, PurposeRoutedEmailProvider, type EmailProvider } from "@/domain/notifications/email";

const db = new PrismaClient();

describe.sequential("Phase 13 employee portal and self-service", () => {
  let organizationId:string,otherOrganizationId:string,ownerId:string,viewerId:string,employeeUserId:string,otherUserId:string,employeeId:string,otherEmployeeId:string,assignmentId:string,contentId:string,assessmentId:string,criticalQuestionId:string,criticalCorrectId:string,normalQuestionId:string,normalCorrectId:string,policyAssignmentId:string,manualStepId:string;
  beforeAll(async()=>{
    const tag=`phase13-${Date.now()}`,owner=await db.user.findUniqueOrThrow({where:{email:"alex.owner@example.test"}}),viewer=await db.user.findUniqueOrThrow({where:{email:"jordan.viewer@example.test"}}),ownerRole=await db.roleDefinition.findFirstOrThrow({where:{organizationId:null,code:"ORGANIZATION_OWNER"}}),auditorRole=await db.roleDefinition.findFirstOrThrow({where:{organizationId:null,code:"AUDITOR"}});ownerId=owner.id;viewerId=viewer.id;
    const org=await db.organization.create({data:{legalName:tag,displayName:tag,slug:tag}});organizationId=org.id;otherOrganizationId=(await db.organization.findFirstOrThrow({where:{slug:"lakeside-community-services"}})).id;
    const membership=await db.organizationMembership.create({data:{organizationId,userId:owner.id,status:"ACTIVE"}});await db.membershipRole.create({data:{membershipId:membership.id,roleDefinitionId:ownerRole.id}});const viewerMembership=await db.organizationMembership.create({data:{organizationId,userId:viewer.id,status:"ACTIVE"}});await db.membershipRole.create({data:{membershipId:viewerMembership.id,roleDefinitionId:auditorRole.id}});
    const employeeUser=await db.user.create({data:{email:`employee-${tag}@example.test`,status:"ACTIVE"}}),otherUser=await db.user.create({data:{email:`other-${tag}@example.test`,status:"ACTIVE"}});employeeUserId=employeeUser.id;otherUserId=otherUser.id;
    const employee=await db.employee.create({data:{organizationId,email:employeeUser.email,firstName:"Portal",lastName:"Employee",employmentStatus:"ACTIVE",hireDate:new Date("2026-01-01"),employmentType:"FULL_TIME"}}),other=await db.employee.create({data:{organizationId,userId:otherUser.id,email:otherUser.email,firstName:"Other",lastName:"Employee",employmentStatus:"ACTIVE"}});employeeId=employee.id;otherEmployeeId=other.id;
    await db.organizationMembership.create({data:{organizationId,userId:otherUser.id,status:"ACTIVE"}});
    const course=await db.trainingCourse.create({data:{organizationId,catalogKey:`${tag}:course`,code:"PORTAL",title:"Portal safety course",category:"SAFETY",ownershipType:"ORGANIZATION",versions:{create:{versionNumber:1,status:"PUBLISHED",effectiveFrom:new Date("2026-01-01"),publishedAt:new Date(),contentHash:"portal-v1",modules:{create:{sequence:1,title:"Written safety lesson",moduleType:"MIXED",contentItems:{create:{sequence:1,contentType:"WRITTEN",payload:{heading:"Safety",body:"Meaningful written training."},required:true}},assessments:{create:{versionNumber:1,title:"Safety assessment",passingScore:50,maxAttempts:3,status:"PUBLISHED",questions:{create:[{sequence:1,questionType:"TRUE_FALSE",prompt:"Critical safety answer",points:1,critical:true,options:{create:[{sequence:1,text:"Correct",isCorrect:true},{sequence:2,text:"Incorrect",isCorrect:false}]}},{sequence:2,questionType:"TRUE_FALSE",prompt:"General answer",points:1,options:{create:[{sequence:1,text:"Correct",isCorrect:true},{sequence:2,text:"Incorrect",isCorrect:false}]}}]}}}}}}}},include:{versions:{include:{modules:{include:{contentItems:true,assessments:{include:{questions:{include:{options:true}}}}}}}}}});
    const version=course.versions[0],learningModule=version.modules[0],assessment=learningModule.assessments[0];contentId=learningModule.contentItems[0].id;assessmentId=assessment.id;criticalQuestionId=assessment.questions[0].id;criticalCorrectId=assessment.questions[0].options.find(x=>x.isCorrect)!.id;normalQuestionId=assessment.questions[1].id;normalCorrectId=assessment.questions[1].options.find(x=>x.isCorrect)!.id;
    const assignment=await db.trainingAssignment.create({data:{fingerprint:`${tag}:assignment`,organizationId,employeeId,courseVersionId:version.id,sourceType:"MANUAL",assignedAt:new Date("2026-01-01"),dueAt:null}});assignmentId=assignment.id;
    const policy=await db.policy.create({data:{organizationId,code:"PORTAL-POLICY",title:"Portal policy",requiresAcknowledgment:true,versions:{create:{versionNumber:1,status:"PUBLISHED",effectiveFrom:new Date("2026-01-01"),publishedAt:new Date(),body:"Read this exact policy version.",contentHash:"policy-v1",createdByUserId:owner.id}}},include:{versions:true}});const pa=await db.policyAssignment.create({data:{fingerprint:`${tag}:policy`,organizationId,employeeId,policyVersionId:policy.versions[0].id,sourceType:"MANUAL",assignedByUserId:owner.id}});policyAssignmentId=pa.id;
    const template=await db.onboardingTemplate.create({data:{organizationId,code:"PORTAL",name:"Portal onboarding",ownerType:"ORGANIZATION",versions:{create:{versionNumber:1,status:"PUBLISHED",effectiveFrom:new Date("2026-01-01"),publishedAt:new Date(),contentHash:"portal-onboarding",steps:{create:[{sequence:1,code:"TRAIN",name:"Complete training",stepType:"TRAINING",required:true},{sequence:2,code:"ADMIN",name:"Administrator verification",stepType:"MANUAL_ADMIN_CHECK",required:true},{sequence:3,code:"ASSESS",name:"Observed assessment",stepType:"COMPETENCY",required:true}]}}}},include:{versions:{include:{steps:true}}}});const onboarding=await db.employeeOnboarding.create({data:{organizationId,employeeId,templateVersionId:template.versions[0].id,status:"IN_PROGRESS",startedAt:new Date(),createdByUserId:owner.id,steps:{create:template.versions[0].steps.map(step=>({stepDefinitionId:step.id,status:"BLOCKED"}))}},include:{steps:{include:{stepDefinition:true}}}});manualStepId=onboarding.steps.find(step=>step.stepDefinition.stepType==="MANUAL_ADMIN_CHECK")!.id;
  });
  const owner=()=>({id:ownerId});const employeeUser=()=>({id:employeeUserId});

  it("securely routes employee invitations through Mailgun, persists acceptance, and claims the existing identity",async()=>{let sentMessage:unknown;const provider={name:"mailgun",configured:true,send:async(message:unknown)=>{sentMessage=message;return{messageId:"synthetic-provider-id",acceptedAt:new Date("2026-10-04T20:00:00Z"),provider:"mailgun"}}};const invited=await inviteEmployeeToPortal(owner(),organizationId,employeeId,provider);expect(invited.invitation).toMatchObject({status:"PENDING",deliveryStatus:"ACCEPTED",deliveryProvider:"mailgun"});expect(invited.invitation.providerAcceptedAt).toEqual(new Date("2026-10-04T20:00:00Z"));expect(sentMessage).toMatchObject({deliveryContext:{organizationId,logicalType:"EmployeePortalInvitation",logicalId:invited.invitation.id,purpose:"WORKFORCE_TRANSACTIONAL"}});await expect(claimEmployeePortalInvitation({id:otherUserId,email:(await db.user.findUniqueOrThrow({where:{id:otherUserId}})).email},organizationId,invited.claimToken)).rejects.toThrow(/different account/);const user=await db.user.findUniqueOrThrow({where:{id:employeeUserId}});expect((await claimEmployeePortalInvitation(user,organizationId,invited.claimToken)).employeeId).toBe(employeeId);expect((await db.employee.findUniqueOrThrow({where:{id:employeeId}})).userId).toBe(employeeUserId)});
  it("keeps invitation enablement under administrator RBAC",async()=>{await expect(inviteEmployeeToPortal({id:viewerId},organizationId,otherEmployeeId)).rejects.toThrow(/employee.manage/)});
  it("fails workforce delivery explicitly without invoking a Paubox provider",async()=>{let sends=0;const invited=await inviteEmployeeToPortal(owner(),organizationId,otherEmployeeId,{name:"paubox",configured:true,send:async()=>{sends+=1;return{messageId:"must-not-send"}}});expect(sends).toBe(0);expect(invited.invitation).toMatchObject({status:"PENDING",deliveryStatus:"FAILED",deliveryErrorCode:"WORKFORCE_EMAIL_PROVIDER_POLICY_VIOLATION"});expect(JSON.stringify(invited.invitation)).not.toContain(invited.claimToken)});
  it("persists ordered provider failover attempts without recipient or message content",async()=>{const primary={name:"paubox",configured:true,send:async()=>{throw new EmailDeliveryError("capacity",true,"PAUBOX_RATE_LIMITED","CAPACITY_OR_QUOTA_FAILURE")}}as EmailProvider,secondary={name:"mailgun",configured:true,send:async()=>({messageId:"mailgun-synthetic-id",acceptedAt:new Date("2026-10-05T16:00:00Z"),provider:"mailgun"})}as EmailProvider,logicalId=`synthetic-${Date.now()}`,router=new PurposeRoutedEmailProvider("CLIENT_SECURE",primary,secondary,persistEmailAttempt);await expect(router.send({to:"synthetic@example.test",subject:"Synthetic",text:"No PHI",deliveryContext:{organizationId,logicalType:"SyntheticVerification",logicalId,purpose:"CLIENT_SECURE"}})).resolves.toMatchObject({provider:"mailgun"});const recorded=await db.emailCommunication.findUniqueOrThrow({where:{organizationId_purpose_logicalType_logicalId:{organizationId,purpose:"CLIENT_SECURE",logicalType:"SyntheticVerification",logicalId}},include:{attempts:{orderBy:{sequence:"asc"}}}});expect(recorded).toMatchObject({state:"PROVIDER_ACCEPTED",selectedProvider:"mailgun",providerMessageId:"mailgun-synthetic-id"});expect(recorded.attempts).toMatchObject([{sequence:1,provider:"paubox",failureClassification:"CAPACITY_OR_QUOTA_FAILURE"},{sequence:2,provider:"mailgun",outcome:"ACCEPTED"}]);expect(JSON.stringify(recorded)).not.toMatch(/synthetic@example|No PHI/)});
  it("reissues safely with only one pending token",async()=>{const first=await db.employeePortalInvitation.findFirstOrThrow({where:{organizationId,employeeId:otherEmployeeId,status:"PENDING"}}),second=await inviteEmployeeToPortal(owner(),organizationId,otherEmployeeId);expect(second.invitation.id).not.toBe(first.id);expect(await db.employeePortalInvitation.count({where:{organizationId,employeeId:otherEmployeeId,status:"PENDING"}})).toBe(1);expect((await db.employeePortalInvitation.findUniqueOrThrow({where:{id:first.id}})).status).toBe("REVOKED")});
  it("rejects unlinked, cross-employee, and cross-tenant access",async()=>{await expect(getEmployeePortal({id:ownerId},organizationId)).rejects.toThrow();await expect(requireEmployeeSelfAccess(employeeUser(),organizationId,otherEmployeeId)).rejects.toThrow();await expect(requireEmployeeSelfAccess(employeeUser(),otherOrganizationId,employeeId)).rejects.toThrow()});
  it("shows actionable onboarding, assignments, policies, and no fabricated deadline",async()=>{const portal=await getEmployeePortal(employeeUser(),organizationId);const steps=portal.onboarding[0].steps;expect(steps.find(x=>x.type==="TRAINING")?.actionOwner).toBe("EMPLOYEE");expect(steps.find(x=>x.type==="MANUAL_ADMIN_CHECK")?.actionOwner).toBe("ORGANIZATION");expect(steps.find(x=>x.type==="COMPETENCY")?.actionOwner).toBe("ASSESSOR");expect(portal.training[0].id).toBe(assignmentId);expect(portal.training[0].dueAt).toBeNull();expect(portal.policies[0].id).toBe(policyAssignmentId)});
  it("prevents an employee from completing administrator-only onboarding evidence",async()=>{await expect(completeManualOnboardingStep(employeeUser(),organizationId,manualStepId,"self grant attempt")).rejects.toThrow();expect((await db.employeeOnboardingStep.findUniqueOrThrow({where:{id:manualStepId}})).status).toBe("BLOCKED")});
  it("persists meaningful content progress without completing the whole course",async()=>{expect(await completeContent(assignmentId,employeeId,contentId)).toBeNull();expect((await db.trainingContentProgress.findUniqueOrThrow({where:{assignmentId_contentItemId:{assignmentId,contentItemId:contentId}}})).status).toBe("COMPLETED");expect(await db.trainingCompletion.findUnique({where:{assignmentId}})).toBeNull()});
  it("scores on the server and enforces critical-question failure",async()=>{const attempt=await startAttempt(assignmentId,employeeId,assessmentId);const wrongCritical=(await db.assessmentOption.findMany({where:{questionId:criticalQuestionId}})).find(x=>!x.isCorrect)!;const result=await submitAttempt(attempt.id,employeeId,{responses:[{questionId:criticalQuestionId,selectedOptionIds:[wrongCritical.id]},{questionId:normalQuestionId,selectedOptionIds:[normalCorrectId]}]});expect(Number(result.percentage)).toBe(50);expect(result.passed).toBe(false);expect(await db.trainingCompletion.findUnique({where:{assignmentId}})).toBeNull()});
  it("uses the atomic completion path and remains idempotent",async()=>{const attempt=await startAttempt(assignmentId,employeeId,assessmentId);const passed=await submitAttempt(attempt.id,employeeId,{responses:[{questionId:criticalQuestionId,selectedOptionIds:[criticalCorrectId]},{questionId:normalQuestionId,selectedOptionIds:[normalCorrectId]}]});expect(passed.passed).toBe(true);const completion=await db.trainingCompletion.findUniqueOrThrow({where:{assignmentId}});expect((await db.trainingCompletion.findMany({where:{assignmentId}}))).toHaveLength(1);expect((await getEmployeePortal(employeeUser(),organizationId)).training[0].completedAt).toEqual(completion.completedAt)});
  it("acknowledges only the employee's assigned policy version",async()=>{const acknowledged=await acknowledgePolicy(employeeUser(),organizationId,policyAssignmentId,{typedName:"Portal Employee"});expect(acknowledged.status).toBe("ACKNOWLEDGED");expect((await db.attestation.findUniqueOrThrow({where:{id:acknowledged.attestationId!}})).resourceVersionId).toBe(acknowledged.policyVersionId);const foreign=await db.policyAssignment.create({data:{fingerprint:`foreign-${Date.now()}`,organizationId,employeeId:otherEmployeeId,policyVersionId:acknowledged.policyVersionId,sourceType:"MANUAL",assignedByUserId:ownerId}});await expect(acknowledgePolicy(employeeUser(),organizationId,foreign.id,{typedName:"Portal Employee"})).rejects.toThrow()});
  it("exposes only owned certificates and preserves medication boundaries",async()=>{const completion=await db.trainingCompletion.findUniqueOrThrow({where:{assignmentId}});await db.certificate.create({data:{organizationId,employeeId,certificateType:"TRAINING",certificateNumber:`P13-${Date.now()}`,courseVersionId:completion.courseVersionId,trainingCompletionId:completion.id,issuedAt:new Date(),verificationToken:`p13-${Date.now()}`,certificateSnapshotJson:{training:true}}});const portal=await getEmployeePortal(employeeUser(),organizationId);expect(portal.certificates).toHaveLength(1);expect(portal.medicationGovernance.disclaimer).toMatch(/not medication qualification or administration authorization/);expect(portal.medicationGovernance.qualifications).toHaveLength(0);expect(portal.medicationGovernance.administrationAuthorizations).toHaveLength(0)});
  it("does not expose privileged remediation controls or full person data",async()=>{await db.complianceIssue.create({data:{fingerprint:`phase13-issue-${Date.now()}`,activeKey:`phase13-active-${Date.now()}`,organizationId,employeeId,issueType:"CLINICAL_SIGNOFF_REQUIRED",priority:"HIGH",sourceType:"MedicationQualification",sourceId:"test",contextJson:{clientName:"must-not-export"},reasonCodesJson:["CLINICAL_SIGNOFF_REQUIRED"],remediationActionsJson:[{type:"CLINICAL_REVIEW_REQUIRED"}],evidenceReferencesJson:[],firstDetectedAt:new Date(),latestDetectedAt:new Date()}});const portal=await getEmployeePortal(employeeUser(),organizationId),issue=portal.compliance.issues.find(x=>x.issueType==="CLINICAL_SIGNOFF_REQUIRED")!;expect(issue.visibility).toBe("WAITING_ON_ORGANIZATION");expect(issue.permittedActions).toEqual([]);expect(JSON.stringify(portal)).not.toContain("must-not-export")});
});
