import { createHash } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { PrismaClient } from "@prisma/client";
import { PDFDocument, PDFName, PDFRawStream } from "pdf-lib";
import { getDocument } from "pdfjs-dist/legacy/build/pdf.mjs";
import { createClient } from "@/domain/clients/service";
import { finalizeClientDocument, generateClientDocument, getDocumentPdf } from "@/domain/clients/documents";
import { cancelSignatureEnvelope, createSignatureEnvelope, createSignNowSession, getFacilitatedSigningReturn, getPublicSigningDocument, getPublicSigningSession, reissueSignatureInvitation, SIGNING_CONSENT_VERSION, signWithInvitation } from "@/domain/clients/signatures";

const db=new PrismaClient();let organizationId="",otherOrganizationId="",adminId="",outsiderId="",clientId="",remoteEnvelopeId="",remoteLinks:{signerId:string;url:string}[]=[];
const admin=()=>({id:adminId});
const token=(url:string)=>url.split("/").at(-1)!;
const typed=(name:string)=>({consent:true as const,consentVersion:SIGNING_CONSENT_VERSION,method:"TYPED" as const,adoptedName:name});
const png="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAF/gL+X9WewAAAAABJRU5ErkJggg==";
async function pdfText(bytes:Uint8Array){const task=getDocument({data:new Uint8Array(bytes),useSystemFonts:true}),pdf=await task.promise,pages:string[]=[];for(let number=1;number<=pdf.numPages;number++){const content=await(await pdf.getPage(number)).getTextContent();pages.push(content.items.map(item=>"str" in item?item.str:"").join(" "))}await task.destroy();return pages.join(" ")}
async function imageCount(bytes:Uint8Array){const pdf=await PDFDocument.load(bytes);return pdf.context.enumerateIndirectObjects().filter(([,object])=>object instanceof PDFRawStream&&object.dict.get(PDFName.of("Subtype"))?.toString()==="/Image").length}
describe.sequential("native electronic signatures",()=>{
 beforeAll(async()=>{const tag=`native-sign-${Date.now()}`,[org,other,adminUser,outsider]=await Promise.all([db.organization.create({data:{legalName:"Native Sign Org",displayName:"Native Sign Org",slug:tag}}),db.organization.create({data:{legalName:"Other",displayName:"Other",slug:`${tag}-other`}}),db.user.create({data:{email:`${tag}@example.test`,status:"ACTIVE"}}),db.user.create({data:{email:`${tag}-outsider@example.test`,status:"ACTIVE"}})]);organizationId=org.id;otherOrganizationId=other.id;adminId=adminUser.id;outsiderId=outsider.id;const permission=await db.permission.upsert({where:{code:"client.signature.manage"},update:{},create:{code:"client.signature.manage"}}),generate=await db.permission.upsert({where:{code:"client.document.generate"},update:{},create:{code:"client.document.generate"}}),create=await db.permission.upsert({where:{code:"client.create"},update:{},create:{code:"client.create"}}),role=await db.roleDefinition.create({data:{organizationId,code:"SIGNER_MANAGER",name:"Signer manager",scope:"ORGANIZATION",permissions:{create:[permission,generate,create].map(row=>({permissionId:row.id}))}}});await db.organizationMembership.create({data:{organizationId,userId:adminId,status:"ACTIVE",roles:{create:{roleDefinitionId:role.id}}}});await db.organizationMembership.create({data:{organizationId:otherOrganizationId,userId:outsiderId,status:"ACTIVE"}});await db.clientDocumentTemplate.create({data:{organizationId,code:"NATIVE-FACE",name:"Native signature test document",documentType:"FACE_SHEET",versionNumber:1,contentJson:{renderer:"BASIC",signerRoles:["CLIENT","ORGANIZATION_STAFF"]}}});clientId=(await createClient(admin(),organizationId,{legalFirstName:"Fictitious",legalLastName:"Signer",dateOfBirth:"1990-01-01"})).client.id});
 beforeAll(async()=>{const read=await db.permission.upsert({where:{code:"client.document.read"},update:{},create:{code:"client.document.read"}}),role=await db.roleDefinition.findFirstOrThrow({where:{organizationId,code:"SIGNER_MANAGER"}});await db.rolePermission.create({data:{roleDefinitionId:role.id,permissionId:read.id}})});
 afterAll(async()=>db.$disconnect());
 it("freezes exact bytes, stores only token digests, and returns a minimal public projection",async()=>{const doc=await generateClientDocument(admin(),organizationId,clientId,"FACE_SHEET");await finalizeClientDocument(admin(),organizationId,clientId,doc.id);const created=await createSignatureEnvelope(admin(),organizationId,clientId,doc.id,"SEND_FOR_SIGNATURE",[{role:"CLIENT",name:"Fictitious Signer",email:"client@example.test"},{role:"ORGANIZATION_STAFF",name:"Staff Signer",email:"staff@example.test"}]),links=(created as typeof created&{deliveryLinks:{signerId:string;url:string}[]}).deliveryLinks;remoteEnvelopeId=created.id;remoteLinks=links;expect(links).toHaveLength(2);const firstToken=token(links[0].url),stored=await db.signatureEnvelope.findUniqueOrThrow({where:{id:created.id},include:{invitations:true}});expect(stored.frozenDocumentHash).toBe(createHash("sha256").update(stored.frozenPdf!).digest("hex"));expect(JSON.stringify(stored)).not.toContain(firstToken);expect(stored.invitations[0].tokenDigest).toHaveLength(64);const projection=await getPublicSigningSession(firstToken);expect(projection).toEqual(expect.objectContaining({organizationName:"Native Sign Org",documentName:"Native signature test document",signerRole:"CLIENT"}));expect(projection).not.toHaveProperty("clientId");expect(projection).not.toHaveProperty("documentId");await db.client.update({where:{id:clientId},data:{legalFirstName:"Changed"}});expect(await getPublicSigningDocument(firstToken)).toEqual(Buffer.from(stored.frozenPdf!));});
 it("keeps partial source and final artifacts distinct, renders signatures, and finalizes exactly once",async()=>{
  const envelope=await db.signatureEnvelope.findUniqueOrThrow({where:{id:remoteEnvelopeId},include:{signers:true,invitations:true}}),staff=envelope.signers.find(row=>row.role==="ORGANIZATION_STAFF")!,client=envelope.signers.find(row=>row.role==="CLIENT")!,oldStaffToken=token(remoteLinks.find(row=>row.signerId===staff.id)!.url),clientToken=token(remoteLinks.find(row=>row.signerId===client.id)!.url),staffReissue=await reissueSignatureInvitation(admin(),organizationId,clientId,envelope.id,staff.id) as {url:string};
  expect(await getPublicSigningSession(clientToken)).not.toHaveProperty("returnUrl");
  await expect(getPublicSigningSession(oldStaffToken)).rejects.toThrow(/invalid|unavailable/i);await expect(getPublicSigningSession("x".repeat(43))).rejects.toThrow(/invalid|unavailable/i);const createdAudit=await db.auditEvent.findFirstOrThrow({where:{entityId:envelope.id,eventType:"client.signature_invitations_created"}});expect(JSON.stringify(createdAudit.metadataJson)).not.toMatch(/Fictitious|example\.test/);await expect(signWithInvitation(clientToken,{...typed("Fictitious Signer"),consent:false})).rejects.toThrow();
  const staffResult=await signWithInvitation(token(staffReissue.url),typed("Staff Signer"));expect(staffResult.complete).toBe(false);const partial=await db.clientDocument.findUniqueOrThrow({where:{id:envelope.documentId}});expect(partial).toMatchObject({status:"PARTIALLY_SIGNED",finalPdf:null});expect(await getDocumentPdf(admin(),organizationId,clientId,envelope.documentId,"source")).toEqual(Buffer.from(envelope.frozenPdf!));await expect(getDocumentPdf(admin(),organizationId,clientId,envelope.documentId,"final")).rejects.toThrow(/unavailable/i);
  const clientResult=await signWithInvitation(clientToken,{consent:true,consentVersion:SIGNING_CONSENT_VERSION,method:"DRAWN",adoptedName:"Fictitious Signer",drawnSignature:png});expect(clientResult.complete).toBe(true);await expect(signWithInvitation(clientToken,typed("Again"))).rejects.toThrow(/invalid|unavailable/i);const done=await db.signatureEnvelope.findUniqueOrThrow({where:{id:envelope.id},include:{document:true,signers:true}}),source=await getDocumentPdf(admin(),organizationId,clientId,envelope.documentId,"source"),final=await getDocumentPdf(admin(),organizationId,clientId,envelope.documentId,"final"),text=await pdfText(final);
  expect(source).toEqual(Buffer.from(done.frozenPdf!));expect(final).toEqual(Buffer.from(done.document.finalPdf!));expect(final).not.toEqual(source);expect(done.frozenDocumentHash).toBe(createHash("sha256").update(source).digest("hex"));expect(done.finalDocumentHash).toBe(createHash("sha256").update(final).digest("hex"));expect(text).toContain("Staff Signer");expect(text).toContain("Fictitious Signer");expect(text).toContain("Electronic signature record");expect(text).not.toContain("/s/");expect(await imageCount(final)).toBeGreaterThan(await imageCount(source));expect(done.evidenceJson).not.toBeNull();expect(done.evidencePdf).not.toBeNull();expect(done.signers.map(row=>row.signatureMethod).sort()).toEqual(["DRAWN","TYPED"]);expect((await PDFDocument.load(final)).getPageCount()).toBeGreaterThan((await PDFDocument.load(source)).getPageCount());expect(await db.signatureEnvelope.count({where:{documentId:done.documentId}})).toBe(1)
 });
 it("provides only facilitated sessions a deterministic same-origin return path",async()=>{
  const doc=await generateClientDocument(admin(),organizationId,clientId,"FACE_SHEET");await finalizeClientDocument(admin(),organizationId,clientId,doc.id);const envelope=await createSignatureEnvelope(admin(),organizationId,clientId,doc.id,"SIGN_NOW",[{role:"CLIENT",name:"Present Signer"}]),session=await createSignNowSession(admin(),organizationId,clientId,envelope.id,envelope.signers[0].id),publicSession=await getPublicSigningSession(token(session.url)),signer=await db.signatureSigner.findUniqueOrThrow({where:{id:envelope.signers[0].id}}),beforeConsent=await db.clientDocument.findUniqueOrThrow({where:{id:doc.id}});
  expect(session.url).toMatch(/\/sign\//);expect(publicSession.returnUrl).toBe(`/sign/${encodeURIComponent(token(session.url))}/return`);expect(publicSession.returnUrl).not.toMatch(/^https?:/);expect(publicSession).not.toHaveProperty("clientId");expect(publicSession).not.toHaveProperty("documentId");expect(signer).toMatchObject({facilitatorUserId:adminId,name:"Present Signer",status:"VIEWED",signedAt:null,consentedAt:null,verificationMethod:"IN_PERSON_FACILITATED"});expect(beforeConsent).toMatchObject({status:"READY_FOR_SIGNATURE",authoritativeCompletedAt:null,finalPdf:null});await cancelSignatureEnvelope(admin(),organizationId,clientId,envelope.id,"Incorrect document information");const stored=await db.clientDocument.findUniqueOrThrow({where:{id:doc.id}});expect(stored.status).toBe("VOIDED");expect(stored.authoritativeCompletedAt).toBeNull();await expect(getPublicSigningSession(token(session.url))).rejects.toThrow(/invalid|unavailable/i)
 });
 it("supports mixed remote and facilitated signing in one arbitrarily ordered envelope",async()=>{
  const doc=await generateClientDocument(admin(),organizationId,clientId,"FACE_SHEET");await finalizeClientDocument(admin(),organizationId,clientId,doc.id);const envelope=await createSignatureEnvelope(admin(),organizationId,clientId,doc.id,"SEND_FOR_SIGNATURE",[{role:"CLIENT",name:"Remote Client",email:"remote@example.test"},{role:"ORGANIZATION_STAFF",name:"Present Staff",email:"staff@example.test"}]),links=(envelope as typeof envelope&{deliveryLinks:{signerId:string;url:string}[]}).deliveryLinks,client=envelope.signers.find(row=>row.role==="CLIENT")!,staff=envelope.signers.find(row=>row.role==="ORGANIZATION_STAFF")!,oldStaffToken=token(links.find(row=>row.signerId===staff.id)!.url),staffSession=await createSignNowSession(admin(),organizationId,clientId,envelope.id,staff.id),staffToken=token(staffSession.url);
  await expect(getPublicSigningSession(oldStaffToken)).rejects.toThrow(/invalid|unavailable/i);expect((await signWithInvitation(token(links.find(row=>row.signerId===client.id)!.url),typed("Remote Client"))).complete).toBe(false);expect((await signWithInvitation(staffToken,typed("Present Staff"))).complete).toBe(true);expect(await getFacilitatedSigningReturn(admin(),staffToken)).toBe(`/admin/clients?organizationId=${encodeURIComponent(organizationId)}&clientId=${encodeURIComponent(clientId)}&documentId=${encodeURIComponent(doc.id)}&view=Documents`);await expect(getFacilitatedSigningReturn({id:outsiderId},staffToken)).rejects.toThrow(/unavailable/i);const stored=await db.signatureEnvelope.findUniqueOrThrow({where:{id:envelope.id},include:{signers:true}});expect(stored.signers.map(row=>row.verificationMethod).sort()).toEqual(["IN_PERSON_FACILITATED","SECURE_INVITATION"]);expect(stored.signers.find(row=>row.id===staff.id)?.facilitatorUserId).toBe(adminId)
 });
 it("fails closed and recovers a legacy completion claim without fabricating signature evidence",async()=>{const doc=await generateClientDocument(admin(),organizationId,clientId,"FACE_SHEET");await finalizeClientDocument(admin(),organizationId,clientId,doc.id);const envelope=await createSignatureEnvelope(admin(),organizationId,clientId,doc.id,"SIGN_NOW",[{role:"CLIENT",name:"Legacy Signer"}]),rendered=(await db.clientDocument.findUniqueOrThrow({where:{id:doc.id}})).renderedPdf!,when=new Date();await db.signatureEnvelope.update({where:{id:envelope.id},data:{status:"COMPLETED",completedAt:when,frozenPdf:rendered,frozenDocumentHash:"a".repeat(64),finalDocumentHash:"b".repeat(64),evidenceJson:{legacy:true},evidencePdf:rendered}});await db.clientDocument.update({where:{id:doc.id},data:{status:"COMPLETED",authoritativeCompletedAt:when,finalPdf:rendered}});const session=await createSignNowSession(admin(),organizationId,clientId,envelope.id,envelope.signers[0].id),recovered=await db.signatureEnvelope.findUniqueOrThrow({where:{id:envelope.id},include:{document:true,signers:true}});expect(session.url).toMatch(/\/sign\//);expect(recovered.status).toBe("READY");expect(recovered.document.status).toBe("READY_FOR_SIGNATURE");expect(recovered.signers[0].status).toBe("PENDING");expect(recovered.evidenceJson).toEqual({legacy:true});expect(await db.auditEvent.count({where:{organizationId,entityId:envelope.id,eventType:"client.signature_inconsistent_completion_recovered"}})).toBe(1)});
 it("expires links without destroying the envelope and records the lifecycle event",async()=>{const doc=await generateClientDocument(admin(),organizationId,clientId,"FACE_SHEET");await finalizeClientDocument(admin(),organizationId,clientId,doc.id);const envelope=await createSignatureEnvelope(admin(),organizationId,clientId,doc.id,"SEND_FOR_SIGNATURE",[{role:"CLIENT",name:"Expiring Signer",email:"expires@example.test"}]),link=(envelope as typeof envelope&{deliveryLinks:{url:string}[]}).deliveryLinks[0];await db.signatureInvitation.updateMany({where:{envelopeId:envelope.id},data:{expiresAt:new Date("2000-01-01T00:00:00Z")}});await expect(getPublicSigningSession(token(link.url))).rejects.toThrow(/invalid|unavailable/i);expect((await db.signatureInvitation.findFirstOrThrow({where:{envelopeId:envelope.id}})).status).toBe("EXPIRED");expect((await db.signatureEnvelope.findUniqueOrThrow({where:{id:envelope.id}})).status).toBe("SENT");expect(await db.auditEvent.count({where:{entityId:envelope.id,eventType:"client.signature_invitation_expired"}})).toBe(1)});
 it("enforces signer roles, management authorization, and tenant scope",async()=>{const doc=await generateClientDocument(admin(),organizationId,clientId,"FACE_SHEET");await finalizeClientDocument(admin(),organizationId,clientId,doc.id);await expect(createSignatureEnvelope(admin(),organizationId,clientId,doc.id,"SIGN_NOW",[{role:"CASE_MANAGER",name:"Wrong Role"}])).rejects.toThrow(/role/i);await expect(createSignatureEnvelope({id:outsiderId},organizationId,clientId,doc.id,"SIGN_NOW",[{role:"CLIENT",name:"No"}])).rejects.toThrow();await expect(createSignatureEnvelope(admin(),otherOrganizationId,clientId,doc.id,"SIGN_NOW",[{role:"CLIENT",name:"No"}])).rejects.toThrow()});
});
