import { beforeAll, describe, expect, it } from "vitest";
import { PrismaClient } from "@prisma/client";
import { configureOrganizationProgram, getOrganizationSetup, updateOrganizationProfile } from "@/domain/organization-setup/service";
import { inviteEmployeeToPortal } from "@/domain/portal/service";
import { getEmployerDashboard } from "@/domain/admin/service";
import { getEmployeePortal } from "@/domain/portal/service";

const db=new PrismaClient();
describe.sequential("Phase 15 organization setup and production onboarding",()=>{
  let organizationId:string,otherOrganizationId:string,ownerId:string,employeeUserId:string,viewerId:string,employeeId:string;
  beforeAll(async()=>{const tag=`phase15-${Date.now()}`,[owner,viewer,ownerRole,auditorRole,other]=await Promise.all([db.user.findUniqueOrThrow({where:{email:"alex.owner@example.test"}}),db.user.findUniqueOrThrow({where:{email:"jordan.viewer@example.test"}}),db.roleDefinition.findFirstOrThrow({where:{organizationId:null,code:"ORGANIZATION_OWNER"}}),db.roleDefinition.findFirstOrThrow({where:{organizationId:null,code:"AUDITOR"}}),db.organization.findFirstOrThrow({where:{slug:"lakeside-community-services"}})]);ownerId=owner.id;viewerId=viewer.id;otherOrganizationId=other.id;const organization=await db.organization.create({data:{legalName:"New Employer",displayName:"New Employer",slug:tag}});organizationId=organization.id;const ownerMembership=await db.organizationMembership.create({data:{organizationId,userId:ownerId,status:"ACTIVE"}}),viewerMembership=await db.organizationMembership.create({data:{organizationId,userId:viewerId,status:"ACTIVE"}});await db.membershipRole.createMany({data:[{membershipId:ownerMembership.id,roleDefinitionId:ownerRole.id},{membershipId:viewerMembership.id,roleDefinitionId:auditorRole.id}]});const employeeUser=await db.user.create({data:{email:`employee-${tag}@example.test`,status:"ACTIVE"}});employeeUserId=employeeUser.id;await db.organizationMembership.create({data:{organizationId,userId:employeeUserId,status:"ACTIVE"}});});
  const owner=()=>({id:ownerId}),employee=()=>({id:employeeUserId});

  it("derives a deterministic not-started state for an empty provisioned tenant",async()=>{const first=await getOrganizationSetup(owner(),organizationId),second=await getOrganizationSetup(owner(),organizationId);expect(first.readiness.lifecycle).toBe("NOT_STARTED");expect(first.readiness.operationallyReady).toBe(false);expect(first.counts.workforce).toBe(0);expect(first.readiness.items.find(item=>item.key==="invitations")?.state).toBe("NOT_APPLICABLE");expect(second.readiness).toEqual(first.readiness)});
  it("validates, persists, and audits the organization profile",async()=>{await expect(updateOrganizationProfile(owner(),organizationId,{legalName:"New Employer",displayName:"New Employer",email:"bad",phone:"651-555-0100",timezone:"America/Chicago"})).rejects.toThrow();await updateOrganizationProfile(owner(),organizationId,{legalName:"New Employer LLC",displayName:"New Employer",email:"compliance@new.example",phone:"651-555-0100",timezone:"America/Chicago",addressLine1:null,addressLine2:null,city:"Saint Paul",state:"mn",postalCode:"55101",country:"US"});const setup=await getOrganizationSetup(owner(),organizationId);expect(setup.organization.state).toBe("MN");expect(setup.readiness.items.find(item=>item.key==="profile")?.state).toBe("COMPLETE");expect(await db.auditEvent.count({where:{organizationId,eventType:"organization.profile_changed",actorUserId:ownerId}})).toBe(1)});
  it("configures only an approved platform-supported program idempotently",async()=>{await expect(configureOrganizationProgram(owner(),organizationId,{licenseType:"MN_144A",licenseStatus:"ACTIVE"})).rejects.toThrow(/not supported/);await expect(configureOrganizationProgram(owner(),organizationId,{licenseType:"MN_245D",licenseStatus:"ACTIVE",organizationId:otherOrganizationId})).rejects.toThrow();const first=await configureOrganizationProgram(owner(),organizationId,{licenseType:"MN_245D",licenseNumber:"TEST-245D",licenseStatus:"PENDING"});expect((await getOrganizationSetup(owner(),organizationId)).readiness.items.find(item=>item.key==="program")?.state).toBe("ACTION_REQUIRED");const second=await configureOrganizationProgram(owner(),organizationId,{licenseType:"MN_245D",licenseNumber:"TEST-245D",licenseStatus:"ACTIVE"}),third=await configureOrganizationProgram(owner(),organizationId,{licenseType:"MN_245D",licenseNumber:"TEST-245D",licenseStatus:"ACTIVE"});expect(second.id).toBe(first.id);expect(third.id).toBe(first.id);expect(await db.organizationLicense.count({where:{organizationId,licenseType:"MN_245D",licenseStatus:{not:"ARCHIVED"}}})).toBe(1);const setup=await getOrganizationSetup(owner(),organizationId);expect(setup.supportedPrograms.map(item=>item.licenseType)).toContain("MN_245D");expect(setup.readiness.items.find(item=>item.key==="training")?.state).toBe("COMPLETE");expect(setup.readiness.operationallyReady).toBe(true)});
  it("moves naturally from empty workforce into invitation readiness without creating evidence",async()=>{const row=await db.employee.create({data:{organizationId,email:`invite-${Date.now()}@example.test`,firstName:"First",lastName:"Worker",employmentStatus:"PENDING"}});employeeId=row.id;let setup=await getOrganizationSetup(owner(),organizationId);expect(setup.readiness.items.find(item=>item.key==="workforce")?.state).toBe("COMPLETE");expect(setup.readiness.items.find(item=>item.key==="invitations")?.state).toBe("OPTIONAL");await inviteEmployeeToPortal(owner(),organizationId,employeeId);setup=await getOrganizationSetup(owner(),organizationId);expect(setup.counts.invitations.PENDING).toBe(1);expect(setup.readiness.items.find(item=>item.key==="invitations")?.state).toBe("COMPLETE");expect(await db.trainingCompletion.count({where:{organizationId}})).toBe(0);expect(await db.competencyAssessment.count({where:{organizationId}})).toBe(0)});
  it("surfaces policy, competency, medication, guardrail, and audit boundaries honestly",async()=>{const setup=await getOrganizationSetup(owner(),organizationId);expect(setup.readiness.items.find(item=>item.key==="policies")?.state).toBe("REQUIRES_REVIEW");expect(setup.readiness.items.find(item=>item.key==="evidence")?.detail).toMatch(/creates no evidence/i);expect(setup.readiness.items.find(item=>item.key==="medication")?.detail).not.toMatch(/qualified|authorized employee/i);expect(setup.readiness.items.find(item=>item.key==="assignments")?.detail).toMatch(/individually evaluated|No active assignment rule/);expect(setup.readiness.items.find(item=>item.key==="audit")?.state).toBe("COMPLETE")});
  it("enforces tenant isolation for reads and mutations",async()=>{await expect(getOrganizationSetup(owner(),otherOrganizationId)).rejects.toThrow();await expect(updateOrganizationProfile(owner(),otherOrganizationId,{legalName:"Attack",displayName:"Attack",email:"attack@example.test",phone:"123",timezone:"America/Chicago",addressLine1:null,addressLine2:null,city:null,state:null,postalCode:null,country:null})).rejects.toThrow();await expect(configureOrganizationProgram(owner(),otherOrganizationId,{licenseType:"MN_245D",licenseStatus:"ACTIVE"})).rejects.toThrow()});
  it("prevents employee and read-only member access or privilege escalation",async()=>{await expect(getOrganizationSetup(employee(),organizationId)).rejects.toThrow(/organization.manage/);await expect(getOrganizationSetup({id:viewerId},organizationId)).rejects.toThrow(/organization.manage/);await expect(updateOrganizationProfile(employee(),organizationId,{})).rejects.toThrow();await expect(configureOrganizationProgram({id:viewerId},organizationId,{licenseType:"MN_245D",licenseStatus:"ACTIVE"})).rejects.toThrow(/organization.manage/);expect(await db.membershipRole.count({where:{membership:{organizationId,userId:employeeUserId}}})).toBe(0)});
  it("preserves the existing employer workspace and employee self-service boundaries",async()=>{expect((await getEmployerDashboard(owner(),organizationId)).activeWorkforce).toBe(0);await expect(getEmployeePortal(employee(),organizationId)).rejects.toThrow();expect(await db.auditEvent.count({where:{organizationId,eventType:{in:["organization.profile_changed","organization.program_configured","organization.program_configuration_changed"]}}})).toBe(3)});
});
