import { afterEach, describe, expect, it, vi } from "vitest";
import { SendEmailCommand } from "@aws-sdk/client-sesv2";
import { configuredEmailProvider, EmailDeliveryError, SesEmailProvider, sesClientOptions } from "@/domain/notifications/email";
import { renderSignatureInvitationEmail } from "@/domain/clients/signature-email";
import { emailEnvironment, validateProductionEnvironment } from "@/lib/env";

const sesConfig={provider:"ses" as const,region:"us-east-2",from:"signatures@example.test",fromName:"Synthetic Compliance",replyTo:"support@example.test"};
describe("production SES email delivery",()=>{
  afterEach(()=>vi.unstubAllEnvs());
  it("builds an SES v2 request with configured sender, reply-to, HTML, text, and no attachment",async()=>{let command:SendEmailCommand|undefined;const client={send:vi.fn(async(input:SendEmailCommand)=>{command=input;return{MessageId:"ses-message-1",$metadata:{}}})},message=renderSignatureInvitationEmail({organizationName:"Synthetic Compliance",signerName:"Synthetic Signer",documentDescription:"Service document",signingUrl:"https://app.waldah.test/sign/safe-token",expiresAt:new Date("2026-10-05T18:00:00Z")}),result=await new SesEmailProvider(sesConfig,client).send({...message,to:" SIGNER@EXAMPLE.TEST "});expect(result.messageId).toBe("ses-message-1");expect(command?.input).toEqual(expect.objectContaining({FromEmailAddress:'"Synthetic Compliance" <signatures@example.test>',Destination:{ToAddresses:["signer@example.test"]},ReplyToAddresses:["support@example.test"]}));expect(command?.input.Content?.Simple?.Body?.Html?.Data).toContain("Review and sign securely");expect(command?.input.Content?.Simple?.Body?.Text?.Data).toContain("https://app.waldah.test/sign/safe-token");expect(command?.input.Content).not.toHaveProperty("Raw");expect(JSON.stringify(command?.input)).not.toMatch(/attachment|pdf/i)});
  it("uses region-only client options so the AWS SDK default ECS task-role chain remains authoritative",()=>{expect(sesClientOptions(sesConfig)).toEqual({region:"us-east-2"});expect(sesClientOptions(sesConfig)).not.toHaveProperty("credentials")});
  it("renders neutral, escaped, understandable HTML and text for long synthetic names",()=>{const message=renderSignatureInvitationEmail({organizationName:`Synthetic & Very Long Provider ${"A".repeat(120)}`,signerName:`Long <Signer> ${"B".repeat(120)}`,documentDescription:"Rights acknowledgment",signingUrl:"https://app.waldah.test/sign/opaque-token",expiresAt:new Date("2026-10-05T18:00:00Z")});expect(message.subject).toContain("document signature requested");expect(message.html).toContain("Long &lt;Signer&gt;");expect(message.text).toContain("Review and sign securely");expect(`${message.subject}${message.text}${message.html}`).not.toMatch(/diagnos|medication|date of birth|MA\/PMI/i)});
  it("supports missing optional reply-to and validates destinations before contacting SES",async()=>{const send=vi.fn(),provider=new SesEmailProvider({...sesConfig,replyTo:undefined},{send});await expect(provider.send({to:"not-an-email",subject:"Signature requested",text:"Review"})).rejects.toThrow();expect(send).not.toHaveBeenCalled()});
  it("maps synchronous SES failures to sanitized retry semantics",async()=>{const provider=new SesEmailProvider(sesConfig,{send:vi.fn().mockRejectedValue({name:"ServiceUnavailableException",$retryable:{},$metadata:{httpStatusCode:503}})});await expect(provider.send({to:"signer@example.test",subject:"Signature requested",text:"Review"})).rejects.toMatchObject({code:"SES_SERVICEUNAVAILABLEEXCEPTION",retryable:true});await expect(provider.send({to:"signer@example.test",subject:"Signature requested",text:"Review"})).rejects.toBeInstanceOf(EmailDeliveryError)});
  it("selects SES only from complete runtime configuration and never falls back to test delivery",()=>{expect(emailEnvironment({EMAIL_PROVIDER:"ses",AWS_REGION:"us-east-2",EMAIL_FROM:"signatures@example.test"})).toEqual(expect.objectContaining({provider:"ses",region:"us-east-2"}));expect(configuredEmailProvider({EMAIL_PROVIDER:"ses",AWS_REGION:"us-east-2",EMAIL_FROM:"signatures@example.test"}).name).toBe("ses");expect(configuredEmailProvider({}).configured).toBe(false);const base={DATABASE_URL:"postgresql://db.invalid/app",APP_BASE_URL:"https://app.waldah.test",PRODUCTION_AUTH_MODE:"trusted-proxy-hmac",AUTH_PROXY_SECRET:"a".repeat(32),JOB_SECRET:"b".repeat(32),JOB_ACTOR_USER_ID:"actor",RATE_LIMIT_URL:"https://limits.example.test",RATE_LIMIT_TOKEN:"c".repeat(20),EVIDENCE_STORAGE_MODE:"external-reference",EVIDENCE_STORAGE_URL:"https://evidence.example.test",EVIDENCE_STORAGE_TOKEN:"d".repeat(20),EMAIL_PROVIDER:"ses",EMAIL_FROM:"signatures@example.test",AWS_REGION:"us-east-2",SIGNING_DELIVERY_MODE:"email"};expect(validateProductionEnvironment(base)).toEqual(expect.objectContaining({EMAIL_PROVIDER:"ses"}));expect(()=>validateProductionEnvironment({...base,SIGNING_DELIVERY_MODE:"test"})).toThrow(/Test signing delivery/);expect(()=>validateProductionEnvironment({...base,EMAIL_PROVIDER:undefined})).toThrow(/EMAIL_PROVIDER/) });
});
