import { createHash, createHmac } from "node:crypto";
import { PDFDocument, StandardFonts } from "pdf-lib";
import { PrismaClient } from "@prisma/client";
import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import { createClient, getClient } from "@/domain/clients/service";
import { createRightsRenewal, finalizeClientDocument, generateClientDocument } from "@/domain/clients/documents";
import { confirmClientImport, createClientImport, reviewClientImportProposal, updateClientImportDocumentSettings } from "@/domain/clients/imports";
import { documentValidityState, getClientRenewalSummary } from "@/domain/clients/renewals";
import { EmailDeliveryError } from "@/domain/notifications/email";
import { reconcileMailgunWebhook } from "@/domain/notifications/mailgun-events";
import { SIGNING_CONSENT_VERSION, signWithInvitation, startManagedSignerAction, type SigningInvitationDelivery } from "@/domain/clients/signatures";

const db=new PrismaClient();
describe.sequential("signature workflow remediation and reviewed imported renewals",()=>{
  let organizationId="",userId="",clientId="";
  const user=()=>({id:userId});
  beforeAll(async()=>{const tag=`signature-renewal-${Date.now()}`,[organization,actor]=await Promise.all([db.organization.create({data:{legalName:tag,displayName:tag,slug:tag,timezone:"America/Chicago"}}),db.user.create({data:{email:`${tag}@example.test`,status:"ACTIVE"}})]);organizationId=organization.id;userId=actor.id;for(const code of["client.create","client.read","client.update","client.document.generate","client.document.read","client.signature.manage"])await db.permission.upsert({where:{code},update:{},create:{code}});const permissions=await db.permission.findMany({where:{code:{startsWith:"client."}}}),role=await db.roleDefinition.create({data:{organizationId,code:"SIGNATURE_RENEWAL_MANAGER",name:"Signature renewal manager",scope:"ORGANIZATION",permissions:{create:permissions.map(item=>({permissionId:item.id}))}}}),membership=await db.organizationMembership.create({data:{organizationId,userId,status:"ACTIVE"}});await db.membershipRole.create({data:{membershipId:membership.id,roleDefinitionId:role.id}});await db.employee.create({data:{organizationId,userId,firstName:"Synthetic",lastName:"Staff",email:`${tag}-staff@example.test`,employmentStatus:"ACTIVE"}});clientId=(await createClient(user(),organizationId,{legalFirstName:"Synthetic",legalLastName:"Client",dateOfBirth:"1990-01-01",email:`${tag}-client@example.test`})).client.id;await db.clientDocumentTemplate.createMany({data:[{organizationId,code:"REMEDIATION-FACE",name:"Remediation face",documentType:"FACE_SHEET",versionNumber:1,renewalPolicy:"NONE",contentJson:{renderer:"BASIC",signerRoles:["CLIENT","ORGANIZATION_STAFF"],signerMethods:{CLIENT:["SIGN_NOW","SEND_FOR_SIGNATURE"],ORGANIZATION_STAFF:["SIGN_NOW"]}}},{organizationId,code:"REMEDIATION-RIGHTS",name:"Remediation rights",documentType:"RIGHTS_ACKNOWLEDGMENT",versionNumber:1,renewalPolicy:"ANNUAL",renewalWarningDays:30,contentJson:{renderer:"BASIC",signerRoles:["CLIENT","ORGANIZATION_STAFF"]}}]})});
  afterAll(async()=>db.$disconnect());

  it("keeps each persisted signer bound to its own methods after staff signs first and reports delivery failure honestly",async()=>{const document=await generateClientDocument(user(),organizationId,clientId,"FACE_SHEET");await finalizeClientDocument(user(),organizationId,clientId,document.id);const roster=[{role:"CLIENT" as const,name:"Synthetic Client",email:"client@example.test"},{role:"ORGANIZATION_STAFF" as const,name:"Synthetic Staff",email:"staff@example.test"}],staff=await startManagedSignerAction(user(),organizationId,clientId,document.id,roster,1,"SIGN_NOW",false) as {url:string};await signWithInvitation(staff.url.split("/").at(-1)!,{consent:true,consentVersion:SIGNING_CONSENT_VERSION,method:"TYPED",adoptedName:"Synthetic Staff"});const detail=await getClient(user(),organizationId,clientId),view=detail.documents.find(item=>item.id===document.id)!,clientSigner=view.envelope!.signers.find(item=>item.role==="CLIENT")!;expect(clientSigner.requirementIndex).toBe(0);expect(view.signatureRequirements[clientSigner.requirementIndex].allowedMethods).toEqual(["SIGN_NOW","SEND_FOR_SIGNATURE"]);expect(view.envelope!.signers.find(item=>item.role==="ORGANIZATION_STAFF")?.status).toBe("SIGNED");const failing:SigningInvitationDelivery={name:"synthetic-failure",configured:true,deliver:vi.fn(async()=>{throw new EmailDeliveryError("synthetic",false,"SYNTHETIC_REJECTED")})},result=await startManagedSignerAction(user(),organizationId,clientId,document.id,roster,0,"SEND_FOR_SIGNATURE",true,failing);expect(result).toMatchObject({deliveryStatus:"FAILED",deliveryErrorCode:"SYNTHETIC_REJECTED"});const stored=await db.signatureInvitation.findFirstOrThrow({where:{signerId:clientSigner.id,status:"ACTIVE"}});expect(stored).toMatchObject({deliveryStatus:"FAILED",providerAcceptedAt:null,deliveredAt:null});expect(await db.signatureInvitation.count({where:{signerId:clientSigner.id,status:"ACTIVE"}})).toBe(1)});

  it("reconciles confirmed Mailgun delivery to the client signature invitation without calling acceptance delivery",async()=>{const invitation=await db.signatureInvitation.findFirstOrThrow({where:{organizationId,deliveryStatus:"FAILED"}}),messageId=`<signature-${Date.now()}@mail.waldah.com>`,acceptedAt=new Date();await db.signatureInvitation.update({where:{id:invitation.id},data:{deliveryStatus:"ACCEPTED",providerMessageId:messageId,providerAcceptedAt:acceptedAt,deliveryErrorCode:null}});const communication=await db.emailCommunication.create({data:{organizationId,purpose:"CLIENT_SECURE",logicalType:"SignatureInvitation",logicalId:invitation.id,state:"PROVIDER_ACCEPTED",selectedProvider:"mailgun",providerMessageId:messageId,providerAcceptedAt:acceptedAt}});await db.emailProviderAttempt.create({data:{communicationId:communication.id,sequence:1,provider:"mailgun",outcome:"ACCEPTED",providerMessageId:messageId,attemptedAt:acceptedAt,acceptedAt}});const signingKey="synthetic-signature-webhook-key-1234567890",timestamp=String(Math.floor(Date.now()/1000)),token=`synthetic-signature-event-token-${invitation.id}`,payload={signature:{timestamp,token,signature:createHmac("sha256",signingKey).update(timestamp+token).digest("hex")},"event-data":{id:`signature-delivered-${Date.now()}-${invitation.id}`,event:"delivered",timestamp:Number(timestamp),message:{headers:{"message-id":messageId}},"delivery-status":{code:250,"enhanced-code":"2.0.0"}}};await expect(reconcileMailgunWebhook(payload,signingKey)).resolves.toEqual({status:"RECONCILED",deliveryState:"DELIVERED"});expect(await db.signatureInvitation.findUniqueOrThrow({where:{id:invitation.id}})).toMatchObject({deliveryStatus:"DELIVERED",deliveryErrorCode:null});expect(await db.auditEvent.count({where:{organizationId,eventType:"client.signature_invitation_delivered",entityId:invitation.id}})).toBe(1)});

  it("preserves reviewed external signatures as non-platform evidence and uses only confirmed validity dates",async()=>{const pdf=await PDFDocument.create(),page=pdf.addPage([612,792]),form=pdf.getForm(),font=await pdf.embedFont(StandardFonts.Helvetica);for(const[name,value]of Object.entries({RIGHTS_017_Signature_Person_served:"apparent mark",RIGHTS_018_Printed_name_Person_served:"Synthetic Client",RIGHTS_019_Date_Person_served:"10/01/2026"})){const field=form.createTextField(name);field.setText(value);field.addToPage(page,{x:40,y:700-Object.keys(form.getFields()).length*30,width:250,height:20})}form.updateFieldAppearances(font);const bytes=Buffer.from(await pdf.save()),session=await createClientImport(user(),organizationId,{target:"UPDATE_EXISTING",existingClientId:clientId,files:[{fileName:"reviewed-rights.pdf",mimeType:"application/pdf",pdfBase64:bytes.toString("base64")}]});for(const proposal of session.proposals)await reviewClientImportProposal(user(),organizationId,session.id,{proposalId:proposal.id,state:"ACCEPTED"});await updateClientImportDocumentSettings(user(),organizationId,session.id,{documentId:session.documents[0].id,classification:"RIGHTS_ACKNOWLEDGMENT",disposition:"HISTORICAL_COMPLETE",completedAt:"2026-10-01",signatureReviewStatus:"CONFIRMED_EXTERNAL",validityReviewStatus:"CONFIRMED",expirationDate:"2026-10-15"});const result=await confirmClientImport(user(),organizationId,session.id,{confirmed:true,target:"UPDATE_EXISTING",clientId,documents:[{documentId:session.documents[0].id,disposition:"HISTORICAL_COMPLETE",completedAt:"2026-10-01",signatureReviewStatus:"CONFIRMED_EXTERNAL",validityReviewStatus:"CONFIRMED",expirationDate:"2026-10-15"}]}),document=await db.clientDocument.findUniqueOrThrow({where:{id:result.createdDocuments[0]}}),snapshot=document.snapshotJson as {externalSignatures:Array<{role:string;apparentMarkPresent:boolean;platformVerified:boolean}>;importReview:{signatureStatus:string;explicitExpirationDate:string}};expect(Buffer.from(document.finalPdf!)).toEqual(bytes);expect(document.sourceDocumentHash).toBe(createHash("sha256").update(bytes).digest("hex"));expect(snapshot.externalSignatures).toContainEqual(expect.objectContaining({role:"CLIENT",apparentMarkPresent:true,platformVerified:false}));expect(snapshot.importReview).toMatchObject({signatureStatus:"CONFIRMED_EXTERNAL",explicitExpirationDate:"2026-10-15"});expect(await db.signatureEnvelope.count({where:{documentId:document.id}})).toBe(0);expect(await db.signatureSigner.count({where:{envelope:{documentId:document.id}}})).toBe(0);const cycle=(await getClientRenewalSummary(user(),organizationId,clientId,new Date("2026-10-15T23:30:00-05:00"))).cycles.find(item=>item.documentId===document.id);expect(cycle).toMatchObject({dueDate:"2026-10-15",validityStatus:"EXPIRES_TODAY"})});

  it("requires reviewed renewal dates, never copies historical signatures, and starts unsigned",async()=>{const source=await db.clientDocument.findFirstOrThrow({where:{clientId,documentType:"RIGHTS_ACKNOWLEDGMENT",source:"IMPORTED",status:"COMPLETED"}});await expect(createRightsRenewal(user(),organizationId,clientId,source.id)).rejects.toThrow(/renewal-sensitive/i);const renewal=await createRightsRenewal(user(),organizationId,clientId,source.id,{writtenCopyReceivedDate:"2026-10-16",rightsExplainedDate:"2026-10-16",explanationMethod:"IN_PERSON"}),snapshot=renewal.snapshotJson as {externalSignatures?:unknown;renewalReview:{historicalSignaturesCopied:boolean;historicalDatesCopied:boolean};form:{writtenCopyReceivedDate:string}};expect(snapshot.externalSignatures).toBeUndefined();expect(snapshot.renewalReview).toEqual(expect.objectContaining({historicalSignaturesCopied:false,historicalDatesCopied:false}));expect(snapshot.form.writtenCopyReceivedDate).toContain("2026-10-16");expect(await db.signatureEnvelope.count({where:{documentId:renewal.id}})).toBe(0)});

  it("handles inclusive expiration and unknown-rule boundaries without inventing validity",()=>{expect(documentValidityState(new Date("2026-10-15T00:00:00Z"),30,new Date("2026-10-15T23:59:00-05:00"),"America/Chicago").status).toBe("EXPIRES_TODAY");expect(documentValidityState(new Date("2026-10-15T00:00:00Z"),30,new Date("2026-10-16T00:01:00-05:00"),"America/Chicago").status).toBe("EXPIRED")});
});
