import { beforeAll,describe,expect,it } from "vitest";import { PrismaClient,type TrainingAssignment } from "@prisma/client";import { assignTrainingForCompliance,createManualAssignment,getAssignment } from "@/domain/training/assignments/service";import { updateCourseVersion } from "@/domain/training/catalog/service";import { acknowledgeContent,completeContent } from "@/domain/training/progress/service";import { startAttempt,submitAttempt } from "@/domain/training/assessments/service";import { deriveAndCreateCompletion } from "@/domain/training/completion/service";import { requireEmployeeSelfAccess } from "@/domain/permissions/authorization";import { AuthorizationError } from "@/domain/auth/errors";import { assessmentSubmissionSchema } from "@/domain/training/schemas";
const db=new PrismaClient();let org:{id:string},other:{id:string},admin:{id:string},learner:{id:string},otherUser:{id:string},employee:{id:string},published:{id:string;courseId:string},draft:string,assignment:TrainingAssignment,written:string,optional:string,ack:string,assessment:string,correct:string[],wrong:string[];
beforeAll(async()=>{const tag=`training-${Date.now()}`;[org,other]=await Promise.all([db.organization.create({data:{legalName:"Training Org",displayName:"Training Org",slug:`${tag}-a`}}),db.organization.create({data:{legalName:"Other Org",displayName:"Other Org",slug:`${tag}-b`}})]);[admin,learner,otherUser]=await Promise.all(["admin","learner","other"].map(x=>db.user.create({data:{email:`${tag}-${x}@example.test`,status:"ACTIVE"}})));employee=await db.employee.create({data:{organizationId:org.id,userId:learner.id,firstName:"Learn",lastName:"Er",employmentStatus:"ACTIVE"}});const perm=await db.permission.upsert({where:{code:"training.assignment.manage"},update:{},create:{code:"training.assignment.manage"}}),read=await db.permission.upsert({where:{code:"employee.read"},update:{},create:{code:"employee.read"}}),role=await db.roleDefinition.create({data:{code:`TRAIN-${tag}`,name:"Training admin",scope:"PLATFORM",isPlatformStandard:true,permissions:{create:[{permissionId:perm.id},{permissionId:read.id}]}}});await db.organizationMembership.create({data:{organizationId:org.id,userId:admin.id,status:"ACTIVE",roles:{create:{roleDefinitionId:role.id}}}});await db.organizationMembership.create({data:{organizationId:org.id,userId:learner.id,status:"ACTIVE"}});await db.organizationMembership.create({data:{organizationId:org.id,userId:otherUser.id,status:"ACTIVE"}});
const course=await db.trainingCourse.create({data:{catalogKey:`org:${tag}`,organizationId:org.id,code:"TEST",title:"Test course",category:"TEST",ownershipType:"ORGANIZATION"}});draft=(await db.trainingCourseVersion.create({data:{courseId:course.id,versionNumber:1,status:"DRAFT",effectiveFrom:new Date("2026-01-01"),contentHash:"draft"}})).id;published=await db.trainingCourseVersion.create({data:{courseId:course.id,versionNumber:2,status:"PUBLISHED",effectiveFrom:new Date("2026-01-01"),publishedAt:new Date(),contentHash:"published-v2",modules:{create:{sequence:1,title:"Required",moduleType:"MIXED",required:true,contentItems:{create:[{sequence:1,contentType:"WRITTEN",required:true,payload:{body:"Demo"}},{sequence:2,contentType:"WRITTEN",required:false,payload:{body:"Optional"}},{sequence:3,contentType:"ACKNOWLEDGMENT",required:true,payload:{statement:"Reviewed"}}]},assessments:{create:{versionNumber:1,title:"Quiz",passingScore:50,maxAttempts:2,status:"PUBLISHED",questions:{create:[{sequence:1,questionType:"SINGLE_CHOICE",prompt:"Choose A",points:1,options:{create:[{sequence:1,text:"A",isCorrect:true},{sequence:2,text:"B",isCorrect:false}]}},{sequence:2,questionType:"TRUE_FALSE",prompt:"True?",points:1,options:{create:[{sequence:1,text:"True",isCorrect:true},{sequence:2,text:"False",isCorrect:false}]}}]}}}}}}});const detail=await db.trainingCourseVersion.findUniqueOrThrow({where:{id:published.id},include:{modules:{include:{contentItems:true,assessments:{include:{questions:{include:{options:true}}}}}}}}),items=detail.modules[0].contentItems;written=items.find(i=>i.sequence===1)!.id;optional=items.find(i=>i.sequence===2)!.id;ack=items.find(i=>i.sequence===3)!.id;assessment=detail.modules[0].assessments[0].id;correct=detail.modules[0].assessments[0].questions.map(q=>q.options.find(o=>o.isCorrect)!.id);wrong=detail.modules[0].assessments[0].questions.map(q=>q.options.find(o=>!o.isCorrect)!.id)});
describe.sequential("training execution",()=>{
it("draft versions cannot be assigned",async()=>await expect(createManualAssignment(admin,org.id,{employeeId:employee.id,courseVersionId:draft})).rejects.toBeInstanceOf(AuthorizationError));
it("published versions can be manually assigned with permission",async()=>{assignment=await createManualAssignment(admin,org.id,{employeeId:employee.id,courseVersionId:published.id});expect(assignment.sourceType).toBe("MANUAL")});
it("published versions cannot be mutated silently",async()=>await expect(updateCourseVersion(published.id,{contentHash:"changed"})).rejects.toThrow("immutable"));
it("organization curriculum cannot be assigned cross-tenant",async()=>{const e=await db.employee.create({data:{organizationId:other.id,firstName:"Other",lastName:"Employee"}});await expect(createManualAssignment(admin,org.id,{employeeId:e.id,courseVersionId:published.id})).rejects.toThrow()});
it("employee self access cannot be spoofed",async()=>await expect(requireEmployeeSelfAccess(otherUser,org.id,employee.id)).rejects.toBeInstanceOf(AuthorizationError));
it("learner detail never exposes correctness markers",async()=>expect(JSON.stringify(await getAssignment(org.id,employee.id,assignment.id))).not.toContain("isCorrect"));
it("learner cannot submit score or pass results",()=>expect(()=>assessmentSubmissionSchema.parse({score:100,passed:true,responses:[]})).toThrow());
it("required content and acknowledgment block completion",async()=>expect(await deriveAndCreateCompletion(assignment.id)).toBeNull());
it("required progress is idempotent and optional content does not block",async()=>{await completeContent(assignment.id,employee.id,written);await completeContent(assignment.id,employee.id,written);expect(await db.trainingContentProgress.count({where:{assignmentId:assignment.id,contentItemId:written}})).toBe(1);expect(await deriveAndCreateCompletion(assignment.id)).toBeNull();expect(optional).toBeTruthy()});
it("acknowledgment is durable and idempotent",async()=>{await acknowledgeContent(assignment.id,employee.id,learner.id,ack);await acknowledgeContent(assignment.id,employee.id,learner.id,ack);expect(await db.trainingAcknowledgment.count({where:{assignmentId:assignment.id,contentItemId:ack}})).toBe(1)});
it("server grades attempts and ignores spoofed score/pass fields",async()=>{const attempt=await startAttempt(assignment.id,employee.id,assessment),questions=(await db.assessment.findUniqueOrThrow({where:{id:assessment},include:{questions:true}})).questions;const result=await submitAttempt(attempt.id,employee.id,{responses:questions.map((q,i)=>({questionId:q.id,selectedOptionIds:[wrong[i]]}))});expect(result.passed).toBe(false);expect(Number(result.score)).toBe(0);expect(await deriveAndCreateCompletion(assignment.id)).toBeNull()});
it("passing retry satisfies assessment and completes exactly once",async()=>{const attempt=await startAttempt(assignment.id,employee.id,assessment),questions=(await db.assessment.findUniqueOrThrow({where:{id:assessment},include:{questions:true}})).questions;const result=await submitAttempt(attempt.id,employee.id,{responses:questions.map((q,i)=>({questionId:q.id,selectedOptionIds:[correct[i]]}))});expect(result.passed).toBe(true);const first=await deriveAndCreateCompletion(assignment.id),second=await deriveAndCreateCompletion(assignment.id);expect(first?.id).toBe(second?.id);expect(first?.courseVersionId).toBe(published.id);expect(first?.contentHash).toBe("published-v2");expect(await db.trainingCompletion.count({where:{assignmentId:assignment.id}})).toBe(1)});
it("max attempt policy prevents another retry",async()=>await expect(startAttempt(assignment.id,employee.id,assessment)).rejects.toThrow("Maximum attempts"));
it("a new version does not rewrite historical completion",async()=>{await db.trainingCourseVersion.create({data:{courseId:published.courseId,versionNumber:3,status:"PUBLISHED",effectiveFrom:new Date("2027-01-01"),contentHash:"v3"}});expect((await db.trainingCompletion.findUniqueOrThrow({where:{assignmentId:assignment.id}})).courseVersionId).toBe(published.id)});
});

describe("compliance training integration",()=>{
  async function fixture(competency:boolean){const tag=`mapping-${Date.now()}-${Math.random()}`,course=await db.trainingCourse.create({data:{catalogKey:tag,code:tag,title:"Mapped",category:"TEST",ownershipType:"PLATFORM"}}),cv=await db.trainingCourseVersion.create({data:{courseId:course.id,versionNumber:1,status:"PUBLISHED",effectiveFrom:new Date("2026-01-01"),publishedAt:new Date(),contentHash:tag}}),req=await db.complianceRequirement.create({data:{code:tag,name:"Mapped requirement",licenseType:"MN_144G",requirementCategory:"WORKFORCE"}}),rv=await db.complianceRequirementVersion.create({data:{requirementId:req.id,versionNumber:1,effectiveFrom:new Date("2026-01-01"),verificationStatus:"PRIMARY_SOURCE_VERIFIED",status:"ACTIVE",applicabilityDefinition:{schemaVersion:1,all:[{type:"ALWAYS"}]},triggerDefinition:{schemaVersion:1,type:"FIXED_REQUIREMENT",fixedAt:"2026-01-01T00:00:00Z"},deadlineDefinition:{schemaVersion:1,type:"NO_FIXED_DEADLINE"},competencyDefinition:competency?{schemaVersion:1,type:"REQUIRED",requirements:["OBSERVED_SKILL"]}:{schemaVersion:1,type:"NONE"},trainingOptions:{create:{trainingCourseVersionId:cv.id,satisfactionType:competency?"TRAINING_AND_COMPETENCY":"TRAINING_ONLY",isDefault:true}}}}),rs=await db.complianceRuleset.create({data:{licenseType:"MN_144G",version:Math.floor(Date.now()/1000)+Math.floor(Math.random()*1000),effectiveFrom:new Date("2026-01-01"),status:"ACTIVE"}}),ci=await db.complianceInstance.create({data:{fingerprint:tag,organizationId:org.id,employeeId:employee.id,requirementVersionId:rv.id,triggerType:"FIXED_REQUIREMENT",requiredAt:new Date("2026-01-01"),status:"REQUIRED",lastEvaluatedAt:new Date(),rulesetId:rs.id}});return{ci,cv}}
  it("creates one idempotent assignment from a mapped compliance instance",async()=>{const f=await fixture(false),a=await assignTrainingForCompliance(f.ci.id),b=await assignTrainingForCompliance(f.ci.id);expect(a?.id).toBe(b?.id);expect(a?.sourceType).toBe("COMPLIANCE_ENGINE")});
  it("mapped training-only completion satisfies compliance",async()=>{const f=await fixture(false),a=await assignTrainingForCompliance(f.ci.id);await deriveAndCreateCompletion(a!.id);expect((await db.complianceInstance.findUniqueOrThrow({where:{id:f.ci.id}})).status).toBe("SATISFIED")});
  it("competency requirements stop at training complete pending validation",async()=>{const f=await fixture(true),a=await assignTrainingForCompliance(f.ci.id);await deriveAndCreateCompletion(a!.id);expect((await db.trainingAssignment.findUniqueOrThrow({where:{id:a!.id}})).status).toBe("TRAINING_COMPLETE_COMPETENCY_PENDING");expect((await db.complianceInstance.findUniqueOrThrow({where:{id:f.ci.id}})).status).toBe("REQUIRED")});
});
