import { beforeAll, describe, expect, it } from "vitest";
import { PrismaClient } from "@prisma/client";
import { createExternalTrainingRecord } from "@/domain/evidence/service";
import { getEmployerDashboard } from "@/domain/admin/service";
import { getOrganizationSetup } from "@/domain/organization-setup/service";
import { createEmployee } from "@/domain/workforce/service";
import { bulkInviteEmployees, confirmWorkforceImport, getWorkforceOnboardingStatus, initializeApplicableTraining, previewWorkforceCsv, workforceCsvTemplate } from "@/domain/workforce/import-service";

const db=new PrismaClient(),header="employee_number,first_name,last_name,email,hire_date,employment_status,job_title,employment_type";
describe.sequential("Phase 16 production workforce onboarding",()=>{
 let organizationId:string,otherOrganizationId:string,ownerId:string,employeeUserId:string,importedId:string,noDateId:string;
 const owner=()=>({id:ownerId}),employee=()=>({id:employeeUserId});
 beforeAll(async()=>{const tag=`phase16-${Date.now()}`,[ownerUser,ownerRole,other,ruleset]=await Promise.all([db.user.findUniqueOrThrow({where:{email:"alex.owner@example.test"}}),db.roleDefinition.findFirstOrThrow({where:{organizationId:null,code:"ORGANIZATION_OWNER"}}),db.organization.findFirstOrThrow({where:{slug:"lakeside-community-services"}}),db.complianceRuleset.findFirstOrThrow({where:{licenseType:"MN_245D",status:"ACTIVE"}})]);ownerId=ownerUser.id;otherOrganizationId=other.id;expect(ruleset.approvedAt).not.toBeNull();const org=await db.organization.create({data:{legalName:tag,displayName:tag,slug:tag,email:`${tag}@example.test`,phone:"651-555-0100",licenses:{create:{licenseType:"MN_245D",licenseStatus:"ACTIVE",effectiveDate:new Date("2020-01-01")}}}});organizationId=org.id;const membership=await db.organizationMembership.create({data:{organizationId,userId:ownerId,status:"ACTIVE"}});await db.membershipRole.create({data:{membershipId:membership.id,roleDefinitionId:ownerRole.id}});const user=await db.user.create({data:{email:`ordinary-${tag}@example.test`,status:"ACTIVE"}});employeeUserId=user.id;await db.organizationMembership.create({data:{organizationId,userId:user.id,status:"ACTIVE"}})});

 it("provides a deterministic, minimal CSV template",()=>{expect(workforceCsvTemplate.startsWith(header)).toBe(true);expect(workforceCsvTemplate).not.toMatch(/ssn|password|admin|medCertified/i)});
 it("previews valid historical and missing-date employees without persisting",async()=>{const csv=`${header}\nP16-001,Historical,Worker,historical-${Date.now()}@example.test,2020-03-15,ACTIVE,DSP,FULL_TIME\nP16-002,Date,Unknown,, ,PENDING,,PART_TIME`;const preview=await previewWorkforceCsv(owner(),organizationId,csv);expect(preview.counts.READY).toBe(2);expect(await db.employee.count({where:{organizationId}})).toBe(0)});
 it("classifies invalid dates, emails, duplicate rows, malformed input, and unsafe cells",async()=>{const invalid=`${header}\nP16-X,=CMD,Worker,not-email,2024-99-99,ACTIVE,DSP,FULL_TIME\nP16-D,Safe,Worker,safe@example.test,2024-01-01,ACTIVE,DSP,FULL_TIME\nP16-D,Safe,Duplicate,second@example.test,2024-01-01,ACTIVE,DSP,FULL_TIME`;const preview=await previewWorkforceCsv(owner(),organizationId,invalid);expect(preview.counts.INVALID).toBe(1);expect(preview.counts.DUPLICATE).toBe(1);await expect(previewWorkforceCsv(owner(),organizationId,`${header}\n"unclosed`)).rejects.toThrow(/unclosed/);await expect(previewWorkforceCsv(owner(),organizationId,"first_name,last_name\nA,B")).rejects.toThrow(/Unexpected CSV columns/)});
 it("rejects a mixed invalid batch atomically",async()=>{const csv=`${header}\nP16-ATOMIC,Valid,Row,valid-${Date.now()}@example.test,2022-01-01,ACTIVE,DSP,FULL_TIME\n,Missing,,bad,not-a-date,ACTIVE,,`;await expect(confirmWorkforceImport(owner(),organizationId,csv)).rejects.toThrow(/requiring correction/);expect(await db.employee.findFirst({where:{organizationId,employeeNumber:"P16-ATOMIC"}})).toBeNull()});
 it("confirms safely, retains historical dates, and is repeat-idempotent",async()=>{const stamp=Date.now(),csv=`${header}\nP16-001,Historical,Worker,historical-${stamp}@example.test,2020-03-15,ACTIVE,DSP,FULL_TIME\nP16-002,Date,Unknown,nodate-${stamp}@example.test,,PENDING,,PART_TIME`;const first=await confirmWorkforceImport(owner(),organizationId,csv);expect(first.counts.created).toBe(2);importedId=first.created[0].id;noDateId=first.created[1].id;expect((await db.employee.findUniqueOrThrow({where:{id:importedId}})).hireDate?.toISOString()).toContain("2020-03-15");expect((await db.employee.findUniqueOrThrow({where:{id:noDateId}})).hireDate).toBeNull();const second=await confirmWorkforceImport(owner(),organizationId,csv);expect(second.counts).toEqual({created:0,alreadyExisting:2});expect(await db.employee.count({where:{organizationId}})).toBe(2)});
 it("protects manual creation with the same identifier conflict boundary",async()=>{await expect(createEmployee(owner(),organizationId,{employeeNumber:"P16-001",firstName:"Other",lastName:"Person"})).rejects.toThrow(/conflicts/);const manual=await createEmployee(owner(),organizationId,{employeeNumber:"P16-003",firstName:"Manual",lastName:"Person",hireDate:"2023-01-02",employmentStatus:"ACTIVE"});expect(manual.userId).toBeNull()});
 it("detects existing and conflicting workforce rows without cross-tenant disclosure",async()=>{const existing=await db.employee.findUniqueOrThrow({where:{id:importedId}}),same=`${header}\nP16-001,Historical,Worker,${existing.email},2020-03-15,ACTIVE,DSP,FULL_TIME`,conflict=`${header}\nP16-001,Different,Name,new-${Date.now()}@example.test,2020-03-15,ACTIVE,DSP,FULL_TIME`;expect((await previewWorkforceCsv(owner(),organizationId,same)).counts.ALREADY_EXISTS).toBe(1);expect((await previewWorkforceCsv(owner(),organizationId,conflict)).counts.CONFLICT).toBe(1)});
 it("bulk-invites eligible employees once without linking accounts automatically",async()=>{const first=await bulkInviteEmployees(owner(),organizationId,[importedId,noDateId]);expect(first.every(row=>row.status==="INVITED")).toBe(true);const second=await bulkInviteEmployees(owner(),organizationId,[importedId,noDateId]);expect(second.every(row=>row.status==="SKIPPED")).toBe(true);expect(await db.employeePortalInvitation.count({where:{organizationId,employeeId:{in:[importedId,noDateId]}}})).toBe(2);expect((await db.employee.findUniqueOrThrow({where:{id:importedId}})).userId).toBeNull()});
 it("initializes applicable training and reconciliation idempotently without completion",async()=>{const duty=await db.dutyDefinition.findUniqueOrThrow({where:{code:"DIRECT_SUPPORT"}});await db.employeeDuty.create({data:{employeeId:importedId,dutyDefinitionId:duty.id,effectiveFrom:new Date("2020-03-15")}});const first=await initializeApplicableTraining(owner(),organizationId,[importedId]),count=await db.trainingAssignment.count({where:{organizationId,employeeId:importedId}});expect(first[0].requirements).toBeGreaterThan(0);expect(count).toBeGreaterThan(0);const issues=await db.complianceIssue.count({where:{organizationId,employeeId:importedId}});const second=await initializeApplicableTraining(owner(),organizationId,[importedId]);expect(second[0].assignmentsCreated).toBe(0);expect(await db.trainingAssignment.count({where:{organizationId,employeeId:importedId}})).toBe(count);expect(await db.complianceIssue.count({where:{organizationId,employeeId:importedId}})).toBe(issues);expect(await db.trainingCompletion.count({where:{organizationId,employeeId:importedId}})).toBe(0)});
 it("integrates prior evidence without auto-verification or clinical/service grants",async()=>{const evidence=await createExternalTrainingRecord(ownerId,organizationId,{employeeId:importedId,providerName:"Prior Provider",trainingName:"Documented prior course",trainingDate:new Date("2021-06-01"),evidenceReference:"secure-document-reference"});expect(evidence.reviewStatus).not.toBe("APPROVED");expect(await db.medicationQualification.count({where:{organizationId,employeeId:importedId}})).toBe(0);expect(await db.medicationAuthorizationEvidence.count({where:{organizationId,employeeId:importedId}})).toBe(0);expect(await db.serviceAssignment.count({where:{organizationId,employeeId:importedId}})).toBe(0);expect((await getWorkforceOnboardingStatus(owner(),organizationId)).find(row=>row.id===importedId)?.evidenceReview).toBe(1)});
 it("rejects tenant crossover and ordinary employee bulk administration",async()=>{const foreign=await db.employee.findFirstOrThrow({where:{organizationId:otherOrganizationId}});await expect(previewWorkforceCsv(owner(),otherOrganizationId,workforceCsvTemplate)).rejects.toThrow();await expect(confirmWorkforceImport(owner(),otherOrganizationId,workforceCsvTemplate)).rejects.toThrow();await expect(bulkInviteEmployees(owner(),organizationId,[foreign.id])).rejects.toThrow(/invalid for this organization/);await expect(initializeApplicableTraining(owner(),organizationId,[foreign.id])).rejects.toThrow(/invalid for this organization/);await expect(previewWorkforceCsv(employee(),organizationId,workforceCsvTemplate)).rejects.toThrow(/employee.manage/);await expect(bulkInviteEmployees(employee(),organizationId,[importedId])).rejects.toThrow(/employee.manage/);await expect(initializeApplicableTraining(employee(),organizationId,[importedId])).rejects.toThrow(/training.assignment.manage/)});
 it("does not import privileges or evidence and keeps existing admin/setup flows functional",async()=>{expect(await db.membershipRole.count({where:{membership:{organizationId,userId:employeeUserId}}})).toBe(0);expect(await db.trainingCompletion.count({where:{organizationId}})).toBe(0);expect(await db.attestation.count({where:{organizationId}})).toBe(0);expect((await getEmployerDashboard(owner(),organizationId)).activeWorkforce).toBeGreaterThan(0);expect((await getOrganizationSetup(owner(),organizationId)).readiness.operationallyReady).toBe(true);expect(await db.auditEvent.count({where:{organizationId,eventType:{in:["workforce.import_completed","workforce.bulk_invitations_issued","workforce.training_initialization_completed"]}}})).toBeGreaterThanOrEqual(3)});
});
