import { z } from "zod";
import { requireAuthenticatedUser } from "@/domain/auth/authentication";
import { errorResponse } from "@/domain/auth/errors";
import { listComplianceIssues, reconcileEmployeeIssues, reconcileOrganizationIssues } from "@/domain/compliance-issues/service";
import { enforceRateLimit,requestRateKey } from "@/lib/rate-limit";

const issueType = z.enum(["TRAINING_REQUIRED", "TRAINING_OVERDUE", "COMPETENCY_REQUIRED", "CREDENTIAL_INVALID", "CREDENTIAL_EXPIRING", "POLICY_ACKNOWLEDGMENT_REQUIRED", "ONBOARDING_INCOMPLETE", "PERSON_SPECIFIC_INSTRUCTION_REQUIRED", "MEDICATION_QUALIFICATION_INCOMPLETE", "MEDICATION_AUTHORIZATION_MISSING", "CLINICAL_SIGNOFF_REQUIRED", "ASSIGNMENT_BLOCKED", "ACTIVE_ASSIGNMENT_BECAME_BLOCKED"]);
const priority = z.enum(["LOW", "NORMAL", "MEDIUM", "HIGH", "CRITICAL"]), status = z.enum(["OPEN", "IN_PROGRESS", "RESOLVED"]);
type Context = { params: Promise<{ organizationId: string }> };
export async function GET(request: Request, context: Context) { try { const user = await requireAuthenticatedUser(request), { organizationId } = await context.params, query = new URL(request.url).searchParams; return Response.json(await listComplianceIssues(user, organizationId, { status: query.get("status") ? status.parse(query.get("status")) : undefined, employeeId: query.get("employeeId") ?? undefined, issueType: query.get("issueType") ? issueType.parse(query.get("issueType")) : undefined, priority: query.get("priority") ? priority.parse(query.get("priority")) : undefined, overdue: query.get("overdue") === "true", upcoming: query.get("upcoming") === "true", medication: query.get("medication") === "true", personSpecific: query.get("personSpecific") === "true", assignmentRelated: query.get("assignmentRelated") === "true" })); } catch (error) { return errorResponse(error); } }
export async function POST(request: Request, context: Context) { try { const user = await requireAuthenticatedUser(request), { organizationId } = await context.params;await enforceRateLimit("compliance-reconcile",requestRateKey(request,user.id),10,60);const body = z.object({ employeeId: z.string().cuid().optional(), evaluatedAt: z.coerce.date().optional() }).parse(await request.json()), at = body.evaluatedAt ?? new Date(); return Response.json(body.employeeId ? await reconcileEmployeeIssues(user, organizationId, body.employeeId, at) : await reconcileOrganizationIssues(user, organizationId, at)); } catch (error) { return errorResponse(error); } }
