import { GetSecretValueCommand, SecretsManagerClient } from "@aws-sdk/client-secrets-manager";

const EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const CODE=/^[A-Z0-9_]+$/;
const CLASSIFICATIONS=new Set(["DEFINITIVELY_NOT_ACCEPTED","RETRYABLE_TRANSPORT_FAILURE","CAPACITY_OR_QUOTA_FAILURE","AMBIGUOUS_OUTCOME","PERMANENT_RECIPIENT_FAILURE","POLICY_OR_VALIDATION_FAILURE","AUTH_OR_CONFIGURATION_FAILURE"]);
function exactKeys(value,allowed){return value&&typeof value==="object"&&!Array.isArray(value)&&Object.keys(value).every(key=>allowed.includes(key))}
function text(value,min,max){return typeof value==="string"&&value.length>=min&&value.length<=max&&!/[\r\n]/.test(value)}
function email(value){return typeof value==="string"&&value.length<=320&&EMAIL.test(value)}
function result(accepted,value={}){return accepted?{accepted:true,messageId:value.messageId,acceptedAt:new Date().toISOString()}:{accepted:false,code:CODE.test(value.code??"")?value.code:"MAILGUN_PROVIDER_FAILURE",retryable:Boolean(value.retryable),classification:CLASSIFICATIONS.has(value.classification)?value.classification:"DEFINITIVELY_NOT_ACCEPTED"}}
function log(entry){console.log(JSON.stringify({timestamp:new Date().toISOString(),operation:"mailgun-transactional-email",...entry}))}
function failure(status){if(status===401||status===403)return{code:"MAILGUN_AUTHENTICATION_REJECTED",retryable:false,classification:"AUTH_OR_CONFIGURATION_FAILURE"};if(status===404)return{code:"MAILGUN_DOMAIN_UNAVAILABLE",retryable:false,classification:"AUTH_OR_CONFIGURATION_FAILURE"};if(status===429)return{code:"MAILGUN_CAPACITY_OR_QUOTA",retryable:true,classification:"CAPACITY_OR_QUOTA_FAILURE"};if(status>=500)return{code:"MAILGUN_TEMPORARY_FAILURE",retryable:true,classification:"RETRYABLE_TRANSPORT_FAILURE"};if(status===400||status===422)return{code:"MAILGUN_POLICY_OR_VALIDATION_REJECTION",retryable:false,classification:"POLICY_OR_VALIDATION_FAILURE"};return{code:"MAILGUN_DEFINITIVE_REJECTION",retryable:false,classification:"DEFINITIVELY_NOT_ACCEPTED"}}

export function createHandler({secrets=new SecretsManagerClient({}),fetchImpl=fetch,environment=process.env,logger=log}={}){
  let credential;
  const configured=()=>{const base=environment.MAILGUN_API_BASE_URL,domain=environment.MAILGUN_DOMAIN,from=environment.MAILGUN_FROM;if(!base||!/^https:\/\/api(?:\.eu)?\.mailgun\.net$/.test(base)||!domain||!/^([a-z0-9-]+\.)+[a-z]{2,}$/i.test(domain)||!email(from)||!from.toLowerCase().endsWith(`@${domain.toLowerCase()}`))throw new Error("CONFIGURATION_UNAVAILABLE");return{base,domain,from}};
  async function apiKey(){if(credential)return credential;if(!environment.MAILGUN_SECRET_ID)throw new Error("CONFIGURATION_UNAVAILABLE");const response=await secrets.send(new GetSecretValueCommand({SecretId:environment.MAILGUN_SECRET_ID})),value=response.SecretString?.trim();if(!value||value.length<20)throw new Error("CONFIGURATION_UNAVAILABLE");credential=value;return credential}
  return async function handler(event,context={}){const requestId=context.awsRequestId??"unavailable";let message,config;try{config=configured();if(!exactKeys(event,["version","from","fromName","replyTo","to","subject","text","html"])||event.version!==1||event.from!==config.from||!email(event.to)||!text(event.subject,1,200)||typeof event.text!=="string"||event.text.length<1||event.text.length>100_000||("fromName" in event&&!text(event.fromName,1,200))||("replyTo" in event&&!email(event.replyTo))||("html" in event&&(typeof event.html!=="string"||event.html.length<1||event.html.length>200_000)))throw new Error("INVALID_REQUEST");message=event}catch(error){const configuration=error?.message==="CONFIGURATION_UNAVAILABLE";logger({level:"warn",outcome:"rejected",requestId,errorCode:configuration?"MAILGUN_CONFIGURATION_UNAVAILABLE":"MAILGUN_REQUEST_INVALID"});return result(false,{code:configuration?"MAILGUN_CONFIGURATION_UNAVAILABLE":"MAILGUN_REQUEST_INVALID",retryable:false,classification:configuration?"AUTH_OR_CONFIGURATION_FAILURE":"POLICY_OR_VALIDATION_FAILURE"})}
    try{const key=await apiKey(),form=new FormData();form.set("from",message.fromName?`${message.fromName} <${message.from}>`:message.from);form.set("to",message.to);form.set("subject",message.subject);form.set("text",message.text);if(message.html)form.set("html",message.html);if(message.replyTo)form.set("h:Reply-To",message.replyTo);form.set("o:tracking","no");form.set("o:tracking-clicks","no");form.set("o:tracking-opens","no");const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),8_000);let response;try{response=await fetchImpl(`${config.base}/v3/${encodeURIComponent(config.domain)}/messages`,{method:"POST",headers:{authorization:`Basic ${Buffer.from(`api:${key}`).toString("base64")}`},body:form,signal:controller.signal})}finally{clearTimeout(timeout)}if(!response.ok){const normalized=failure(response.status);logger({level:"warn",outcome:"provider-rejected",requestId,errorCode:normalized.code,providerStatus:response.status});return result(false,normalized)}let body;try{body=await response.json()}catch{body=null}if(!body||typeof body.id!=="string"||body.id.length<1||body.id.length>300){logger({level:"error",outcome:"malformed-response",requestId,errorCode:"MAILGUN_RESPONSE_INVALID"});return result(false,{code:"MAILGUN_RESPONSE_INVALID",retryable:false,classification:"AMBIGUOUS_OUTCOME"})}logger({level:"info",outcome:"accepted",requestId});return result(true,{messageId:body.id})}catch(error){const timeout=error?.name==="AbortError",configuration=error?.message==="CONFIGURATION_UNAVAILABLE";logger({level:"error",outcome:"dependency-failed",requestId,errorCode:configuration?"MAILGUN_CONFIGURATION_UNAVAILABLE":timeout?"MAILGUN_TIMEOUT":"MAILGUN_TRANSPORT_UNKNOWN"});return result(false,{code:configuration?"MAILGUN_CONFIGURATION_UNAVAILABLE":timeout?"MAILGUN_TIMEOUT":"MAILGUN_TRANSPORT_UNKNOWN",retryable:false,classification:configuration?"AUTH_OR_CONFIGURATION_FAILURE":"AMBIGUOUS_OUTCOME"})}}
}
export const handler=createHandler();
