import { Prisma, PrismaClient } from "@prisma/client";
const db = new PrismaClient();
const permissionCodes = ["organization.read","organization.manage","employee.read","employee.manage","training.read","training.manage","recipient.read","recipient.readSensitive","recipient.readDocuments","recipient.uploadDocuments","recipient.assignStaff","clinical.review","medication.approve","audit.read"];
const dutyRows = [
  ["DIRECT_SUPPORT","Direct support"],["UNSUPERVISED_DIRECT_CONTACT","Unsupervised direct contact"],["MEDICATION_ADMINISTRATION","Medication administration"],
  ["MEDICATION_SETUP","Medication setup"],["TRANSPORTATION","Transportation"],["MEAL_PREPARATION","Meal preparation"],["POSITIVE_SUPPORT_IMPLEMENTATION","Positive support implementation"],
  ["MEDICAL_EQUIPMENT_SUPPORT","Medical equipment support"],["SUPERVISION","Supervision"],
] as const;
const roleMap: Record<string,string[]> = {
  ORGANIZATION_OWNER: permissionCodes, COMPLIANCE_ADMIN:["organization.read","employee.read","employee.manage","training.read","training.manage","audit.read"],
  TRAINING_ADMIN:["organization.read","employee.read","training.read","training.manage"], PROGRAM_MANAGER:["organization.read","employee.read","employee.manage","training.read"],
  SUPERVISOR:["organization.read","employee.read","training.read"], CLINICAL_RN:["organization.read","employee.read","clinical.review","medication.approve"],
  TRAINER:["organization.read","employee.read","training.read","training.manage"], DSP:["organization.read","training.read"], AUDITOR:["organization.read","employee.read","training.read","audit.read"],
};
const regulatorySources = [
  ["245D.09","Staff qualifications and orientation","https://www.revisor.mn.gov/statutes/cite/245D.09"],
  ["245D.095","License holder requirements","https://www.revisor.mn.gov/statutes/cite/245D.095"],
  ["245D.05","Health services","https://www.revisor.mn.gov/statutes/cite/245D.05"], ["245D.04","Protection standards","https://www.revisor.mn.gov/statutes/cite/245D.04"],
  ["245D.06","Protection standards","https://www.revisor.mn.gov/statutes/cite/245D.06"], ["245D.061","Incident response","https://www.revisor.mn.gov/statutes/cite/245D.061"],
  ["245D.07","Service planning","https://www.revisor.mn.gov/statutes/cite/245D.07"], ["245D.11","Policies and procedures","https://www.revisor.mn.gov/statutes/cite/245D.11"],
  ["245A.65","Maltreatment reporting","https://www.revisor.mn.gov/statutes/cite/245A.65"], ["626.557","Vulnerable adults reporting","https://www.revisor.mn.gov/statutes/cite/626.557"],
] as const;
const requirementNames = ["Staff Qualifications and Competency","Job Description and Job-Function Orientation","Incident Reporting","Safety Practices","License Holder Policies and Procedures","Data Privacy and Confidentiality","Service Recipient Rights","Maltreatment and Mandated Reporting","Person-Centered Service Planning and Delivery","Emergency Manual Restraint and Restraint Awareness","Prohibited Procedures","Basic First Aid","Healthy Relationships, Consent, Bodily Autonomy and Sexual Violence Risk Reduction","Other Topics Required by Support Plan, Case Manager or License Holder","Annual 245D Refresher Bundle","External Prior Training Equivalency","Periodic Performance Evaluation","Temporary and Subcontract Staff Compliance","Volunteer Direct-Support Training"];
async function seedRegulatory(northstarId:string,lakesideId:string){
  const authority=await db.regulatoryAuthority.upsert({where:{jurisdiction_agency_name:{jurisdiction:"Minnesota",agency:"Minnesota Legislature / Revisor",name:"Minnesota Revisor of Statutes"}},update:{},create:{jurisdiction:"Minnesota",agency:"Minnesota Legislature / Revisor",name:"Minnesota Revisor of Statutes",sourceUrl:"https://www.revisor.mn.gov/statutes/"}});
  await db.regulatoryAuthority.upsert({where:{jurisdiction_agency_name:{jurisdiction:"Minnesota",agency:"Department of Human Services",name:"Minnesota Department of Human Services"}},update:{},create:{jurisdiction:"Minnesota",agency:"Department of Human Services",name:"Minnesota Department of Human Services",sourceUrl:"https://mn.gov/dhs/"}});
  const versions=new Map<string,string>();for(const [citation,title,url] of regulatorySources){const regulation=await db.regulation.upsert({where:{authorityId_citation:{authorityId:authority.id,citation}},update:{title},create:{authorityId:authority.id,citation,title}});let version=await db.regulationVersion.findFirst({where:{regulationId:regulation.id,effectiveFrom:new Date("2026-08-01T00:00:00Z")}});version??=await db.regulationVersion.create({data:{regulationId:regulation.id,effectiveFrom:new Date("2026-08-01T00:00:00Z"),sourceUrl:url,verificationStatus:"PRIMARY_SOURCE_VERIFIED",verifiedAt:new Date(),status:"ACTIVE"}});versions.set(citation,version.id)}
  const ruleset=await db.complianceRuleset.upsert({where:{licenseType_version:{licenseType:"MN_245D",version:1}},update:{},create:{licenseType:"MN_245D",version:1,effectiveFrom:new Date("2026-08-01T00:00:00Z"),status:"ACTIVE",approvedAt:new Date(),contentHash:"frozen-phase-0-v1"}});
  const executable=new Set([1,2,3,4,5,6,7,8,9,10,11,12,13,17,18,19]);
  for(let n=1;n<=19;n++){const code=`245D-WF-${String(n).padStart(3,"0")}`, requirement=await db.complianceRequirement.upsert({where:{code},update:{name:requirementNames[n-1]},create:{code,name:requirementNames[n-1],licenseType:"MN_245D",requirementCategory:"WORKFORCE"}});let rv=await db.complianceRequirementVersion.findUnique({where:{requirementId_versionNumber:{requirementId:requirement.id,versionNumber:1}}});if(!rv){
    const base={schemaVersion:1,all:[{type:"ORGANIZATION_LICENSE",licenseType:"MN_245D"},{type:"EMPLOYEE_DUTY_ANY",duties:["DIRECT_SUPPORT"]}]};let applicability:Prisma.InputJsonValue=base, trigger:Prisma.InputJsonValue={schemaVersion:1,type:"EMPLOYEE_HIRED"},deadline:Prisma.InputJsonValue={schemaVersion:1,type:"WITHIN_CALENDAR_DAYS",days:60};const recurrence:Prisma.InputJsonValue={schemaVersion:1,type:(n>=6&&n<=13)?"ANNUAL":"NONE"},grace:Prisma.InputJsonValue=(n>=6&&n<=13)?{schemaVersion:1,type:"CALENDAR_DAYS_AFTER_NOMINAL_DUE",days:90,effectiveFrom:"2026-08-01",appliesTo:"ANNUAL_ONLY"}:{schemaVersion:1,type:"NONE"};
    if([1,14,15,16,17].includes(n)){trigger={schemaVersion:1,type:"FIXED_REQUIREMENT"};deadline={schemaVersion:1,type:"NO_FIXED_DEADLINE"}} if(n===8){trigger={schemaVersion:1,type:"FIRST_DIRECT_CONTACT"};deadline={schemaVersion:1,type:"WITHIN_HOURS",hours:72}} if(n===18)applicability={schemaVersion:1,all:[{type:"ORGANIZATION_LICENSE",licenseType:"MN_245D"},{type:"EMPLOYMENT_TYPE",employmentTypes:["TEMPORARY","CONTRACTOR"]}]};if(n===19)applicability={schemaVersion:1,all:[{type:"ORGANIZATION_LICENSE",licenseType:"MN_245D"},{type:"EMPLOYMENT_TYPE",employmentTypes:["VOLUNTEER"]},{type:"EMPLOYEE_DUTY",duty:"DIRECT_SUPPORT"}]};
    rv=await db.complianceRequirementVersion.create({data:{requirementId:requirement.id,versionNumber:1,effectiveFrom:new Date("2026-08-01T00:00:00Z"),verificationStatus:"PRIMARY_SOURCE_VERIFIED",status:"ACTIVE",applicabilityDefinition:applicability,triggerDefinition:trigger,deadlineDefinition:deadline,recurrenceDefinition:recurrence,legalGraceDefinition:grace,competencyDefinition:n===10?{schemaVersion:1,type:"REQUIRED",requirements:["KNOWLEDGE_TEST","OBSERVED_SKILL"]}:{schemaVersion:1,type:"NONE"},evidenceDefinition:{schemaVersion:1,required:["TRAINING_COMPLETION"]},blockingScope:n===8?"DIRECT_CONTACT":null}})}
    const citation=n===8?"245A.65":"245D.09",regulationVersionId=versions.get(citation)!;await db.requirementAuthorityMapping.upsert({where:{requirementVersionId_regulationVersionId_relationshipType:{requirementVersionId:rv.id,regulationVersionId,relationshipType:"PRIMARY"}},update:{},create:{requirementVersionId:rv.id,regulationVersionId,relationshipType:"PRIMARY",citationNote:n===8?"Minn. Stat. §245D.09 subd. 4(5), with applicable maltreatment statutes":`Minn. Stat. §245D.09${n>1&&n<15?` subd. 4(${Math.min(n-1,11)})`:""}`}});if(executable.has(n))await db.complianceRulesetRequirement.upsert({where:{rulesetId_requirementVersionId:{rulesetId:ruleset.id,requirementVersionId:rv.id}},update:{},create:{rulesetId:ruleset.id,requirementVersionId:rv.id}});
  }
  for(const organizationId of [northstarId,lakesideId])if(!await db.organizationLicense.findFirst({where:{organizationId,licenseType:"MN_245D"}}))await db.organizationLicense.create({data:{organizationId,licenseType:"MN_245D",licenseStatus:"ACTIVE",effectiveDate:new Date("2026-08-01T00:00:00Z"),issuingAuthority:"Minnesota Department of Human Services"}});
}
async function main(){
  for(const code of permissionCodes) await db.permission.upsert({where:{code},update:{},create:{code}});
  for(const [code,name] of dutyRows) await db.dutyDefinition.upsert({where:{code},update:{name},create:{code,name}});
  for(const [code,codes] of Object.entries(roleMap)){
    const role=await db.roleDefinition.findFirst({where:{organizationId:null,code}})??await db.roleDefinition.create({data:{code,name:code.split("_").map(x=>x[0]+x.slice(1).toLowerCase()).join(" "),scope:"PLATFORM",isPlatformStandard:true}});
    const permissions=await db.permission.findMany({where:{code:{in:codes}}});
    for(const p of permissions) await db.rolePermission.upsert({where:{roleDefinitionId_permissionId:{roleDefinitionId:role.id,permissionId:p.id}},update:{},create:{roleDefinitionId:role.id,permissionId:p.id}});
  }
  const northstar=await db.organization.upsert({where:{slug:"northstar-support-services"},update:{},create:{legalName:"Northstar Support Services, Inc.",displayName:"Northstar Support Services",slug:"northstar-support-services",state:"MN",country:"US"}});
  const lakeside=await db.organization.upsert({where:{slug:"lakeside-community-services"},update:{},create:{legalName:"Lakeside Community Services, Inc.",displayName:"Lakeside Community Services",slug:"lakeside-community-services",state:"MN",country:"US"}});
  const community=await db.program.upsert({where:{organizationId_code:{organizationId:northstar.id,code:"COMMUNITY"}},update:{},create:{organizationId:northstar.id,name:"Community Supports",code:"COMMUNITY"}});
  const residential=await db.program.upsert({where:{organizationId_code:{organizationId:northstar.id,code:"RESIDENTIAL"}},update:{},create:{organizationId:northstar.id,name:"Residential Supports",code:"RESIDENTIAL"}});
  if(!await db.location.findFirst({where:{organizationId:northstar.id,name:"Northstar Woodbury Site"}})) await db.location.create({data:{organizationId:northstar.id,programId:community.id,name:"Northstar Woodbury Site",city:"Woodbury",state:"MN",country:"US"}});
  if(!await db.location.findFirst({where:{organizationId:northstar.id,name:"Northstar Oakdale Site"}})) await db.location.create({data:{organizationId:northstar.id,programId:residential.id,name:"Northstar Oakdale Site",city:"Oakdale",state:"MN",country:"US"}});
  const owner=await db.user.upsert({where:{email:"alex.owner@example.test"},update:{},create:{email:"alex.owner@example.test",status:"ACTIVE"}});
  const viewer=await db.user.upsert({where:{email:"jordan.viewer@example.test"},update:{},create:{email:"jordan.viewer@example.test",status:"ACTIVE"}});
  const shared=await db.user.upsert({where:{email:"taylor.shared@example.test"},update:{},create:{email:"taylor.shared@example.test",status:"ACTIVE"}});
  const ownerRole=(await db.roleDefinition.findFirstOrThrow({where:{organizationId:null,code:"ORGANIZATION_OWNER"}})); const auditorRole=await db.roleDefinition.findFirstOrThrow({where:{organizationId:null,code:"AUDITOR"}});
  for(const [org,user,role] of [[northstar,owner,ownerRole],[northstar,viewer,auditorRole],[northstar,shared,auditorRole],[lakeside,shared,ownerRole]] as const){ const m=await db.organizationMembership.upsert({where:{organizationId_userId:{organizationId:org.id,userId:user.id}},update:{status:"ACTIVE"},create:{organizationId:org.id,userId:user.id,status:"ACTIVE",joinedAt:new Date()}}); await db.membershipRole.upsert({where:{membershipId_roleDefinitionId:{membershipId:m.id,roleDefinitionId:role.id}},update:{},create:{membershipId:m.id,roleDefinitionId:role.id}}); }
  for(const [org,user,num,first,last] of [[northstar,shared,"1001","Taylor","Morgan"],[lakeside,shared,"1001","Taylor","Morgan"]] as const) if(!await db.employee.findFirst({where:{organizationId:org.id,userId:user.id}})) await db.employee.create({data:{organizationId:org.id,userId:user.id,employeeNumber:num,firstName:first,lastName:last,employmentStatus:"ACTIVE",employmentType:"FULL_TIME"}});
  const noLogin=await db.employee.findFirst({where:{organizationId:northstar.id,employeeNumber:"1002"}}); if(!noLogin) await db.employee.create({data:{organizationId:northstar.id,employeeNumber:"1002",firstName:"Casey",lastName:"Rivera",employmentStatus:"PENDING"}});
  await seedRegulatory(northstar.id,lakeside.id);
  console.log(JSON.stringify({developmentUsers:{owner:{id:owner.id,email:owner.email},viewer:{id:viewer.id,email:viewer.email},multiOrganization:{id:shared.id,email:shared.email}},organizations:{northstar:northstar.id,lakeside:lakeside.id}},null,2));
}
main().finally(()=>db.$disconnect());
