import { createHash } from "node:crypto";
import type { Prisma, PrismaClient } from "@prisma/client";

const courses=[
 {code:"245D-101",title:"Introduction to 245D and Employee Responsibilities",requirements:["245D-WF-001","245D-WF-002","245D-WF-005"],subject:"245D_ROLE_RESPONSIBILITIES",minutes:35,focus:"follow assigned duties, current policies, role limits, documented training, and demonstrated competency"},
 {code:"245D-102",title:"Incident Reporting and Safety",requirements:["245D-WF-003","245D-WF-004"],subject:"INCIDENT_REPORTING",minutes:45,focus:"protect immediate safety, obtain emergency help, preserve facts, and report incidents without unsupported conclusions",critical:true},
 {code:"245D-103",title:"License Holder Policies and Procedures",requirements:["245D-WF-005"],subject:"POLICIES_PROCEDURES",minutes:25,focus:"locate and follow the organization’s current policies and ask for guidance when requirements are unclear"},
 {code:"245D-104",title:"Data Privacy and Confidentiality",requirements:["245D-WF-006"],subject:"DATA_PRIVACY",minutes:35,focus:"use minimum necessary access, protect physical and electronic privacy, and report suspected privacy incidents",critical:true},
 {code:"245D-105",title:"Service Recipient Rights",requirements:["245D-WF-007"],subject:"SERVICE_RECIPIENT_RIGHTS",minutes:40,focus:"support choice, dignity, privacy, grievances, advocacy, nonretaliation, and context-appropriate residential rights"},
 {code:"245D-106",title:"Maltreatment and Mandated Reporting",requirements:["245D-WF-008"],subject:"MALTREATMENT_REPORTING",minutes:50,focus:"recognize possible abuse, neglect, or exploitation; protect immediate safety; report rather than investigate; and avoid retaliation",critical:true},
 {code:"245D-107",title:"Person-Centered Services",requirements:["245D-WF-009"],subject:"PERSON_CENTERED_SERVICES",minutes:40,focus:"honor goals, preferences, informed choice, dignity of risk, routines, independence, and community inclusion"},
 {code:"245D-108",title:"Emergency Manual Restraint Awareness",requirements:["245D-WF-010"],subject:"EMERGENCY_MANUAL_RESTRAINT",minutes:35,focus:"recognize imminent risk, use the least restrictive emergency response, stop when danger ends, call for help, and report",critical:true},
 {code:"245D-109",title:"Prohibited Procedures",requirements:["245D-WF-011"],subject:"PROHIBITED_PROCEDURES",minutes:35,focus:"recognize punishment, coercion, unauthorized restraint or deprivation, staff-convenience practices, and reporting duties",critical:true},
 {code:"245D-110",title:"Basic First Aid Awareness",requirements:["245D-WF-012"],subject:"BASIC_FIRST_AID",minutes:45,focus:"assess immediate safety, activate emergency services, use infection precautions, and report emergency events",critical:true},
 {code:"245D-111",title:"Healthy Relationships, Consent, Bodily Autonomy and Sexual Violence Prevention",requirements:["245D-WF-013"],subject:"HEALTHY_RELATIONSHIPS_CONSENT",minutes:45,focus:"respect bodily autonomy, consent, adult relationships, privacy, professional boundaries, and safe reporting"},
 {code:"245D-112",title:"Annual 245D Refresher",requirements:["245D-WF-006","245D-WF-007","245D-WF-008","245D-WF-009","245D-WF-010","245D-WF-011","245D-WF-012","245D-WF-013","245D-WF-015"],subject:"ANNUAL_245D_REFRESHER",minutes:60,focus:"refresh high-risk reporting, privacy, rights, person-centered support, emergency response, prohibited procedures, first-aid awareness, and consent",critical:true},
] as const;
const subjectNames:Record<string,string>={"245D_ROLE_RESPONSIBILITIES":"245D role responsibilities",INCIDENT_REPORTING:"Incident reporting",SAFETY_PRACTICES:"Safety practices",POLICIES_PROCEDURES:"Policies and procedures",DATA_PRIVACY:"Data privacy",SERVICE_RECIPIENT_RIGHTS:"Service recipient rights",MALTREATMENT_REPORTING:"Maltreatment reporting",PERSON_CENTERED_SERVICES:"Person-centered services",EMERGENCY_MANUAL_RESTRAINT:"Emergency manual restraint awareness",PROHIBITED_PROCEDURES:"Prohibited procedures",BASIC_FIRST_AID:"Basic first aid awareness",HEALTHY_RELATIONSHIPS_CONSENT:"Healthy relationships and consent"};

export async function seedProductionCurriculum(db:PrismaClient|Prisma.TransactionClient){for(const spec of courses){const course=await db.trainingCourse.upsert({where:{catalogKey:`platform:${spec.code}`},update:{title:spec.title,description:`Production generic Minnesota 245D workforce curriculum. Estimated learning time only; ${spec.focus}.`},create:{catalogKey:`platform:${spec.code}`,code:spec.code,title:spec.title,description:`Production generic Minnesota 245D workforce curriculum. Estimated learning time only; ${spec.focus}.`,category:spec.subject,status:"ACTIVE",ownershipType:"PLATFORM"}});let version=await db.trainingCourseVersion.findUnique({where:{courseId_versionNumber:{courseId:course.id,versionNumber:1}}});if(!version){version=await db.trainingCourseVersion.create({data:{courseId:course.id,versionNumber:1,status:"DRAFT",effectiveFrom:new Date("2026-09-08"),estimatedDurationMinutes:spec.minutes,contentHash:createHash("sha256").update(`${spec.code}:v1:${spec.focus}`).digest("hex")}});const trainingModule=await db.trainingModule.create({data:{courseVersionId:version.id,sequence:1,title:`${spec.title}: principles and scenarios`,moduleType:"MIXED",required:true,estimatedDurationMinutes:spec.minutes}});const content=await Promise.all([
 db.trainingContentItem.create({data:{moduleId:trainingModule.id,sequence:1,contentType:"RICH_TEXT",payload:{type:"section",heading:"Purpose and responsibilities",paragraphs:[`This course helps direct support professionals ${spec.focus}.`,`Your organization’s current procedures and your assigned role control what you do in practice. Ask a supervisor when instructions are unclear.`],keyPoint:"Training completion documents learning; it does not expand the limits of your role."}}}),
 db.trainingContentItem.create({data:{moduleId:trainingModule.id,sequence:2,contentType:"RICH_TEXT",payload:{type:"lesson",heading:"Apply the principle",bullets:["Protect immediate health, safety, dignity, and privacy.","Follow the current plan, policy, and supervisor direction that applies to your work.","Document observable facts and report concerns through the required channels.","Do not improvise outside your training, competency, or assigned authority."]}}}),
 db.trainingContentItem.create({data:{moduleId:trainingModule.id,sequence:3,contentType:"RICH_TEXT",payload:{type:"scenario",heading:"DSP scenario",scenario:"Jordan notices a situation that may affect a person’s safety or rights. A coworker suggests waiting until the end of the shift.",prompt:"Choose the response that protects the person, follows current reporting expectations, and stays within the employee’s role.",example:"Address immediate danger first, obtain emergency help when needed, preserve facts, and promptly use the applicable reporting process."}}}),
 db.trainingContentItem.create({data:{moduleId:trainingModule.id,sequence:4,contentType:"RICH_TEXT",payload:{type:"warning",heading:"Important boundary",warning:spec.code==="245D-108"?"Awareness training is not authorization to perform a physical restraint technique.":spec.code==="245D-110"?"This course is not an external hands-on first-aid or CPR certification.":spec.code==="245D-103"?"Generic training does not prove acknowledgment of your organization’s exact policy version.":"Apply current organization instructions and seek help when the situation exceeds your role."}}}),
 db.trainingContentItem.create({data:{moduleId:trainingModule.id,sequence:5,contentType:"ACKNOWLEDGMENT",required:true,payload:{type:"summary",heading:"Key takeaways",bullets:[spec.focus,"Respond to immediate safety needs.","Report and document facts without conducting an unauthorized investigation."],statement:"I acknowledge that I reviewed this generic training and understand that organization-specific and person-specific instructions may also apply."}}}),]);
 const objectives=await Promise.all([1,2,3].map((n)=>db.learningObjective.create({data:{courseVersionId:version!.id,code:`${spec.code.replace("245D-","")}-OBJ-00${n}`,title:n===1?`Explain how to ${spec.focus}.`:n===2?"Select a safe, role-appropriate response in a realistic scenario.":"Identify when to report, document, or seek supervisor or emergency assistance.",description:"Production learning objective with regulatory, content, and assessment traceability.",required:true,assessmentRequired:true,criticalSafety:!!("critical" in spec && spec.critical)&&n===1}})));
 const bank=await db.questionBank.create({data:{courseVersionId:version.id,code:`${spec.code}-BANK`,name:`${spec.title} question bank`}}),bankVersion=await db.questionBankVersion.create({data:{questionBankId:bank.id,versionNumber:1,status:"ACTIVE",contentHash:createHash("sha256").update(`${spec.code}:questions:v1`).digest("hex")}}),assessment=await db.assessment.create({data:{moduleId:trainingModule.id,versionNumber:1,title:`${spec.title} final assessment`,passingScore:80,maxAttempts:3,randomizeQuestions:true,status:"PUBLISHED",questionBankVersionId:bankVersion.id}});
 const questions=[];for(let n=1;n<=5;n++){const critical=!!("critical" in spec && spec.critical)&&n===1,q=await db.assessmentQuestion.create({data:{assessmentId:assessment.id,questionBankVersionId:bankVersion.id,questionType:n===4?"TRUE_FALSE":"SINGLE_CHOICE",prompt:n===1?`Scenario: A concern related to ${spec.title.toLowerCase()} creates an immediate safety or reporting issue. What should the DSP do first?`:n===2?"What best describes the employee’s responsibility?":n===3?"Why should observable facts be documented?":n===4?"Course completion automatically expands an employee’s authority beyond assigned duties.":"What should an employee do when current instructions are unclear?",explanation:"Review the linked lesson and scenario before retrying.",sequence:n,points:1,required:true,critical,remediationContentItemId:content[1].id,options:{create:n===4?[{sequence:1,text:"True",isCorrect:false},{sequence:2,text:"False",isCorrect:true}]:[{sequence:1,text:n===1?"Protect immediate safety, obtain needed help, and follow the reporting process":"Follow current duties, policy, and role limits",isCorrect:true},{sequence:2,text:"Wait or improvise without reporting",isCorrect:false},{sequence:3,text:"Conduct an independent investigation",isCorrect:false}]}}});questions.push(q)}
 const requirementVersions=await db.complianceRequirementVersion.findMany({where:{status:"ACTIVE",requirement:{code:{in:[...spec.requirements]}}},include:{requirement:true}});for(const [index,o] of objectives.entries()){await db.learningObjectiveModule.create({data:{learningObjectiveId:o.id,moduleId:trainingModule.id}});for(const item of content.slice(index,Math.min(index+3,content.length)))await db.learningObjectiveContent.create({data:{learningObjectiveId:o.id,contentItemId:item.id}});await db.learningObjectiveQuestion.create({data:{learningObjectiveId:o.id,questionId:questions[index].id}});for(const rv of requirementVersions)await db.learningObjectiveRequirement.create({data:{learningObjectiveId:o.id,requirementVersionId:rv.id}})}
 const subjects=spec.code==="245D-112"?["DATA_PRIVACY","SERVICE_RECIPIENT_RIGHTS","MALTREATMENT_REPORTING","PERSON_CENTERED_SERVICES","EMERGENCY_MANUAL_RESTRAINT","PROHIBITED_PROCEDURES","BASIC_FIRST_AID","HEALTHY_RELATIONSHIPS_CONSENT"]:[spec.subject];const base=Math.floor(spec.minutes/subjects.length),extra=spec.minutes-base*subjects.length;for(const [i,code] of subjects.entries())await db.trainingModuleSubjectArea.create({data:{moduleId:trainingModule.id,subjectAreaCode:code,subjectAreaName:subjectNames[code]??code,minutes:base+(i===0?extra:0)}});version=await db.trainingCourseVersion.update({where:{id:version.id},data:{status:"ACTIVE",publishedAt:new Date("2026-09-08")}})}
 const requirementVersions=await db.complianceRequirementVersion.findMany({where:{status:"ACTIVE",requirement:{code:{in:[...spec.requirements]}}},include:{requirement:true}});for(const rv of requirementVersions){if(rv.requirement.code==="245D-WF-014"||rv.requirement.code==="245D-WF-016"||rv.requirement.code==="245D-WF-017")continue;await db.requirementTrainingOption.upsert({where:{complianceRequirementVersionId_trainingCourseVersionId:{complianceRequirementVersionId:rv.id,trainingCourseVersionId:version.id}},update:{},create:{complianceRequirementVersionId:rv.id,trainingCourseVersionId:version.id,satisfactionType:rv.competencyDefinition&&((rv.competencyDefinition as{type?:string}).type==="REQUIRED")?"TRAINING_AND_COMPETENCY":"TRAINING_ONLY",isDefault:spec.code!=="245D-112"||rv.requirement.code==="245D-WF-015"}})}}}
