import { createHash } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { DEVELOPMENT_VISUAL_QA_ORGANIZATION_NAME, DEVELOPMENT_VISUAL_QA_ORGANIZATION_SLUG, DEVELOPMENT_VISUAL_QA_OWNER_EMAIL } from "../src/domain/auth/development-visual-qa";

if (process.env.NODE_ENV === "production" || process.env.VISUAL_QA_MODE !== "true") throw new Error("Visual-QA seed requires the development-only visual-QA runtime.");
const target = new URL(process.env.DATABASE_URL ?? "");
if (!["localhost", "127.0.0.1", "[::1]"].includes(target.hostname) || target.port !== "55433" || target.pathname !== "/compliance_platform_visual_qa") throw new Error("Visual-QA seed refused a non-local or non-QA database target.");

const db = new PrismaClient();
const permissions = ["organization.read","organization.manage","employee.read","employee.manage","training.read","training.manage","training.catalog.read","training.catalog.manage","training.assignment.read","training.assignment.manage","training.progress.read","training.assessment.manage","training.equivalency.review","training.curriculum.publish","training.curriculum.coverage.read","competency.read","competency.assess","competency.manage","certificate.read","certificate.issue","certificate.revoke","onboarding.read","onboarding.manage","policy.read","policy.manage","policy.assign","work_readiness.read","work_readiness.evaluate","compliance.operations.read","service_assignment.read","service_assignment.manage","service_assignment.override","compliance_issue.read","compliance_issue.reconcile","compliance_issue.manage","recipient.read","recipient.readSensitive","recipient.readDocuments","recipient.uploadDocuments","recipient.assignStaff","clinical.review","medication.approve","audit.read","audit.export","audit.session.manage","audit.portal.read","client.read","client.create","client.update","client.intake.manage","client.document.read","client.document.generate","client.signature.manage","client.export"];
const at = (value: string) => new Date(value);
const digest = (value: string|Uint8Array) => createHash("sha256").update(value).digest("hex");
async function syntheticPdf(title:string,status:string){const pdf=await PDFDocument.create(),page=pdf.addPage([612,792]),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);page.drawText(title,{x:54,y:720,size:18,font:bold,color:rgb(.08,.24,.19)});page.drawText(`Development-only visual-QA ${status} document`,{x:54,y:690,size:11,font});page.drawText("Contains synthetic data only.",{x:54,y:665,size:10,font});return Buffer.from(await pdf.save())}

async function main() {
  if (await db.organization.count()) throw new Error("Visual-QA seed expects an empty dedicated database. Run pnpm visual-qa:reset.");
  const permissionRows = await Promise.all(permissions.map(code => db.permission.upsert({where:{code},update:{},create:{code}})));
  const ownerRole = await db.roleDefinition.findFirst({where:{organizationId:null,code:"ORGANIZATION_OWNER"}}) ?? await db.roleDefinition.create({data:{code:"ORGANIZATION_OWNER",name:"Organization Owner",scope:"PLATFORM",isPlatformStandard:true}});
  for(const permission of permissionRows) await db.rolePermission.upsert({where:{roleDefinitionId_permissionId:{roleDefinitionId:ownerRole.id,permissionId:permission.id}},update:{},create:{roleDefinitionId:ownerRole.id,permissionId:permission.id}});
  const organization = await db.organization.create({data:{legalName:`${DEVELOPMENT_VISUAL_QA_ORGANIZATION_NAME} LLC`,displayName:DEVELOPMENT_VISUAL_QA_ORGANIZATION_NAME,slug:DEVELOPMENT_VISUAL_QA_ORGANIZATION_SLUG,state:"MN",country:"US",timezone:"America/Chicago"}});
  const owner = await db.user.create({data:{email:DEVELOPMENT_VISUAL_QA_OWNER_EMAIL,status:"ACTIVE"}});
  await db.organizationMembership.create({data:{organizationId:organization.id,userId:owner.id,status:"ACTIVE",joinedAt:at("2026-01-05"),roles:{create:{roleDefinitionId:ownerRole.id}}}});

  const employees = await Promise.all([
    ["QA-1001","Avery","Stone","ACTIVE","Direct Support Professional","FULL_TIME"],
    ["QA-1002","Jordan","Lee","PENDING","Direct Support Professional","PART_TIME"],
    ["QA-1003","Morgan","Reed","ACTIVE","Lead Direct Support Professional","FULL_TIME"],
    ["QA-1004","Casey","Brooks","LEAVE","Direct Support Professional","PART_TIME"],
    ["QA-1005","Riley","Quinn","ACTIVE","Community Support Specialist","FULL_TIME"],
    ["QA-1006","Taylor","Park","TERMINATED","Direct Support Professional","FULL_TIME"],
  ].map(([employeeNumber,firstName,lastName,employmentStatus,jobTitle,employmentType])=>db.employee.create({data:{organizationId:organization.id,employeeNumber,firstName,lastName,email:`${firstName.toLowerCase()}.${lastName.toLowerCase()}@example.test`,employmentStatus:employmentStatus as "ACTIVE",jobTitle,employmentType:employmentType as "FULL_TIME",hireDate:at("2026-01-12")}})));

  const onboardingTemplate = await db.onboardingTemplate.create({data:{organizationId:organization.id,code:"VISUAL-QA-ONBOARDING",name:"Visual-QA employee onboarding",description:"Synthetic development-only onboarding.",ownerType:"ORGANIZATION",versions:{create:{versionNumber:1,status:"PUBLISHED",effectiveFrom:at("2026-01-01"),publishedAt:at("2026-01-01"),contentHash:digest("visual-qa-onboarding-v1"),steps:{create:[{sequence:1,code:"EMPLOYEE-INFO",name:"Employee information review",stepType:"EMPLOYEE_INFORMATION",required:true,blockingScope:"GENERAL_WORK"},{sequence:2,code:"POLICY-REVIEW",name:"Required policy review",stepType:"POLICY_ACKNOWLEDGMENT",required:true,blockingScope:"DIRECT_CONTACT"}]}}}},include:{versions:{include:{steps:true}}}});
  await db.employeeOnboarding.create({data:{organizationId:organization.id,employeeId:employees[1].id,templateVersionId:onboardingTemplate.versions[0].id,status:"IN_PROGRESS",startedAt:at("2026-09-28"),createdByUserId:owner.id,steps:{create:onboardingTemplate.versions[0].steps.map((step,index)=>({stepDefinitionId:step.id,status:index===0?"COMPLETED":"PENDING",completedAt:index===0?at("2026-09-28"):undefined,completedByUserId:index===0?owner.id:undefined,dueAt:index===1?at("2026-10-14"):undefined}))}}});

  const course = await db.trainingCourse.create({data:{organizationId:organization.id,catalogKey:"visual-qa:orientation",code:"VQA-101",title:"Synthetic Direct Support Orientation",description:"Development-only representative training; not regulatory or clinical authorization.",category:"ORIENTATION",ownershipType:"ORGANIZATION",versions:{create:{versionNumber:1,status:"ACTIVE",effectiveFrom:at("2026-01-01"),publishedAt:at("2026-01-01"),estimatedDurationMinutes:25,contentHash:digest("visual-qa-course-v1"),modules:{create:{sequence:1,title:"Role boundaries and reporting",moduleType:"CONTENT",estimatedDurationMinutes:25,contentItems:{create:[{sequence:1,contentType:"RICH_TEXT",payload:{heading:"Synthetic orientation",body:"Review role boundaries and report concerns through the organization workflow."}},{sequence:2,contentType:"ACKNOWLEDGMENT",payload:{statement:"I reviewed this synthetic visual-QA lesson."}}]}}}}}},include:{versions:{include:{modules:{include:{contentItems:true}}}}}});
  const version = course.versions[0], content = version.modules[0].contentItems[0];
  const inProgress = await db.trainingAssignment.create({data:{fingerprint:"visual-qa-training-in-progress",activeKey:"visual-qa-training-in-progress",organizationId:organization.id,employeeId:employees[0].id,courseVersionId:version.id,sourceType:"MANUAL",status:"IN_PROGRESS",assignedByUserId:owner.id,assignedAt:at("2026-09-25"),dueAt:at("2026-10-20"),startedAt:at("2026-10-01")}});
  await db.trainingContentProgress.create({data:{assignmentId:inProgress.id,contentItemId:content.id,status:"COMPLETED",startedAt:at("2026-10-01"),completedAt:at("2026-10-01")}});
  await db.trainingAssignment.create({data:{fingerprint:"visual-qa-training-overdue",activeKey:"visual-qa-training-overdue",organizationId:organization.id,employeeId:employees[4].id,courseVersionId:version.id,sourceType:"MANUAL",status:"NOT_STARTED",assignedByUserId:owner.id,assignedAt:at("2026-09-01"),dueAt:at("2026-10-01")}});

  const policy = await db.policy.create({data:{organizationId:organization.id,code:"VQA-PRIVACY",title:"Synthetic Privacy and Records Policy",description:"Development-only policy fixture.",requiresAcknowledgment:true,reacknowledgeOnNewVersion:true,blockingScope:"DIRECT_CONTACT",versions:{create:{versionNumber:1,status:"PUBLISHED",effectiveFrom:at("2026-01-01"),publishedAt:at("2026-01-01"),body:"Use only the minimum synthetic information necessary for this visual-QA environment.",contentHash:digest("visual-qa-policy-v1"),createdByUserId:owner.id}}},include:{versions:true}});
  await db.policyAssignment.create({data:{fingerprint:"visual-qa-policy-pending",organizationId:organization.id,employeeId:employees[1].id,policyVersionId:policy.versions[0].id,assignedByUserId:owner.id,sourceType:"MANUAL",sourceReferenceId:"visual-qa-seed",status:"PENDING",dueAt:at("2026-10-15")}});
  await db.professionalCredential.create({data:{organizationId:organization.id,employeeId:employees[2].id,credentialType:"OTHER",credentialName:"Synthetic Community Support Certificate",issuedAt:at("2026-02-01"),expiresAt:at("2027-02-01"),verificationStatus:"SELF_REPORTED",evidenceReference:"visual-qa-only",status:"ACTIVE"}});
  await db.complianceIssue.create({data:{fingerprint:"visual-qa-issue-onboarding",activeKey:"visual-qa-issue-onboarding",organizationId:organization.id,employeeId:employees[1].id,issueType:"ONBOARDING_INCOMPLETE",priority:"MEDIUM",sourceType:"EmployeeOnboarding",sourceId:"visual-qa-onboarding",contextJson:{synthetic:true},reasonCodesJson:["ONBOARDING_STEP_REQUIRED"],remediationActionsJson:[{type:"COMPLETE_ONBOARDING_STEP"}],evidenceReferencesJson:[],dueAt:at("2026-10-14"),firstDetectedAt:at("2026-10-01"),latestDetectedAt:at("2026-10-01")}});
  await db.employeePortalInvitation.create({data:{organizationId:organization.id,employeeId:employees[1].id,invitedEmail:"jordan.lee@example.test",tokenHash:digest("visual-qa-pending-invitation"),status:"PENDING",deliveryStatus:"PENDING",invitedByUserId:owner.id,invitedAt:at("2026-10-02")}});

  const clients = await Promise.all([
    db.client.create({data:{organizationId:organization.id,status:"ACTIVE",legalFirstName:"Sample",legalLastName:"Client One",preferredName:"Sam",dateOfBirth:at("1990-01-01"),email:"sample.client.one@example.test",city:"St. Paul",state:"MN",waiverProgram:"Synthetic CADI",supportNeeds:"Synthetic record for visual QA only.",createdByUserId:owner.id,services:{create:{organizationId:organization.id,serviceType:"Individualized home supports",status:"ACTIVE",startDate:at("2026-02-01")}},representatives:{create:{organizationId:organization.id,representativeType:"GUARDIAN",name:"Sample Representative",relationship:"Synthetic guardian",email:"sample.representative@example.test",isPrimary:true}}}}),
    db.client.create({data:{organizationId:organization.id,status:"INTAKE_IN_PROGRESS",legalFirstName:"Demo",legalLastName:"Client Two",dateOfBirth:at("1988-02-02"),email:"demo.client.two@example.test",city:"Maplewood",state:"MN",createdByUserId:owner.id,intakes:{create:{organizationId:organization.id,status:"IN_PROGRESS",currentStep:"CONTACTS",progressJson:{synthetic:true},checklistItems:{create:[{code:"FACE_SHEET",label:"Synthetic face sheet",status:"COMPLETED",completedAt:at("2026-10-01"),sequence:1},{code:"RIGHTS",label:"Synthetic rights acknowledgment",status:"PENDING",sequence:2}]}}}}}),
    db.client.create({data:{organizationId:organization.id,status:"PROSPECTIVE",legalFirstName:"Example",legalLastName:"Client Three",dateOfBirth:at("1995-03-03"),email:"example.client.three@example.test",city:"Roseville",state:"MN",createdByUserId:owner.id}}),
  ]);
  const [rightsTemplate,faceTemplate] = await Promise.all([
    db.clientDocumentTemplate.create({data:{organizationId:organization.id,code:"VQA-RIGHTS",name:"Synthetic Rights Acknowledgment",documentType:"RIGHTS_ACKNOWLEDGMENT",versionNumber:1,renewalPolicy:"ANNUAL",renewalWarningDays:30,contentJson:{renderer:"BASIC",synthetic:true}}}),
    db.clientDocumentTemplate.create({data:{organizationId:organization.id,code:"VQA-FACE",name:"Synthetic Face Sheet",documentType:"FACE_SHEET",versionNumber:1,renewalPolicy:"NONE",contentJson:{renderer:"BASIC",synthetic:true,signerRoles:["CLIENT"]}}}),
  ]);
  const rightsPdf=await syntheticPdf("Synthetic Rights Acknowledgment","completed"),facePdf=await syntheticPdf("Synthetic Face Sheet","signature-ready");
  await db.clientDocument.create({data:{organizationId:organization.id,clientId:clients[0].id,templateId:rightsTemplate.id,documentType:"RIGHTS_ACKNOWLEDGMENT",status:"COMPLETED",source:"IMPORTED",originalFileName:"synthetic-historical-rights.pdf",sourceDocumentHash:digest(rightsPdf),importedAt:at("2025-10-01"),snapshotJson:{synthetic:true,completionBasis:"historical imported QA fixture"},renderedPdf:rightsPdf,finalPdf:rightsPdf,generatedByUserId:owner.id,generatedAt:at("2025-10-01"),finalizedAt:at("2025-10-01"),authoritativeCompletedAt:at("2025-10-01")}});
  const signatureDocument = await db.clientDocument.create({data:{organizationId:organization.id,clientId:clients[1].id,templateId:faceTemplate.id,documentType:"FACE_SHEET",status:"READY_FOR_SIGNATURE",source:"GENERATED",snapshotJson:{synthetic:true},renderedPdf:facePdf,generatedByUserId:owner.id,generatedAt:at("2026-10-03"),finalizedAt:at("2026-10-03")}}),frozenHash=digest(facePdf);
  const signatureEnvelope=await db.signatureEnvelope.create({data:{organizationId:organization.id,clientId:clients[1].id,documentId:signatureDocument.id,mode:"SIGN_NOW",provider:"native",status:"READY",frozenPdf:facePdf,frozenDocumentHash:frozenHash,consentVersion:"native-esign-consent-v1",signers:{create:{role:"CLIENT",name:"Demo Client Two",required:true,status:"PENDING"}}}}),rendition=await db.signatureRendition.create({data:{envelopeId:signatureEnvelope.id,sequence:0,pdf:facePdf,renditionHash:frozenHash,sourceContentHash:frozenHash}});
  await db.signatureEnvelope.update({where:{id:signatureEnvelope.id},data:{currentRenditionId:rendition.id}});

  console.log(JSON.stringify({dataset:"visual-qa",organization:DEVELOPMENT_VISUAL_QA_ORGANIZATION_NAME,owner:DEVELOPMENT_VISUAL_QA_OWNER_EMAIL,employees:employees.length,clients:clients.length},null,2));
}

main().finally(()=>db.$disconnect());
