import { Prisma, type ComplianceIssuePriority, type ComplianceIssueType, type User } from "@prisma/client";
import { AuthorizationError, ResourceNotFoundError } from "@/domain/auth/errors";
import { computeEmployeeOperationalProfile } from "@/domain/compliance/operations/service";
import { listMedicationQualifications } from "@/domain/medication/service";
import { getServiceAssignment, reevaluateServiceAssignment } from "@/domain/service-assignments/service";
import { requireEmployeeAccess, requireOrganizationAccess, requirePermission } from "@/domain/permissions/authorization";
import { prisma } from "@/lib/prisma";

export const COMPLIANCE_ISSUE_ENGINE_VERSION = "phase11-v1";
type Candidate = { activeKey: string; issueType: ComplianceIssueType; priority: ComplianceIssuePriority; sourceType: string; sourceId: string; serviceAssignmentId?: string; context: Prisma.InputJsonValue; reasons: string[]; remediations: Prisma.InputJsonValue; evidence: Prisma.InputJsonValue; dueAt?: Date | null };

async function authorize(user: Pick<User, "id">, organizationId: string, permission: "compliance_issue.read" | "compliance_issue.reconcile" | "compliance_issue.manage") { const { membership } = await requireOrganizationAccess(user, organizationId); await requirePermission(membership.id, permission); return membership; }
const key = (organizationId: string, employeeId: string, type: ComplianceIssueType, sourceType: string, sourceId: string, context = "general") => [organizationId, employeeId, type, sourceType, sourceId, context].join(":");
const medicationType = (reasons: string[]): ComplianceIssueType => reasons.includes("PERSON_SPECIFIC_INSTRUCTION_REQUIRED") ? "PERSON_SPECIFIC_INSTRUCTION_REQUIRED" : reasons.some(reason => ["AUTHORIZATION_REQUIRED", "DELEGATION_REQUIRED"].includes(reason)) ? "MEDICATION_AUTHORIZATION_MISSING" : reasons.includes("CLINICAL_SIGNOFF_REQUIRED") ? "CLINICAL_SIGNOFF_REQUIRED" : "MEDICATION_QUALIFICATION_INCOMPLETE";
const priorityFor = (type: ComplianceIssueType, dueAt: Date | null | undefined, at: Date): ComplianceIssuePriority => type === "ACTIVE_ASSIGNMENT_BECAME_BLOCKED" ? "CRITICAL" : ["ASSIGNMENT_BLOCKED", "MEDICATION_AUTHORIZATION_MISSING", "PERSON_SPECIFIC_INSTRUCTION_REQUIRED"].includes(type) ? "HIGH" : dueAt && dueAt < at ? "HIGH" : dueAt ? "MEDIUM" : "NORMAL";

async function detectCandidates(user: Pick<User, "id">, organizationId: string, employeeId: string, at: Date): Promise<Candidate[]> {
  const [profile, medication, employee] = await Promise.all([
    computeEmployeeOperationalProfile(organizationId, employeeId, at),
    listMedicationQualifications(user, organizationId, employeeId, at),
    prisma.employee.findFirst({
      where: { id: employeeId, organizationId },
      include: {
        policyAssignments: { where: { status: { in: ["PENDING", "OVERDUE"] } }, include: { policyVersion: { include: { policy: true } } } },
        onboardings: { where: { status: { notIn: ["COMPLETED", "CANCELED"] } }, include: { steps: { where: { status: { notIn: ["COMPLETED", "NOT_APPLICABLE"] } }, include: { stepDefinition: true } } } },
        professionalCredentials: { where: { status: "ACTIVE" } },
        serviceAssignments: { where: { status: { in: ["ACTIVE", "BLOCKED"] } }, select: { id: true, status: true } },
      },
    }),
  ]);
  if (!employee) throw new ResourceNotFoundError("Employee not found");
  const candidates: Candidate[] = [];
  for (const requirement of profile.requirements.filter(item => item.status !== "READY")) {
    const competency = requirement.remediations.some(item => ["COMPLETE_COMPETENCY_ASSESSMENT", "OBTAIN_ASSESSOR_SIGN_OFF"].includes(item.type));
    const issueType: ComplianceIssueType = competency ? "COMPETENCY_REQUIRED" : requirement.overdue ? "TRAINING_OVERDUE" : "TRAINING_REQUIRED";
    candidates.push({ activeKey: key(organizationId, employeeId, issueType, "ComplianceInstance", requirement.complianceInstanceId), issueType, priority: priorityFor(issueType, requirement.dueAt ? new Date(requirement.dueAt) : null, at), sourceType: "ComplianceInstance", sourceId: requirement.complianceInstanceId, context: { requirementVersionId: requirement.requirementVersionId, blockingScope: requirement.blockingScope }, reasons: [`REQUIREMENT_${requirement.status}`], remediations: requirement.remediations as unknown as Prisma.InputJsonValue, evidence: requirement.evidence as unknown as Prisma.InputJsonValue, dueAt: requirement.dueAt ? new Date(requirement.dueAt) : null });
  }
  for (const assignment of employee.policyAssignments) candidates.push({ activeKey: key(organizationId, employeeId, "POLICY_ACKNOWLEDGMENT_REQUIRED", "PolicyAssignment", assignment.id), issueType: "POLICY_ACKNOWLEDGMENT_REQUIRED", priority: priorityFor("POLICY_ACKNOWLEDGMENT_REQUIRED", assignment.dueAt, at), sourceType: "PolicyAssignment", sourceId: assignment.id, context: { policyVersionId: assignment.policyVersionId, policyTitle: assignment.policyVersion.policy.title }, reasons: ["POLICY_ACKNOWLEDGMENT_REQUIRED"], remediations: [{ type: "ACKNOWLEDGE_REQUIRED_POLICY", resourceType: "PolicyAssignment", resourceId: assignment.id }], evidence: [], dueAt: assignment.dueAt });
  for (const onboarding of employee.onboardings) for (const step of onboarding.steps.filter(item => item.stepDefinition.required)) candidates.push({ activeKey: key(organizationId, employeeId, "ONBOARDING_INCOMPLETE", "EmployeeOnboardingStep", step.id), issueType: "ONBOARDING_INCOMPLETE", priority: priorityFor("ONBOARDING_INCOMPLETE", step.dueAt, at), sourceType: "EmployeeOnboardingStep", sourceId: step.id, context: { onboardingId: onboarding.id, stepDefinitionId: step.stepDefinitionId }, reasons: ["ONBOARDING_STEP_REQUIRED"], remediations: [{ type: "COMPLETE_ONBOARDING_STEP", resourceType: "EmployeeOnboardingStep", resourceId: step.id }], evidence: [], dueAt: step.dueAt });
  const upcomingCutoff = new Date(at.getTime() + 30 * 86_400_000);
  for (const credential of employee.professionalCredentials) if (credential.expiresAt && credential.expiresAt <= upcomingCutoff) { const expired = credential.expiresAt < at, issueType: ComplianceIssueType = expired ? "CREDENTIAL_INVALID" : "CREDENTIAL_EXPIRING"; candidates.push({ activeKey: key(organizationId, employeeId, issueType, "ProfessionalCredential", credential.id), issueType, priority: expired ? "HIGH" : "LOW", sourceType: "ProfessionalCredential", sourceId: credential.id, context: { credentialType: credential.credentialType }, reasons: [expired ? "CREDENTIAL_EXPIRED" : "CREDENTIAL_EXPIRING"], remediations: [{ type: "RENEW_EXPIRED_CREDENTIAL", resourceType: "ProfessionalCredential", resourceId: credential.id }], evidence: [{ type: "EXTERNAL_CREDENTIAL", referenceId: credential.id }], dueAt: credential.expiresAt }); }
  for (const qualification of medication.filter(item => item.state !== "QUALIFIED")) { const issueType = medicationType(qualification.reasons); candidates.push({ activeKey: key(organizationId, employeeId, issueType, "MedicationQualificationPathway", qualification.pathway.id), issueType, priority: "HIGH", sourceType: "MedicationQualificationPathway", sourceId: qualification.pathway.id, context: { requirementVersionId: qualification.pathway.requirementVersionId, state: qualification.state }, reasons: qualification.reasons, remediations: qualification.remediations as unknown as Prisma.InputJsonValue, evidence: { trainingCompletionId: qualification.completion?.id ?? null, assessmentId: qualification.observedAssessment?.id ?? null, qualificationId: qualification.qualification?.id ?? null } }); }
  for (const row of employee.serviceAssignments) {
    if (row.status === "ACTIVE") await reevaluateServiceAssignment(user, organizationId, row.id);
    const assignment = await getServiceAssignment(user, organizationId, row.id), latest = assignment.eligibilityEvaluations.at(-1); if (!latest || latest.decision !== "BLOCKED") continue;
    const result = latest.resultSnapshot as { reasonCodes?: string[]; evidenceBasis?: unknown; context?: { serviceRecipientRef?: string | null } }, changed = assignment.events.some(event => event.action === "assignment.eligibility_changed" && (event.metadata as { evaluationId?: string } | null)?.evaluationId === latest.id), classifiedMedication = medicationType(result.reasonCodes ?? []), issueType: ComplianceIssueType = changed ? "ACTIVE_ASSIGNMENT_BECAME_BLOCKED" : ["PERSON_SPECIFIC_INSTRUCTION_REQUIRED", "MEDICATION_AUTHORIZATION_MISSING", "CLINICAL_SIGNOFF_REQUIRED"].includes(classifiedMedication) ? classifiedMedication : "ASSIGNMENT_BLOCKED";
    candidates.push({ activeKey: key(organizationId, employeeId, issueType, "ServiceAssignment", assignment.id, result.context?.serviceRecipientRef ?? "general"), issueType, priority: priorityFor(issueType, null, at), sourceType: "ServiceAssignment", sourceId: assignment.id, serviceAssignmentId: assignment.id, context: { programId: assignment.programId, locationId: assignment.locationId, serviceRecipientRef: assignment.serviceRecipientRef, blockingScope: assignment.blockingScope }, reasons: result.reasonCodes ?? ["ASSIGNMENT_BLOCKED"], remediations: [{ type: "REEVALUATE_OR_REMOVE_ASSIGNMENT", resourceType: "ServiceAssignment", resourceId: assignment.id }], evidence: (result.evidenceBasis ?? {}) as Prisma.InputJsonValue });
  }
  return candidates;
}

function materialChanged(issue: { priority: ComplianceIssuePriority; dueAt: Date | null; reasonCodesJson: Prisma.JsonValue; remediationActionsJson: Prisma.JsonValue }, candidate: Candidate) { return issue.priority !== candidate.priority || issue.dueAt?.toISOString() !== candidate.dueAt?.toISOString() || JSON.stringify(issue.reasonCodesJson) !== JSON.stringify(candidate.reasons) || JSON.stringify(issue.remediationActionsJson) !== JSON.stringify(candidate.remediations); }
async function event(issueId: string, organizationId: string, action: string, snapshot: Prisma.InputJsonValue, actorUserId?: string, dedupeKey?: string) { return prisma.complianceIssueEvent.create({ data: { complianceIssueId: issueId, organizationId, action, snapshotJson: snapshot, actorUserId, dedupeKey } }).catch(error => { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") return null; throw error; }); }

export async function reconcileEmployeeIssues(user: Pick<User, "id">, organizationId: string, employeeId: string, at = new Date()) {
  await authorize(user, organizationId, "compliance_issue.reconcile"); await requireEmployeeAccess(user, organizationId, employeeId, "employee.read");
  const candidates = await detectCandidates(user, organizationId, employeeId, at), active = await prisma.complianceIssue.findMany({ where: { organizationId, employeeId, status: { in: ["OPEN", "IN_PROGRESS"] } } }), seen = new Set<string>();
  const detected = [];
  for (const candidate of candidates) {
    seen.add(candidate.activeKey); const existing = active.find(issue => issue.activeKey === candidate.activeKey);
    if (existing) { const changed = materialChanged(existing, candidate); const updated = await prisma.complianceIssue.update({ where: { id: existing.id }, data: { latestDetectedAt: at, priority: candidate.priority, reasonCodesJson: candidate.reasons, remediationActionsJson: candidate.remediations, evidenceReferencesJson: candidate.evidence, contextJson: candidate.context, dueAt: candidate.dueAt } }); if (changed) await event(updated.id, organizationId, "issue.materially_changed", { priority: updated.priority, reasons: candidate.reasons, dueAt: candidate.dueAt?.toISOString() ?? null }, user.id); detected.push(updated); continue; }
    const recurrence = await prisma.complianceIssue.count({ where: { organizationId, employeeId, sourceType: candidate.sourceType, sourceId: candidate.sourceId, issueType: candidate.issueType } }), issue = await prisma.complianceIssue.create({ data: { fingerprint: `${candidate.activeKey}:occurrence:${recurrence + 1}`, activeKey: candidate.activeKey, organizationId, employeeId, issueType: candidate.issueType, priority: candidate.priority, sourceType: candidate.sourceType, sourceId: candidate.sourceId, serviceAssignmentId: candidate.serviceAssignmentId, contextJson: candidate.context, reasonCodesJson: candidate.reasons, remediationActionsJson: candidate.remediations, evidenceReferencesJson: candidate.evidence, dueAt: candidate.dueAt, firstDetectedAt: at, latestDetectedAt: at } }); await event(issue.id, organizationId, "issue.detected", { issueType: issue.issueType, priority: issue.priority, reasons: candidate.reasons }, user.id); detected.push(issue);
  }
  const resolved = [];
  for (const issue of active.filter(item => item.activeKey && !seen.has(item.activeKey))) { const updated = await prisma.complianceIssue.update({ where: { id: issue.id }, data: { status: "RESOLVED", activeKey: null, resolvedAt: at, resolutionReason: "Underlying compliance evaluator no longer reports the deficiency." } }); await event(updated.id, organizationId, "issue.resolved", { resolutionReason: updated.resolutionReason, resolvedAt: at.toISOString() }, user.id); resolved.push(updated); }
  for (const issue of detected.filter(item => item.dueAt)) { const state = issue.dueAt! < at ? "overdue" : issue.dueAt! <= new Date(at.getTime() + 30 * 86_400_000) ? "approaching" : null; if (state) await event(issue.id, organizationId, `issue.deadline_${state}`, { dueAt: issue.dueAt!.toISOString() }, undefined, `${issue.id}:${state}:${issue.dueAt!.toISOString()}`); }
  return { organizationId, employeeId, evaluatedAt: at.toISOString(), detected, resolved };
}

export async function reconcileOrganizationIssues(user: Pick<User, "id">, organizationId: string, at = new Date()) { await authorize(user, organizationId, "compliance_issue.reconcile"); const employees = await prisma.employee.findMany({ where: { organizationId, employmentStatus: { not: "ARCHIVED" } }, select: { id: true },orderBy:{id:"asc"},take:501 });if(employees.length>500)throw new AuthorizationError("Organization reconciliation is bounded to 500 employees per invocation"); const results = []; for (const employee of employees) results.push(await reconcileEmployeeIssues(user, organizationId, employee.id, at)); return { organizationId, evaluatedAt: at.toISOString(), employeesScanned: employees.length, detected: results.reduce((sum, result) => sum + result.detected.length, 0), resolved: results.reduce((sum, result) => sum + result.resolved.length, 0) }; }

export async function startIssueRemediation(user: Pick<User, "id">, organizationId: string, issueId: string) { await authorize(user, organizationId, "compliance_issue.manage"); const issue = await prisma.complianceIssue.findFirst({ where: { id: issueId, organizationId } }); if (!issue) throw new ResourceNotFoundError("Compliance issue not found"); if (issue.status === "RESOLVED") throw new AuthorizationError("Resolved issues cannot be manually reopened or falsely resolved"); if (issue.status === "IN_PROGRESS") return issue; const updated = await prisma.complianceIssue.update({ where: { id: issue.id }, data: { status: "IN_PROGRESS", workflowStartedAt: new Date(), workflowStartedByUserId: user.id } }); await event(updated.id, organizationId, "issue.remediation_started", { status: updated.status }, user.id); return updated; }

export async function getComplianceIssue(user: Pick<User, "id">, organizationId: string, issueId: string) { await authorize(user, organizationId, "compliance_issue.read"); const issue = await prisma.complianceIssue.findFirst({ where: { id: issueId, organizationId }, include: { events: { orderBy: { createdAt: "asc" } } } }); if (!issue) throw new ResourceNotFoundError("Compliance issue not found"); return issue; }
export async function listComplianceIssues(user: Pick<User, "id">, organizationId: string, filters: { status?: "OPEN" | "IN_PROGRESS" | "RESOLVED"; employeeId?: string; issueType?: ComplianceIssueType; priority?: ComplianceIssuePriority; overdue?: boolean; upcoming?: boolean; medication?: boolean; personSpecific?: boolean; assignmentRelated?: boolean } = {}, at = new Date()) { await authorize(user, organizationId, "compliance_issue.read"); const medicationTypes: ComplianceIssueType[] = ["PERSON_SPECIFIC_INSTRUCTION_REQUIRED", "MEDICATION_QUALIFICATION_INCOMPLETE", "MEDICATION_AUTHORIZATION_MISSING", "CLINICAL_SIGNOFF_REQUIRED"]; const assignmentTypes: ComplianceIssueType[] = ["ASSIGNMENT_BLOCKED", "ACTIVE_ASSIGNMENT_BECAME_BLOCKED"]; const where: Prisma.ComplianceIssueWhereInput = { organizationId, status: filters.status, employeeId: filters.employeeId, issueType: filters.issueType ?? (filters.medication ? { in: medicationTypes } : filters.personSpecific ? "PERSON_SPECIFIC_INSTRUCTION_REQUIRED" : filters.assignmentRelated ? { in: assignmentTypes } : undefined), priority: filters.priority, dueAt: filters.overdue ? { lt: at } : filters.upcoming ? { gte: at, lte: new Date(at.getTime() + 30 * 86_400_000) } : undefined }; const issues = await prisma.complianceIssue.findMany({ where, include: { employee: { select: { id: true, firstName: true, lastName: true } }, events: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: [{ priority: "desc" }, { dueAt: "asc" }, { firstDetectedAt: "asc" }] }); const grouped = await prisma.complianceIssue.groupBy({ by: ["status"], where: { organizationId }, _count: true }); return { organizationId, evaluatedAt: at.toISOString(), counts: Object.fromEntries(grouped.map(row => [row.status, row._count])), issues: issues.map(issue => ({ ...issue, deadlineState: !issue.dueAt ? "NONE" : issue.dueAt < at ? "OVERDUE" : issue.dueAt <= new Date(at.getTime() + 30 * 86_400_000) ? "UPCOMING" : "FUTURE" })) }; }
