import { createHash } from "node:crypto";
import { Prisma, type PolicyStatus, type User } from "@prisma/client";
import { z } from "zod";
import { AuthorizationError, ResourceNotFoundError, ValidationError } from "@/domain/auth/errors";
import { requireEmployeeSelfAccess, requireOrganizationAccess, requirePermission } from "@/domain/permissions/authorization";
import { evaluateEmployeeWorkReadiness } from "@/domain/readiness/service";
import { prisma } from "@/lib/prisma";

type PolicyInput={code:string;title:string;description?:string;requiresAcknowledgment?:boolean;reacknowledgeOnNewVersion?:boolean;blockingScope?:"GENERAL_WORK"|"DIRECT_CONTACT"|"UNSUPERVISED_CONTACT"|"PERSON_SPECIFIC_TASK"|"MEDICATION_ADMINISTRATION"};
const policyInput=z.object({code:z.string().trim().min(1).max(100),title:z.string().trim().min(1).max(255),description:z.string().trim().max(2000).optional(),requiresAcknowledgment:z.boolean().optional(),reacknowledgeOnNewVersion:z.boolean().optional(),blockingScope:z.enum(["GENERAL_WORK","DIRECT_CONTACT","UNSUPERVISED_CONTACT","PERSON_SPECIFIC_TASK","MEDICATION_ADMINISTRATION"]).optional()}).strict();
const versionInput=z.object({effectiveFrom:z.coerce.date(),body:z.string().min(1).max(1_000_000)}).strict();
async function permitted(user:Pick<User,"id">,organizationId:string,code:string){const{membership}=await requireOrganizationAccess(user,organizationId);await requirePermission(membership.id,code)}
async function audit(organizationId:string,actorUserId:string,eventType:string,entityType:string,entityId:string,metadataJson?:Prisma.InputJsonValue,employeeId?:string){await prisma.auditEvent.create({data:{organizationId,actorUserId,eventType,entityType,entityId,metadataJson,employeeId}})}

export async function listPolicyLibrary(user:Pick<User,"id">,organizationId:string,filters:{search?:string;status?:PolicyStatus;requiresAcknowledgment?:boolean;outstanding?:boolean;page?:number;pageSize?:number}={}){
 await permitted(user,organizationId,"policy.read");const requestedPage=Number.isFinite(filters.page)?filters.page!:1,requestedPageSize=Number.isFinite(filters.pageSize)?filters.pageSize!:25,page=Math.max(1,Math.floor(requestedPage)),pageSize=Math.max(1,Math.min(Math.floor(requestedPageSize),100)),search=filters.search?.trim();
 const where:Prisma.PolicyWhereInput={organizationId,status:filters.status,requiresAcknowledgment:filters.requiresAcknowledgment,OR:search?[{code:{contains:search,mode:"insensitive"}},{title:{contains:search,mode:"insensitive"}},{description:{contains:search,mode:"insensitive"}}]:undefined,...(filters.outstanding?{versions:{some:{assignments:{some:{status:{in:["PENDING","OVERDUE"]}}}}}}:{})};
 const [total,policies]=await Promise.all([prisma.policy.count({where}),prisma.policy.findMany({where,orderBy:[{title:"asc"},{code:"asc"},{id:"asc"}],skip:(page-1)*pageSize,take:pageSize,include:{versions:{orderBy:{versionNumber:"desc"},include:{assignments:{select:{status:true,dueAt:true,acknowledgedAt:true}}}}}})]),now=new Date(),dueSoon=new Date(now.getTime()+30*86_400_000);
 const items=policies.map(policy=>{const current=policy.versions.find(version=>version.status==="PUBLISHED")??null,assignments=current?.assignments??[],acknowledged=assignments.filter(row=>row.status==="ACKNOWLEDGED").length,outstanding=assignments.filter(row=>["PENDING","OVERDUE"].includes(row.status)).length,overdue=assignments.filter(row=>row.dueAt&&row.dueAt<now&&row.status!=="ACKNOWLEDGED").length,dueSoonCount=assignments.filter(row=>row.dueAt&&row.dueAt>=now&&row.dueAt<=dueSoon&&row.status!=="ACKNOWLEDGED").length;return{id:policy.id,code:policy.code,title:policy.title,description:policy.description,status:policy.status,requiresAcknowledgment:policy.requiresAcknowledgment,reacknowledgeOnNewVersion:policy.reacknowledgeOnNewVersion,blockingScope:policy.blockingScope,currentVersion:current?{id:current.id,versionNumber:current.versionNumber,status:current.status,effectiveFrom:current.effectiveFrom,publishedAt:current.publishedAt,contentHash:current.contentHash}:null,lastVersionAt:policy.versions[0]?.createdAt??policy.createdAt,versionCount:policy.versions.length,distribution:{assigned:assignments.length,acknowledged,outstanding,overdue,dueSoon:dueSoonCount,acknowledgmentPercentage:assignments.length?Math.round(acknowledged/assignments.length*100):null}}});
 return{organizationId,page,pageSize,total,pages:Math.max(1,Math.ceil(total/pageSize)),items,semantics:{dueSoonDays:30,acknowledgmentPercentage:"Acknowledged assignments divided by current-version assignments; not legal compliance."}};
}
export async function getPolicyOperationsSummary(user:Pick<User,"id">,organizationId:string){await permitted(user,organizationId,"policy.read");const now=new Date(),recentSince=new Date(now.getTime()-30*86_400_000),[activePolicies,assignments,recent]=await Promise.all([prisma.policy.count({where:{organizationId,status:"ACTIVE",versions:{some:{status:"PUBLISHED"}}}}),prisma.policyAssignment.findMany({where:{organizationId,policyVersion:{status:"PUBLISHED",policy:{status:"ACTIVE"}}},select:{status:true,dueAt:true,employeeId:true}}),prisma.policyVersion.count({where:{policy:{organizationId},publishedAt:{gte:recentSince}}})]),acknowledged=assignments.filter(row=>row.status==="ACKNOWLEDGED").length,outstanding=assignments.filter(row=>["PENDING","OVERDUE"].includes(row.status)).length,overdue=assignments.filter(row=>row.dueAt&&row.dueAt<now&&row.status!=="ACKNOWLEDGED").length;return{organizationId,generatedAt:now.toISOString(),activePolicies,assigned:assignments.length,acknowledged,outstanding,overdue,employeesOutstanding:new Set(assignments.filter(row=>["PENDING","OVERDUE"].includes(row.status)).map(row=>row.employeeId)).size,recentlyPublishedOrRevised:recent,acknowledgmentPercentage:assignments.length?Math.round(acknowledged/assignments.length*100):null,disclaimer:"Operational policy acknowledgment metrics are not a legal compliance certification."}}
export async function getPolicyDetail(user:Pick<User,"id">,organizationId:string,policyId:string){
 await permitted(user,organizationId,"policy.read");
 const policy=await prisma.policy.findFirst({where:{id:policyId,organizationId},include:{versions:{orderBy:{versionNumber:"desc"},include:{createdBy:{select:{email:true}},assignments:{include:{employee:{select:{id:true,firstName:true,lastName:true,employeeNumber:true,employmentStatus:true}},attestation:{select:{id:true,signedAt:true,typedName:true,statementVersion:true,signatureHash:true}}},orderBy:[{status:"asc"},{assignedAt:"asc"},{id:"asc"}]}}}}});
 if(!policy)throw new ResourceNotFoundError("Policy not found");return policy;
}

export async function createPolicy(user:Pick<User,"id">,organizationId:string,input:PolicyInput){await permitted(user,organizationId,"policy.manage");const data=policyInput.parse(input),policy=await prisma.policy.create({data:{organizationId,...data}});await audit(organizationId,user.id,"policy.created","Policy",policy.id,{code:policy.code,requiresAcknowledgment:policy.requiresAcknowledgment});return policy}
export async function correctPolicyMetadata(user:Pick<User,"id">,organizationId:string,policyId:string,raw:unknown){await permitted(user,organizationId,"policy.manage");const parsed=policyInput.partial().extend({reason:z.string().trim().min(3).max(1000)}).strict().parse(raw),{reason,...changes}=parsed,policy=await prisma.policy.findFirst({where:{id:policyId,organizationId}});if(!policy)throw new ResourceNotFoundError("Policy not found");const changedFields=Object.keys(changes).filter(key=>changes[key as keyof typeof changes]!==undefined&&String(changes[key as keyof typeof changes]??"")!==String(policy[key as keyof typeof policy]??""));if(!changedFields.length)return{policy,changedFields};const updated=await prisma.policy.update({where:{id:policy.id},data:changes});await audit(organizationId,user.id,"policy.metadata_corrected","Policy",policy.id,{changedFields,administrativeReason:reason});return{policy:updated,changedFields}}
export async function createPolicyVersion(user:Pick<User,"id">,organizationId:string,policyId:string,input:{effectiveFrom:Date;body:string}){await permitted(user,organizationId,"policy.manage");const data=versionInput.parse(input),policy=await prisma.policy.findFirst({where:{id:policyId,organizationId,status:"ACTIVE"}});if(!policy)throw new ResourceNotFoundError("Active policy not found");const last=await prisma.policyVersion.findFirst({where:{policyId},orderBy:{versionNumber:"desc"}}),version=await prisma.policyVersion.create({data:{policyId,versionNumber:(last?.versionNumber??0)+1,effectiveFrom:data.effectiveFrom,body:data.body,contentHash:createHash("sha256").update(data.body).digest("hex"),createdByUserId:user.id}});await audit(organizationId,user.id,"policy.version_created","PolicyVersion",version.id,{policyId,versionNumber:version.versionNumber,effectiveFrom:version.effectiveFrom.toISOString()});return version}
export async function updateDraftPolicyVersion(user:Pick<User,"id">,organizationId:string,id:string,raw:unknown){await permitted(user,organizationId,"policy.manage");const input=z.object({effectiveFrom:z.coerce.date().optional(),body:z.string().min(1).max(1_000_000).optional(),reason:z.string().trim().min(3).max(1000)}).strict().parse(raw),version=await prisma.policyVersion.findFirst({where:{id,policy:{organizationId}}});if(!version)throw new ResourceNotFoundError("Policy version not found");if(version.status!=="DRAFT")throw new AuthorizationError("Published and historical policy versions are immutable");const changedFields=[...(input.effectiveFrom&&input.effectiveFrom.getTime()!==version.effectiveFrom.getTime()?["effectiveFrom"]:[]),...(input.body&&input.body!==version.body?["body"]:[])],updated=await prisma.policyVersion.update({where:{id},data:{effectiveFrom:input.effectiveFrom,body:input.body,contentHash:input.body?createHash("sha256").update(input.body).digest("hex"):undefined}});if(changedFields.length)await audit(organizationId,user.id,"policy.draft_corrected","PolicyVersion",id,{policyId:version.policyId,versionNumber:version.versionNumber,changedFields,administrativeReason:input.reason});return updated}

export async function publishPolicyVersion(user:Pick<User,"id">,organizationId:string,id:string){await permitted(user,organizationId,"policy.manage");return prisma.$transaction(async tx=>{const version=await tx.policyVersion.findFirst({where:{id,policy:{organizationId,status:"ACTIVE"}},include:{policy:true}});if(!version)throw new ResourceNotFoundError("Policy version not found");if(version.status!=="DRAFT")throw new ValidationError("Only draft policy versions may be published");const now=new Date(),prior=await tx.policyVersion.findFirst({where:{policyId:version.policyId,status:"PUBLISHED"},include:{assignments:true}}),eligibleEmployeeIds=prior?prior.assignments.filter(row=>["PENDING","OVERDUE"].includes(row.status)||version.policy.reacknowledgeOnNewVersion&&row.status==="ACKNOWLEDGED").map(row=>row.employeeId):[];
  if(prior){await tx.policyVersion.update({where:{id:prior.id},data:{status:"SUPERSEDED",effectiveUntil:now}});await tx.policyAssignment.updateMany({where:{policyVersionId:prior.id,status:{in:["PENDING","OVERDUE"]}},data:{status:"SUPERSEDED"}});await tx.auditEvent.create({data:{organizationId,actorUserId:user.id,eventType:"policy.version_superseded",entityType:"PolicyVersion",entityId:prior.id,metadataJson:{policyId:version.policyId,replacedByVersionId:version.id}}})}
  const published=await tx.policyVersion.update({where:{id},data:{status:"PUBLISHED",publishedAt:now}}),activeEmployees=eligibleEmployeeIds.length?await tx.employee.findMany({where:{organizationId,id:{in:[...new Set(eligibleEmployeeIds)]},employmentStatus:"ACTIVE"},select:{id:true}}):[];
  if(version.policy.requiresAcknowledgment&&activeEmployees.length)await tx.policyAssignment.createMany({data:activeEmployees.map(employee=>({fingerprint:[organizationId,employee.id,version.id,"ORGANIZATION_POLICY",version.id].join(":"),organizationId,employeeId:employee.id,policyVersionId:version.id,sourceType:"ORGANIZATION_POLICY",sourceReferenceId:version.id,assignedByUserId:user.id})),skipDuplicates:true});
  const reacknowledgmentAssignments=version.policy.requiresAcknowledgment?activeEmployees.length:0;if(reacknowledgmentAssignments)await tx.auditEvent.create({data:{organizationId,actorUserId:user.id,eventType:"policy.reacknowledgment_required",entityType:"PolicyVersion",entityId:version.id,metadataJson:{policyId:version.policyId,versionNumber:version.versionNumber,assignmentCount:reacknowledgmentAssignments}}});
  await tx.auditEvent.create({data:{organizationId,actorUserId:user.id,eventType:"policy.version_published",entityType:"PolicyVersion",entityId:version.id,metadataJson:{policyId:version.policyId,versionNumber:version.versionNumber,supersededVersionId:prior?.id??null,reacknowledgmentAssignments}}});return published})}
export async function archivePolicy(user:Pick<User,"id">,organizationId:string,policyId:string,reason:string){await permitted(user,organizationId,"policy.manage");const explanation=z.string().trim().min(3).max(1000).parse(reason),policy=await prisma.policy.findFirst({where:{id:policyId,organizationId}});if(!policy)throw new ResourceNotFoundError("Policy not found");if(policy.status==="ARCHIVED")return policy;return prisma.$transaction(async tx=>{const updated=await tx.policy.update({where:{id:policy.id},data:{status:"ARCHIVED"}});await tx.policyVersion.updateMany({where:{policyId,status:"PUBLISHED"},data:{status:"RETIRED",effectiveUntil:new Date()}});await tx.policyAssignment.updateMany({where:{policyVersion:{policyId},status:{in:["PENDING","OVERDUE"]}},data:{status:"CANCELED"}});await tx.auditEvent.create({data:{organizationId,actorUserId:user.id,eventType:"policy.archived",entityType:"Policy",entityId:policy.id,metadataJson:{administrativeReason:explanation}}});return updated})}

export async function assignPolicy(user:Pick<User,"id">|null,organizationId:string,employeeId:string,policyVersionId:string,sourceType:"ONBOARDING"|"COMPLIANCE"|"MANUAL"|"ORGANIZATION_POLICY",sourceReferenceId?:string,dueAt?:Date){if(user)await permitted(user,organizationId,"policy.assign");const[employee,version]=await Promise.all([prisma.employee.findFirst({where:{id:employeeId,organizationId}}),prisma.policyVersion.findFirst({where:{id:policyVersionId,status:"PUBLISHED",policy:{organizationId,status:"ACTIVE"}}})]);if(!employee||!version)throw new ResourceNotFoundError("Published active policy or employee not found");if(user&&["LEAVE","TERMINATED","ARCHIVED"].includes(employee.employmentStatus))throw new ValidationError("New manual policy assignments are not allowed for inactive employees");const fingerprint=[organizationId,employeeId,policyVersionId,sourceType,sourceReferenceId??""].join(":"),existing=await prisma.policyAssignment.findUnique({where:{fingerprint}}),assignment=await prisma.policyAssignment.upsert({where:{fingerprint},create:{fingerprint,organizationId,employeeId,policyVersionId,sourceType,sourceReferenceId,dueAt,assignedByUserId:user?.id},update:{dueAt}});if(user&&!existing)await audit(organizationId,user.id,"policy.assigned","PolicyAssignment",assignment.id,{policyVersionId,sourceType,dueAt:dueAt?.toISOString()??null},employeeId);return assignment}
export async function bulkAssignPolicy(user:Pick<User,"id">,organizationId:string,policyVersionId:string,employeeIds:string[],dueAt?:Date){await permitted(user,organizationId,"policy.assign");const ids=[...new Set(z.array(z.string().cuid()).min(1).max(500).parse(employeeIds))],employees=await prisma.employee.findMany({where:{organizationId,id:{in:ids}},select:{id:true,employmentStatus:true}});if(employees.length!==ids.length)throw new ValidationError("One or more employees are outside this organization");const results=[];for(const employee of employees){if(["LEAVE","TERMINATED","ARCHIVED"].includes(employee.employmentStatus)){results.push({employeeId:employee.id,status:"SKIPPED",reason:"Employee is inactive"});continue}const existing=await prisma.policyAssignment.findFirst({where:{organizationId,employeeId:employee.id,policyVersionId,status:{in:["PENDING","OVERDUE","ACKNOWLEDGED"]}},orderBy:{createdAt:"asc"}});if(existing){results.push({employeeId:employee.id,status:"EXISTING",assignmentId:existing.id});continue}const assignment=await assignPolicy(user,organizationId,employee.id,policyVersionId,"ORGANIZATION_POLICY",`bulk:${policyVersionId}`,dueAt);results.push({employeeId:employee.id,status:"ASSIGNED",assignmentId:assignment.id})}await audit(organizationId,user.id,"policy.bulk_assigned","PolicyVersion",policyVersionId,{requested:ids.length,assigned:results.filter(row=>row.status==="ASSIGNED").length,existing:results.filter(row=>row.status==="EXISTING").length,skipped:results.filter(row=>row.status==="SKIPPED").length,dueAt:dueAt?.toISOString()??null});return results}

export async function acknowledgePolicy(user:Pick<User,"id">,organizationId:string,assignmentId:string,input:{typedName:string;ipAddress?:string;userAgent?:string;sessionReference?:string}){const assignment=await prisma.policyAssignment.findFirst({where:{id:assignmentId,organizationId},include:{employee:true,policyVersion:{include:{policy:true}},attestation:true}});if(!assignment)throw new ResourceNotFoundError("Policy assignment not found");await requireEmployeeSelfAccess(user,organizationId,assignment.employeeId);if(assignment.attestation)return assignment;if(!["PENDING","OVERDUE"].includes(assignment.status))throw new ValidationError("This policy assignment is not available for acknowledgment");const signedAt=new Date(),statement=`I acknowledge that I reviewed policy ${assignment.policyVersion.policy.title}, version ${assignment.policyVersion.versionNumber}.`,canonical=JSON.stringify({organizationId,signerUserId:user.id,resourceType:"POLICY_ASSIGNMENT",resourceId:assignment.id,resourceVersionId:assignment.policyVersionId,statementVersion:`policy-${assignment.policyVersion.versionNumber}`,statementSnapshot:statement,signedAt:signedAt.toISOString()});const result=await prisma.$transaction(async tx=>{const attestation=await tx.attestation.create({data:{organizationId,attestationType:"POLICY_ACKNOWLEDGMENT",signerUserId:user.id,signerEmployeeId:assignment.employeeId,typedName:input.typedName,statementVersion:`policy-${assignment.policyVersion.versionNumber}`,statementSnapshot:statement,resourceType:"POLICY_ASSIGNMENT",resourceId:assignment.id,resourceVersionId:assignment.policyVersionId,signedAt,ipAddress:input.ipAddress,userAgent:input.userAgent,sessionReference:input.sessionReference,signatureHash:createHash("sha256").update(canonical).digest("hex")}}),saved=await tx.policyAssignment.update({where:{id:assignment.id},data:{status:"ACKNOWLEDGED",acknowledgedAt:signedAt,attestationId:attestation.id}});await tx.auditEvent.create({data:{organizationId,actorUserId:user.id,employeeId:assignment.employeeId,eventType:"employee.policy_acknowledged",entityType:"PolicyAssignment",entityId:assignment.id,metadataJson:{policyVersionId:assignment.policyVersionId,attestationId:attestation.id}}});return saved});await evaluateEmployeeWorkReadiness(organizationId,assignment.employeeId,"POLICY_ACKNOWLEDGED");return result}
export async function updatePublishedPolicyVersion(){throw new AuthorizationError("Published policy versions are immutable")}
