import { Prisma, type User } from "@prisma/client";
import { z } from "zod";
import { ValidationError } from "@/domain/auth/errors";
import { evaluateEmployeeCompliance } from "@/domain/compliance/evaluation/service";
import { reconcileEmployeeIssues } from "@/domain/compliance-issues/service";
import { requireOrganizationAccess, requirePermission } from "@/domain/permissions/authorization";
import { inviteEmployeeToPortal } from "@/domain/portal/service";
import { prisma } from "@/lib/prisma";

export const workforceCsvHeaders=["employee_number","first_name","last_name","email","hire_date","employment_status","job_title","employment_type"] as const;
export const workforceCsvTemplate=`${workforceCsvHeaders.join(",")}\nEMP-001,Jordan,Lee,jordan.lee@example.com,2024-06-15,ACTIVE,Direct Support Professional,FULL_TIME\n`;
const maxBytes=1024*1024,maxRows=1000,unsafe=/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/,formula=/^[=+\-@]/;
const value=z.string().trim().max(255).refine(v=>!unsafe.test(v),"Control characters are not allowed").refine(v=>!formula.test(v),"Spreadsheet formula prefixes are not allowed");
const rowSchema=z.object({employee_number:value.optional().default(""),first_name:value.min(1),last_name:value.min(1),email:z.string().trim().email().or(z.literal("")),hire_date:z.iso.date().or(z.literal("")),employment_status:z.enum(["PENDING","ACTIVE","LEAVE","TERMINATED"]).default("PENDING"),job_title:value.optional().default(""),employment_type:z.enum(["FULL_TIME","PART_TIME","TEMPORARY","CONTRACTOR","VOLUNTEER","OTHER"]).or(z.literal(""))}).strict();
type Parsed=z.infer<typeof rowSchema>;
export type ImportRow={rowNumber:number;state:"READY"|"DUPLICATE"|"CONFLICT"|"INVALID"|"ALREADY_EXISTS";reasons:string[];data:Parsed|null;existingEmployeeId?:string};
async function authorize(user:Pick<User,"id">,organizationId:string,permission="employee.manage"){const{membership}=await requireOrganizationAccess(user,organizationId);await requirePermission(membership.id,permission);}
function parseCsv(csv:string){if(Buffer.byteLength(csv,"utf8")>maxBytes)throw new ValidationError("CSV exceeds the 1 MB limit");const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<csv.length;i++){const char=csv[i];if(char==='"'){if(quoted&&csv[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(char===","&&!quoted){row.push(cell);cell=""}else if((char==="\n"||char==="\r")&&!quoted){if(char==="\r"&&csv[i+1]==="\n")i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell=""}else cell+=char}if(quoted)throw new ValidationError("Malformed CSV: unclosed quoted field");row.push(cell);if(row.some(v=>v.trim()))rows.push(row);if(!rows.length)throw new ValidationError("CSV is empty");if(rows.length-1>maxRows)throw new ValidationError(`CSV exceeds the ${maxRows}-row limit`);return rows;}
const key=(text:string)=>text.trim().toLowerCase();
export async function previewWorkforceCsv(user:Pick<User,"id">,organizationId:string,csv:string){await authorize(user,organizationId);const rows=parseCsv(csv),headers=rows[0].map(v=>v.trim().toLowerCase());if(headers.join("|")!==workforceCsvHeaders.join("|"))throw new ValidationError("Unexpected CSV columns",{expected:workforceCsvHeaders,received:headers});const raw=rows.slice(1),numbers=raw.map(r=>key(r[0]??"")).filter(Boolean),emails=raw.map(r=>key(r[3]??"")).filter(Boolean),existing=await prisma.employee.findMany({where:{organizationId,OR:[{employeeNumber:{in:numbers,mode:"insensitive"}},{email:{in:emails,mode:"insensitive"}}]},select:{id:true,employeeNumber:true,email:true,firstName:true,lastName:true}}),seenNumbers=new Set<string>(),seenEmails=new Set<string>();
 const results:ImportRow[]=raw.map((cells,index)=>{const rowNumber=index+2;if(cells.length!==headers.length)return{rowNumber,state:"INVALID",reasons:[`Expected ${headers.length} columns; received ${cells.length}`],data:null};const record=Object.fromEntries(headers.map((header,i)=>[header,(cells[i]??"").trim()]));const parsed=rowSchema.safeParse(record);if(!parsed.success)return{rowNumber,state:"INVALID",reasons:parsed.error.issues.map(issue=>`${issue.path.join(".")}: ${issue.message}`),data:null};const data=parsed.data,number=key(data.employee_number),email=key(data.email),duplicate=(number&&seenNumbers.has(number))||(email&&seenEmails.has(email));if(number)seenNumbers.add(number);if(email)seenEmails.add(email);if(duplicate)return{rowNumber,state:"DUPLICATE",reasons:["Duplicate employee number or email within this file"],data};const numberMatch=number?existing.find(item=>key(item.employeeNumber??"")===number):undefined,emailMatch=email?existing.find(item=>key(item.email??"")===email):undefined;if(numberMatch&&emailMatch&&numberMatch.id!==emailMatch.id)return{rowNumber,state:"CONFLICT",reasons:["Employee number and email match different existing workforce records"],data};const match=numberMatch??emailMatch;if(match){const sameName=key(match.firstName)===key(data.first_name)&&key(match.lastName)===key(data.last_name);return{rowNumber,state:sameName?"ALREADY_EXISTS":"CONFLICT",reasons:[sameName?"Matching workforce record already exists":"Identifier conflicts with an existing workforce record"],data,existingEmployeeId:match.id}}return{rowNumber,state:"READY",reasons:[],data}});
 return{organizationId,totalRows:results.length,counts:Object.fromEntries(["READY","DUPLICATE","CONFLICT","INVALID","ALREADY_EXISTS"].map(state=>[state,results.filter(row=>row.state===state).length])),rows:results};}
function employeeData(data:Parsed){return{employeeNumber:data.employee_number||null,firstName:data.first_name,lastName:data.last_name,email:data.email.toLowerCase()||null,hireDate:data.hire_date?new Date(`${data.hire_date}T00:00:00.000Z`):null,employmentStatus:data.employment_status,jobTitle:data.job_title||null,employmentType:data.employment_type||null};}
export async function confirmWorkforceImport(user:Pick<User,"id">,organizationId:string,csv:string){
 const preview=await previewWorkforceCsv(user,organizationId,csv),blocking=preview.rows.filter(row=>["INVALID","DUPLICATE","CONFLICT"].includes(row.state));if(blocking.length)throw new ValidationError("Import contains rows requiring correction",{rows:blocking});const ready=preview.rows.filter(row=>row.state==="READY"&&row.data);
 const created=await prisma.$transaction(async tx=>{const latest=await tx.employee.findMany({where:{organizationId,OR:[{employeeNumber:{in:ready.map(row=>row.data!.employee_number).filter(Boolean),mode:"insensitive"}},{email:{in:ready.map(row=>row.data!.email).filter(Boolean),mode:"insensitive"}}]},select:{id:true}});if(latest.length)throw new ValidationError("Workforce changed after preview; preview again");const records=[];for(const row of ready){const employee=await tx.employee.create({data:{organizationId,...employeeData(row.data!)}});records.push(employee);await tx.auditEvent.create({data:{organizationId,actorUserId:user.id,employeeId:employee.id,eventType:"employee.created",entityType:"Employee",entityId:employee.id,metadataJson:{source:"CSV_IMPORT",rowNumber:row.rowNumber}}});}if(records.length)await tx.auditEvent.create({data:{organizationId,actorUserId:user.id,eventType:"workforce.import_completed",entityType:"Organization",entityId:organizationId,metadataJson:{createdCount:records.length,alreadyExistingCount:preview.counts.ALREADY_EXISTS}}});return records},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
 for(const employee of created)await evaluateEmployeeCompliance(organizationId,employee.id,"EMPLOYEE_CREATED");return{created:created.map(row=>({id:row.id,employeeNumber:row.employeeNumber,email:row.email})),alreadyExisting:preview.rows.filter(row=>row.state==="ALREADY_EXISTS").map(row=>({rowNumber:row.rowNumber,employeeId:row.existingEmployeeId})),counts:{created:created.length,alreadyExisting:preview.counts.ALREADY_EXISTS}};
}
export async function bulkInviteEmployees(user:Pick<User,"id">,organizationId:string,employeeIds:string[]){await authorize(user,organizationId);const ids=[...new Set(z.array(z.string().cuid()).max(1000).parse(employeeIds))],employees=await prisma.employee.findMany({where:{organizationId,id:{in:ids}},include:{portalInvitations:{orderBy:{invitedAt:"desc"},take:1}}});if(employees.length!==ids.length)throw new ValidationError("One or more employee identifiers are invalid for this organization");const results=[];for(const employee of employees){const current=employee.portalInvitations[0];if(current&&["PENDING","ACCEPTED"].includes(current.status)){results.push({employeeId:employee.id,status:"SKIPPED",reason:`Invitation is ${current.status.toLowerCase()}`});continue}if(!employee.email){results.push({employeeId:employee.id,status:"INELIGIBLE",reason:"Employee email is required"});continue}const invited=await inviteEmployeeToPortal(user,organizationId,employee.id);results.push({employeeId:employee.id,status:"INVITED",invitationId:invited.invitation.id,claimToken:invited.claimToken});}if(results.some(row=>row.status==="INVITED"))await prisma.auditEvent.create({data:{organizationId,actorUserId:user.id,eventType:"workforce.bulk_invitations_issued",entityType:"Organization",entityId:organizationId,metadataJson:{invitedCount:results.filter(row=>row.status==="INVITED").length}}});return results;}
export async function initializeApplicableTraining(user:Pick<User,"id">,organizationId:string,employeeIds:string[]){await authorize(user,organizationId,"training.assignment.manage");const ids=[...new Set(z.array(z.string().cuid()).max(1000).parse(employeeIds))],employees=await prisma.employee.findMany({where:{organizationId,id:{in:ids}},select:{id:true}});if(employees.length!==ids.length)throw new ValidationError("One or more employee identifiers are invalid for this organization");const results=[];for(const employee of employees){const before=await prisma.trainingAssignment.count({where:{organizationId,employeeId:employee.id}}),evaluation=await evaluateEmployeeCompliance(organizationId,employee.id,"MANUAL"),after=await prisma.trainingAssignment.count({where:{organizationId,employeeId:employee.id}});results.push({employeeId:employee.id,requirements:evaluation.instances.length,unresolved:evaluation.unresolved,assignmentsCreated:after-before});await reconcileEmployeeIssues(user,organizationId,employee.id);}const assignmentsCreated=results.reduce((sum,row)=>sum+row.assignmentsCreated,0);if(assignmentsCreated)await prisma.auditEvent.create({data:{organizationId,actorUserId:user.id,eventType:"workforce.training_initialization_completed",entityType:"Organization",entityId:organizationId,metadataJson:{employeeCount:employees.length,assignmentsCreated}}});return results;}
export async function getWorkforceOnboardingStatus(user:Pick<User,"id">,organizationId:string){await authorize(user,organizationId);const employees=await prisma.employee.findMany({where:{organizationId,employmentStatus:{not:"ARCHIVED"}},include:{portalInvitations:{orderBy:{invitedAt:"desc"},take:1},trainingAssignments:{include:{completion:true}},externalTrainingRecords:true,policyAssignments:true,competencyAssessments:true,complianceIssues:{where:{status:{in:["OPEN","IN_PROGRESS"]}}}},orderBy:[{lastName:"asc"},{firstName:"asc"}]});return employees.map(employee=>{const pendingTraining=employee.trainingAssignments.filter(row=>!row.completion&&!['CANCELLED','SUPERSEDED'].includes(row.status)).length,evidenceReview=employee.externalTrainingRecords.filter(row=>row.reviewStatus!=="APPROVED").length,actions=pendingTraining+evidenceReview+employee.policyAssignments.filter(row=>row.status!=="ACKNOWLEDGED").length+employee.competencyAssessments.filter(row=>row.status!=="FINALIZED").length+employee.complianceIssues.length;return{id:employee.id,employeeNumber:employee.employeeNumber,name:`${employee.firstName} ${employee.lastName}`,hireDate:employee.hireDate,invitationStatus:employee.portalInvitations[0]?.status??"NOT_INVITED",pendingTraining,evidenceReview,openIssues:employee.complianceIssues.length,state:actions?"ACTION_REQUIRED":employee.userId?"READY_FOR_NORMAL_OPERATIONS":"RECORD_CREATED"};});}
