"use client";
import { DragEvent, FormEvent, KeyboardEvent, useEffect, useRef, useState } from "react";

type Method="UPLOAD"|"DETAILS"|null;
type Details={legalFirstName:string;legalLastName:string;preferredName:string;dateOfBirth:string;maPmiNumber:string;phone:string;email:string};
const emptyDetails:Details={legalFirstName:"",legalLastName:"",preferredName:"",dateOfBirth:"",maPmiNumber:"",phone:"",email:""};
const MAX_FILES=20,MAX_FILE_BYTES=10_000_000,MAX_TOTAL_BYTES=50_000_000;
async function base64(file:File){const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(let offset=0;offset<bytes.length;offset+=32768)binary+=String.fromCharCode(...bytes.subarray(offset,offset+32768));return btoa(binary)}
const size=(bytes:number)=>bytes>=1_000_000?`${(bytes/1_000_000).toFixed(1)} MB`:`${Math.max(1,Math.round(bytes/1000))} KB`;

export default function AddClientDrawer({open,organizationId,headers,onClose,onClientCreated,onImportCreated}:{open:boolean;organizationId:string;headers:Record<string,string>;onClose:()=>void;onClientCreated:(clientId:string)=>void;onImportCreated:(sessionId:string)=>void}){
  const[method,setMethod]=useState<Method>(null),[details,setDetails]=useState<Details>(emptyDetails),[files,setFiles]=useState<File[]>([]),[status,setStatus]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[dragging,setDragging]=useState(false);
  const dialog=useRef<HTMLElement>(null),closeButton=useRef<HTMLButtonElement>(null),returnFocus=useRef<HTMLElement|null>(null),clientRequestId=useRef(crypto.randomUUID()),importRequestId=useRef(crypto.randomUUID());
  useEffect(()=>{if(open){returnFocus.current=document.activeElement instanceof HTMLElement?document.activeElement:null;closeButton.current?.focus();document.body.style.overflow="hidden"}return()=>{document.body.style.overflow="";returnFocus.current?.focus()}},[open]);
  if(!open)return null;
  function close(){if(!busy)onClose()}
  function keyDown(event:KeyboardEvent){if(event.key==="Escape"){event.preventDefault();close()}if(event.key==="Tab"&&dialog.current){const focusable=[...dialog.current.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[href]')];if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}}
  function methodKeyDown(event:KeyboardEvent<HTMLButtonElement>,next:Exclude<Method,null>){if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(event.key)){event.preventDefault();choose(next);[...(event.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>('[role="radio"]')??[])].find(button=>button!==event.currentTarget)?.focus()}}
  function choose(next:Method){setMethod(next);setError("");setStatus("")}
  function validateFiles(next:File[]){if(next.length>MAX_FILES)return`Select no more than ${MAX_FILES} PDFs.`;if(next.some(file=>file.type!=="application/pdf"&&!file.name.toLowerCase().endsWith(".pdf")))return"Only PDF files can be uploaded.";if(next.some(file=>file.size>MAX_FILE_BYTES))return"Each PDF must be 10 MB or smaller.";if(next.reduce((sum,file)=>sum+file.size,0)>MAX_TOTAL_BYTES)return"Selected PDFs must total no more than 50 MB.";return""}
  function addFiles(selected:File[]){const next=[...files,...selected],validation=validateFiles(next);if(validation){setError(validation);return}setFiles(next);setError("")}
  function drop(event:DragEvent){event.preventDefault();setDragging(false);addFiles([...event.dataTransfer.files])}
  async function create(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setStatus("Creating client…");setError("");try{const response=await fetch(`/api/organizations/${organizationId}/clients`,{method:"POST",headers,body:JSON.stringify({...details,dateOfBirth:details.dateOfBirth||undefined,preferredName:details.preferredName||undefined,maPmiNumber:details.maPmiNumber||undefined,phone:details.phone||undefined,email:details.email||undefined,requestId:clientRequestId.current})}),result=await response.json();if(!response.ok)throw new Error(result.error??"Client could not be created.");setStatus("Opening guided intake…");onClientCreated(result.client.id)}catch(reason){setError(reason instanceof Error?reason.message:"Client could not be created. Review the fields and retry.");setStatus("");setBusy(false)}}
  async function upload(){if(busy)return;const validation=validateFiles(files);if(validation||!files.length){setError(validation||"Select one or more PDFs.");return}setBusy(true);setStatus("Uploading documents…");setError("");try{const encoded=await Promise.all(files.map(async file=>({fileName:file.name,mimeType:"application/pdf" as const,pdfBase64:await base64(file)})));setStatus("Preparing review…");const response=await fetch(`/api/organizations/${organizationId}/clients/imports`,{method:"POST",headers,body:JSON.stringify({action:"CREATE",requestId:importRequestId.current,target:"CREATE_NEW",files:encoded})}),result=await response.json();if(!response.ok)throw new Error(result.error??"Documents could not be prepared for review.");setStatus("Opening review…");onImportCreated(result.id)}catch(reason){setError(reason instanceof Error?reason.message:"Upload failed. Your selected files are still available to retry.");setStatus("");setBusy(false)}}
  const update=(name:keyof Details,value:string)=>setDetails(current=>({...current,[name]:value}));
  return <div className="drawer-backdrop add-client-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section ref={dialog} className="portal-drawer add-client-drawer" role="dialog" aria-modal="true" aria-labelledby="add-client-title" onKeyDown={keyDown}>
    <header className="drawer-heading"><div><h2 id="add-client-title">Add client</h2><p>Choose how you&apos;d like to get started.</p></div><button ref={closeButton} type="button" className="icon-button" aria-label="Close add client" disabled={busy} onClick={close}>×</button></header>
    <div className="add-client-content"><div className="method-options" role="radiogroup" aria-label="Add client method"><button type="button" role="radio" aria-checked={method==="UPLOAD"} className={`method-card ${method==="UPLOAD"?"selected":""}`} disabled={busy} onClick={()=>choose("UPLOAD")} onKeyDown={event=>methodKeyDown(event,"DETAILS")}><span className="method-icon" aria-hidden="true">⇧</span><span><strong>Upload documents</strong><small>Start from existing PDFs and review extracted information.</small></span><em>Recommended</em></button><button type="button" role="radio" aria-checked={method==="DETAILS"} className={`method-card ${method==="DETAILS"?"selected":""}`} disabled={busy} onClick={()=>choose("DETAILS")} onKeyDown={event=>methodKeyDown(event,"UPLOAD")}><span className="method-icon" aria-hidden="true">＋</span><span><strong>Enter details</strong><small>Create the client, then continue through guided intake.</small></span></button></div>
      {method==="DETAILS"?<form className="drawer-form" onSubmit={create}><div className="form-grid"><label>Legal first name <span>Required</span><input value={details.legalFirstName} onChange={event=>update("legalFirstName",event.target.value)} required maxLength={100}/></label><label>Legal last name <span>Required</span><input value={details.legalLastName} onChange={event=>update("legalLastName",event.target.value)} required maxLength={100}/></label><label>Preferred name <span>Optional</span><input value={details.preferredName} onChange={event=>update("preferredName",event.target.value)} maxLength={100}/></label><label>Date of birth <span>Optional</span><input type="date" value={details.dateOfBirth} onChange={event=>update("dateOfBirth",event.target.value)}/></label><label>MA / PMI <span>Optional</span><input value={details.maPmiNumber} onChange={event=>update("maPmiNumber",event.target.value)} maxLength={100}/></label><label>Phone <span>Optional</span><input type="tel" value={details.phone} onChange={event=>update("phone",event.target.value)} maxLength={50}/></label><label className="full">Email <span>Optional</span><input type="email" value={details.email} onChange={event=>update("email",event.target.value)}/></label></div><p className="drawer-note">After creating this client, you&apos;ll continue in the full guided intake. These details will already be filled in.</p><div className="drawer-actions"><button type="button" className="secondary" disabled={busy} onClick={close}>Cancel</button><button disabled={busy}>{busy?"Creating client…":"Create and begin intake"}</button></div></form>:null}
      {method==="UPLOAD"?<section className="upload-method"><div className={`file-drop ${dragging?"dragging":""}`} onDragEnter={event=>{event.preventDefault();setDragging(true)}} onDragOver={event=>event.preventDefault()} onDragLeave={()=>setDragging(false)} onDrop={drop}><span className="method-icon" aria-hidden="true">⇧</span><strong>Drop PDF files here</strong><span>or</span><label className="button secondary">Browse files<input type="file" accept="application/pdf,.pdf" multiple disabled={busy} onChange={event=>{addFiles([...(event.target.files??[])]);event.target.value=""}}/></label><small>Up to {MAX_FILES} PDFs · 10 MB each · 50 MB total</small></div>{files.length?<div className="selected-files" aria-label="Selected PDF files"><h3>{files.length} file{files.length===1?"":"s"} selected</h3>{files.map((file,index)=><div key={`${file.name}:${file.size}:${index}`}><span aria-hidden="true">PDF</span><p><strong>{file.name}</strong><small>{size(file.size)}</small></p><button type="button" className="icon-button" aria-label={`Remove ${file.name}`} disabled={busy} onClick={()=>setFiles(current=>current.filter((_,itemIndex)=>itemIndex!==index))}>×</button></div>)}</div>:null}<p className="drawer-note"><strong>What happens next</strong><br/>We&apos;ll preserve the originals and prepare extracted information for your explicit review. No client is created by this upload.</p><div className="drawer-actions"><button type="button" className="secondary" disabled={busy} onClick={close}>Cancel</button><button type="button" disabled={busy||!files.length} onClick={upload}>{busy?status||"Uploading documents…":"Upload and review"}</button></div></section>:null}
      {status?<p className="action-feedback" role="status" aria-live="polite"><span className="spinner" aria-hidden="true"/>{status}</p>:null}{error?<p className="action-feedback error" role="alert">{error}</p>:null}
    </div>
  </section></div>;
}
