"use client";
import { useEffect, useMemo, useState } from "react";

export type TrainingQuestion={id:string;questionType:string;prompt:string;critical:boolean;options:{id:string;text:string}[]};
export type TrainingAssessment={id:string;title:string;questions:TrainingQuestion[]};
export type TrainingContent={id:string;contentType:string;payload:unknown;required:boolean};
export type TrainingAssignmentView={id:string;status:string;employee?:{firstName:string;lastName:string;preferredName:string|null};courseVersion:{versionNumber:number;course:{title:string;code?:string};modules:{id:string;title:string;contentItems:TrainingContent[];assessments:TrainingAssessment[]}[]};contentProgress:{contentItemId:string;status:string}[];acknowledgments:{contentItemId:string}[];attempts:{id:string;assessmentId:string;attemptNumber:number;submittedAt:string|null;passed:boolean|null;draftResponses:{questionId:string;selectedOptionIds:unknown;updatedAt:string}[]}[];completion:unknown};

type Props={course:TrainingAssignmentView;answers:Record<string,string[]>;busy:boolean;saving:string|null;administrative?:boolean;onAnswer:(assessment:TrainingAssessment,question:TrainingQuestion,selected:string[])=>void;onComplete:(item:TrainingContent)=>void;onSubmit:(assessment:TrainingAssessment)=>void};
const asPayload=(payload:unknown)=>(payload??{})as{heading?:string;title?:string;body?:string;text?:string;warning?:string;callout?:string;example?:string;scenario?:string;prompt?:string;paragraphs?:string[];bullets?:string[];items?:string[];keyPoint?:string;statement?:string;sourceUrl?:string;provider?:string;attribution?:string;description?:string;durationMinutes?:number;delivery?:string;completionMode?:string};

function Content({item}:{item:TrainingContent}){const v=asPayload(item.payload),list=v.bullets??v.items;if(item.contentType==="VIDEO")return <div className="lesson-copy media-content"><p className="eyebrow">Instructional video</p><h4>{v.title??"Video learning component"}</h4>{v.description?<p>{v.description}</p>:null}<p>{v.provider??v.attribution??"External instructional provider"}{v.durationMinutes?` · approximately ${v.durationMinutes} minutes`:""}</p>{v.sourceUrl?<a className="button-link" href={v.sourceUrl} target="_blank" rel="noreferrer">Open provider-hosted video</a>:<p role="alert">This video source is currently unavailable. Contact your organization before continuing.</p>}<small>The platform does not claim playback telemetry. Use the completion control only after reviewing the linked material.</small></div>;return <div className="lesson-copy">{v.heading||v.title?<h4>{v.heading??v.title}</h4>:null}{v.paragraphs?.map((text,index)=><p key={index}>{text}</p>)}{v.body||v.text?<p>{v.body??v.text}</p>:null}{v.keyPoint?<aside role="note"><strong>Key point:</strong> {v.keyPoint}</aside>:null}{v.warning?<aside role="note"><strong>Important:</strong> {v.warning}</aside>:null}{v.callout?<aside role="note">{v.callout}</aside>:null}{v.example?<p><strong>Example:</strong> {v.example}</p>:null}{v.scenario?<p><strong>Scenario:</strong> {v.scenario}</p>:null}{v.prompt?<p><strong>Consider:</strong> {v.prompt}</p>:null}{list?.length?<ul>{list.map((text,index)=><li key={index}>{text}</li>)}</ul>:null}{v.statement?<p>{v.statement}</p>:null}{v.sourceUrl?<p><a href={v.sourceUrl} target="_blank" rel="noreferrer">Open source reference</a></p>:null}{!v.heading&&!v.title&&!v.body&&!v.text&&!v.paragraphs&&!v.warning&&!v.scenario&&!list&&!v.statement?<p>This content format is unavailable in the current player. Contact your organization; it has not been marked complete.</p>:null}</div>}

export default function TrainingCoursePlayer({course,answers,busy,saving,administrative=false,onAnswer,onComplete,onSubmit}:Props){
 const items=useMemo(()=>course.courseVersion.modules.flatMap(module=>module.contentItems.map(item=>({...item,moduleTitle:module.title}))),[course]),done=(item:TrainingContent)=>course.contentProgress.some(progress=>progress.contentItemId===item.id&&progress.status==="COMPLETED")||course.acknowledgments.some(ack=>ack.contentItemId===item.id),firstIncomplete=items.findIndex(item=>!done(item)),resumeIndex=firstIncomplete<0?Math.max(0,items.length-1):firstIncomplete,[index,setIndex]=useState(resumeIndex);
 useEffect(()=>setIndex(resumeIndex),[course.id,resumeIndex]);
 const current=items[index],completed=items.filter(done).length,requiredComplete=items.filter(item=>item.required).every(done),percent=items.length?Math.round(completed/items.length*100):course.completion?100:0;
 return <section className="course-player" aria-label={`${course.courseVersion.course.title} course player`}><div className="section-heading"><div><p className="eyebrow">{administrative?"Employee training — administrative assistance":"Version-bound course"}</p><h3>{course.courseVersion.course.title}</h3><p>Version {course.courseVersion.versionNumber} · {completed} of {items.length} learning components complete</p></div><strong>{percent}%</strong></div><progress value={completed} max={Math.max(1,items.length)} aria-label={`${course.courseVersion.course.title} progress`}/>{administrative?<aside role="note">You are changing the employee’s authoritative training record as an organization owner. Employee acknowledgment and lifecycle safeguards cannot be bypassed.</aside>:null}{current?<article className="lesson-focus"><p className="eyebrow">{current.moduleTitle} · component {index+1} of {items.length}</p><Content item={current}/><p className="item-state">{done(current)?"Completed":current.required?"Required":"Optional"}</p><div className="action-group"><button type="button" className="secondary" disabled={index===0||busy} onClick={()=>setIndex(value=>Math.max(0,value-1))}>Previous</button>{!done(current)&&!course.completion?<button type="button" disabled={busy||administrative&&current.contentType==="ACKNOWLEDGMENT"} onClick={()=>onComplete(current)}>{current.contentType==="ACKNOWLEDGMENT"?(administrative?"Employee acknowledgment required":"Acknowledge and continue"):current.contentType==="VIDEO"?"Confirm reviewed and continue":"Mark complete and continue"}</button>:null}<button type="button" className="secondary" disabled={index>=items.length-1||busy} onClick={()=>setIndex(value=>Math.min(items.length-1,value+1))}>Next</button></div></article>:<div className="empty-state">No instructional content is available.</div>}
 <section className="assessment-panel"><h4>Assessment</h4>{!requiredComplete?<p>Complete all required instructional components before submitting an assessment.</p>:null}{course.courseVersion.modules.flatMap(module=>module.assessments).map(assessment=>{const attempt=course.attempts.find(item=>item.assessmentId===assessment.id&&!item.submittedAt);return <form key={assessment.id} onSubmit={event=>{event.preventDefault();if(administrative){const name=course.employee?.preferredName??course.employee?.firstName??"this employee";if(!window.confirm(`Submit this assessment on behalf of ${name}?`))return}onSubmit(assessment)}}><h4>{assessment.title}</h4>{assessment.questions.map(question=><fieldset key={question.id} disabled={Boolean(course.completion)}><legend>{question.prompt}{question.critical?" (critical)":""}</legend>{question.options.map(option=>{const multiple=question.questionType==="MULTIPLE_CHOICE",selected=answers[question.id]??[];return <label key={option.id} className="answer"><input type={multiple?"checkbox":"radio"} name={question.id} checked={selected.includes(option.id)} onChange={()=>onAnswer(assessment,question,multiple?selected.includes(option.id)?selected.filter(id=>id!==option.id):[...selected,option.id]:[option.id])}/> {option.text}</label>})}<small>{saving===question.id?"Saving…":attempt?.draftResponses.some(response=>response.questionId===question.id)?"Saved":"Not answered"}</small></fieldset>)}<button type="submit" disabled={busy||!requiredComplete||assessment.questions.some(question=>!answers[question.id]?.length)||Boolean(course.completion)}>{administrative?"Submit on behalf of employee":"Submit assessment"}</button><small>Answers are saved as current responses. Scores and answer keys remain server-side.</small></form>})}</section></section>
}
