import assert from "node:assert/strict";
import { describe,it } from "node:test";
import { createHandler } from "../src/handler.mjs";

const valid={version:1,from:"signatures@email.waldah.com",fromName:"Synthetic Organization",replyTo:"support@email.waldah.com",to:"recipient@example.test",subject:"Signature requested",text:"Open the secure platform invitation.",html:"<p>Open the secure platform invitation.</p>"};
function harness(fetchImpl=async()=>new Response(JSON.stringify({sourceTrackingId:"tracking-1",data:"Service OK"}),{status:200,headers:{"content-type":"application/json"}})){
  const calls=[],logs=[],secrets={send:async command=>{calls.push({secretId:command.input.SecretId});return{SecretString:"synthetic-api-key-never-log"}}},wrapped=async(url,options)=>{calls.push({url,options});return fetchImpl(url,options)},handler=createHandler({secrets,fetchImpl:wrapped,environment:{PAUBOX_SECRET_ID:"compliance-platform/prod/paubox"},logger:event=>logs.push(event)});return{handler,calls,logs};
}

describe("Paubox relay",()=>{
  it("accepts only the controlled sender and official single-message contract",async()=>{const {handler,calls}=harness(),response=await handler(valid,{awsRequestId:"request-1"});assert.equal(response.accepted,true);assert.equal(response.messageId,"tracking-1");assert.deepEqual(calls[0],{secretId:"compliance-platform/prod/paubox"});const request=JSON.parse(calls[1].options.body);assert.deepEqual(request.data.message.recipients,[valid.to]);assert.deepEqual(request.data.message.headers,{subject:valid.subject,from:valid.from,"reply-to":valid.replyTo});assert.equal(request.data.message.content["text/plain"],valid.text);assert.equal(request.data.message.content["text/html"],valid.html);assert.equal("attachments" in request.data.message,false);assert.match(calls[1].options.headers.authorization,/^Bearer /)});
  it("rejects malformed, unexpected, attachment, and uncontrolled-sender requests before dependencies",async()=>{for(const input of[{}, {...valid,from:"attacker@example.test"},{...valid,attachments:[]},{...valid,to:"not-an-email"},{...valid,subject:"bad\r\nheader"}]){const {handler,calls}=harness(),response=await handler(input);assert.deepEqual(response,{accepted:false,code:"PAUBOX_REQUEST_INVALID",retryable:false});assert.equal(calls.length,0)}});
  it("normalizes provider restrictions, throttling, permanent failures, and temporary failures",async()=>{for(const [status,expected]of[[401,["PAUBOX_AUTHENTICATION_REJECTED",false]],[403,["PAUBOX_RESTRICTED",false]],[422,["PAUBOX_PERMANENT_REJECTION",false]],[429,["PAUBOX_RATE_LIMITED",true]],[503,["PAUBOX_TEMPORARY_FAILURE",true]]]){const {handler}=harness(async()=>new Response("{}",{status})),response=await handler(valid);assert.deepEqual(response,{accepted:false,code:expected[0],retryable:expected[1]})}});
  it("treats timeout/network and malformed success responses as retryable without false acceptance",async()=>{const timeout=harness(async()=>{const error=new Error("timed out");error.name="AbortError";throw error}),network=harness(async()=>{throw new Error("contains sensitive transport detail")}),malformed=harness(async()=>new Response(JSON.stringify({data:"Service OK"}),{status:200}));assert.deepEqual(await timeout.handler(valid),{accepted:false,code:"PAUBOX_TIMEOUT",retryable:true});assert.deepEqual(await network.handler(valid),{accepted:false,code:"PAUBOX_RELAY_DEPENDENCY_UNAVAILABLE",retryable:true});assert.deepEqual(await malformed.handler(valid),{accepted:false,code:"PAUBOX_RESPONSE_INVALID",retryable:true})});
  it("logs only safe correlation and outcome fields",async()=>{const {handler,logs}=harness();await handler(valid,{awsRequestId:"safe-request"});const serialized=JSON.stringify(logs);assert.match(serialized,/safe-request/);assert.doesNotMatch(serialized,/recipient@example|synthetic-api-key|secure platform|authorization|Signature requested/i)});
});
