"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
type Org = { id:string; displayName:string; legalName:string; slug:string };
type Duty = { id:string; name:string };
type Employee = { id:string; firstName:string; lastName:string; employeeNumber:string|null; employmentStatus:string; duties:{id:string; effectiveUntil:string|null; dutyDefinition:Duty}[] };
type Compliance = {id:string;status:string;requiredAt:string;nominalDueAt:string|null;statutoryDelayUntil:string|null;triggerType:string;triggerReference:string|null;requirementVersion:{requirement:{code:string;name:string}}};

export function FoundationConsole() {
  const [userId,setUserId]=useState(""); const [orgs,setOrgs]=useState<Org[]>([]); const [orgId,setOrgId]=useState(""); const [employees,setEmployees]=useState<Employee[]>([]); const [duties,setDuties]=useState<Duty[]>([]); const [compliance,setCompliance]=useState<Record<string,Compliance[]>>({}); const [access,setAccess]=useState<{permissions:string[];roles:{name:string}[]} | null>(null); const [message,setMessage]=useState("Enter a seeded user ID to begin.");
  const headers = useCallback(() => ({"content-type":"application/json","x-dev-user-id":userId}),[userId]);
  const loadOrgs=async()=>{ const r=await fetch("/api/organizations",{headers:headers()}); const body=await r.json(); if(!r.ok){setMessage(body.error);return;} setOrgs(body); setOrgId(body[0]?.id??""); setMessage(`${body.length} organization(s) available.`); };
  const loadOrg=useCallback(async()=>{if(!orgId)return; const [a,b,c]=await Promise.all([fetch(`/api/organizations/${orgId}`,{headers:headers()}),fetch(`/api/organizations/${orgId}/employees`,{headers:headers()}),fetch("/api/duties",{headers:headers()})]); const [aa,bb,cc]=await Promise.all([a.json(),b.json(),c.json()]); if(!a.ok||!b.ok){setMessage(aa.error??bb.error);return;} setAccess(aa);setEmployees(bb);setDuties(cc);},[orgId,headers]);
  useEffect(()=>{void loadOrg()},[loadOrg]);
  const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault(); const f=new FormData(e.currentTarget); const r=await fetch(`/api/organizations/${orgId}/employees`,{method:"POST",headers:headers(),body:JSON.stringify({firstName:f.get("firstName"),lastName:f.get("lastName"),employeeNumber:f.get("employeeNumber")||null,employmentStatus:"ACTIVE"})}); const body=await r.json();setMessage(r.ok?`Created ${body.firstName} ${body.lastName}`:body.error);if(r.ok){e.currentTarget.reset();await loadOrg();}};
  const addDuty=async(employeeId:string,dutyDefinitionId:string)=>{if(!dutyDefinitionId)return;const r=await fetch(`/api/organizations/${orgId}/employees/${employeeId}/duties`,{method:"POST",headers:headers(),body:JSON.stringify({dutyDefinitionId,effectiveFrom:new Date().toISOString().slice(0,10)})});const body=await r.json();setMessage(r.ok?"Duty assigned.":body.error);if(r.ok)await loadOrg();};
  const editEmployee=async(employee:Employee)=>{const firstName=window.prompt("First name",employee.firstName);if(!firstName)return;const lastName=window.prompt("Last name",employee.lastName);if(!lastName)return;const r=await fetch(`/api/organizations/${orgId}/employees/${employee.id}`,{method:"PATCH",headers:headers(),body:JSON.stringify({firstName,lastName})});const body=await r.json();setMessage(r.ok?"Employee updated.":body.error);if(r.ok)await loadOrg();};
  const removeDuty=async(employeeId:string,dutyId:string)=>{const r=await fetch(`/api/organizations/${orgId}/employees/${employeeId}/duties/${dutyId}`,{method:"DELETE",headers:headers()});const body=await r.json();setMessage(r.ok?"Duty ended.":body.error);if(r.ok)await loadOrg();};
  const loadCompliance=async(employeeId:string,reevaluate=false)=>{if(reevaluate){const r=await fetch(`/api/organizations/${orgId}/employees/${employeeId}/compliance`,{method:"POST",headers:headers()});const b=await r.json();if(!r.ok){setMessage(b.error);return;}setMessage(`Compliance reevaluated; ${b.unresolved.length} unresolved trigger(s).`)}const r=await fetch(`/api/organizations/${orgId}/employees/${employeeId}/compliance`,{headers:headers()});const body=await r.json();if(r.ok)setCompliance(c=>({...c,[employeeId]:body}));};
  return <main><header><p className="eyebrow">Phase 2 · compliance console</p><h1>Deterministic compliance, versioned at the source.</h1><p className="lede">A lean interface for exercising workforce context, regulatory rules, and compliance instances.</p></header><section className="auth"><label>Development user ID<input value={userId} onChange={e=>setUserId(e.target.value)} placeholder="Copy an ID printed by db:seed"/></label><button onClick={loadOrgs}>Load access</button><span>{message}</span></section>{orgs.length>0&&<><nav aria-label="Organizations">{orgs.map(o=><button className={o.id===orgId?"active":""} onClick={()=>setOrgId(o.id)} key={o.id}>{o.displayName}</button>)}</nav><section className="grid"><article><h2>Access snapshot</h2><p>{access?.roles.map(r=>r.name).join(", ")||"No roles"}</p><ul>{access?.permissions.map(p=><li key={p}>{p}</li>)}</ul></article><article><h2>Add employee</h2><form onSubmit={create}><input name="firstName" required placeholder="First name"/><input name="lastName" required placeholder="Last name"/><input name="employeeNumber" placeholder="Employee number (optional)"/><button type="submit">Create employee</button></form></article></section><section><h2>Employees & compliance</h2><div className="employees">{employees.map(e=><article key={e.id}><div><strong>{e.lastName}, {e.firstName}</strong><small>{e.employeeNumber??"No employee number"} · {e.employmentStatus}</small><button className="textButton" onClick={()=>void editEmployee(e)}>Edit</button></div><ul>{e.duties.filter(d=>!d.effectiveUntil).map(d=><li key={d.id}>{d.dutyDefinition.name} <button className="remove" aria-label={`End ${d.dutyDefinition.name}`} onClick={()=>void removeDuty(e.id,d.id)}>×</button></li>)}</ul><div><select defaultValue="" onChange={x=>void addDuty(e.id,x.target.value)}><option value="" disabled>Add duty…</option>{duties.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button className="textButton" onClick={()=>void loadCompliance(e.id)}>View compliance</button><button onClick={()=>void loadCompliance(e.id,true)}>Reevaluate</button></div>{compliance[e.id]&&<div className="compliance">{compliance[e.id].map(c=><div key={c.id}><strong>{c.requirementVersion.requirement.code} · {c.requirementVersion.requirement.name}</strong><small>{c.status} · trigger {c.triggerType} ({c.triggerReference??"date"})</small><small>Required {new Date(c.requiredAt).toLocaleString()} · Due {c.nominalDueAt?new Date(c.nominalDueAt).toLocaleString():"none"} · Legal delay {c.statutoryDelayUntil?new Date(c.statutoryDelayUntil).toLocaleString():"none"}</small></div>)}</div>}</article>)}</div></section></>}</main>;
}
