"use client";
import { FormEvent, useState } from "react";

type AssignmentState={state:"AVAILABLE"|"ASSIGNED"|"IN_PROGRESS"|"COMPLETED"|"FAILED";assignment:{status:string;dueAt:string|null}|null};
type Readiness={
  baseline:{licenseTypes:string[];meaning:string;courses:{id:string;code:string;title:string;description:string|null;versions:({id:string;versionNumber:number;status:string;estimatedDurationMinutes:number|null;requirements:{code:string;name:string}[]}&AssignmentState)[]}[]};
  firstAid:{status:string;meaning:string;evidence:{providerName:string;trainingName:string;trainingDate:string;expiresAt:string|null;reviewStatus:string}|null;requirement:{code:string;name:string}|null};
  medication:{status:string;meaning:string;evidence:{providerName:string;trainingName:string;trainingDate:string;expiresAt:string|null;reviewStatus:string}|null;pathways:{id:string;title:string;requirementCode:string;courseVersionId:string;assignment:AssignmentState;qualificationState:string}[]};
  personSpecific:{meaning:string;assignments:{serviceAssignmentId:string;personName:string;blockingScope:string;assignmentStatus:string;requirements:{ruleId:string;ruleName:string;requirementVersionId:string|null;requirementCode:string|null;requirementName:string|null;medicationPathwayId:string|null;course:({title:string;courseVersionId:string}&AssignmentState)|null}[]}[]};
};
const pretty=(value:string)=>value.toLowerCase().replaceAll("_"," ");
const evidence=(form:HTMLFormElement)=>{const data=new FormData(form);return{providerName:data.get("providerName"),trainingName:data.get("trainingName"),trainingDate:data.get("trainingDate"),expiresAt:data.get("expiresAt")||undefined,credentialNumber:data.get("credentialNumber")||undefined,evidenceReference:data.get("evidenceReference"),notes:data.get("notes")||undefined}};

export default function EmployeeTrainingReadiness({organizationId,employeeId,userId,productionIdentity=false}:{organizationId:string;employeeId:string;userId:string;productionIdentity?:boolean}){
 const[data,setData]=useState<Readiness|null>(null),[state,setState]=useState<"idle"|"loading"|"success"|"empty"|"error">("idle"),[message,setMessage]=useState(""),[selected,setSelected]=useState<string[]>([]),headers:Record<string,string>=productionIdentity?{"content-type":"application/json"}:{"content-type":"application/json","x-dev-user-id":userId};
 async function request(init?:RequestInit){const response=await fetch(`/api/organizations/${organizationId}/employees/${employeeId}/training-readiness`,{...init,headers:{...headers,...(init?.headers??{})}}),body=await response.json();if(!response.ok)throw new Error(body.error??"Training readiness operation failed");return body}
 async function load(success="Applicable catalog and readiness loaded."){setState("loading");setMessage("");try{const result=await request() as Readiness;setData(result);setState(result.baseline.courses.length?"success":"empty");setMessage(success)}catch(error){setState("error");setMessage(error instanceof Error?error.message:"Catalog could not be loaded")}}
 async function post(action:string,payload:unknown,success:string){setState("loading");setMessage("");try{const result=await request({method:"POST",body:JSON.stringify({action,payload})}) as Readiness|{readiness:Readiness};setData("readiness" in result?result.readiness:result);setSelected([]);setState(("readiness" in result?result.readiness:result).baseline.courses.length?"success":"empty");setMessage(success)}catch(error){setState("error");setMessage(error instanceof Error?error.message:"Training readiness operation failed")}}
 function submitEvidence(event:FormEvent<HTMLFormElement>,action:"FIRST_AID"|"MEDICATION"){event.preventDefault();void post(action,{choice:"ALREADY_HAVE",evidence:evidence(event.currentTarget)},`${action==="FIRST_AID"?"First Aid":"Medication"} evidence submitted for authorized review; no qualification or authority was granted.`)}
 function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id])}
 return <section className="training-readiness"><div className="section-heading"><div><h3>Training and workforce readiness</h3><p>Baseline training, external evidence, competency, clinical approval, and person-specific authorization remain separate.</p></div><button disabled={state==="loading"} onClick={()=>void load()}>{state==="loading"?"Loading catalog…":data?"Refresh catalog":"Load applicable training catalog"}</button></div><p role="status" aria-live="polite">{message}</p>
 {state==="error"?<div className="empty-state"><strong>Catalog unavailable</strong><p>Correct the reported access or configuration issue, then retry. No assignment was created.</p></div>:null}
 {state==="empty"?<div className="empty-state"><strong>No applicable baseline courses found</strong><p>{data?.baseline.meaning}</p></div>:null}
 {data?<div className="readiness-sections"><section><h4>Baseline requirements and training</h4><p>{data.baseline.meaning}</p><p>Active configuration: {data.baseline.licenseTypes.map(pretty).join(", ")||"none"}</p>{data.baseline.courses.length?<div className="readiness-course-list">{data.baseline.courses.flatMap(course=>course.versions.map(version=><label className="readiness-course" key={version.id}><input type="checkbox" disabled={version.state!=="AVAILABLE"} checked={selected.includes(version.id)} onChange={()=>toggle(version.id)}/><span><strong>{course.code} · {course.title}</strong><small>Version {version.versionNumber} · {pretty(version.state)}{version.estimatedDurationMinutes?` · ${version.estimatedDurationMinutes} minutes`:""}</small><small>{version.requirements.map(item=>`${item.code} ${item.name}`).join(" · ")}</small></span></label>))}</div>:null}<button disabled={!selected.length||state==="loading"} onClick={()=>void post("ASSIGN_BASELINE",{courseVersionIds:selected},"Selected version-pinned baseline training assigned through the existing lifecycle.")}>Assign selected baseline training</button></section>
 <section><h4>First Aid readiness</h4><p><strong>{pretty(data.firstAid.status)}</strong> · {data.firstAid.requirement?`${data.firstAid.requirement.code} ${data.firstAid.requirement.name}`:"No active mapped requirement"}</p><p>{data.firstAid.meaning}</p>{data.firstAid.evidence?<article><strong>{data.firstAid.evidence.trainingName}</strong><p>{data.firstAid.evidence.providerName} · {pretty(data.firstAid.evidence.reviewStatus)} · completed {new Date(data.firstAid.evidence.trainingDate).toLocaleDateString()}</p></article>:null}<details><summary>Employee already has current qualifying evidence</summary><EvidenceForm label="First Aid training/certification" onSubmit={event=>submitEvidence(event,"FIRST_AID")}/></details><button className="secondary" disabled={state==="loading"} onClick={()=>void post("FIRST_AID",{choice:"NEEDS_TRAINING"},"Applicable First Aid training assigned. No external certification was fabricated.")}>No current evidence — assign applicable training</button></section>
 <section><h4>Medication readiness</h4><p><strong>{pretty(data.medication.status)}</strong></p><p>{data.medication.meaning}</p>{data.medication.evidence?<article><strong>{data.medication.evidence.trainingName}</strong><p>{data.medication.evidence.providerName} · {pretty(data.medication.evidence.reviewStatus)}</p></article>:null}{data.medication.pathways.map(pathway=><article key={pathway.id}><strong>{pathway.title}</strong><p>{pretty(pathway.assignment.state)} · {pretty(pathway.qualificationState)} · {pathway.requirementCode}</p></article>)}<details><summary>Already have qualifying medication training/evidence</summary><EvidenceForm label="Medication training" onSubmit={event=>submitEvidence(event,"MEDICATION")}/></details><div className="action-group"><button disabled={state==="loading"} onClick={()=>void post("MEDICATION",{choice:"NEEDS_TRAINING"},"Governed medication training assigned; observed competency and clinical authorization remain required.")}>Needs medication training</button><button className="secondary" disabled={state==="loading"} onClick={()=>void post("MEDICATION",{choice:"NOT_CURRENTLY_APPLICABLE"},"Medication responsibilities recorded as not currently applicable; this does not waive future prerequisites.")}>Not currently applicable</button></div></section>
 <section><h4>Person-specific training</h4><p>{data.personSpecific.meaning}</p>{data.personSpecific.assignments.map(assignment=><article key={assignment.serviceAssignmentId}><strong>{assignment.personName} · {pretty(assignment.blockingScope)}</strong><p>Service assignment {pretty(assignment.assignmentStatus)}</p>{assignment.requirements.length?assignment.requirements.map(requirement=><p key={requirement.ruleId}>{requirement.ruleName}: {requirement.requirementCode??"clinical pathway"} · {requirement.course?`${requirement.course.title} (${pretty(requirement.course.state)})`:"No mapped course; other evidence/competency may be required"}</p>):<p>No configured person-specific training mapping for this responsibility.</p>}{assignment.requirements.some(row=>row.requirementVersionId&&row.course)?<button disabled={state==="loading"} onClick={()=>void post("ASSIGN_PERSON_SPECIFIC",{serviceAssignmentIds:[assignment.serviceAssignmentId]},"Person-specific requirements initialized through the existing registry and service-assignment guardrail.")}>Assign person-specific training</button>:null}</article>)}</section></div>:null}
 </section>
}
function EvidenceForm({label,onSubmit}:{label:string;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){return <form className="inline-form evidence-intake" onSubmit={onSubmit}><label>Provider/source<input name="providerName" required/></label><label>Training/evidence name<input name="trainingName" defaultValue={label} required/></label><label>Completion/issue date<input name="trainingDate" type="date" required/></label><label>Expiration date, if applicable<input name="expiresAt" type="date"/></label><label>Credential number, if applicable<input name="credentialNumber"/></label><label>Private evidence upload reference<input name="evidenceReference" placeholder="secure:…" required/></label><label>Notes<input name="notes"/></label><p>The reference must point to an object already uploaded through approved private evidence storage. Submission remains pending until authorized review.</p><button>Submit evidence for review</button></form>}
