import assert from "node:assert/strict";
import { describe,it } from "node:test";
import { createHandler } from "../src/handler.mjs";
const environment={MAILGUN_SECRET_ID:"compliance-platform/prod/mailgun",MAILGUN_API_BASE_URL:"https://api.mailgun.net",MAILGUN_DOMAIN:"mail.waldah.com",MAILGUN_FROM:"notifications@mail.waldah.com"};
const valid={version:1,from:environment.MAILGUN_FROM,fromName:"Synthetic Compliance",replyTo:"support@waldah.com",to:"recipient@example.test",subject:"Synthetic invitation",text:"This is synthetic and contains no PHI.",html:"<p>This is synthetic and contains no PHI.</p>"};
function harness(fetchImpl=async()=>new Response(JSON.stringify({id:"<provider-id@mail.waldah.com>",message:"Queued. Thank you."}),{status:200})){const calls=[],logs=[],secrets={send:async command=>{calls.push({secretId:command.input.SecretId});return{SecretString:"key-synthetic-never-log-value"}}},wrapped=async(url,options)=>{calls.push({url,options});return fetchImpl(url,options)},handler=createHandler({secrets,fetchImpl:wrapped,environment,logger:event=>logs.push(event)});return{handler,calls,logs}}
describe("Mailgun relay",()=>{
  it("submits the supported single-message contract and returns provider acceptance",async()=>{const {handler,calls}=harness(),response=await handler(valid,{awsRequestId:"request-1"});assert.equal(response.accepted,true);assert.equal(response.messageId,"<provider-id@mail.waldah.com>");assert.deepEqual(calls[0],{secretId:environment.MAILGUN_SECRET_ID});assert.equal(calls[1].url,"https://api.mailgun.net/v3/mail.waldah.com/messages");assert.match(calls[1].options.headers.authorization,/^Basic /);assert.equal(calls[1].options.body.get("to"),valid.to);assert.equal(calls[1].options.body.get("html"),valid.html)});
  it("rejects malformed requests and uncontrolled senders before dependencies",async()=>{for(const input of[{}, {...valid,from:"attacker@example.test"},{...valid,attachments:[]},{...valid,to:"invalid"},{...valid,subject:"bad\r\nheader"}]){const {handler,calls}=harness(),response=await handler(input);assert.equal(response.classification,"POLICY_OR_VALIDATION_FAILURE");assert.equal(calls.length,0)}});
  it("rejects a configured sender outside the Mailgun sending domain",async()=>{const calls=[],handler=createHandler({environment:{...environment,MAILGUN_FROM:"notifications@other.example"},secrets:{send:async command=>{calls.push(command);return{SecretString:"must-not-be-read"}}},logger:()=>{}}),response=await handler({...valid,from:"notifications@other.example"});assert.equal(response.code,"MAILGUN_CONFIGURATION_UNAVAILABLE");assert.equal(response.classification,"AUTH_OR_CONFIGURATION_FAILURE");assert.equal(calls.length,0)});
  it("classifies auth, domain, quota, validation, temporary, and definitive rejections",async()=>{const cases=[[401,"AUTH_OR_CONFIGURATION_FAILURE"],[403,"AUTH_OR_CONFIGURATION_FAILURE"],[404,"AUTH_OR_CONFIGURATION_FAILURE"],[429,"CAPACITY_OR_QUOTA_FAILURE"],[400,"POLICY_OR_VALIDATION_FAILURE"],[422,"POLICY_OR_VALIDATION_FAILURE"],[503,"RETRYABLE_TRANSPORT_FAILURE"],[409,"DEFINITIVELY_NOT_ACCEPTED"]];for(const [status,classification]of cases){const {handler}=harness(async()=>new Response("{}",{status}));assert.equal((await handler(valid)).classification,classification)}});
  it("treats timeout, network, and malformed success as ambiguous and never accepted",async()=>{for(const fetchImpl of[async()=>{const error=new Error("timeout");error.name="AbortError";throw error},async()=>{throw new Error("sensitive network detail")},async()=>new Response(JSON.stringify({message:"Queued"}),{status:200})]){const response=await harness(fetchImpl).handler(valid);assert.equal(response.accepted,false);assert.equal(response.classification,"AMBIGUOUS_OUTCOME")}});
  it("logs no credential, recipient, subject, or body",async()=>{const {handler,logs}=harness();await handler(valid,{awsRequestId:"safe-request"});const serialized=JSON.stringify(logs);assert.match(serialized,/safe-request/);assert.doesNotMatch(serialized,/recipient@example|synthetic-never-log|Synthetic invitation|contains no PHI|authorization/i)});
});
