import { z } from "zod";
import { requireAuthenticatedUser } from "@/domain/auth/authentication";
import { errorResponse } from "@/domain/auth/errors";
import { requireOrganizationMembership,requirePermission } from "@/domain/permissions/authorization";
import { assessmentCreateSchema,assessmentFinalizeSchema } from "@/domain/evidence/schemas";
import { createCompetencyAssessment,finalizeCompetencyAssessment } from "@/domain/evidence/service";
import { prisma } from "@/lib/prisma";
export async function GET(request:Request,context:{params:Promise<{organizationId:string}>}){try{const user=await requireAuthenticatedUser(request),{organizationId}=await context.params,membership=await requireOrganizationMembership(user.id,organizationId),q=new URL(request.url).searchParams;await requirePermission(membership.id,"competency.read");const page=Math.max(1,z.coerce.number().int().catch(1).parse(q.get("page")??1)),pageSize=Math.min(100,Math.max(1,z.coerce.number().int().catch(25).parse(q.get("pageSize")??25))),where={organizationId,employeeId:q.get("employeeId")??undefined,status:q.get("status")?z.enum(["DRAFT","IN_PROGRESS","FINALIZED","VOIDED"]).parse(q.get("status")):undefined},[total,items]=await Promise.all([prisma.competencyAssessment.count({where}),prisma.competencyAssessment.findMany({where,include:{employee:true,competencyDefinition:true,skillChecklistVersion:{include:{items:{orderBy:{sequence:"asc"}}}},items:{include:{skillChecklistItem:true}}},orderBy:[{createdAt:"desc"},{id:"desc"}],skip:(page-1)*pageSize,take:pageSize})]);return Response.json({page,pageSize,total,items})}catch(error){return errorResponse(error)}}
export async function POST(request:Request,context:{params:Promise<{organizationId:string}>}){try{const user=await requireAuthenticatedUser(request);return Response.json(await createCompetencyAssessment(user.id,(await context.params).organizationId,assessmentCreateSchema.parse(await request.json())),{status:201})}catch(error){return errorResponse(error)}}
export async function PATCH(request:Request,context:{params:Promise<{organizationId:string}>}){try{const user=await requireAuthenticatedUser(request),body=await request.json(),input=assessmentFinalizeSchema.parse(body);return Response.json(await finalizeCompetencyAssessment(user.id,(await context.params).organizationId,String(body.id),input))}catch(error){return errorResponse(error)}}
