import type { User } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { AuthorizationError,ResourceNotFoundError } from "@/domain/auth/errors";
import { requireEmployeeAccess,requireOrganizationAccess,requirePermission } from "@/domain/permissions/authorization";
import { assignmentSchema } from "../schemas";
import { getAssignableCourseVersion } from "../catalog/service";
export async function createManualAssignment(user:Pick<User,"id">,organizationId:string,input:unknown){const {membership}=await requireOrganizationAccess(user,organizationId);await requirePermission(membership.id,"training.assignment.manage");const data=assignmentSchema.parse(input);await requireEmployeeAccess(user,organizationId,data.employeeId,"employee.read");const courseVersion=await getAssignableCourseVersion(organizationId,data.courseVersionId);if(!courseVersion)throw new AuthorizationError("Course version is not published or available to this organization");const fingerprint=`manual:${organizationId}:${data.employeeId}:${data.courseVersionId}:${Date.now()}`;return prisma.trainingAssignment.create({data:{fingerprint,organizationId,employeeId:data.employeeId,courseVersionId:data.courseVersionId,sourceType:"MANUAL",assignedByUserId:user.id,dueAt:data.dueAt}})}
export async function assignTrainingForCompliance(complianceInstanceId:string){const instance=await prisma.complianceInstance.findUnique({where:{id:complianceInstanceId},include:{requirementVersion:{include:{trainingOptions:{where:{isDefault:true},include:{trainingCourseVersion:{include:{course:true}}}}}}}});if(!instance)return null;const now=new Date(),option=instance.requirementVersion.trainingOptions.find(o=>o.trainingCourseVersion.status==="PUBLISHED"&&(!o.effectiveFrom||o.effectiveFrom<=now)&&(!o.effectiveUntil||o.effectiveUntil>=now)&&(!o.trainingCourseVersion.course.organizationId||o.trainingCourseVersion.course.organizationId===instance.organizationId));if(!option)return null;const fingerprint=`compliance:${instance.id}:${option.trainingCourseVersionId}`;return prisma.trainingAssignment.upsert({where:{fingerprint},create:{fingerprint,organizationId:instance.organizationId,employeeId:instance.employeeId,courseVersionId:option.trainingCourseVersionId,sourceType:"COMPLIANCE_ENGINE",sourceReferenceId:instance.id,complianceInstanceId:instance.id,dueAt:instance.nominalDueAt},update:{dueAt:instance.nominalDueAt}})}
export async function getAssignment(organizationId:string,employeeId:string,assignmentId:string){const assignment=await prisma.trainingAssignment.findFirst({where:{id:assignmentId,organizationId,employeeId},include:{courseVersion:{include:{course:true,modules:{orderBy:{sequence:"asc"},include:{contentItems:{orderBy:{sequence:"asc"}},assessments:{where:{status:"PUBLISHED"},include:{questions:{orderBy:{sequence:"asc"},select:{id:true,questionType:true,prompt:true,sequence:true,points:true,options:{orderBy:{sequence:"asc"},select:{id:true,text:true,sequence:true}}}}}}}}}},moduleProgress:true,contentProgress:true,acknowledgments:true,attempts:true,completion:true}});if(!assignment)throw new ResourceNotFoundError("Training assignment not found");return assignment}
