import { z } from "zod";
import { requireAuthenticatedUser } from "@/domain/auth/authentication";
import { errorResponse } from "@/domain/auth/errors";
import { acceptRemainingClientImportProposals, appendClientImportDocuments, cancelClientImport, classifyClientImportDocument, confirmClientImport, createClientImport, getClientImport, getClientImportPdf, listClientImports, resolveClientImportConflict, reviewClientImportProposal, updateClientImportDocumentSettings } from "@/domain/clients/imports";

const actionSchema=z.discriminatedUnion("action",[
  z.object({action:z.literal("CREATE"),requestId:z.string().uuid().optional(),target:z.enum(["CREATE_NEW","UPDATE_EXISTING"]),existingClientId:z.string().cuid().optional(),files:z.array(z.object({fileName:z.string(),mimeType:z.literal("application/pdf"),pdfBase64:z.string()}))}),
  z.object({action:z.literal("REVIEW"),sessionId:z.string().cuid(),proposalId:z.string().cuid(),state:z.enum(["ACCEPTED","CORRECTED","REJECTED"]),correctedValue:z.union([z.string(),z.number(),z.boolean(),z.array(z.string())]).optional()}),
  z.object({action:z.literal("CLASSIFY"),sessionId:z.string().cuid(),documentId:z.string().cuid(),classification:z.enum(["INTAKE_CHECKLIST","FACE_SHEET","RIGHTS_ACKNOWLEDGMENT","ROI","UNKNOWN"])}),
  z.object({action:z.literal("APPEND"),sessionId:z.string().cuid(),files:z.array(z.object({fileName:z.string(),mimeType:z.literal("application/pdf"),pdfBase64:z.string()}))}),
  z.object({action:z.literal("SETTINGS"),sessionId:z.string().cuid(),documentId:z.string().cuid(),classification:z.enum(["INTAKE_CHECKLIST","FACE_SHEET","RIGHTS_ACKNOWLEDGMENT","ROI","UNKNOWN"]),disposition:z.enum(["PRESERVE_ONLY","HISTORICAL_COMPLETE","CURRENT_SIGNATURE_REQUIRED"]),completedAt:z.string().optional(),signatureReviewStatus:z.enum(["UNREVIEWED","CONFIRMED_EXTERNAL","NEEDS_REVIEW","MISSING_REQUIRED_SIGNATURE","REJECTED","NOT_APPLICABLE"]),validityReviewStatus:z.enum(["UNREVIEWED","CONFIRMED","UNKNOWN","NOT_APPLICABLE"]),expirationDate:z.string().optional()}),
  z.object({action:z.literal("ACCEPT_REMAINING"),sessionId:z.string().cuid()}),
  z.object({action:z.literal("RESOLVE_CONFLICT"),sessionId:z.string().cuid(),proposalId:z.string().cuid(),correctedValue:z.union([z.string(),z.number(),z.boolean(),z.array(z.string())]).optional()}),
  z.object({action:z.literal("CONFIRM"),sessionId:z.string().cuid(),confirmed:z.literal(true),target:z.enum(["CREATE_NEW","UPDATE_EXISTING"]),clientId:z.string().cuid().optional(),documents:z.array(z.object({documentId:z.string().cuid(),disposition:z.enum(["PRESERVE_ONLY","HISTORICAL_COMPLETE","CURRENT_SIGNATURE_REQUIRED"]),completedAt:z.coerce.date().optional(),signatureReviewStatus:z.enum(["UNREVIEWED","CONFIRMED_EXTERNAL","NEEDS_REVIEW","MISSING_REQUIRED_SIGNATURE","REJECTED","NOT_APPLICABLE"]),validityReviewStatus:z.enum(["UNREVIEWED","CONFIRMED","UNKNOWN","NOT_APPLICABLE"]),expirationDate:z.coerce.date().optional()}))}),
  z.object({action:z.literal("CANCEL"),sessionId:z.string().cuid()}),
]);

export async function GET(request:Request,context:{params:Promise<{organizationId:string}>}){try{const user=await requireAuthenticatedUser(request),{organizationId}=await context.params,query=new URL(request.url).searchParams,sessionId=query.get("sessionId"),documentId=query.get("documentId"),clientId=query.get("clientId");if(sessionId&&documentId){const document=await getClientImportPdf(user,organizationId,sessionId,documentId);return new Response(document.originalBytes,{headers:{"content-type":"application/pdf","content-disposition":`inline; filename="${document.originalFileName.replace(/[\"\\]/g,"_")}"`,"cache-control":"no-store","x-content-type-options":"nosniff"}})}return Response.json(sessionId?await getClientImport(user,organizationId,sessionId):await listClientImports(user,organizationId,clientId??undefined))}catch(error){return errorResponse(error)}}
export async function POST(request:Request,context:{params:Promise<{organizationId:string}>}){try{const user=await requireAuthenticatedUser(request),{organizationId}=await context.params,body=actionSchema.parse(await request.json());if(body.action==="CREATE")return Response.json(await createClientImport(user,organizationId,body),{status:201});if(body.action==="APPEND")return Response.json(await appendClientImportDocuments(user,organizationId,body));if(body.action==="REVIEW")return Response.json(await reviewClientImportProposal(user,organizationId,body.sessionId,body));if(body.action==="CLASSIFY")return Response.json(await classifyClientImportDocument(user,organizationId,body.sessionId,body.documentId,body.classification));if(body.action==="SETTINGS")return Response.json(await updateClientImportDocumentSettings(user,organizationId,body.sessionId,body));if(body.action==="ACCEPT_REMAINING")return Response.json(await acceptRemainingClientImportProposals(user,organizationId,body.sessionId));if(body.action==="RESOLVE_CONFLICT")return Response.json(await resolveClientImportConflict(user,organizationId,body.sessionId,body.proposalId,body.correctedValue));if(body.action==="CONFIRM")return Response.json(await confirmClientImport(user,organizationId,body.sessionId,body));return Response.json(await cancelClientImport(user,organizationId,body.sessionId))}catch(error){return errorResponse(error)}}
