import type { EmploymentStatus, User } from "@prisma/client";
import { getEmployeeAuditRecord } from "@/domain/audit/service";
import { getMedicationEvidence, listMedicationQualifications } from "@/domain/medication/service";
import { getComplianceOperationsSummary, getEmployeeComplianceProfile } from "@/domain/operations/service";
import { requireEmployeeAccess, requireOrganizationAccess, requirePermission } from "@/domain/permissions/authorization";
import { prisma } from "@/lib/prisma";

async function authorize(user: Pick<User,"id">, organizationId: string, permission: string) { const { membership } = await requireOrganizationAccess(user, organizationId); await requirePermission(membership.id, permission); return membership; }

export async function getEmployerDashboard(user: Pick<User,"id">, organizationId: string) {
  await authorize(user, organizationId, "compliance.operations.read");
  const [operations, activeWorkforce, invitations, unresolvedIssues, onboardingIncomplete] = await Promise.all([
    getComplianceOperationsSummary(user, organizationId),
    prisma.employee.count({ where: { organizationId, employmentStatus: "ACTIVE" } }),
    prisma.employeePortalInvitation.groupBy({ by: ["status"], where: { organizationId }, _count: true }),
    prisma.complianceIssue.count({ where: { organizationId, status: { in: ["OPEN","IN_PROGRESS"] } } }),
    prisma.employeeOnboarding.count({ where: { organizationId, status: { notIn: ["READY","COMPLETED","CANCELED"] } } }),
  ]);
  return { organizationId, generatedAt: new Date().toISOString(), activeWorkforce, workforce: operations.workforce.counts, training: { overdue: operations.trainingOverdue, dueSoon: operations.trainingDueSoon, competencyPending: operations.competencyPending }, onboarding: { incomplete: onboardingIncomplete, byStatus: operations.onboarding }, policies: { pendingAcknowledgments: operations.policyAcknowledgmentsPending }, compliance: { unresolvedIssues, overdue: operations.overdueCompliance, byIssueStatus: operations.complianceIssues }, medication: operations.medication, serviceAssignments: operations.serviceAssignments, certificates: operations.certificates, invitations: Object.fromEntries(invitations.map(item=>[item.status,item._count])) };
}

export async function getWorkforceDirectory(user: Pick<User,"id">, organizationId: string, filters: { search?: string; status?: EmploymentStatus; attention?: boolean; page?: number; pageSize?: number } = {}) {
  await authorize(user, organizationId, "compliance.operations.read");
  const page=Math.max(1,filters.page??1),pageSize=Math.max(1,Math.min(filters.pageSize??25,100)),search=filters.search?.trim();
  const where={organizationId,employmentStatus:filters.status,OR:search?[{firstName:{contains:search,mode:"insensitive" as const}},{lastName:{contains:search,mode:"insensitive" as const}},{employeeNumber:{contains:search,mode:"insensitive" as const}},{email:{contains:search,mode:"insensitive" as const}}]:undefined};
  const [total,employees]=await Promise.all([prisma.employee.count({where}),prisma.employee.findMany({where,orderBy:[{lastName:"asc"},{firstName:"asc"},{id:"asc"}],skip:(page-1)*pageSize,take:pageSize,select:{id:true,employeeNumber:true,firstName:true,lastName:true,email:true,jobTitle:true,employmentStatus:true,hireDate:true,terminationDate:true,userId:true,portalInvitations:{orderBy:{invitedAt:"desc"},take:1,select:{status:true,invitedAt:true,acceptedAt:true,revokedAt:true}},trainingAssignments:{select:{status:true}},_count:{select:{complianceIssues:{where:{status:{in:["OPEN","IN_PROGRESS"]}}},policyAssignments:{where:{status:{in:["PENDING","OVERDUE"]}}},competencyAssessments:{where:{OR:[{status:{in:["DRAFT","IN_PROGRESS"]}},{status:"FINALIZED",result:{in:["FAIL","REMEDIATION_REQUIRED","INCOMPLETE"]}}]}},medicationQualifications:{where:{status:"ACTIVE",decision:"DENIED"}},serviceAssignments:{where:{status:"BLOCKED"}}}}}})]);
  const userIds=employees.flatMap(employee=>employee.userId?[employee.userId]:[]),memberships=userIds.length?await prisma.organizationMembership.findMany({where:{organizationId,userId:{in:userIds}},include:{roles:{include:{roleDefinition:true}}}}):[];
  const rows=employees.map(employee=>{const membership=memberships.find(item=>item.userId===employee.userId),counts=employee._count,training=employee.trainingAssignments.reduce<Record<string,number>>((result,item)=>({...result,[item.status]:(result[item.status]??0)+1}),{}),trainingActions=employee.trainingAssignments.filter(item=>["NOT_STARTED","IN_PROGRESS","FAILED","TRAINING_COMPLETE_COMPETENCY_PENDING"].includes(item.status)).length,openActionCount=counts.complianceIssues+trainingActions+counts.policyAssignments+counts.competencyAssessments;return{id:employee.id,employeeNumber:employee.employeeNumber,firstName:employee.firstName,lastName:employee.lastName,email:employee.email,jobTitle:employee.jobTitle,employmentStatus:employee.employmentStatus,hireDate:employee.hireDate,terminationDate:employee.terminationDate,userId:employee.userId,portalInvitation:employee.portalInvitations[0]??null,accountStatus:membership?.status??(employee.userId?"UNAVAILABLE":"NOT_LINKED"),roles:membership?.roles.map(item=>({id:item.roleDefinition.id,code:item.roleDefinition.code,name:item.roleDefinition.name}))??[],complianceStatus:counts.complianceIssues?"ATTENTION_REQUIRED":"NO_OPEN_ISSUES_DETECTED",openActionCount,blockingRequirementCount:counts.serviceAssignments,training,policyActionCount:counts.policyAssignments,competencyActionCount:counts.competencyAssessments,medicationActionCount:counts.medicationQualifications,blockedServiceAssignmentCount:counts.serviceAssignments}});
  const visible=filters.attention?rows.filter(row=>row.openActionCount>0||row.blockedServiceAssignmentCount>0):rows;
  return{organizationId,page,pageSize,total,returned:visible.length,items:visible,disclaimer:"No open issues detected does not certify legal compliance."};
}

export async function getEmployerEmployeeDetail(user: Pick<User,"id">, organizationId: string, employeeId: string) {
  await authorize(user, organizationId, "compliance.operations.read");await requireEmployeeAccess(user,organizationId,employeeId,"employee.read");
  const [profile,medication,medicationEvidence,auditRecord,recentActivity]=await Promise.all([getEmployeeComplianceProfile(user,organizationId,employeeId),listMedicationQualifications(user,organizationId,employeeId),getMedicationEvidence(user,organizationId,employeeId),getEmployeeAuditRecord(user,organizationId,employeeId),prisma.auditEvent.findMany({where:{organizationId,employeeId},orderBy:[{occurredAt:"desc"},{id:"desc"}],take:50})]);
  const invitation=await prisma.employeePortalInvitation.findFirst({where:{organizationId,employeeId},orderBy:{invitedAt:"desc"},select:{id:true,invitedEmail:true,status:true,invitedAt:true,acceptedAt:true,revokedAt:true}}),employee=await prisma.employee.findFirstOrThrow({where:{id:employeeId,organizationId},select:{userId:true}}),membership=employee.userId?await prisma.organizationMembership.findUnique({where:{organizationId_userId:{organizationId,userId:employee.userId}},include:{roles:{include:{roleDefinition:true}}}}):null;
  return{organizationId,employeeId,portalAccess:invitation,organizationAccess:membership?{id:membership.id,status:membership.status,joinedAt:membership.joinedAt,endedAt:membership.endedAt,roles:membership.roles.map(item=>({id:item.roleDefinition.id,code:item.roleDefinition.code,name:item.roleDefinition.name}))}:null,profile,medication:{pathways:medication,evidence:medicationEvidence},audit:{knownEvidenceGaps:auditRecord.knownEvidenceGaps,materialAuditHistory:auditRecord.materialAuditHistory,requirementCount:auditRecord.requirements.length,recentActivity}};
}
